/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.rmo.rp.issresord.bean.ejb.session;

/**
 * Home interface for IssResOrdFacade.
 * @generated 
 * @wtp generated
 */
public interface IssResOrdFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/IssResOrdFacade";
   public static final String JNDI_NAME="IssResOrdFacade";

   public com.tmmas.scl.operations.rmo.rp.issresord.bean.ejb.session.IssResOrdFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
