package com.tmmas.cl.scl.spnsclws.pa;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Sat Oct 29 16:51:36 CLST 2011  
 */

public interface SpnSclWS extends java.rmi.Remote {
     
  /**
    * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getListadoPlanTarifario   */

	public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListPlanTarifarioOutDTO getListadoPlanTarifario() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getListadoPlanTarifarioAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
	
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getClasificaciones   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsClasificacionOutDTO getClasificaciones() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getClasificacionesAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}rechazoVenta   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.RechazoVentaOutDTO rechazoVenta(com.tmmas.cl.scl.spnsclwscommon.commonapp.dto.in.WsRechazoVentaInDTO rechazoVenta,int rollback) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void rechazoVentaAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.spnsclwscommon.commonapp.dto.in.WsRechazoVentaInDTO rechazoVenta,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getListadoTipoPago   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListTipoPagoOutDTO getListadoTipoPago() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getListadoTipoPagoAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getListadoCiudades   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListadoCiudadesOutDTO getListadoCiudades(com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.ProvinciaDTO provinciaDTO) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getListadoCiudadesAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.ProvinciaDTO provinciaDTO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}deleteTienda   */

  public void deleteTienda(java.lang.Long codTienda) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void deleteTiendaAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.Long codTienda) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}cancelaVenta   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.RechazoVentaOutDTO cancelaVenta(com.tmmas.cl.scl.spnsclwscommon.commonapp.dto.in.WsRechazoVentaInDTO cancelaVenta,int rollback) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void cancelaVentaAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.spnsclwscommon.commonapp.dto.in.WsRechazoVentaInDTO cancelaVenta,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getConsultaPlanesTarifarios   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListConsultaPlanTarifarioOutDTO getConsultaPlanesTarifarios(com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsConsultaPlanTarifarioInDTO consultaPlanTarifarioIn) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getConsultaPlanesTarifariosAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsConsultaPlanTarifarioInDTO consultaPlanTarifarioIn) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}solicitaBajaAbonado   */

  public com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WSSolicitudBajaAbonadoOutDTO solicitaBajaAbonado(com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WSSolicitudBajaAbonadoDTO solicitudBajaAbonadoDTO,int rollback) throws java.rmi.RemoteException;
    public void solicitaBajaAbonadoAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WSSolicitudBajaAbonadoDTO solicitudBajaAbonadoDTO,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getDetalleUltimaLlamadasRoamingTOL   */

  public com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.RoamingOUTDTO getDetalleUltimaLlamadasRoamingTOL(com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.RoamingDTO rommingDTO) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getDetalleUltimaLlamadasRoamingTOLAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.RoamingDTO rommingDTO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}recuperaArrayTipificacion   */

  public com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.ArrayOfTipificaClientizaDTO_Literal recuperaArrayTipificacion() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void recuperaArrayTipificacionAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getCrediticia   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsCrediticiaOutDTO getCrediticia() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getCrediticiaAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}clientePorNumeroCelular   */

  public com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.DatosClienteDTO clientePorNumeroCelular(long numeroCelular) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void clientePorNumeroCelularAsync(weblogic.wsee.async.AsyncPreCallContext apc, long numeroCelular) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}foo   */

  public java.lang.String foo(java.lang.String param) throws java.rmi.RemoteException;
    public void fooAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String param) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getTiposPrestacion   */

  public com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WsListTipoPrestacionOutDTO getTiposPrestacion(java.lang.String codGrupoPrestacion,java.lang.String tipoCliente) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getTiposPrestacionAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String codGrupoPrestacion,java.lang.String tipoCliente) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getListadoRegiones   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListadoRegionesOutDTO getListadoRegiones() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getListadoRegionesAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getTiendaVendedor   */

  public com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.WsTiendaVendedorOutDTO getTiendaVendedor(java.lang.String codTienda) throws java.rmi.RemoteException;
    public void getTiendaVendedorAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String codTienda) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}deleteTipificacion   */

  public void deleteTipificacion(java.lang.Long codArticulo) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void deleteTipificacionAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.Long codArticulo) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}recCampanaBeneficio   */

  public com.tmmas.cl.scl.commonapp.dto.ArrayOfWsBeneficioPromocionOutDTO_Literal recCampanaBeneficio(com.tmmas.cl.scl.commonapp.dto.WsBeneficioPromocionInDTO beneficioPromocion) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void recCampanaBeneficioAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.commonapp.dto.WsBeneficioPromocionInDTO beneficioPromocion) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getListaCaja   */

  public com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.WsCajaOutDTO getListaCaja(java.lang.String codOficina) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getListaCajaAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String codOficina) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}reservaDesreserva   */

  public com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.ReservaOutDTO reservaDesreserva(com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.ReservaDTO solicitaReservaDTO,java.lang.String tipoSolicitud,int rollback) throws java.rmi.RemoteException;
    public void reservaDesreservaAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.ReservaDTO solicitaReservaDTO,java.lang.String tipoSolicitud,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}updateTipificacion   */

  public void updateTipificacion(com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.TipificaClientizaDTO tipificaClientizaDTO) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void updateTipificacionAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.TipificaClientizaDTO tipificaClientizaDTO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}agregarDirecciones   */

  public com.tmmas.cl.scl.commonapp.dto.WsDireccionesOutDTO agregarDirecciones(com.tmmas.cl.scl.commonapp.dto.ArrayOfWsDireccionInDTO_Literal WsDireccionesIn,int rollback) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void agregarDireccionesAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.commonapp.dto.ArrayOfWsDireccionInDTO_Literal WsDireccionesIn,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getCategoriasCambio   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListadoCategoriaCambioDTO getCategoriasCambio() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getCategoriasCambioAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}AltaCuentaSubCuenta   */

  public com.tmmas.cl.scl.commonapp.dto.WsAltaCuentaSubCuentaOutDTO altaCuentaSubCuenta(com.tmmas.cl.scl.commonapp.dto.WsAltaCuentaSubCuentaInDTO cuentaIn,int rollback) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void altaCuentaSubCuentaAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.commonapp.dto.WsAltaCuentaSubCuentaInDTO cuentaIn,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}pruebaJMS   */

  public java.lang.String pruebaJMS(java.lang.String prueba) throws java.rmi.RemoteException;
    public void pruebaJMSAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String prueba) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}AltaDeLinea   */

  public com.tmmas.cl.scl.commonapp.dto.WsCunetaAltaDeLineaOutDTO altaDeLinea(com.tmmas.cl.scl.commonapp.dto.WsCunetaAltaDeLineaDTO altaLinea,int rollback) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void altaDeLineaAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.commonapp.dto.WsCunetaAltaDeLineaDTO altaLinea,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getCentralesQuiosco   */

  public com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WSCentralQuioscoOutDTO getCentralesQuiosco() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getCentralesQuioscoAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getListCategorias   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListadoCategoriasClienteOutDTO getListCategorias() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getListCategoriasAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}insertTienda   */

  public com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.WsInsertTiendaOutDTO insertTienda(com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.TiendaDTO tiendaDTO) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void insertTiendaAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.TiendaDTO tiendaDTO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}registraCampanaBeneficio   */

  public void registraCampanaBeneficio(com.tmmas.cl.scl.commonapp.dto.WsRegistraCampanaByPInDTO registraCampanaByPIn) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void registraCampanaBeneficioAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.commonapp.dto.WsRegistraCampanaByPInDTO registraCampanaByPIn) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getTiendas   */

  public com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.WsTiendasOutDTO getTiendas() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getTiendasAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getListadoPlanesTarifarios   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListPlanTarifarioOutDTO getListadoPlanesTarifarios(com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsPlanTarifarioInDTO inWSLstPlanTarifDTO) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getListadoPlanesTarifariosAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsPlanTarifarioInDTO inWSLstPlanTarifDTO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getImpuesto   */

  public float getImpuesto(java.lang.String codigoVendedor) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getImpuestoAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String codigoVendedor) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}solicitaBajaAbonadoPrepago   */

  public com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WSSolicitudBajaAbonadoOutDTO solicitaBajaAbonadoPrepago(com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WSSolicitudBajaAbonadoDTO solicitudBajaAbonadoDTO,int rollback) throws java.rmi.RemoteException;
    public void solicitaBajaAbonadoPrepagoAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WSSolicitudBajaAbonadoDTO solicitudBajaAbonadoDTO,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}AltaDeStructuraComercial   */

  public com.tmmas.cl.scl.spnsclwscommon.quiosco.dto.WsStructuraComercialOutDTO altaDeStructuraComercial(com.tmmas.cl.scl.spnsclwscommon.quiosco.dto.WsCreaStructuraComercialInDTO WsCreaStructuraComercial) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void altaDeStructuraComercialAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.spnsclwscommon.quiosco.dto.WsCreaStructuraComercialInDTO WsCreaStructuraComercial) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getCargosFacturacion   */

  public com.tmmas.cl.scl.commonapp.dto.WsConsCargosVentaOutDTO getCargosFacturacion(com.tmmas.cl.scl.commonapp.dto.WsConsCargosVentaInDTO WsFacturacionVentaIn) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getCargosFacturacionAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.commonapp.dto.WsConsCargosVentaInDTO WsFacturacionVentaIn) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}WSMigracionClientePrepagoAPostpago   */

  public com.tmmas.scl.serviciospostventasiga.transport.MigracionPrepagoPostpagoDTO wSMigracionClientePrepagoAPostpago(com.tmmas.scl.serviciospostventasiga.transport.MigracionDTO migracionDTO) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void wSMigracionClientePrepagoAPostpagoAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.scl.serviciospostventasiga.transport.MigracionDTO migracionDTO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}recuperaDatoTipificacion   */

  public com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.ArrayOfTipificacionDTO_Literal recuperaDatoTipificacion(java.lang.String datoTipificacion,java.lang.String codVendedor) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void recuperaDatoTipificacionAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String datoTipificacion,java.lang.String codVendedor) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getZip   */

  public java.lang.String getZip(com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.DireccionDTO direccion) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getZipAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.DireccionDTO direccion) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getListadoTarjetas   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListTarjetaOutDTO getListadoTarjetas() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getListadoTarjetasAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}agregarDireccion   */

  public com.tmmas.cl.scl.commonapp.dto.WsDireccionOutDTO agregarDireccion(com.tmmas.cl.scl.commonapp.dto.WsDireccionInDTO WsDireccionesIn,int rollback) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void agregarDireccionAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.commonapp.dto.WsDireccionInDTO WsDireccionesIn,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}AltaCliente   */

  public com.tmmas.cl.scl.commonapp.dto.WsAltaClienteOutDTO altaCliente(com.tmmas.cl.scl.commonapp.dto.WsCuentaInNDTO cuenta,int rollback) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void altaClienteAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.commonapp.dto.WsCuentaInNDTO cuenta,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getListadoBancosPAC   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListBancoOutDTO getListadoBancosPAC() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getListadoBancosPACAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getSSincluidosEnPlan   */

  public com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WsOutSSuplementariosDTO getSSincluidosEnPlan(java.lang.String codigoPlanTarifario) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getSSincluidosEnPlanAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String codigoPlanTarifario) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}obtieneListaTienda   */

  public com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.ArrayOfTiendaDTO_Literal obtieneListaTienda() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void obtieneListaTiendaAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}setAgregaEliminaSS   */

  public com.tmmas.cl.scl.commonapp.dto.SSuplementarioOutDTO setAgregaEliminaSS(com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.ArrayOfWsAgregaEliminaSSInDTO_Literal sSuplemenAgregar,com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.ArrayOfWsAgregaEliminaSSInDTO_Literal sSuplemenEliminar,java.lang.Long NumeroCelular,java.lang.String NomUsuario,int rollback) throws java.rmi.RemoteException;
    public void setAgregaEliminaSSAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.ArrayOfWsAgregaEliminaSSInDTO_Literal sSuplemenAgregar,com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.ArrayOfWsAgregaEliminaSSInDTO_Literal sSuplemenEliminar,java.lang.Long NumeroCelular,java.lang.String NomUsuario,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}AltaDeLineaBusito   */

  public com.tmmas.cl.scl.spnsclwscommon.busito.dto.AltaDeLineaBusitoOutDTO altaDeLineaBusito(com.tmmas.cl.scl.spnsclwscommon.busito.dto.AltaDeLineaBusitoInDTO altaDeLineaBusitoIn) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void altaDeLineaBusitoAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.spnsclwscommon.busito.dto.AltaDeLineaBusitoInDTO altaDeLineaBusitoIn) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}aceptacionVenta   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.AceptacionVentaOutDTO aceptacionVenta(com.tmmas.cl.scl.spnsclwscommon.commonapp.dto.in.WsAceptacionVentaInDTO aceptacionVenta,int rollback) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void aceptacionVentaAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.spnsclwscommon.commonapp.dto.in.WsAceptacionVentaInDTO aceptacionVenta,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getSSOpcionalesAlPlan   */

  public com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WsOutSSuplementariosDTO getSSOpcionalesAlPlan(java.lang.String codigoPlanTarifario,java.lang.String codigoArticulo,java.lang.String codigCentral) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getSSOpcionalesAlPlanAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String codigoPlanTarifario,java.lang.String codigoArticulo,java.lang.String codigCentral) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}cierreVenta   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.CierreVentaOutDTO cierreVenta(com.tmmas.cl.scl.spnsclwscommon.commonapp.dto.in.WsCierreVentaInDTO cierreVenta,int rollback) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void cierreVentaAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.spnsclwscommon.commonapp.dto.in.WsCierreVentaInDTO cierreVenta,int rollback) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getDatosDireccion   */

  public com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.WsDatosDireccionOutDTO getDatosDireccion(com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.DireccionDTO direccionDTO) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getDatosDireccionAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.DireccionDTO direccionDTO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}insertarTipificacion   */

  public com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.WsInsertTipificacionOutDTO insertarTipificacion(com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.TipificaClientizaDTO tipificaClientizaDTO) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void insertarTipificacionAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.TipificaClientizaDTO tipificaClientizaDTO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getTiposIdentificacion   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListadoTiposIdentificacionOutDTO getTiposIdentificacion() throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getTiposIdentificacionAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}updateTienda   */

  public com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.WsUpdateTiendaOutDTO updateTienda(com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.TiendaDTO tiendaModDTO) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void updateTiendaAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.ventadeaccesorios.businessobject.dto.TiendaDTO tiendaModDTO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}recuperarAltaAsincrono   */

  public com.tmmas.cl.scl.commonapp.dto.WsCunetaAltaDeLineaOutDTO recuperarAltaAsincrono(java.lang.String id_Transaccion) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void recuperarAltaAsincronoAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String id_Transaccion) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getListadoProvincias   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListadoProvinciasOutDTO getListadoProvincias(com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.RegionDTO regionDTO) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getListadoProvinciasAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.RegionDTO regionDTO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}getListadoComunas   */

  public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListadoComunasOutDTO getListadoComunas(com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.CiudadDTO ciudadDTO) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void getListadoComunasAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.CiudadDTO ciudadDTO) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://com/tmmas/cl/scl/spnsclws/ws}ProcesoDeFacturacion   */

  public com.tmmas.cl.scl.commonapp.dto.WsFacturacionVentaOutDTO procesoDeFacturacion(com.tmmas.cl.scl.commonapp.dto.WsFacturacionVentaInDTO wsFacturacionVentaIn,int rollback) throws java.rmi.RemoteException, com.tmmas.cl.framework.exception.GeneralException;
    public void procesoDeFacturacionAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.tmmas.cl.scl.commonapp.dto.WsFacturacionVentaInDTO wsFacturacionVentaIn,int rollback) throws java.rmi.RemoteException ;
  
}