package com.tmmas.cl.scl.spnsclws.pa;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Sat Oct 29 16:51:36 CLST 2011  
 */

public interface SpnSclWSService extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: SpnSclWSSoapPort  
     // Port Type: SpnSclWS   
     //***********************************
     
  /**
   * returns SpnSclWSSoapPort port in this service 
   */
  com.tmmas.cl.scl.spnsclws.pa.SpnSclWS getSpnSclWSSoapPort() throws javax.xml.rpc.ServiceException;

  /**
   * @deprecated Use getSpnSclWSSoapPort(byte[] username, byte[] password);
   */
  com.tmmas.cl.scl.spnsclws.pa.SpnSclWS getSpnSclWSSoapPort(String username, String password) throws javax.xml.rpc.ServiceException;

  com.tmmas.cl.scl.spnsclws.pa.SpnSclWS getSpnSclWSSoapPort(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
    
  }