/*
 * Generated by XDoclet - Do not edit!
 */
package com;

/**
 * Home interface for My.
 * @generated 
 * @wtp generated
 */
public interface MyHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/My";
   public static final String JNDI_NAME="My";

   public com.My create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
