/*
 * Generated by XDoclet - Do not edit!
 */
package com;

/**
 * Local home interface for My.
 * @generated 
 * @wtp generated
 */
public interface MyLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MyLocal";
   public static final String JNDI_NAME="MyLocal";

   public com.MyLocal create()
      throws javax.ejb.CreateException;

}
