/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.bean.ejb.session;

/**
 * Local home interface for CusRelManFacade.
 * @generated 
 * @wtp generated
 */
public interface CusRelManFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CusRelManFacadeLocal";
   public static final String JNDI_NAME="CusRelManFacadeLocal";

   public com.tmmas.scl.operations.crm.bean.ejb.session.CusRelManFacadeLocal create()
      throws javax.ejb.CreateException;

}
