/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.logistica.negocio.ejb.session;

/**
 * Local home interface for LogisticaFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface LogisticaFacadeSTLLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LogisticaFacadeSTLLocal";
   public static final String JNDI_NAME="LogisticaFacadeSTLLocal";

   public com.tmmas.cl.scl.logistica.negocio.ejb.session.LogisticaFacadeSTLLocal create()
      throws javax.ejb.CreateException;

}
