/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.doblecuenta.negocio.ejb.session;

/**
 * Home interface for DobleCuentaFacade.
 * @generated 
 * @wtp generated
 */
public interface DobleCuentaFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/DobleCuentaFacade";
   public static final String JNDI_NAME="DobleCuentaFacade";

   public com.tmmas.scl.doblecuenta.negocio.ejb.session.DobleCuentaFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
