GRANT EXECUTE ON IC_DETALLEMOVIMIENTO_TO_SP_PG TO MAS_ADMIN_RO
/
GRANT EXECUTE ON IC_DETALLEMOVIMIENTO_TO_SP_PG TO MAS_APPLICATION_RO
/
GRANT EXECUTE ON IC_DETALLEMOVIMIENTO_TO_SP_PG TO MAS_SELECT_RO
/
