GRANT EXECUTE ON IC_GENERACOMANDO_PG TO MAS_ADMIN_RO
/
GRANT EXECUTE ON IC_GENERACOMANDO_PG TO MAS_APPLICATION_RO
/
GRANT EXECUTE ON IC_GENERACOMANDO_PG TO MAS_SELECT_RO
/
GRANT EXECUTE ON IC_GENERACOMANDO_PG TO SISCEL
/
