GRANT EXECUTE ON IC_PROVISION_PG TO MAS_ADMIN_RO
/
GRANT EXECUTE ON IC_PROVISION_PG TO MAS_APPLICATION_RO
/
GRANT EXECUTE ON IC_PROVISION_PG TO MAS_SELECT_RO
/
GRANT EXECUTE ON IC_PROVISION_PG TO SISCEL
/
GRANT EXECUTE ON IC_PROVISION_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON IC_PROVISION_PG TO SISCEL_PV
/
GRANT EXECUTE ON IC_PROVISION_PG TO SISCEL_SELECT
/
