GRANT EXECUTE ON IC_PROVISION_LST_QT TO SISCEL
/
GRANT EXECUTE ON IC_PROVISION_LST_QT TO SISCEL_ADMIN
/
GRANT EXECUTE ON IC_PROVISION_LST_QT TO SISCEL_PV
/
GRANT EXECUTE ON IC_PROVISION_LST_QT TO SISCEL_SELECT
/
