GRANT EXECUTE ON IC_SECTRANSACCION_SP_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON IC_SECTRANSACCION_SP_PG TO SISCEL_IC
/
GRANT EXECUTE ON IC_SECTRANSACCION_SP_PG TO SISCEL_PV
/
GRANT EXECUTE ON IC_SECTRANSACCION_SP_PG TO SISCEL_SELECT
/
