GRANT EXECUTE ON  SE_PROD_PROVISIONADO_TO_SP_PG TO MAS_ADMIN_RO
/
GRANT EXECUTE ON  SE_PROD_PROVISIONADO_TO_SP_PG TO MAS_APPLICATION_RO
/
GRANT EXECUTE ON  SE_PROD_PROVISIONADO_TO_SP_PG TO MAS_SELECT_RO
/
GRANT EXECUTE ON  SE_PROD_PROVISIONADO_TO_SP_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON  SE_PROD_PROVISIONADO_TO_SP_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON  SE_PROD_PROVISIONADO_TO_SP_PG TO SISCEL_PV
/
GRANT EXECUTE ON  SE_PROD_PROVISIONADO_TO_SP_PG TO SISCEL
/