GRANT EXECUTE ON SV_LISTA_CONTRATADA_PG TO MAS_ADMIN_RO
/
GRANT EXECUTE ON SV_LISTA_CONTRATADA_PG TO MAS_APPLICATION_RO
/
GRANT EXECUTE ON SV_LISTA_CONTRATADA_PG TO MAS_SELECT_RO
/
GRANT EXECUTE ON SV_LISTA_CONTRATADA_PG TO SISCEL
/
GRANT EXECUTE ON SV_LISTA_CONTRATADA_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON SV_LISTA_CONTRATADA_PG TO SISCEL_PV
/
GRANT EXECUTE ON SV_LISTA_CONTRATADA_PG TO SISCEL_SELECT
/
