GRANT EXECUTE ON SV_PROD_CONTRA_QT TO MAS_ADMIN_RO
/
GRANT EXECUTE ON SV_PROD_CONTRA_QT TO MAS_APPLICATION_RO
/
GRANT EXECUTE ON SV_PROD_CONTRA_QT TO MAS_SELECT_RO
/
GRANT EXECUTE ON SV_PROD_CONTRA_QT TO SISCEL
/
GRANT EXECUTE ON SV_PROD_CONTRA_QT TO SISCEL_ADMIN
/
GRANT EXECUTE ON SV_PROD_CONTRA_QT TO SISCEL_PV
/
GRANT EXECUTE ON SV_PROD_CONTRA_QT TO SISCEL_SELECT
/
