CREATE OR REPLACE PACKAGE GE_JUSTIFICACION_DOCUM_D_PG
IS

 FUNCTION GE_ELIMINAR_FN
               (
                EV_valor ge_valores_dominios_td.valor%TYPE
               )
 RETURN NUMBER;

END GE_JUSTIFICACION_DOCUM_D_PG;
/
SHOW ERRORS
