CREATE OR REPLACE PACKAGE PS_TIPO_COMPORTAMIENTO_D_PG
IS

 FUNCTION PS_ELIMINAR_FN
               (
                EV_valor GE_VALORES_dominios_td.valor%TYPE
               )
 RETURN NUMBER;

END PS_TIPO_COMPORTAMIENTO_D_PG;
/
SHOW ERRORS
