CREATE OR REPLACE PACKAGE body PV_CONSULTAS_USER_WLOGIC_PG IS
PROCEDURE PV_REC_IND_LOGIN(EV_NOM_USUARIO IN VARCHAR2, SN_ind_login OUT NOCOPY NUMBER)
IS
BEGIN
   SELECT U.FIRST_LOGIN
   INTO SN_ind_login
   FROM USER_SECURITY U
   WHERE U.USER_NAME = EV_NOM_USUARIO;
END PV_REC_IND_LOGIN;
END PV_CONSULTAS_USER_WLOGIC_PG;
/
SHOW ERRORS