/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.gte.pagoonlineejb.session;

/**
 * Local home interface for PagoOnLineFacade.
 * @generated 
 * @wtp generated
 */
public interface PagoOnLineFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PagoOnLineFacadeLocal";
   public static final String JNDI_NAME="PagoOnLineFacadeLocal";

   public com.tmmas.gte.pagoonlineejb.session.PagoOnLineFacadeLocal create()
      throws javax.ejb.CreateException;

}
