/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.gte.pagoonlineejb.session;

/**
 * Home interface for PagoOnLineFacade.
 * @generated 
 * @wtp generated
 */
public interface PagoOnLineFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PagoOnLineFacade";
   public static final String JNDI_NAME="PagoOnLineFacade";

   public com.tmmas.gte.pagoonlineejb.session.PagoOnLineFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
