/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.gte.pagoonlinews.session;

/**
 * Remote interface for PagoOnLineWS.
 * @generated 
 * @wtp generated
 */
public interface PagoOnLineWS
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.pagoonlinecommon.dto.RespuestaPagoDTO aplicarPagoOnLine( com.tmmas.gte.pagoonlinecommon.dto.PagoDTO inParam0 )
      throws com.tmmas.gte.pagoonlinecommon.exception.PagoOnLineException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.pagoonlinecommon.dto.RespuestaReversaDTO reversarPagoOnLine( com.tmmas.gte.pagoonlinecommon.dto.ReversaDTO inParam0 )
      throws com.tmmas.gte.pagoonlinecommon.exception.PagoOnLineException, java.rmi.RemoteException;
   
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

}
