GRANT SELECT ON AL_GAMA_VW TO GE_ADMIN_RO
/
GRANT SELECT ON AL_GAMA_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON AL_GAMA_VW TO SISCEL
/
GRANT SELECT ON AL_GAMA_VW TO SISCEL_ADMIN
/
GRANT SELECT ON AL_GAMA_VW TO SISCEL_SELECT
/