GRANT SELECT ON AL_PARAMETROS_MULTIPLES_VW TO GE_ADMIN_RO
/
GRANT SELECT ON AL_PARAMETROS_MULTIPLES_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON AL_PARAMETROS_MULTIPLES_VW TO SISCEL
/
GRANT SELECT ON AL_PARAMETROS_MULTIPLES_VW TO SISCEL_SELECT
/
