GRANT SELECT ON CO_DOCTOS_PAGO_VALI_VW TO GE_ADMIN_RO
/
GRANT SELECT ON CO_DOCTOS_PAGO_VALI_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON CO_DOCTOS_PAGO_VALI_VW TO SISCEL
/
GRANT SELECT ON CO_DOCTOS_PAGO_VALI_VW TO SISCEL_ADMIN
/
GRANT SELECT ON CO_DOCTOS_PAGO_VALI_VW TO SISCEL_SELECT
/
