GRANT SELECT ON CO_PARAMETROS_SISTEMA_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON CO_PARAMETROS_SISTEMA_VW TO SISCEL
/
GRANT SELECT ON CO_PARAMETROS_SISTEMA_VW TO SISCEL_ADMIN
/
GRANT SELECT ON CO_PARAMETROS_SISTEMA_VW TO SISCEL_GA
/
GRANT SELECT ON CO_PARAMETROS_SISTEMA_VW TO SISCEL_PV
/
GRANT SELECT ON CO_PARAMETROS_SISTEMA_VW TO SISCEL_SELECT
/
