GRANT EXECUTE ON FA_FACTOR_TIPO_UNIDAD_D_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON FA_FACTOR_TIPO_UNIDAD_D_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON FA_FACTOR_TIPO_UNIDAD_D_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_FACTOR_TIPO_UNIDAD_D_PG TO SISCEL_FA
/
