GRANT EXECUTE ON FA_NIVEL_IMPRESION_D_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON FA_NIVEL_IMPRESION_D_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_NIVEL_IMPRESION_D_PG TO SISCEL_FA
/
GRANT EXECUTE ON FA_NIVEL_IMPRESION_D_PG TO SISCEL_SELECT
/
