GRANT SELECT ON FA_PARAMETROS_MULTIPLES_VW TO GE_ADMIN_RO
/
GRANT SELECT ON FA_PARAMETROS_MULTIPLES_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON FA_PARAMETROS_MULTIPLES_VW TO SISCEL_ADMIN
/
GRANT SELECT ON FA_PARAMETROS_MULTIPLES_VW TO SISCEL_SELECT
/