GRANT EXECUTE ON FA_PARAMETROS_SIMPLES_U_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON FA_PARAMETROS_SIMPLES_U_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON FA_PARAMETROS_SIMPLES_U_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PARAMETROS_SIMPLES_U_PG TO SISCEL_FA
/
