GRANT SELECT ON FA_PARAMETROS_SIMPLES_VW TO GE_ADMIN_RO
/
GRANT SELECT ON FA_PARAMETROS_SIMPLES_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON FA_PARAMETROS_SIMPLES_VW TO SISCEL
/
GRANT SELECT ON FA_PARAMETROS_SIMPLES_VW TO SISCEL_FA
/
GRANT SELECT ON FA_PARAMETROS_SIMPLES_VW TO SISCEL_SELECT
/
