GRANT EXECUTE ON FA_TIPO_GRUPO_U_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON FA_TIPO_GRUPO_U_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_TIPO_GRUPO_U_PG TO SISCEL_FA
/
GRANT EXECUTE ON FA_TIPO_GRUPO_U_PG TO SISCEL_SELECT
/
