GRANT EXECUTE ON FA_TIPO_UNIDAD_I_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON FA_TIPO_UNIDAD_I_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_TIPO_UNIDAD_I_PG TO SISCEL_FA
/
GRANT EXECUTE ON FA_TIPO_UNIDAD_I_PG TO SISCEL_SELECT
/
