GRANT SELECT ON FA_TIPO_UNIDAD_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON FA_TIPO_UNIDAD_VW TO SISCEL_ADMIN
/
GRANT SELECT ON FA_TIPO_UNIDAD_VW TO SISCEL_FA
/
GRANT SELECT ON FA_TIPO_UNIDAD_VW TO SISCEL_SELECT
/
