GRANT EXECUTE ON GA_CAUSAS_DESCUENTOS_D_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON GA_CAUSAS_DESCUENTOS_D_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON GA_CAUSAS_DESCUENTOS_D_PG TO SISCEL
/
GRANT EXECUTE ON GA_CAUSAS_DESCUENTOS_D_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_CAUSAS_DESCUENTOS_D_PG TO SISCEL_SELECT
/
