GRANT SELECT ON GA_CAUSAS_DESCUENTOS_VW TO GE_ADMIN_RO
/
GRANT SELECT ON GA_CAUSAS_DESCUENTOS_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON GA_CAUSAS_DESCUENTOS_VW TO SISCEL
/
GRANT SELECT ON GA_CAUSAS_DESCUENTOS_VW TO SISCEL_ADMIN
/
GRANT SELECT ON GA_CAUSAS_DESCUENTOS_VW TO SISCEL_SELECT
/
