GRANT EXECUTE ON GA_CLIENTES_MAYORISTAS_D_PG TO EBZ_SISCEL
/
GRANT EXECUTE ON GA_CLIENTES_MAYORISTAS_D_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON GA_CLIENTES_MAYORISTAS_D_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON GA_CLIENTES_MAYORISTAS_D_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_CLIENTES_MAYORISTAS_D_PG TO SISCEL_SELECT
/
