GRANT EXECUTE ON GA_PARAMETROS_SIMPLES_D_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON GA_PARAMETROS_SIMPLES_D_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON GA_PARAMETROS_SIMPLES_D_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_PARAMETROS_SIMPLES_D_PG TO SISCEL_SELECT
/
