GRANT SELECT ON GE_PARAMETROS_SISTEMA_VW TO GE_ADMIN_RO
/
GRANT SELECT ON GE_PARAMETROS_SISTEMA_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON GE_PARAMETROS_SISTEMA_VW TO SISCEL_ADMIN
/
GRANT SELECT ON GE_PARAMETROS_SISTEMA_VW TO SISCEL_SELECT
/
GRANT SELECT ON GE_PARAMETROS_SISTEMA_VW TO SISCEL
/
