GRANT SELECT ON GE_PARAMETROS_MULTIPLES_KNL_VW TO GE_CONSULTA_RO
/
GRANT INSERT ON GE_PARAMETROS_MULTIPLES_KNL_VW TO OPS$SQLPARAM
/
GRANT SELECT ON GE_PARAMETROS_MULTIPLES_KNL_VW TO OPS$SQLPARAM
/
GRANT UPDATE ON GE_PARAMETROS_MULTIPLES_KNL_VW TO OPS$SQLPARAM
/
