GRANT SELECT ON GE_TABLAS_DOMINIOS_SCL_VW TO GE_ADMIN_RO
/
GRANT SELECT ON GE_TABLAS_DOMINIOS_SCL_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON GE_TABLAS_DOMINIOS_SCL_VW TO SISCEL
/
GRANT SELECT ON GE_TABLAS_DOMINIOS_SCL_VW TO SISCEL_ADMIN
/
GRANT SELECT ON GE_TABLAS_DOMINIOS_SCL_VW TO SISCEL_SELECT
/
