GRANT SELECT ON GE_TIPO_PLATAFORM_COMER_VW TO GE_ADMIN_RO
/
GRANT SELECT ON GE_TIPO_PLATAFORM_COMER_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON GE_TIPO_PLATAFORM_COMER_VW TO SISCEL_ADMIN
/
GRANT SELECT ON GE_TIPO_PLATAFORM_COMER_VW TO SISCEL_SELECT
/
