GRANT EXECUTE ON IC_PARAMETROS_MULTIPLES_I_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON IC_PARAMETROS_MULTIPLES_I_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON IC_PARAMETROS_MULTIPLES_I_PG TO SISCEL
/
GRANT EXECUTE ON IC_PARAMETROS_MULTIPLES_I_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON IC_PARAMETROS_MULTIPLES_I_PG TO SISCEL_SELECT
/
