GRANT SELECT ON IC_PARAMETROS_MULTIPLES_VW TO GE_ADMIN_RO
/
GRANT SELECT ON IC_PARAMETROS_MULTIPLES_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON IC_PARAMETROS_MULTIPLES_VW TO MAS_SERVICE_DML
/
GRANT SELECT ON IC_PARAMETROS_MULTIPLES_VW TO SISCEL
/
GRANT SELECT ON IC_PARAMETROS_MULTIPLES_VW TO SISCEL_ADMIN
/
GRANT SELECT ON IC_PARAMETROS_MULTIPLES_VW TO SISCEL_SELECT
/
