GRANT SELECT ON PF_CANAL_DISTRIBUCION_VW TO GE_ADMIN_RO
/
GRANT SELECT ON PF_CANAL_DISTRIBUCION_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON PF_CANAL_DISTRIBUCION_VW TO SISCEL_ADMIN
/
GRANT SELECT ON PF_CANAL_DISTRIBUCION_VW TO SISCEL_SELECT
/
