GRANT SELECT ON PS_TIPO_COMPORTAMIENTO_VW TO GE_ADMIN_RO
/
GRANT SELECT ON PS_TIPO_COMPORTAMIENTO_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON PS_TIPO_COMPORTAMIENTO_VW TO SISCEL_ADMIN
/
GRANT SELECT ON PS_TIPO_COMPORTAMIENTO_VW TO SISCEL_SELECT
/
