GRANT EXECUTE ON PS_TIPO_COMPORTAMIENTO_I_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON PS_TIPO_COMPORTAMIENTO_I_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON PS_TIPO_COMPORTAMIENTO_I_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PS_TIPO_COMPORTAMIENTO_I_PG TO SISCEL_SELECT
/
