GRANT EXECUTE ON PV_CONSULTAS_USER_WLOGIC_PG  TO SISCEL_SELECT
/
GRANT EXECUTE ON PV_CONSULTAS_USER_WLOGIC_PG  TO  SISCEL_ADMIN
/
GRANT EXECUTE ON PV_CONSULTAS_USER_WLOGIC_PG  TO  SISCEL_GA
/
GRANT EXECUTE ON PV_CONSULTAS_USER_WLOGIC_PG  TO SISCEL_VE
/