GRANT EXECUTE ON RA_PROCESO_AUDITORIA_U_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON RA_PROCESO_AUDITORIA_U_PG TO RA_SELECT_RO
/
GRANT EXECUTE ON RA_PROCESO_AUDITORIA_U_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON RA_PROCESO_AUDITORIA_U_PG TO SISCEL_SELECT
/
