GRANT SELECT ON RA_TIPO_AUDITORIA_VW TO GE_ADMIN_RO
/
GRANT SELECT ON RA_TIPO_AUDITORIA_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON RA_TIPO_AUDITORIA_VW TO MAS_REPORTES
/
GRANT SELECT ON RA_TIPO_AUDITORIA_VW TO RA_SELECT_RO
/
GRANT SELECT ON RA_TIPO_AUDITORIA_VW TO SISCEL_ADMIN
/
GRANT SELECT ON RA_TIPO_AUDITORIA_VW TO SISCEL_SELECT
/
