GRANT EXECUTE ON RA_TIPO_AUDITORIA_U_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON RA_TIPO_AUDITORIA_U_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON RA_TIPO_AUDITORIA_U_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON RA_TIPO_AUDITORIA_U_PG TO SISCEL_SELECT
/
