GRANT EXECUTE ON SE_CATEGORIAS_DESTINO_D_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON SE_CATEGORIAS_DESTINO_D_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON SE_CATEGORIAS_DESTINO_D_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON SE_CATEGORIAS_DESTINO_D_PG TO SISCEL_SELECT
/
