GRANT SELECT ON SE_CATEGORIAS_DESTINO_VW TO GE_ADMIN_RO
/
GRANT SELECT ON SE_CATEGORIAS_DESTINO_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON SE_CATEGORIAS_DESTINO_VW TO SISCEL_ADMIN
/
GRANT SELECT ON SE_CATEGORIAS_DESTINO_VW TO SISCEL_SELECT
/
