GRANT SELECT ON SE_TIPO_SERVICIO_VW TO GE_ADMIN_RO
/
GRANT SELECT ON SE_TIPO_SERVICIO_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON SE_TIPO_SERVICIO_VW TO SISCEL_ADMIN
/
GRANT SELECT ON SE_TIPO_SERVICIO_VW TO SISCEL_SELECT
/
