GRANT EXECUTE ON SE_TIPO_LISTA_ALTAMIRA_U_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON SE_TIPO_LISTA_ALTAMIRA_U_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON SE_TIPO_LISTA_ALTAMIRA_U_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON SE_TIPO_LISTA_ALTAMIRA_U_PG TO SISCEL_SELECT
/
