GRANT EXECUTE ON VE_PARAMETROS_SIMPLES_D_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON VE_PARAMETROS_SIMPLES_D_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON VE_PARAMETROS_SIMPLES_D_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_PARAMETROS_SIMPLES_D_PG TO SISCEL_SELECT
/
