GRANT SELECT ON VE_PARAMETROS_SIMPLES_VW TO GE_ADMIN_RO
/
GRANT SELECT ON VE_PARAMETROS_SIMPLES_VW TO GE_CONSULTA_RO
/
GRANT SELECT ON VE_PARAMETROS_SIMPLES_VW TO SISCEL
/
GRANT SELECT ON VE_PARAMETROS_SIMPLES_VW TO SISCEL_ADMIN
/
GRANT SELECT ON VE_PARAMETROS_SIMPLES_VW TO SISCEL_SELECT
/
