/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.o.csr.supcusintman.bean.ejb.session;

/**
 * Remote interface for SupCusIntManFacade.
 * @generated 
 * @wtp generated
 */
public interface SupCusIntManFacade
   extends javax.ejb.EJBObject
{
   /**
    * Valida cuenta personal <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO validaCuentaPersonal( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.CuentaPersonalDTO cuenta )
      throws com.tmmas.scl.operations.crm.o.csr.supcusintman.common.exception.SupCusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.serviceDomain.serviceABE.businessObject.dataTransferObject.NumeroDTO obtenerTipoNumero( com.tmmas.scl.framework.serviceDomain.serviceABE.businessObject.dataTransferObject.NumeroDTO numero )
      throws com.tmmas.scl.operations.crm.o.csr.supcusintman.common.exception.SupCusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO validarCliente( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.o.csr.supcusintman.common.exception.SupCusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RestriccionesContratacionListDTO obtenerRestriccionesContratacion( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RestriccionesContratacionDTO restriccionesContratacion )
      throws com.tmmas.scl.operations.crm.o.csr.supcusintman.common.exception.SupCusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO validarContratanteBeneficiario( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ContratanteBeneficiarioDTO contratanteBeneficiarioDTO )
      throws com.tmmas.scl.operations.crm.o.csr.supcusintman.common.exception.SupCusIntManException, java.rmi.RemoteException;

}
