/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.o.csr.supcusintman.bean.ejb.session;

/**
 * Home interface for SupCusIntManFacade.
 * @generated 
 * @wtp generated
 */
public interface SupCusIntManFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SupCusIntManFacade";
   public static final String JNDI_NAME="SupCusIntManFacade";

   public com.tmmas.scl.operations.crm.o.csr.supcusintman.bean.ejb.session.SupCusIntManFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
