CREATE OR REPLACE TYPE                  CU_BENEF_PROD_QT AS OBJECT
(
  COD_CLIENTE_CONTRATANTE NUMBER(38),
  NUM_ABONADO_CONTRATANTE NUMBER(38),
  TIPO_COMPORTAMIENTO VARCHAR2(5),
  FEC_INICIO_VIGENCIA DATE,
  NUM_ABONADO_BENEFICIARIO NUMBER(38),
  FEC_TERMINO_VIGENCIA DATE,
  NUM_CELULAR NUMBER(15),
  NOMBRE VARCHAR2(50)
)
/
SHOW ERRORS
