CREATE OR REPLACE TYPE CU_VETADOS_PROD_QT AS OBJECT
(
  COD_CLIENTE           NUMBER(38),
  NUM_ABONADO           NUMBER(8),
  TIPO_COMPORTAMIENTO   VARCHAR2(5 BYTE),
  FEC_INICIO_VIGENCIA   DATE,
  FEC_TERMINO_VIGENCIA  DATE
);
/
SHOW ERRORS
