/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.osr.mancusinv.bean.ejb.session;

/**
 * Remote interface for ManCusInvFacade.
 * @generated 
 * @wtp generated
 */
public interface ManCusInvFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.ProductoContratadoListDTO obtenerProductoContratado( com.tmmas.scl.framework.customerDomain.customerOrderABE.dataTransferObject.OrdenServicioDTO ordenServicio )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.PaqueteContratadoDTO obtenerProductoContratadoPorPaquete( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.PaqueteContratadoDTO paqueteContratado )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.serviceDomain.serviceABE.businessObject.dataTransferObject.NumeroDTO obtieneModificacionesProducto( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.ProductoContratadoDTO productoContratado )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ManCusInvException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO crearListaNumeros( com.tmmas.scl.framework.serviceDomain.serviceABE.businessObject.dataTransferObject.NumeroListDTO listaNumeros )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ManCusInvException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO eliminarListaNumeros( com.tmmas.scl.framework.serviceDomain.serviceABE.businessObject.dataTransferObject.NumeroListDTO listaNumeros )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ManCusInvException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.ProductoContratadoListDTO obtenerDetalleProductoContratado( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.ProductoContratadoListDTO listaProductos )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ManCusInvException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.serviceDomain.serviceABE.businessObject.dataTransferObject.NumeroListDTO obtenerListaNumeros( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.ProductoContratadoDTO productoContratado )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ManCusInvException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.CantidadProductoContratadoDTO obtieneCantidadProductosContratados( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.CantidadProductoContratadoDTO producto )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ManCusInvException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO informarLC( com.tmmas.scl.framework.productDomain.productSpecificationABE.dataTransferObject.LimiteConsumoPlanAdicionalListDTO LimConsLista )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ManCusInvException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO actualizarLC( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.ProductoContratadoListDTO prodList )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ManCusInvException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO cambiarLC( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.ProductoContratadoListDTO prodList )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ManCusInvException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO informarAbonoLimiteConsumo( com.tmmas.scl.framework.productDomain.productSpecificationABE.dataTransferObject.AbonoLimiteConsumoListDTO listaAbonoLimiteConsumo )
      throws com.tmmas.scl.operations.crm.osr.mancusinv.common.exception.ManCusInvException, java.rmi.RemoteException;

}
