/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.osr.mancusinv.bean.ejb.session;

/**
 * Local interface for ManCusInvFacade.
 * @generated 
 * @wtp generated
 */
public interface ManCusInvFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
