set echo off verify off

spool $WORKDIR/tab_PF_TOLTARIFICA_&1.log

prompt Table  PF_TOLTARIFICA_&1

CREATE TABLE PF_TOLTARIFICA_&1
(
  SEC_EMPA          VARCHAR2(30),
  SEC_CDR           VARCHAR2(6),
  RECORD_TYPE       VARCHAR2(2),
  A_SUSC_NUMBER     VARCHAR2(15),
  A_SUSC_MS_NUMBER  VARCHAR2(15),
  B_SUSC_NUMBER     VARCHAR2(18),
  B_SUSC_MS_NUMBER  VARCHAR2(15),
  A_CATEGORY        NUMBER(2),
  DATE_START_CHARG  VARCHAR2(8),
  TIME_START_CHARG  VARCHAR2(6),
  CHARGABLE_DURAT   VARCHAR2(6),
  DATE_SEND_CHARG   VARCHAR2(6),
  TIME_SEND_CHARG   VARCHAR2(6),
  SEND_DURAT        VARCHAR2(6),
  COD_CCC           VARCHAR2(5),
  OUTGOING_ROUTE    VARCHAR2(7),
  INCOMING_ROUTE    VARCHAR2(7),
  INSI_CODE         VARCHAR2(16),
  COD_AGRL          VARCHAR2(5),
  COD_SENT          VARCHAR2(5),
  COD_LLAM          VARCHAR2(5),
  COD_TDIR          VARCHAR2(5),
  COD_TCOR          VARCHAR2(5),
  COD_THOR          VARCHAR2(5),
  COD_TDIA          VARCHAR2(5),
  COD_FCOB          VARCHAR2(5),
  IND_TABLA         VARCHAR2(5),
  COD_CARG          NUMBER(5),
  COD_CARR          VARCHAR2(5),
  COD_GRUPO         NUMBER(8)                   NOT NULL,
  NUM_CLIE          NUMBER(8)                   NOT NULL,
  NUM_ABON          NUMBER(8)                   NOT NULL,
  COD_PLAN          VARCHAR2(5),
  COD_CICL          NUMBER(5),
  COD_AREAC         VARCHAR2(5),
  COD_ALMC          VARCHAR2(5),
  COD_LIMITE        VARCHAR2(5),
  IND_APLICA        VARCHAR2(5),
  COD_BOLSA         VARCHAR2(5),
  IND_APLB          VARCHAR2(5),
  COD_OPERA         VARCHAR2(5),
  COD_TOPRA         VARCHAR2(5),
  COD_DOPERA        VARCHAR2(5),
  COD_TRANA         VARCHAR2(5),
  COD_ALMA          VARCHAR2(5),
  COD_AREAA         VARCHAR2(5),
  COD_LOCAA         VARCHAR2(5),
  COD_OPERB         VARCHAR2(5),
  COD_TOPRB         VARCHAR2(5),
  COD_DOPEB         VARCHAR2(5),
  COD_TRANB         VARCHAR2(5),
  COD_ALMB          VARCHAR2(5),
  COD_AREAB         VARCHAR2(5),
  COD_LOCAB         VARCHAR2(5),
  COD_PAIS          VARCHAR2(5),
  COD_SUBFRANJA     VARCHAR2(5),
  IND_DCTO_MLIB     VARCHAR2(1),
  IND_MUESTRA_LLAM  VARCHAR2(1),
  DUR_REAL          NUMBER(6)                   DEFAULT 0,
  NUM_PULSO         NUMBER(6)                   DEFAULT 0,
  TIP_MONE          VARCHAR2(5),
  MTO_REAL          NUMBER(15,5),
  TIP_DCTO          VARCHAR2(5),
  COD_DCTO          VARCHAR2(5),
  ITM_DCTO          VARCHAR2(5),
  DUR_DCTO          NUMBER(6),
  MTO_FACT          NUMBER(15,5),
  MTO_DCTO          NUMBER(15,5),
  IND_EXEDENTE      VARCHAR2(1),
  COD_UMBRAL        VARCHAR2(5),
  DES_DESTINO       VARCHAR2(30),
  COD_CICLFACT      NUMBER(8),
  IND_BILLETE       VARCHAR2(2),
  DUR_FACT          NUMBER(6)                   DEFAULT 0,
  COD_MARCA         VARCHAR2(6),
  IND_IMPRESION     VARCHAR2(2),
  VALOR_UNIDAD      NUMBER(15,5),
  DES_LLAMADA       VARCHAR2(100)  
)
TABLESPACE TOL_DETFACTURA_DATA_20041108
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL;

CREATE PUBLIC SYNONYM PF_TOLTARIFICA_&1 FOR PF_TOLTARIFICA_&1;

GRANT DELETE, INSERT, SELECT, UPDATE ON  PF_TOLTARIFICA_&1 TO SISCEL_ADMIN;

GRANT SELECT ON  PF_TOLTARIFICA_&1 TO SISCEL_SELECT;


spool off

exit;
