CREATE OR REPLACE PROCEDURE        CAMBIO_CUENTA IS
CURSOR C_CUENTA IS
       SELECT COD_DOMINIO_CTO, COD_EVENTO_CTO, COD_CONCEPTO, COD_CUENTA, COD_CONTRAP,
              NOM_USUARIO, FEC_ACTUALIZ, IND_GRP_DOMINIO, COD_OPERADORA_SCL
         FROM SC_CTO_CTA
        WHERE SUBSTR(COD_CUENTA,14,4)IN (1075,1076,1078,1079,2041,2042)
          AND SUBSTR(COD_CUENTA,4,4) != '9500';
BEGIN
       FOR I IN C_CUENTA LOOP
            UPDATE  SC_CTO_CTA
                SET COD_CUENTA = SUBSTR(COD_CUENTA,1,3)||'9500-0000-'||SUBSTR(COD_CUENTA,14,14)||'000-'||SUBSTR(COD_CUENTA,32,3)
     WHERE COD_OPERADORA_SCL = I.COD_OPERADORA_SCL
                AND COD_DOMINIO_CTO   = I.COD_DOMINIO_CTO
                AND COD_EVENTO_CTO    = I.COD_EVENTO_CTO
                AND COD_CONCEPTO      = I.COD_CONCEPTO;
    END LOOP;
       COMMIT;
END CAMBIO_CUENTA;
/
SHOW ERRORS
