CREATE OR REPLACE PROCEDURE CAMBIO_NUEVE IS
CURSOR C_CAMBIA IS
SELECT * FROM SC_CTO_CTA
WHERE SUBSTR(COD_CUENTA,14,4) = '2042'
AND SUBSTR(COD_CUENTA,19,4) != '0000';
BEGIN
     FOR I IN C_CAMBIA LOOP
	  UPDATE  SC_CTO_CTA
                SET COD_CUENTA = SUBSTR(COD_CUENTA,1,18)||'0000'||SUBSTR(COD_CUENTA,23,12)
			  WHERE COD_OPERADORA_SCL = I.COD_OPERADORA_SCL
                AND COD_DOMINIO_CTO   = I.COD_DOMINIO_CTO
                AND COD_EVENTO_CTO    = I.COD_EVENTO_CTO
                AND COD_CONCEPTO      = I.COD_CONCEPTO;
     END LOOP;
   COMMIT;
END;
/
SHOW ERRORS
