CREATE OR REPLACE PROCEDURE        EMPRESAINTAR_XTEMPX IS
  CURSOR C1 IS
   SELECT COD_EMPRESA
   FROM GA_EMPRESA WHERE COD_PRODUCTO   = 1 AND COD_CICLO=5;
  V_FECSYS DATE;
  V_ABONADO GA_ABOCEL.NUM_ABONADO%TYPE;
  V_EMPRESA GA_ABOCEL.COD_EMPRESA%TYPE;
  V_TIPPLANTARIF GA_ABOCEL.TIP_PLANTARIF%TYPE;
  VP_PROC  VARCHAR2(200);
  VP_TABLA  VARCHAR2(200);
  VP_ACT  VARCHAR2(200);
  VP_SQLCODE  VARCHAR2(200) ;
  VP_SQLERRM  VARCHAR2(200);
  VP_ERROR  VARCHAR2(200);
  --ERROR_PROCESO EXCEPTION;
BEGIN
   VP_PROC := 'P_ANULA_BAJAABO';
   VP_TABLA := 'C1';
   VP_ACT := 'O';
   OPEN C1;
   VP_ERROR := 0;
   LOOP
      FETCH C1 INTO V_EMPRESA;
      EXIT WHEN C1%NOTFOUND;
      BEGIN
	SELECT NUM_ABONADO, TIP_PLANTARIF, FEC_ALTA
        INTO V_ABONADO, V_TIPPLANTARIF, V_FECSYS
        FROM GA_ABOCEL WHERE COD_EMPRESA = V_EMPRESA
        AND TIP_PLANTARIF = 'E'
        AND ROWNUM = 1 ;
        GA_P_EMPRESA_ABONADO_XTEMPX(V_ABONADO,1,V_TIPPLANTARIF,V_EMPRESA, V_FECSYS,
		VP_PROC,VP_TABLA,VP_ACT,VP_SQLCODE, VP_SQLERRM,VP_ERROR);
        IF VP_ERROR = 4 THEN
           rollback;
           VP_ERROR := 0;
	   VP_ERROR := VP_ERROR;
        ELSIF VP_ERROR = 0 THEN
	  COMMIT;
        END IF;
      EXCEPTION
          WHEN NO_DATA_FOUND THEN
             NULL;
      END;
   END LOOP;
   dbms_output.put_line ('sale del loop de abonados');
   CLOSE C1;
   dbms_output.put_line ('sale del loop de abonados');
END;
/
SHOW ERRORS
