CREATE OR REPLACE PACKAGE BODY ER_BEUP_SOLICITUD_PG
IS
PROCEDURE ER_BEUP_SOLICITUD_PR (
 EN_NUM_SOLICITUD                      	IN ERH_SOLICITUD.NUM_SOLICITUD%TYPE
, EN_IND_TIPO_SOLICITUD                 	IN ERH_SOLICITUD.IND_TIPO_SOLICITUD%TYPE
, ED_FEC_INGRESO_H                      	IN ERH_SOLICITUD.FEC_INGRESO_H%TYPE
, ED_FEC_APROBACION_OFFLINE_H           	IN ERH_SOLICITUD.FEC_APROBACION_OFFLINE_H%TYPE
, EN_COD_ESTADO                                 IN ERH_SOLICITUD.COD_ESTADO%TYPE
, EV_NOM_USUARIO_EVALUACION             	IN ERH_SOLICITUD.NOM_USUARIO_EVALUACION%TYPE
, EV_COD_USUARIO_EVALUACION             	IN ERH_SOLICITUD.COD_USUARIO_EVALUACION%TYPE
, EV_COD_USUARIO_POSTEVALUACION         	IN ERH_SOLICITUD.COD_USUARIO_POSTEVALUACION%TYPE
, EN_IND_EVENTO                         	IN ERH_SOLICITUD.IND_EVENTO%TYPE
, EV_DES_OBS_EVALUACION                 	IN ERH_SOLICITUD.DES_OBS_EVALUACION%TYPE
, EV_DES_OBS_POSTEVALUACION             	IN ERH_SOLICITUD.DES_OBS_POSTEVALUACION%TYPE
, EN_IND_TIPO_CLIENTE                   	IN ERH_SOLICITUD.IND_TIPO_CLIENTE%TYPE
, EV_COD_BANCO                          	IN ERH_SOLICITUD.COD_BANCO%TYPE
, EV_NUM_CUENTA_CORRIENTE               	IN ERH_SOLICITUD.NUM_CUENTA_CORRIENTE%TYPE
, EV_NUM_DOCUMENTO                      	IN ERH_SOLICITUD.NUM_DOCUMENTO%TYPE
, EV_COD_TIPTARJETA                     	IN ERH_SOLICITUD.COD_TIPTARJETA%TYPE
, EN_COD_CASA_COMERCIAL                 	IN ERH_SOLICITUD.COD_CASA_COMERCIAL%TYPE
, EN_COD_ACREDITACION                  	        IN ERH_SOLICITUD.COD_ACREDITACION%TYPE
, EN_MTO_RENTA                          	IN ERH_SOLICITUD.MTO_RENTA%TYPE
, EN_IND_PERSONERIA                     	IN ERH_SOLICITUD.IND_PERSONERIA%TYPE
, EN_IND_GIRO_COMERCIAL                 	IN ERH_SOLICITUD.IND_GIRO_COMERCIAL%TYPE
, EN_COD_CATEGORIA                      	IN ERH_SOLICITUD.COD_CATEGORIA%TYPE
, EN_IND_TIPO_EMPRESA                   	IN ERH_SOLICITUD.IND_TIPO_EMPRESA%TYPE
, EN_COD_ESQUEMA                        	IN ERH_SOLICITUD.COD_ESQUEMA%TYPE
, EV_COD_OFICINA                        	IN ERH_SOLICITUD.COD_OFICINA%TYPE
, EV_COD_TIPCOMIS                       	IN ERH_SOLICITUD.COD_TIPCOMIS%TYPE
, EN_COD_VENDEDOR                       	IN ERH_SOLICITUD.COD_VENDEDOR%TYPE
, EN_COD_VENDEDOR_AGENTE                	IN ERH_SOLICITUD.COD_VENDEDOR_AGENTE%TYPE
, EN_COD_VENDEDOR_DEALER                	IN ERH_SOLICITUD.COD_VENDEDOR_DEALER%TYPE
, EV_IND_EXCEPCION_RENTA                	IN ERH_SOLICITUD.IND_EXCEPCION_RENTA%TYPE
, EV_IND_EXCEPCION_MOROSIDAD            	IN ERH_SOLICITUD.IND_EXCEPCION_MOROSIDAD%TYPE
, EV_COD_EXCEPCION                      	IN ERH_SOLICITUD.COD_EXCEPCION%TYPE
, EV_COD_APROBACION                     	IN ERH_SOLICITUD.COD_APROBACION%TYPE
, EN_COD_ESTADOFINAL                    	IN ERH_SOLICITUD.COD_ESTADOFINAL%TYPE
, EN_MTO_GARANTIA                       	IN ERH_SOLICITUD.MTO_GARANTIA%TYPE
, EV_COD_TIPIDENT                       	IN ERH_SOLICITUD.COD_TIPIDENT%TYPE
, EV_NUM_IDENT_CLIENTE                  	IN ERH_SOLICITUD.NUM_IDENT_CLIENTE%TYPE
, EV_NUM_IDENT_EMPLEADOR                    IN ERH_SOLICITUD.NUM_IDENT_EMPLEADOR%TYPE
, EN_COD_PUNTAJE				            IN ERH_SOLICITUD.COD_PUNTAJE%TYPE
, EV_COD_CALIFICACION			            IN ERH_SOLICITUD.COD_CALIFICACION%TYPE
, EV_IND_ORIGEN                             IN ERH_SOLICITUD.IND_ORIGEN%TYPE
)
IS

/*<Documentación TipoDoc = "Procedimiento">

<Elemento Nombre = "ER_BEUP_SOLICITUD_PR" Lenguaje="PL/SQL" Fecha="16-12-2005" Versión="1.0" Diseñador= Claudio Leyton"****" Programador=Patricia Astudillo"****" Ambiente="BD">

<Retorno>NA</Retorno>

<Descripción>Procedimiento que efectua inserción en las tablas ERT de data desde el trigger </Descripción>
<Parámetros>
<Entrada>
</Entrada>

<Salida>
</Salida>

</Parámetros>

</Elemento>

</Documentación>*/

BEGIN
INSERT into
ERH_SOLICITUD
    (
	NUM_SOLICITUD,
	IND_TIPO_SOLICITUD,
	FEC_INGRESO_H,
	FEC_APROBACION_OFFLINE_H,
	COD_ESTADO,
	NOM_USUARIO_EVALUACION,
	COD_USUARIO_EVALUACION,
	COD_USUARIO_POSTEVALUACION,
	IND_EVENTO,
	DES_OBS_EVALUACION,
	DES_OBS_POSTEVALUACION,
	IND_TIPO_CLIENTE,
	COD_BANCO,
	NUM_CUENTA_CORRIENTE,
	NUM_DOCUMENTO,
	COD_TIPTARJETA,
	COD_CASA_COMERCIAL,
	COD_ACREDITACION,
	MTO_RENTA,
	IND_PERSONERIA,
	IND_GIRO_COMERCIAL,
	COD_CATEGORIA,
	IND_TIPO_EMPRESA,
	COD_ESQUEMA,
	COD_OFICINA,
	COD_TIPCOMIS,
	COD_VENDEDOR,
	COD_VENDEDOR_AGENTE,
	COD_VENDEDOR_DEALER,
	IND_EXCEPCION_RENTA,
	IND_EXCEPCION_MOROSIDAD,
	COD_EXCEPCION,
	COD_APROBACION,
	COD_ESTADOFINAL,
	MTO_GARANTIA,
	COD_TIPIDENT,
	NUM_IDENT_CLIENTE,
	NUM_IDENT_EMPLEADOR,
    COD_PUNTAJE,
    COD_CALIFICACION,
    IND_ORIGEN
	)
values
    (	 EN_NUM_SOLICITUD
	, EN_IND_TIPO_SOLICITUD
	, ED_FEC_INGRESO_H
	, ED_FEC_APROBACION_OFFLINE_H
	, EN_COD_ESTADO
	, EV_NOM_USUARIO_EVALUACION
	, EV_COD_USUARIO_EVALUACION
	, EV_COD_USUARIO_POSTEVALUACION
	, EN_IND_EVENTO
	, EV_DES_OBS_EVALUACION
	, EV_DES_OBS_POSTEVALUACION
	, EN_IND_TIPO_CLIENTE
	, EV_COD_BANCO
	, EV_NUM_CUENTA_CORRIENTE
	, EV_NUM_DOCUMENTO
	, EV_COD_TIPTARJETA
	, EN_COD_CASA_COMERCIAL
	, EN_COD_ACREDITACION
	, EN_MTO_RENTA
	, EN_IND_PERSONERIA
	, EN_IND_GIRO_COMERCIAL
	, EN_COD_CATEGORIA
	, EN_IND_TIPO_EMPRESA
	, EN_COD_ESQUEMA
	, EV_COD_OFICINA
	, EV_COD_TIPCOMIS
	, EN_COD_VENDEDOR
	, EN_COD_VENDEDOR_AGENTE
	, EN_COD_VENDEDOR_DEALER
	, EV_IND_EXCEPCION_RENTA
	, EV_IND_EXCEPCION_MOROSIDAD
	, EV_COD_EXCEPCION
	, EV_COD_APROBACION
	, EN_COD_ESTADOFINAL
	, EN_MTO_GARANTIA
	, EV_COD_TIPIDENT
	, EV_NUM_IDENT_CLIENTE
	, EV_NUM_IDENT_EMPLEADOR
        , EN_COD_PUNTAJE
        , EV_COD_CALIFICACION
        , EV_IND_ORIGEN
	);

  INSERT into ERH_SOLICITUD_CAMPOS
		SELECT NUM_SOLICITUD, DES_NOMBRE,IND_PERSONERIA,DES_DIRECCION,DES_COMUNA,DES_CIUDAD,DES_ACTIVIDAD,FEC_NACIMIENTO,FEC_DEFUNCION,
		IND_QUIEBRA,NUM_MOVIMIENTOS_QUIEBRA,IND_DEUDA_LABORAL,VAL_CANT_DEUDAPREVI,NUM_CHEQUE,NUM_CTACTE,MTO_CHEQUE,IND_TIPO_RECHAZO,
		MTO_IMPAGOS,VAL_CANT_IMPAGOS,VAL_CANT_ACREEIMPAGOS,VAL_CANT_DOCACLARADO,VAL_CANT_ACREEACLARADOS,IND_TIPCLIENTE_TM,
		VAL_CANT_FACTURAS_TM,MTO_DEUDA_TM,IND_ESTADO_DEUDA_TM,FEC_VENCIMIENTO_TM,FEC_PUBLICACION_TM,REG_ATRER,COD_TIPIDENT,
		FEC_BLOQUEO_NUM_IDENT,FEC_VENCIMIENTO_NUM_IDENT,GLS_FUENTE_BLOQ_NUM_IDENT,GLS_MOTIVO_BLOQ_NUM_IDENT,NUM_CONSULTAS_NUM_IDENT,NUM_IDENT,
		NOMBRE_CLIENTE, PRIMER_APELLIDO, SEGUNDO_APELLIDO
		FROM ERT_SOLICITUD_CAMPOS	WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;

  INSERT into ERH_SOLICITUD_DETCAMPO
  		 	SELECT NUM_SOLICITUD,	IND_TIPO_DEUDA,	IND_TIPO_DOCUMENTO,	COD_MONEDA,	MTO_DEUDA,
			FEC_VENCIMIENTO,	DES_LIBRADOR, DES_CAUSA_PUBLICACION
			FROM ERT_SOLICITUD_DETCAMPO	WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;

  INSERT into ERH_SOLICITUD_SUELDO
			SELECT NUM_SOLICITUD,	VAL_ANO_SUELDO, VAL_MES_SUELDO, MTO_SUELDO
			FROM ERT_SOLICITUD_SUELDO	WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;

  INSERT into ERH_SOLICITUD_IVA
			SELECT NUM_SOLICITUD, VAL_ANO_DECLARACION, VAL_MES_DECLARACION, VAL_FOLIO_DECLARACION, MTO_DECLARACION
			FROM ERT_SOLICITUD_IVA
			WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;

  INSERT into ERH_SOLICITUD_PLANES
			SELECT NUM_SOLICITUD,	COD_PLANTARIF,	VAL_CANT_TERMINALES,	VAL_CANT_VENDIDOS,	IND_VENTA
			FROM ERT_SOLICITUD_PLANES
			WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;

  INSERT into ERH_SOLICITUD_VENTA
  		 	SELECT NUM_SOLICITUD,	NUM_VENTA
			FROM ERT_SOLICITUD_VENTA
			WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;

  INSERT into ERH_SOLICITUD_EXCEPCIONES
  		 	SELECT NUM_SOLICITUD, TIP_EXCEPCION, COD_EXCEPCION, COD_FUENTE, NOM_USUARIO, FEC_ULTMOD
			FROM ERT_SOLICITUD_EXCEPCIONES
			WHERE NUM_SOLICITUD = EN_NUM_SOLICITUD;

   DELETE ERT_SOLICITUD_DETCAMPO	WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;
   DELETE ERT_SOLICITUD_SUELDO		WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;
   DELETE ERT_SOLICITUD_PLANES		WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;
   DELETE ERT_SOLICITUD_IVA		WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;
   DELETE ERT_SOLICITUD_CAMPOS		WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;
   DELETE ERT_SOLICITUD_VENTA		WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;
   DELETE ERT_SOLICITUD_EXCEPCIONES	WHERE NUM_SOLICITUD= EN_NUM_SOLICITUD;


EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20003,'ERROR EN PACKAGE ER_BEUP_SOLICITUD_PG.ER_BEUP_SOLICITUD_PR: '|| 'ERROR'||' ORA'||TO_CHAR(SQLCODE),TRUE);
END;
END;
/
SHOW ERRORS
