CREATE OR REPLACE FUNCTION        FA_dtoa(Numero IN NUMBER) RETURN CHAR IS
	 valor CHAR(30) := ' ';
BEGIN

	 SELECT RTRIM(LTRIM(TO_CHAR(Numero,'99999999999999999990.9999999')))
	 INTO	valor
	 FROM   dual;
	 RETURN valor;

   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       NULL;
     WHEN OTHERS THEN
       NULL;
END FA_DTOA;
/
SHOW ERRORS
