CREATE OR REPLACE PACKAGE FA_TRAZA_CICLO_PG IS

TYPE RET_TAB IS TABLE OF VARCHAR2(10);

FUNCTION FA_OBTIENE_TDOCUM_CDESPACHO_FN ( EN_CODCICLO IN NUMBER, EN_CODTIPDOCUM IN NUMBER, EN_CODDESPACHO IN VARCHAR2, EN_HOSTID IN VARCHAR2) RETURN RET_TAB pipelined;

PROCEDURE FA_TRATA_TRAZA_IMPCICLO_FN ( EN_CODCICLO IN NUMBER, EN_CODTIPDOCUM IN NUMBER, EN_CODDESPACHO IN VARCHAR2, EN_HOSTID IN VARCHAR2 , EN_COMANDO IN VARCHAR2, SN_COD_ERROR OUT NUMBER);


END FA_TRAZA_CICLO_PG;
/
SHOW ERRORS
