CREATE OR REPLACE PACKAGE FA_TRCT_ADMIN_PG IS

        PROCEDURE FA_TRUNC_OPER_RESP_CICL_TH_PR ;
        PROCEDURE FA_TRUNC_ACUMOPER_RESP_TH_PR ;
        PROCEDURE FA_TRUNC_FA_AGRZONAIMP_TO_PR ;

END;
/
SHOW ERRORS
