CREATE OR REPLACE PACKAGE GA_ACTABO_MOD_PG AS
  PROCEDURE GA_EXISTE_PR (EV_cod_actabo IN ga_actabo.cod_actabo%type,
                         SN_cantidad OUT NOCOPY NUMBER,
						 SN_COD_RETORNO OUT NOCOPY NUMBER, SV_MENS_RETORNO OUT NOCOPY VARCHAR2, SN_NUM_EVENTO OUT NOCOPY NUMBER)
  ;

END;
/
SHOW ERRORS
