CREATE OR REPLACE PACKAGE BODY GA_HIST_MIGR_PG AS


PROCEDURE GA_INSERTA_TRASPASO_PR(
		  									   	   P_NUM_TRANSACCION	IN GA_TRANSACABO.NUM_TRANSACCION%TYPE,
					   							   P_NUM_ABONADO   		IN GA_TRASPABO.NUM_ABONADO%TYPE,
										   		   P_COD_CLIENUE		IN GA_TRASPABO.COD_CLIENNUE%TYPE,
												   P_COD_CUENTANUE		IN GA_TRASPABO.COD_CUENTANUE%TYPE,
										   		   P_COD_SUBCUENTA		IN GA_TRASPABO.COD_SUBCTANUE%TYPE,
												   P_COD_USUARNUE		IN GA_TRASPABO.COD_USUARNUE%TYPE,
												   P_COD_PRODUCTO		IN GA_TRASPABO.COD_PRODUCTO%TYPE,
												   P_NUM_TERMINAL		IN GA_TRASPABO.NUM_TERMINAL%TYPE,
												   P_NUM_ABONADOANT		IN GA_TRASPABO.NUM_ABONADOANT%TYPE,
												   P_COD_CLIENTEANT		IN GA_TRASPABO.COD_CLIENANT%TYPE,
												   P_COD_CUENTAANT		IN GA_TRASPABO.COD_CUENTAANT%TYPE,
												   P_COD_SUBCTAANT		IN GA_TRASPABO.COD_SUBCTAANT%TYPE,
												   P_COD_USUARANT		IN GA_TRASPABO.COD_USUARANT%TYPE,
												   P_IND_TRASDEUDA		IN GA_TRASPABO.IND_TRASDEUDA%TYPE,
												   P_NOM_USUARORA		IN GA_TRASPABO.NOM_USUARORA%TYPE,
												   P_IND_TRASPASO		IN GA_TRASPABO.IND_TRASPASO%TYPE,
												   P_COD_PLAN_ORIG		IN GA_TRASPABO.COD_PLANTARIF_ORIG%TYPE,
												   P_COD_PLAN_DEST		IN GA_TRASPABO.COD_PLANTARIF_DEST%TYPE,
												   P_COD_VENDEDOR		IN GA_TRASPABO.COD_VENDEDOR%TYPE


												   )
IS

   V_SQLCODE            GA_ERRORES.COD_SQLCODE%TYPE;
   V_SQLERRM            VARCHAR2(255);
   V_ERROR              VARCHAR2(1);

BEGIN

   V_ERROR             := '0';

	INSERT INTO GA_TRASPABO
		   		( NUM_ABONADO,FEC_MODIFICA,	COD_CLIENNUE, COD_CUENTANUE, COD_SUBCTANUE,
				COD_USUARNUE, COD_PRODUCTO,	NUM_TERMINAL, NUM_ABONADOANT, COD_CLIENANT,
				COD_CUENTAANT, COD_SUBCTAANT, COD_USUARANT, IND_TRASDEUDA, NOM_USUARORA,
				IND_TRASPASO,COD_PLANTARIF_ORIG	, COD_PLANTARIF_DEST, COD_VENDEDOR
				)
				VALUES (
  			    P_NUM_ABONADO,SYSDATE, P_COD_CLIENUE, P_COD_CUENTANUE, P_COD_SUBCUENTA,
			    P_COD_USUARNUE,	P_COD_PRODUCTO, P_NUM_TERMINAL, P_NUM_ABONADOANT, P_COD_CLIENTEANT,
			    P_COD_CUENTAANT, P_COD_SUBCTAANT, P_COD_USUARANT, P_IND_TRASDEUDA, P_NOM_USUARORA,
			    P_IND_TRASPASO, P_COD_PLAN_ORIG, P_COD_PLAN_DEST, P_COD_VENDEDOR);


			   INSERT INTO GA_TRANSACABO
			   (NUM_TRANSACCION, COD_RETORNO, DES_CADENA)
			   VALUES
			   ( P_NUM_TRANSACCION,V_ERROR ,NULL);



EXCEPTION

    WHEN OTHERS THEN
	     V_ERROR   := '4';
	     V_SQLCODE := SUBSTR(SQLCODE,1,15);
         V_SQLERRM := SUBSTR(SQLERRM,1,255);
         INSERT INTO GA_TRANSACABO
         (NUM_TRANSACCION, COD_RETORNO, DES_CADENA)
         VALUES
         ( P_NUM_TRANSACCION,V_ERROR,SUBSTR(V_SQLCODE || V_SQLERRM,1,255));

END GA_INSERTA_TRASPASO_PR;


PROCEDURE GA_INS_SS_LISTA_VOZ_PR( 			   	   P_NUM_ABONADO  		IN GA_ABOCEL.NUM_ABONADO%TYPE,
		  										   VP_COD_ERROR			IN OUT Integer,
												   VP_CODSQL_ERR		OUT VARCHAR2,
												   VP_MSGSQL_ERR		OUT VARCHAR2)
IS

   V_COD_PRODUCTO	   GA_ABOCEL.COD_PRODUCTO%TYPE;
   V_TIP_TERMINAL	   GA_ABOCEL.TIP_TERMINAL%TYPE;
   V_NUM_MOVIMIENTO    ICC_MOVIMIENTO.NUM_MOVIMIENTO%TYPE;
   V_SERV_FREC		   GED_PARAMETROS.VAL_PARAMETRO%TYPE;
   V_NUM_CELULAR	   GA_ABOCEL.NUM_CELULAR%TYPE;
   V_COD_SERVICIO      GA_SERVSUPL.COD_SERVICIO%TYPE;
   V_COD_CENTRAL       ICC_MOVIMIENTO.COD_CENTRAL%TYPE;
   V_NUM_SERIEHEX      ICC_MOVIMIENTO.NUM_SERIE%TYPE;
   V_NUM_MIN           ICC_MOVIMIENTO.NUM_MIN%TYPE;
   V_COD_ACTUACION     ICC_MOVIMIENTO.COD_ACTUACION%TYPE;
   V_COD_TECNOLOGIA    GA_ABOAMIST.COD_TECNOLOGIA%TYPE;
   V_SERVICIO		   ICC_MOVIMIENTO.COD_SERVICIOS%TYPE;
   V_COD_CONCEPTO      GA_SERVSUPLABO.COD_CONCEPTO%TYPE;
   sVALParam_MIGRA     GED_PARAMETROS.NOM_PARAMETRO%TYPE;
   V_PERFIL            GA_ABOAMIST.PERFIL_ABONADO%TYPE;
   V_CLASE			   GA_ABOAMIST.CLASE_SERVICIO%TYPE;
   V_GRP_TECNO_GSM     AL_TECNOLOGIA.COD_GRUPO%TYPE;
   V_GRP_TECNO_DMA     AL_TECNOLOGIA.COD_GRUPO%TYPE;
   V_COD_TIPSERV       GA_ACTUASERV.COD_TIPSERV%TYPE:='2';
   V_ACTABO_FA         GA_ACTUASERV.COD_ACTABO%TYPE:='FA';
   V_NUM_SERIE         GA_ABOAMIST.NUM_SERIE%TYPE;
   V_NUM_IMEI          GA_ABOAMIST.NUM_SERIE%TYPE;
   V_IMSI              ICC_MOVIMIENTO.IMSI%TYPE;
   V_ICC               ICC_MOVIMIENTO.ICC%TYPE;
   V_IMEI              ICC_MOVIMIENTO.IMEI%TYPE;
   V_CLASE_SERVICIO    GA_ABOCEL.CLASE_SERVICIO%TYPE;

   V_SERVSUPL			NUMBER(2);
   V_NIVEL  			NUMBER(4);

BEGIN

   sVALParam_MIGRA := GE_FN_DEVVALPARAM('GA',1,'MIG_NUM_FREC');

   VP_COD_ERROR:= 2;

   IF  TRIM(sVALParam_MIGRA) ='TRUE' THEN

	   V_GRP_TECNO_GSM := GE_FN_DEVVALPARAM('GA',1,'GRUPO_TEC_GSM');
	   V_GRP_TECNO_DMA := GE_FN_DEVVALPARAM('GA',1,'GRUPO_TEC_DMA');

	   SELECT ICC_SEQ_NUMMOV.NEXTVAL
	   INTO   V_NUM_MOVIMIENTO
	   FROM DUAL;

	   VP_COD_ERROR     := 3;

	   BEGIN
		   SELECT  COD_CENTRAL,NUM_SERIEHEX,NUM_MIN,COD_TECNOLOGIA,NUM_SERIE,NUM_IMEI,NUM_CELULAR,COD_PRODUCTO,TIP_TERMINAL ,CLASE_SERVICIO
		   INTO V_COD_CENTRAL,V_NUM_SERIEHEX,V_NUM_MIN,V_COD_TECNOLOGIA,V_NUM_SERIE,V_NUM_IMEI,V_NUM_CELULAR,V_COD_PRODUCTO,V_TIP_TERMINAL,V_CLASE_SERVICIO
		   FROM GA_ABOAMIST
		   WHERE NUM_ABONADO = P_NUM_ABONADO;
	   EXCEPTION
	   		WHEN NO_DATA_FOUND THEN
			   SELECT  COD_CENTRAL,NUM_SERIEHEX,NUM_MIN,COD_TECNOLOGIA,NUM_SERIE,NUM_IMEI,NUM_CELULAR,COD_PRODUCTO,TIP_TERMINAL ,CLASE_SERVICIO
			   INTO V_COD_CENTRAL,V_NUM_SERIEHEX,V_NUM_MIN,V_COD_TECNOLOGIA,V_NUM_SERIE,V_NUM_IMEI,V_NUM_CELULAR,V_COD_PRODUCTO,V_TIP_TERMINAL,V_CLASE_SERVICIO
			   FROM GA_ABOCEL
			   WHERE NUM_ABONADO = P_NUM_ABONADO;
	   END;

	   VP_COD_ERROR:= 4;

	   V_SERV_FREC := GE_FN_DEVVALPARAM('GA',1,'SERV_LISTA_FREC');

	   VP_COD_ERROR:= 5;

	   SELECT COD_SERVSUPL,COD_NIVEL
	   INTO V_SERVSUPL,V_NIVEL
	   FROM GA_SERVSUPL
	   WHERE COD_PRODUCTO=V_COD_PRODUCTO
	   AND COD_SERVICIO = TRIM(V_SERV_FREC);

       --V_CLASE_SERVICIO := '';
	   V_SERVICIO       :=CONCAT (TRIM(V_SERVSUPL) , TRIM(TO_CHAR(V_NIVEL,'0999')));

		VP_COD_ERROR:= 6;

	   SELECT COD_ACTCEN
	   INTO V_COD_ACTUACION
	   FROM GA_ACTABO
	   WHERE COD_MODULO='GA'	   	   AND
	   COD_PRODUCTO   = V_COD_PRODUCTO AND
       COD_ACTABO     = 'SS'           AND
	   COD_TECNOLOGIA = V_COD_TECNOLOGIA;

		VP_COD_ERROR:= 7;

	    SELECT COD_CONCEPTO
		INTO V_COD_CONCEPTO
		FROM GA_ACTUASERV
		WHERE COD_PRODUCTO = V_COD_PRODUCTO
		AND COD_TIPSERV    = V_COD_TIPSERV
		AND COD_SERVICIO   = V_SERV_FREC
		AND COD_ACTABO     = V_ACTABO_FA;

		VP_COD_ERROR:= 8;

	   IF (V_GRP_TECNO_GSM = GA_APROVISIONAR_CENTRAL_PG.PV_GRUPO_TECNOLOGICO_FN(V_COD_TECNOLOGIA)) THEN

		  SELECT FN_RECUPERA_IMSI(V_NUM_SERIE)
 			  INTO V_IMSI
       			  FROM DUAL;

		  V_ICC  := V_NUM_SERIE;
		  V_IMEI := V_NUM_IMEI;

		   ELSE
  		  	  V_IMSI :='';
		  V_ICC  :='';
		  V_IMEI :='';
	   END IF;


		VP_COD_ERROR:= 9;

		INSERT INTO ICC_MOVIMIENTO
		(NUM_MOVIMIENTO    , NUM_ABONADO  , NUM_CELULAR   , COD_ESTADO       ,COD_MODULO     ,
		COD_ACTUACION     , NOM_USUARORA , FEC_INGRESO   , COD_CENTRAL      ,NUM_SERIE      ,
		COD_SERVICIOS     , TIP_TERMINAL , COD_ACTABO    , TIP_TECNOLOGIA   ,NUM_MIN        ,ICC, IMSI, IMEI)
		VALUES
		(V_NUM_MOVIMIENTO ,P_NUM_ABONADO , V_NUM_CELULAR, '1'              ,'GA'       ,
		V_COD_ACTUACION  ,USER          , SYSDATE       , V_COD_CENTRAL   ,V_NUM_SERIEHEX,
		V_SERVICIO       ,V_TIP_TERMINAL, 'SS'          , V_COD_TECNOLOGIA,V_NUM_MIN     ,V_ICC, V_IMSI, V_IMEI);


		VP_COD_ERROR:= 10;

		INSERT INTO GA_SERVSUPLABO
		(NUM_ABONADO    , COD_SERVICIO   , FEC_ALTABD, COD_SERVSUPL, COD_NIVEL, NUM_TERMINAL  ,
		COD_PRODUCTO   , NOM_USUARORA   , IND_ESTADO,COD_CONCEPTO)
		VALUES
		(P_NUM_ABONADO  , TRIM(V_SERV_FREC), SYSDATE   , V_SERVSUPL , V_NIVEL , V_NUM_CELULAR,
		V_COD_PRODUCTO , USER           , 1,V_COD_CONCEPTO);

		VP_COD_ERROR:= 11;

	   DELETE
	   FROM GA_TRASP_NUMFREC_TEMP
	   WHERE COD_ACTABO  = 'SS'  AND
	   NUM_ABONADO = P_NUM_ABONADO;

	   VP_COD_ERROR:= 12;

	   UPDATE GA_TRASP_NUMFREC_TEMP
	   SET NUM_MOVIMIENTO = V_NUM_MOVIMIENTO
	   WHERE COD_ACTABO  = 'FI'  AND
	   NUM_ABONADO = P_NUM_ABONADO;


	   V_CLASE_SERVICIO := V_CLASE_SERVICIO || V_SERVICIO;

	   P_LIMPIAR_CLASEABO (V_COD_PRODUCTO,P_NUM_ABONADO,V_CLASE_SERVICIO);


   END IF;

   VP_COD_ERROR:=0;
   VP_MSGSQL_ERR := 'OK';

EXCEPTION
    WHEN OTHERS THEN
		 VP_CODSQL_ERR := SUBSTR(SQLCODE,1,15);
         VP_MSGSQL_ERR := SUBSTR('[' || VP_COD_ERROR || '] ' || SQLERRM,1,255);
END GA_INS_SS_LISTA_VOZ_PR;


PROCEDURE GA_INS_NUMEROSFREC_PR( 			   	   P_NUM_ABONADO  		IN GA_ABOCEL.NUM_ABONADO%TYPE,
												   P_NUM_FRECUENTE  	IN GA_TRASP_NUMFREC_TEMP.NUM_CELULAR%TYPE,
												   P_TIP_FRECUENTE		IN GA_TRASP_NUMFREC_TEMP.TIP_FRECUENTE%TYPE,
												   VP_COD_ERROR			IN OUT Integer,
												   VP_CODSQL_ERR		OUT VARCHAR2,
												   VP_MSGSQL_ERR		OUT VARCHAR2)

Is
--vNum_abonado,vNum_celular,vTip_frecuente,vCod_error,vMsgErr

   V_COD_PRODUCTO 		GA_ABOCEL.COD_PRODUCTO%TYPE;
   V_NUM_MOVIMIENTO    ICC_MOVIMIENTO.NUM_MOVIMIENTO%TYPE;
   V_SERV_FREC			GED_PARAMETROS.VAL_PARAMETRO%TYPE;
   V_NUM_CELULAR_ABO   GA_ABOAMIST.NUM_CELULAR%TYPE;
   V_IND_LISTA         GED_CODIGOS.DES_VALOR%TYPE;
   V_COD_CENTRAL       ICC_MOVIMIENTO.COD_CENTRAL%TYPE;
   V_NUM_SERIEHEX      ICC_MOVIMIENTO.NUM_SERIE%TYPE;
   V_COD_TECNOLOGIA    GA_ABOAMIST.COD_TECNOLOGIA%TYPE;
   sVALParam_MIGRA      GED_PARAMETROS.NOM_PARAMETRO%TYPE;
   V_NUM_SERIE         GA_ABOAMIST.NUM_SERIE%TYPE;
   V_NUM_IMEI          GA_ABOAMIST.NUM_SERIE%TYPE;
   V_IMSI              ICC_MOVIMIENTO.IMSI%TYPE;
   V_ICC               ICC_MOVIMIENTO.ICC%TYPE;
   V_GRP_TECNO_GSM      AL_TECNOLOGIA.COD_GRUPO%TYPE;
   V_GRP_TECNO_DMA      AL_TECNOLOGIA.COD_GRUPO%TYPE;
   V_TIP_TERMINAL		GA_ABOCEL.TIP_TERMINAL%TYPE;

   V_SERVSUPL			VARCHAR2(5);

   FECHA_SINCRO         DATE;

   V_COD_PLANTARIF		TA_PLANTARIF.COD_PLANTARIF%TYPE;
   V_COD_ACTABO			GA_ACTABO.COD_ACTABO%TYPE;
   V_CODACTUACION		ICC_MOVIMIENTO.COD_ACTUACION%TYPE;
BEGIN

   VP_COD_ERROR := 2;
   sVALParam_MIGRA := GE_FN_DEVVALPARAM('GA',1,'MIG_NUM_FREC');

   IF  TRIM(sVALParam_MIGRA) ='TRUE' THEN

   	   VP_COD_ERROR := 3;

   	   V_GRP_TECNO_GSM := GE_FN_DEVVALPARAM('GA',1,'GRUPO_TEC_GSM');
   	   V_GRP_TECNO_DMA := GE_FN_DEVVALPARAM('GA',1,'GRUPO_TEC_DMA');

		VP_COD_ERROR := 4;

			BEGIN
			   SELECT  COD_CENTRAL      ,NUM_SERIEHEX      ,
			           COD_TECNOLOGIA   ,NUM_CELULAR ,NUM_SERIE,NUM_IMEI, COD_PRODUCTO,TIP_TERMINAL,
					   COD_PLANTARIF
			   INTO    V_COD_CENTRAL   ,V_NUM_SERIEHEX   ,
			           V_COD_TECNOLOGIA,V_NUM_CELULAR_ABO ,V_NUM_SERIE,V_NUM_IMEI, V_COD_PRODUCTO,V_TIP_TERMINAL,
					   V_COD_PLANTARIF
			   FROM GA_ABOAMIST
			   WHERE NUM_ABONADO = P_NUM_ABONADO;

			   EXCEPTION
	   		       WHEN NO_DATA_FOUND THEN
					    SELECT  COD_CENTRAL      ,NUM_SERIEHEX      ,
			                   COD_TECNOLOGIA   ,NUM_CELULAR ,NUM_SERIE,NUM_IMEI, COD_PRODUCTO ,TIP_TERMINAL,
							   COD_PLANTARIF
			   		   INTO    V_COD_CENTRAL   ,V_NUM_SERIEHEX   ,
			                   V_COD_TECNOLOGIA,V_NUM_CELULAR_ABO ,V_NUM_SERIE,V_NUM_IMEI,V_COD_PRODUCTO,V_TIP_TERMINAL,
							   V_COD_PLANTARIF
					    FROM GA_ABOCEL
					    WHERE NUM_ABONADO = P_NUM_ABONADO;
           END;


	   VP_COD_ERROR := 5;

	   V_SERV_FREC := GE_FN_DEVVALPARAM('GA',1,'SERV_LISTA_FREC');

		VP_COD_ERROR := 6;

          SELECT COD_SERVSUPL
          INTO V_SERVSUPL
          FROM GA_SERVSUPL
          WHERE COD_PRODUCTO=V_COD_PRODUCTO
		  AND COD_SERVICIO = TRIM(V_SERV_FREC);

        VP_COD_ERROR := 7;

		  SELECT  DES_VALOR
		  INTO V_IND_LISTA
		  FROM  GED_CODIGOS
		  WHERE
		  COD_MODULO  = 'GA'		   	   AND
		  NOM_TABLA   = 'PPT_NUMEROFRECUENTE'  AND
		  NOM_COLUMNA = 'IND_LISTA'            AND
		  COD_VALOR   = V_SERVSUPL;

		  VP_COD_ERROR := 8;

		   BEGIN
			   SELECT COD_ACTABO INTO V_COD_ACTABO FROM PV_ACTABO_TIPLAN
			   WHERE COD_TIPMODI='FI'
			   AND COD_TIPLAN in (SELECT COD_TIPLAN FROM TA_PLANTARIF
			   	   			  	 		 WHERE COD_PRODUCTO=V_COD_PRODUCTO
										 AND COD_PLANTARIF=V_COD_PLANTARIF);
			EXCEPTION
					 WHEN OTHERS THEN
					 	  V_COD_ACTABO:='FI';
		   END;

	 	   V_CODACTUACION := FN_CODACTCEN (1,V_COD_ACTABO,'GA',V_COD_TECNOLOGIA);

		   VP_COD_ERROR := 9;

			IF (V_GRP_TECNO_GSM = GA_APROVISIONAR_CENTRAL_PG.PV_GRUPO_TECNOLOGICO_FN(V_COD_TECNOLOGIA)) THEN

			  V_IMSI := FN_RECUPERA_IMSI(V_NUM_SERIE );
		      V_ICC  := V_NUM_SERIE;

 			ELSE
    		  	  V_IMSI :='';
				  V_ICC  :='';
		  	END IF;

			VP_COD_ERROR := 10;

			FECHA_SINCRO:=SYSDATE;

			SELECT NVL(MAX(FEC_MODIFICACION) + (1/(24*60*60)) ,FECHA_SINCRO)
			INTO FECHA_SINCRO
			FROM PPT_NUMEROFRECUENTE
			WHERE NUM_ABONADO=P_NUM_ABONADO
			AND FEC_MODIFICACION >= FECHA_SINCRO;

		   VP_COD_ERROR := 11;

	 		INSERT INTO PPT_NUMEROFRECUENTE
	  		(NUM_ABONADO     , NUM_FRECUENTE    , NUM_POSICION,
	   		TIP_NUMFRECUENTE, FEC_MODIFICACION , NOM_USUARORA,
	   		IND_LISTA       , NUM_FRECUENTE_ANT, FEC_DESDE   ,
	   		FEC_HASTA)
	  		VALUES(P_NUM_ABONADO,P_NUM_FRECUENTE,0,
			DECODE(P_TIP_FRECUENTE,'M',1,'F',2,Null),
			FECHA_SINCRO,USER,
			V_IND_LISTA,'',SYSDATE,TO_DATE('31-12-3000 23:59:59','DD-MM-YYYY HH24:MI:SS'));

	 		VP_COD_ERROR := 12;

/********  EJEMPLO DE INSERCION DE NuMERO FRECUENTE PARA ABONADO GSM  ***************
INSERT INTO ICC_MOVIMIENTO ( NUM_MOVIMIENTO, NUM_ABONADO, COD_ESTADO, COD_ACTABO,
COD_MODULO, NUM_INTENTOS, DES_RESPUESTA, COD_ACTUACION, NOM_USUARORA, FEC_INGRESO,
TIP_TERMINAL, COD_CENTRAL, IND_BLOQUEO, NUM_CELULAR, NUM_SERIE, CARGA, TIP_TECNOLOGIA,
IMSI, ICC
 ) VALUES (35138711, 3883265, 1, 'FI', 'GA', 0, 'PENDIENTE', 1259, USER,
 SYSDATE, 'G', 23, 0, 6561562949, '7F35ED86', 15, 'GSM', '*', '8952031143000494505');

/********* EJEMPLO DE INSERCION DE NuMERO FRECUENTE PARA ABONADO CDMA  ***************
INSERT INTO ICC_MOVIMIENTO ( NUM_MOVIMIENTO, NUM_ABONADO, COD_ESTADO, COD_ACTABO,
COD_MODULO, NUM_INTENTOS, DES_RESPUESTA, COD_ACTUACION, NOM_USUARORA, FEC_INGRESO,
TIP_TERMINAL, COD_CENTRAL, IND_BLOQUEO, NUM_CELULAR, NUM_SERIE, CARGA, TIP_TECNOLOGIA,
IMSI ) VALUES (35138728, 3964194, 1, 'FI', 'GA', 0, 'PENDIENTE', 1359, 'TMM_04010',
TO_Date( '12/27/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'D', 15, 0, 9398020017, '7B0E8F00', 0, 'CDM850', 'NO ENTRO');
 /************************************************************************************/
 	        SELECT ICC_SEQ_NUMMOV.NEXTVAL
	        INTO   V_NUM_MOVIMIENTO
	      	FROM DUAL;

	 		INSERT INTO ICC_MOVIMIENTO
			( NUM_MOVIMIENTO, NUM_ABONADO, COD_ESTADO, COD_ACTABO,
			COD_MODULO, NUM_INTENTOS, DES_RESPUESTA, COD_ACTUACION, NOM_USUARORA, FEC_INGRESO,
			TIP_TERMINAL, COD_CENTRAL, IND_BLOQUEO, NUM_CELULAR, NUM_SERIE, CARGA, TIP_TECNOLOGIA,
			IMSI, ICC )
		    VALUES
			(V_NUM_MOVIMIENTO,P_NUM_ABONADO,1,'FI',
			'GA',0,'PENDIENTE',V_CODACTUACION,User, FECHA_SINCRO,
			V_TIP_TERMINAL,V_COD_CENTRAL,0,V_NUM_CELULAR_ABO,V_NUM_SERIEHEX,0,V_COD_TECNOLOGIA,
			V_IMSI,V_ICC);


			VP_COD_ERROR := 13;

		   	  DELETE GA_TRASP_NUMFREC_TEMP
		  	  WHERE COD_ACTABO  = 'FI'
			  AND NUM_ABONADO = P_NUM_ABONADO
			  AND NUM_CELULAR=P_NUM_FRECUENTE;

    END IF;

   VP_COD_ERROR := 0;
   VP_MSGSQL_ERR := 'OK';

EXCEPTION
    WHEN OTHERS THEN
		 VP_CODSQL_ERR := SUBSTR(SQLCODE,1,15);
         VP_MSGSQL_ERR := SUBSTR('[' || VP_COD_ERROR || '] ' || SQLERRM,1,255);
		 dbms_output.put_line( VP_MSGSQL_ERR );
END GA_INS_NUMEROSFREC_PR;

PROCEDURE GA_ACT_INGRESO_SS_PR(
		   P_COD_ACTABO			IN ICC_MOVIMIENTO.COD_ACTABO%TYPE,
		   P_NUM_ABONADO		IN ICC_MOVIMIENTO.NUM_ABONADO%TYPE,
		   P_NUM_CELULAR		IN ICC_MOVIMIENTO.NUM_CELULAR%TYPE)
is
	V_EXISMIGFREC GED_PARAMETROS.VAL_PARAMETRO%TYPE;
BEGIN

	V_EXISMIGFREC := GE_FN_DEVVALPARAM('GA',1, 'MIG_NUM_FREC');

	IF V_EXISMIGFREC = 'TRUE' AND P_COD_ACTABO in ('AM','AH') then

		Update GA_TRASP_NUMFREC_TEMP
   		Set cod_estado=1
   		Where cod_actabo = 'SS'
   		and num_Abonado = P_NUM_ABONADO
   		and num_celular = To_char(P_NUM_CELULAR);

		if SQL%FOUND then
   	  	   Update Fa_intQueueproc
	  	   Set Cod_activacion='A',cod_estado=1
	  	   where cod_aplic='PVA'
	  	   and cod_modgener='FRE'
	  	   and cod_proceso=991;
		End if;

	End if;

exception
  when Others Then
  	   Null;
END GA_ACT_INGRESO_SS_PR;

PROCEDURE GA_ACT_INGRESO_NFREC_PR(
		   P_COD_ACTABO			IN ICC_MOVIMIENTO.COD_ACTABO%TYPE,
		   P_NUM_ABONADO		IN ICC_MOVIMIENTO.NUM_ABONADO%TYPE,
		   P_NUM_MOVIMIENTO		IN ICC_MOVIMIENTO.NUM_MOVIMIENTO%TYPE)
is
	V_EXISMIGFREC GED_PARAMETROS.VAL_PARAMETRO%TYPE;
BEGIN

	 V_EXISMIGFREC := GE_FN_DEVVALPARAM('GA',1, 'MIG_NUM_FREC');

	 IF V_EXISMIGFREC = 'TRUE'AND P_COD_ACTABO in ('SS') then

   		Update GA_TRASP_NUMFREC_TEMP
   		Set cod_estado=1
   		Where cod_actabo='FI'
   		and num_Abonado=P_NUM_ABONADO
   		and num_movimiento=P_NUM_MOVIMIENTO;

		if SQL%FOUND then

		   		Update Fa_intQueueproc
	  			Set Cod_activacion='A',cod_estado=1
	  			where cod_aplic='PVA'
	  			and cod_modgener='FRE'
	  			and cod_proceso=991;

		End if;
	End if;

exception
  when Others Then
  	   Null;
END GA_ACT_INGRESO_NFREC_PR;

END GA_HIST_MIGR_PG;
/
SHOW ERRORS
