CREATE OR REPLACE PACKAGE GA_MODCLI_MOD_PG AS
  PROCEDURE GA_INSERTA_PR (TE_modcli IN GA_MODCLI%ROWTYPE, SN_COD_RETORNO OUT NOCOPY NUMBER, SV_MENS_RETORNO OUT NOCOPY VARCHAR2, SN_NUM_EVENTO OUT NOCOPY NUMBER);

END;
/
SHOW ERRORS
