CREATE OR REPLACE PROCEDURE        GA_P_UPDINFACCEL
 (V_CLIENTE IN GA_INFACCEL.COD_CLIENTE%TYPE,
                            V_PROC IN OUT VARCHAR2,
                            V_TABLA IN OUT VARCHAR2,
                            V_ACT IN OUT VARCHAR2,
                            V_SQLCODE IN OUT VARCHAR2,
                            V_SQLERRM IN OUT VARCHAR2,
                            V_ERROR IN OUT VARCHAR2) IS
V_FILA ROWID;
V_VALOR NUMBER;
V_IND_ACTUAC_ANU NUMBER;
V_IND_ACTUAC_BAJA NUMBER;
V_CICLFACT FA_CICLFACT.COD_CICLFACT%TYPE;
BEGIN
 V_IND_ACTUAC_ANU := 6;
 V_IND_ACTUAC_BAJA := 2;
 V_VALOR := 0;
 V_PROC:='GA_P_UPDINFACCEL';
 V_TABLA:='FA_CICLFACT';
 V_ACT:='S';
 SELECT COD_CICLFACT
 INTO V_CICLFACT
 FROM FA_CICLFACT A
 WHERE A.COD_CICLO IN (SELECT COD_CICLO
 FROM GE_CLIENTES B
 WHERE A.COD_CICLO=B.COD_CICLO
 AND  B.COD_CLIENTE= V_CLIENTE)
 AND SYSDATE BETWEEN FEC_DESDELLAM AND FEC_HASTALLAM;
 V_TABLA:='GA_INFACCEL';
 V_ACT:='S';
 BEGIN
  SELECT ROWID INTO V_FILA
  FROM GA_INFACCEL
  WHERE COD_CLIENTE = V_CLIENTE
  AND NUM_ABONADO = V_VALOR
  AND COD_CICLFACT=V_CICLFACT
  AND IND_ACTUAC= V_IND_ACTUAC_BAJA;
  V_TABLA:='GA_INFACCEL';
  V_ACT:='U';
  UPDATE GA_INFACCEL
  		 SET IND_ACTUAC = V_IND_ACTUAC_ANU
  WHERE ROWID = V_FILA;
 EXCEPTION
  WHEN NO_DATA_FOUND THEN
  	   NULL;
 END;
 V_ERROR:='0';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
       V_ERROR:='0';
       V_SQLCODE := SQLCODE;
       V_SQLERRM := SQLERRM;
  WHEN OTHERS THEN
       V_ERROR:='4';
       V_SQLCODE := SQLCODE;
       V_SQLERRM := SQLERRM;
END;
/
SHOW ERRORS
