CREATE OR REPLACE PACKAGE GE_CLIENTES_MOD_PG AS
  PROCEDURE GE_ACTUALIZA_MAIL_FACT_ELEC_PR (TE_cliente IN GE_CLIENTES%ROWTYPE, SN_COD_RETORNO OUT NOCOPY NUMBER, SV_MENS_RETORNO OUT NOCOPY VARCHAR2, SN_NUM_EVENTO OUT NOCOPY NUMBER);
  PROCEDURE GE_RECUPERA_PR (TE_cliente IN OUT NOCOPY  GE_CLIENTES%ROWTYPE, SN_COD_RETORNO OUT NOCOPY NUMBER, SV_MENS_RETORNO OUT NOCOPY VARCHAR2, SN_NUM_EVENTO OUT NOCOPY NUMBER);


END;
/
SHOW ERRORS
