CREATE OR REPLACE PACKAGE GE_PROCED IS
  --
  -- Retrofitted
  PROCEDURE P_GE_RESPUESTA(
  V_PRODUCTO IN GE_PRODUCTOS.COD_PRODUCTO%TYPE ,
  V_MODULO IN GE_MODULOS.COD_MODULO%TYPE ,
  V_REG_BMOV IN ICB_MOVIMIENTO%ROWTYPE ,
  V_REG_CMOV IN ICC_MOVIMIENTO%ROWTYPE ,
  V_REG_MMOV IN ICM_MOVIMIENTO%ROWTYPE ,
  V_REG_RMOV IN ICR_MOVIMIENTO%ROWTYPE );
END GE_PROCED;
/
SHOW ERRORS
