CREATE OR REPLACE PACKAGE BODY          "GE_PAC_GENERAL"  IS
 FUNCTION PARAM_GENERAL(NOMPARAMETRO IN  GED_PARAMETROS.NOM_PARAMETRO%type)
                           RETURN GED_PARAMETROS.VAL_PARAMETRO%type IS
 BEGIN
 DECLARE
	   VALPARAMETRO GED_PARAMETROS.VAL_PARAMETRO%type ;
	   CODMODULO    GED_PARAMETROS.COD_MODULO%type ;
   	   CODPRODUCTO  GED_PARAMETROS.COD_PRODUCTO%type ;
	   BEGIN
	   		  CODMODULO   := 'GE';
			  CODPRODUCTO := 1;


	   		  SELECT VAL_PARAMETRO INTO VALPARAMETRO
	   		  FROM   GED_PARAMETROS
	   		  where  COD_MODULO    = CODMODULO
	   		  and    NOM_PARAMETRO = UPPER(NOMPARAMETRO)
			  AND    COD_PRODUCTO  = CODPRODUCTO;

	   		  RETURN VALPARAMETRO;

	   		  EXCEPTION WHEN no_data_found THEN
       		  raise_application_error(-20101, 'NO EXISTEN DATOS CON EL PARAMETRO INGRESADO....' ||NOMPARAMETRO);
	   END;
 END;

 FUNCTION REDONDEA(VP_ORIGINAL IN NUMBER, VP_PRECISION IN NUMBER ,VP_USO IN NUMBER) RETURN NUMBER IS
 BEGIN
 -- FUNCION QUE APLICA EL REDONDEO A UN VALOR X (VP_ORIGINAL)
 DECLARE
	   BEGIN
	      IF VP_USO = 0 THEN
		  	 RETURN (ROUND(VP_ORIGINAL,VP_PRECISION));
		  ELSE
    	  	 RAISE_APPLICATION_ERROR(-20001,'EL PARAMETRO USO NO ES EL INDICADO');
		  END IF;
	   END;
 END;
END GE_PAC_GENERAL;
/
SHOW ERRORS
