CREATE OR REPLACE PACKAGE GE_SEG_USUARIO_MOD_PG AS
  PROCEDURE GE_EXISTE_PR (EV_nom_usuario IN VARCHAR2, SN_cantidad OUT NOCOPY NUMBER, SN_COD_RETORNO OUT NOCOPY NUMBER, SV_MENS_RETORNO OUT NOCOPY VARCHAR2, SN_NUM_EVENTO OUT NOCOPY NUMBER);


END;
/
SHOW ERRORS
