CREATE OR REPLACE PACKAGE GR_TIPOS_PG IS

   TYPE ref_cursor IS REF CURSOR;
   TYPE COL1 IS TABLE OF VARCHAR2(20) INDEX BY BINARY_INTEGER;
   TYPE COL2 IS TABLE OF NUMBER INDEX BY BINARY_INTEGER;

END GR_TIPOS_PG;
/
SHOW ERRORS
