CREATE OR REPLACE PACKAGE        IC_PASOHMOVPIN IS
PROCEDURE P_IC_PASOHCMOVPIN(V_PRODUCTO IN GE_PRODUCTOS.COD_PRODUCTO%TYPE ,
                            V_OLD_CMOV IN ICC_MOVPIN%ROWTYPE ,
                            V_NEW_CMOV IN ICC_MOVPIN%ROWTYPE );
END IC_PASOHMOVPIN;
/
SHOW ERRORS
