CREATE OR REPLACE PACKAGE IC_RANGOS_SERIES_PG IS

FUNCTION FN_TMM_serieini(V_NUM_MOV IN ICC_MOVIMIENTO.NUM_MOVIMIENTO%TYPE) RETURN VARCHAR2;

FUNCTION FN_TMM_seriefin(v_num_mov IN ICC_MOVIMIENTO.NUM_MOVIMIENTO%TYPE) RETURN VARCHAR2;


END IC_RANGOS_SERIES_PG;
/
SHOW ERRORS
