CREATE OR REPLACE PACKAGE ICC_EVALUA_SERV_PREREQ_PG IS


	   FUNCTION ICC_EVALUA_SERV_PREREQ_FN(EN_NUM_MOV IN ICC_MOVIMIENTO.NUM_MOVIMIENTO%TYPE, EN_NUM_ABO IN ICC_MOVIMIENTO.NUM_ABONADO%TYPE, EN_CAD_SERV IN ICC_MOVIMIENTO.COD_SERVICIOS%TYPE) RETURN VARCHAR2;

END ICC_EVALUA_SERV_PREREQ_PG;
/
SHOW ERRORS
