CREATE OR REPLACE PROCEDURE        P_ACEP_CAMSERIE
 (V_ABONADO IN GA_ABOCEL.NUM_ABONADO%TYPE,
V_ERROR OUT VARCHAR2)IS
BEGIN
   UPDATE GA_ABOCEL
      SET COD_SITUACION='AAA'
   WHERE NUM_ABONADO=V_ABONADO;
   V_ERROR:='0';
EXCEPTION
   WHEN OTHERS THEN
      V_ERROR:='4';
END;
/
SHOW ERRORS
