CREATE OR REPLACE PROCEDURE P_AL_HIST_TRASPASOS (iNum_Trasp IN AL_TRASPASOS_MASIVO.NUM_TRASPASO_MASIVO%type) IS
V_ESTADO_TRAS  VARCHAR2(2);
i          NUMBER(8);
V          AL_TRASPASOS_MASIVO%ROWTYPE;
V_FILA		ROWID;
CURSOR c_ser_seriado is
       SELECT NUM_TRASPASO_MASIVO,COD_ESTADO_TRAS,NUM_TRASPASO,NUM_PETICION,
 				       COD_BODEGA_ORI,COD_BODEGA_DEST,TIP_STOCK,TIP_STOCK_DEST,COD_ARTICULO,
				       COD_USO,COD_ESTADO,NUM_SERIE,FEC_TRASPASO_MASIVO,TIP_MOVIM_AUT,
				       TIP_MOVIM_ENV,TIP_MOVIM_REC,USU_TRASPASO_MASIVO,DES_OBSERVACION,
				       CAP_CODE,NUM_TELEFONO,COD_CENTRAL,COD_SUBALM,COD_CAT,NUM_SERIEMEC,
				       NOM_USUAPROC,FEC_PROCESO,SQLCODE,SQLERRM,NUM_CANTIDAD,COD_PEDIDO,
				       ROWID FILA
       FROM AL_TRASPASOS_MASIVO
       WHERE NUM_TRASPASO_MASIVO = iNum_Trasp
	         AND COD_ESTADO_TRAS = 'CE';

BEGIN
              i:=0;
              open c_ser_seriado;
                   loop
			fetch c_ser_seriado into V.NUM_TRASPASO_MASIVO,V.COD_ESTADO_TRAS,V.NUM_TRASPASO,V.NUM_PETICION,
				              V.COD_BODEGA_ORI,V.COD_BODEGA_DEST,V.TIP_STOCK,V.TIP_STOCK_DEST,V.COD_ARTICULO,
				              V.COD_USO,V.COD_ESTADO,V.NUM_SERIE,V.FEC_TRASPASO_MASIVO,V.TIP_MOVIM_AUT,
				              V.TIP_MOVIM_ENV,V.TIP_MOVIM_REC,V.USU_TRASPASO_MASIVO,V.DES_OBSERVACION,
				              V.CAP_CODE,V.NUM_TELEFONO,V.COD_CENTRAL,V.COD_SUBALM,V.COD_CAT,V.NUM_SERIEMEC,
				              V.NOM_USUAPROC,V.FEC_PROCESO,V.SQLCODE,V.SQLERRM,V.NUM_CANTIDAD,V.COD_PEDIDO,
				              V_FILA;
			exit when c_ser_seriado%NOTFOUND;
                        INSERT INTO AL_HTRASPASOS_MASIVO(NUM_TRASPASO_MASIVO,COD_ESTADO_TRAS,NUM_TRASPASO,NUM_PETICION,
 				       COD_BODEGA_ORI,COD_BODEGA_DEST,TIP_STOCK,TIP_STOCK_DEST,COD_ARTICULO,
				       COD_USO,COD_ESTADO,NUM_SERIE,FEC_TRASPASO_MASIVO,TIP_MOVIM_AUT,
				       TIP_MOVIM_ENV,TIP_MOVIM_REC,USU_TRASPASO_MASIVO,DES_OBSERVACION,
				       CAP_CODE,NUM_TELEFONO,COD_CENTRAL,COD_SUBALM,COD_CAT,NUM_SERIEMEC,
				       NOM_USUAPROC,FEC_PROCESO,SQLCODE,SQLERRM,NUM_CANTIDAD,COD_PEDIDO,
				       FEC_HIST,USU_HIST)
                               VALUES
			              (V.NUM_TRASPASO_MASIVO,V.COD_ESTADO_TRAS,V.NUM_TRASPASO,V.NUM_PETICION,
				              V.COD_BODEGA_ORI,V.COD_BODEGA_DEST,V.TIP_STOCK,V.TIP_STOCK_DEST,V.COD_ARTICULO,
				              V.COD_USO,V.COD_ESTADO,V.NUM_SERIE,V.FEC_TRASPASO_MASIVO,V.TIP_MOVIM_AUT,
				              V.TIP_MOVIM_ENV,V.TIP_MOVIM_REC,V.USU_TRASPASO_MASIVO,V.DES_OBSERVACION,
				              V.CAP_CODE,V.NUM_TELEFONO,V.COD_CENTRAL,V.COD_SUBALM,V.COD_CAT,V.NUM_SERIEMEC,
				              V.NOM_USUAPROC,V.FEC_PROCESO,V.SQLCODE,V.SQLERRM,V.NUM_CANTIDAD,V.COD_PEDIDO,
				              SYSDATE,USER);
			DELETE AL_TRASPASOS_MASIVO
              		WHERE ROWID = V_FILA;
                       i:= i +1;
                       IF i > 999 THEN
                          COMMIT;
                          i:=0;
                       END IF;
              end loop;
	      close    c_ser_seriado;
		  commit;

EXCEPTION
            WHEN OTHERS THEN
  	   	    COMMIT;
		    if c_ser_seriado%ISOPEN then close c_ser_seriado;end if;
	        RAISE_APPLICATION_ERROR (-20002,'Error Traspaso a historico: ' || TO_CHAR(SQLCODE) ||' '|| SQLERRM );
			ROLLBACK;
END;
/
SHOW ERRORS
