CREATE OR REPLACE PROCEDURE        P_CONFIRMAR_VENTA(
  VP_PRODUCTO IN NUMBER ,
  VP_ABONADO IN NUMBER ,
  VP_FECSYS IN DATE )
IS
--
-- Procedimiento de Actualizacion de las tablas de abonados de productos
-- al realizarse una aceptacion de ventas.
--
   V_PROCED VARCHAR2(25) := NULL;
BEGIN
   V_PROCED := 'P_CONFIRMAR_VENTA';
   IF VP_PRODUCTO = 1 THEN
      UPDATE GA_ABOCEL
         SET COD_SITUACION  = 'AAA',
             PERFIL_ABONADO = CLASE_SERVICIO
       WHERE NUM_ABONADO    = VP_ABONADO;
   ELSIF VP_PRODUCTO = 2 THEN
      UPDATE GA_ABOBEEP
         SET COD_SITUACION = 'AAA',
             PERFIL_ABONADO = CLASE_SERVICIO
       WHERE NUM_ABONADO   = VP_ABONADO;
   ELSIF VP_PRODUCTO = 3 THEN
      UPDATE GA_ABOTRUNK
         SET COD_SITUACION = 'AAA',
             PERFIL_ABONADO = CLASE_SERVICIO
       WHERE NUM_ABONADO   = VP_ABONADO;
   ELSIF VP_PRODUCTO = 4 THEN
      UPDATE GA_ABOTREK
         SET COD_SITUACION = 'AAA',
             PERFIL_ABONADO = CLASE_SERVICIO
       WHERE NUM_ABONADO   = VP_ABONADO;
   ELSE
      RAISE_APPLICATION_ERROR (-20206,V_PROCED||' '||SQLERRM);
   END IF;
   UPDATE GA_SERVSUPLABO
      SET FEC_ALTACEN = VP_FECSYS,
          IND_ESTADO = 2
    WHERE NUM_ABONADO = VP_ABONADO
      AND IND_ESTADO = 1;
EXCEPTION
   WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR (-20206,V_PROCED||' '||SQLERRM);
END;
/
SHOW ERRORS
