CREATE OR REPLACE PROCEDURE        P_DATOS_ABOBEEP(
  VP_ABONADO IN NUMBER ,
  VP_CLIENTE IN OUT NUMBER ,
  VP_IMPLIMCONS IN OUT NUMBER ,
  VP_TIPPLANTARIF IN OUT VARCHAR2 ,
  VP_PLANTARIF IN OUT VARCHAR2 ,
  VP_CAPCODE IN OUT NUMBER ,
  VP_BEEPER IN OUT NUMBER ,
  VP_CARGOBASICO IN OUT VARCHAR2 ,
  VP_CICLO IN OUT NUMBER ,
  VP_PLANSERV IN OUT VARCHAR2 ,
  VP_GRPSERV IN OUT VARCHAR2 ,
  VP_EMPRESA IN OUT VARCHAR2 ,
  VP_HOLDING IN OUT VARCHAR2 ,
  VP_PROCALTA IN OUT NUMBER ,
  VP_AGENTE IN OUT NUMBER ,
  VP_FECALTA IN OUT DATE ,
  VP_VENTA IN OUT NUMBER ,
  VP_INDFACT IN OUT NUMBER ,
  VP_FINCONTRA IN OUT DATE ,
  VP_BAJACEN IN OUT DATE ,
  VP_BAJA IN OUT DATE ,
  VP_CREDMOR IN OUT VARCHAR2 ,
  VP_USUARIO IN OUT NUMBER ,
  VP_PROC IN OUT VARCHAR2 ,
  VP_TABLA IN OUT VARCHAR2 ,
  VP_ACT IN OUT VARCHAR2 ,
  VP_SQLCODE IN OUT VARCHAR2 ,
  VP_SQLERRM IN OUT VARCHAR2 ,
  VP_ERROR IN OUT VARCHAR2 )
IS
--
-- Procedimiento que recupera datos en la tabla de abonados beeper
--
--            Los posibles retornos del procedimiento son :
--                - '0' Actualizaciones realizadas correctamente
--                - '4' Error en el proceso
--
  V_LIMCONSUMO GA_ABOBEEP.COD_LIMCONSUMO%TYPE;
BEGIN
   VP_PROC := 'P_DATOS_ABOBEEP';
   VP_TABLA := 'GA_ABOBEEP';
   VP_ACT := 'S';
   SELECT COD_CLIENTE,COD_LIMCONSUMO,TIP_PLANTARIF,
   COD_PLANTARIF,CAP_CODE,NUM_BEEPER,
          COD_CARGOBASICO,COD_CICLO,COD_PLANSERV,
          COD_GRPSERV,COD_EMPRESA,COD_HOLDING,
          IND_PROCALTA,COD_VENDEDOR_AGENTE,FEC_ACTCEN,
          NUM_VENTA,IND_FACTUR,FEC_FINCONTRA,
   FEC_BAJACEN,FEC_BAJA,COD_CREDMOR,
   COD_USUARIO
     INTO VP_CLIENTE,V_LIMCONSUMO,VP_TIPPLANTARIF,
   VP_PLANTARIF,VP_CAPCODE,VP_BEEPER,
          VP_CARGOBASICO,VP_CICLO,VP_PLANSERV,
          VP_GRPSERV,VP_EMPRESA,VP_HOLDING,
          VP_PROCALTA,VP_AGENTE,VP_FECALTA,
          VP_VENTA,VP_INDFACT,VP_FINCONTRA,
   VP_BAJACEN,VP_BAJA,VP_CREDMOR,
   VP_USUARIO
     FROM GA_ABOBEEP
    WHERE NUM_ABONADO = VP_ABONADO;
    VP_TABLA := 'TA_LIMCONSUMO';
    VP_ACT := 'S';
    SELECT IMP_LIMCONSUMO
      INTO VP_IMPLIMCONS
      FROM TA_LIMCONSUMO
     WHERE COD_PRODUCTO = 2
       AND COD_LIMCONSUMO = V_LIMCONSUMO;
EXCEPTION
   WHEN OTHERS THEN
 VP_SQLCODE := SQLCODE;
 VP_SQLERRM := SQLERRM;
        VP_ERROR := '4';
END;
/
SHOW ERRORS
