CREATE OR REPLACE PROCEDURE        P_DEL_RESERVANUMERO
 (V_ABONADO IN GA_ABOCEL.NUM_ABONADO%TYPE,
V_ERROR OUT VARCHAR2)IS
V_CELULAR GA_ABOCEL.NUM_CELULAR%TYPE;
BEGIN
  SELECT NUM_CELULAR
  INTO V_CELULAR
  FROM GA_ABOCEL
  WHERE NUM_ABONADO=V_ABONADO;
  DELETE GA_RESNUMCEL WHERE NUM_CELULAR=V_CELULAR;
  V_ERROR:='0';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    V_ERROR:='4';
  WHEN OTHERS THEN
    V_ERROR:='4';
END;
/
SHOW ERRORS
