CREATE OR REPLACE PROCEDURE        P_DES_MOVIMIENTO
 (V_ABONADO IN GA_ABOCEL.NUM_ABONADO%TYPE,
V_MOVIMIENTO IN  ICC_MOVIMIENTO.NUM_MOVIMIENTO%TYPE,
V_ERROR OUT VARCHAR2)IS
BEGIN
  UPDATE ICC_MOVIMIENTO
     SET COD_ESTADO = 10
  WHERE NUM_MOVIMIENTO=V_MOVIMIENTO;
  V_ERROR:='0';
EXCEPTION
   WHEN OTHERS THEN
       V_ERROR:='4';
END;
/
SHOW ERRORS
