CREATE OR REPLACE PROCEDURE        P_DEL_CTCMOVIM
(V_TELEFIJA IN NUMBER,
V_ERROR IN OUT VARCHAR2)IS
V_FILA ROWID;
BEGIN
  V_FILA:=' ';
  SELECT ROWID
  INTO V_FILA
  FROM GA_CTC_MOVIMIENTOS
  WHERE NUM_REDFIJA=V_TELEFIJA;
  IF V_FILA != ' ' THEN
     DELETE GA_CTC_MOVIMIENTOS
     WHERE ROWID=V_FILA;
  END IF;
  V_ERROR:='0';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    V_ERROR:='4';
END;
/
SHOW ERRORS
