CREATE OR REPLACE PROCEDURE        P_MODIFICA_NUMPROCESO(
  VP_ABONADO IN NUMBER ,
  VP_PROC IN OUT VARCHAR2 ,
  VP_TABLA IN OUT VARCHAR2 ,
  VP_ACT IN OUT VARCHAR2 ,
  VP_SQLCODE IN OUT VARCHAR2 ,
  VP_SQLERRM IN OUT VARCHAR2 ,
  VP_ERROR IN OUT VARCHAR2 )
IS
--
--
BEGIN
   UPDATE FA_CICLOCLI
      SET NUM_PROCESO = 0
    WHERE NUM_ABONADO = VP_ABONADO;
EXCEPTION
   WHEN OTHERS THEN
        VP_ERROR := '4';
 VP_SQLCODE := SQLCODE;
 VP_SQLERRM := SQLERRM;
END;
/
SHOW ERRORS
