CREATE OR REPLACE PROCEDURE        P_SELECT_REUTILIZABLESROA(
  VP_OPERADOR IN VARCHAR2 ,
  VP_PAIS IN VARCHAR2 ,
  VP_ZONA IN VARCHAR2 ,
  VP_CELULAR IN OUT VARCHAR2 ,
  VP_FECBAJA IN OUT DATE ,
  VP_ERROR IN OUT VARCHAR2 )
IS
   V_ROWID ROWID;
   V_DIAS GA_DATOSGENER.NUM_DIASREUTIL%TYPE;
   CURSOR C2 IS
   SELECT ROWID
     FROM GA_REUTNUMROA
    WHERE COD_OPERADOR = VP_OPERADOR
      AND COD_PAIS     = VP_PAIS
      AND COD_ZONA     = VP_ZONA
      AND FEC_BAJA + V_DIAS <= SYSDATE
    ORDER BY NUM_CELULAR;
BEGIN
    SELECT NUM_DIASREUTIL
      INTO V_DIAS
      FROM GA_DATOSGENER;
    OPEN C2;
    LOOP
      IF VP_ERROR <> '2' THEN
         EXIT;
      END IF;
      BEGIN
         FETCH C2 INTO V_ROWID;
         EXIT WHEN C2%NOTFOUND;
         SELECT NUM_CELULAR,FEC_BAJA
           INTO VP_CELULAR,VP_FECBAJA
           FROM GA_REUTNUMROA
          WHERE ROWID = V_ROWID
            FOR UPDATE OF NUM_CELULAR NOWAIT;
         DELETE GA_REUTNUMROA WHERE ROWID = V_ROWID;
         VP_ERROR := '0';
      EXCEPTION
         WHEN NO_DATA_FOUND THEN
              NULL;
         WHEN OTHERS THEN
              IF SQLCODE = -54 THEN
                 NULL;
              ELSE
                 VP_ERROR := '4';
              END IF;
      END;
    END LOOP;
    CLOSE C2;
EXCEPTION
    WHEN OTHERS THEN
         VP_ERROR := '4';
END;
/
SHOW ERRORS
