CREATE OR REPLACE PROCEDURE        P_VALIDA_ROBADAS(
  V_SERIE IN GA_ABOCEL.NUM_SERIE%TYPE ,
  V_ERROR IN OUT CHAR )
IS
    VAR1 GA_ABOCEL.NUM_SERIE%TYPE;
BEGIN
    SELECT NUM_SERIE
      INTO VAR1
      FROM GA_LNCELU
     WHERE NUM_SERIE = V_SERIE;
     V_ERROR := '3';
EXCEPTION
   WHEN NO_DATA_FOUND THEN
        V_ERROR := '0';
   WHEN TOO_MANY_ROWS THEN
        V_ERROR := '3';
   WHEN OTHERS THEN
        V_ERROR := '4';
--
--
END;
/
SHOW ERRORS
