CREATE OR REPLACE PROCEDURE        P_VALIDA_FORMATO(
  V_SERIE IN GA_ABOCEL.NUM_SERIE%TYPE ,
  V_ERROR IN OUT CHAR )
IS
BEGIN
--
--
   IF SUBSTR(V_SERIE,1,3) > 255 OR SUBSTR(V_SERIE,4,8) > 16777215 THEN
      V_ERROR := '1';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
        V_ERROR := '4';
--
--
END;
/
SHOW ERRORS
