CREATE OR REPLACE PACKAGE        PKG_ICC_SERVSUPLABO IS
  PROCEDURE GetAbo(CodCli IN NUMBER, NumCel IN NUMBER, NumAbo OUT NUMBER);
  PROCEDURE SetSerSupAbo(NumAbonado IN NUMBER, CodSer IN VARCHAR2);
  PROCEDURE InsMovCel(NumMov OUT INTEGER);
  PROCEDURE InsOOSS(TipOS IN VARCHAR2);
END pkg_icc_servsuplabo;
/
SHOW ERRORS
