CREATE OR REPLACE PACKAGE PV_CONSULTA_SERIENEGATIVAS_PG IS

        PROCEDURE PV_SERIES_NEGATIVAS_PR
        (
          EV_SERIE IN VARCHAR2,
          EV_SALIDA OUT BOOLEAN
        );

END PV_CONSULTA_SERIENEGATIVAS_PG;
/
SHOW ERRORS
