CREATE OR REPLACE PACKAGE PV_MASCARA_NUM_PERSONAL_PG
IS

	PROCEDURE PV_MASCARA_ACTUALIZA_NUMCEL_PR(
	  EV_NUM_CELULAR_PER   IN VARCHAR2,
	  EV_NUM_CELULAR_COR   IN VARCHAR2,
	  EV_ACTABO            IN VARCHAR2
    );
end PV_MASCARA_NUM_PERSONAL_PG;
/
SHOW ERRORS
