CREATE OR REPLACE PACKAGE PV_PROCESO_PG IS

PROCEDURE PV_ACTUALIZA_BAJA_ALTA_SS_PR(VP_PRODUCTO IN NUMBER,
                                       VP_ABONADO  IN NUMBER,
                                       VP_CLASEABO IN VARCHAR2);
END PV_PROCESO_PG; 
/
SHOW ERRORS
