CREATE OR REPLACE PROCEDURE        PV_PR_DEVVALPARAM
(vCOD_MODULO	IN VARCHAR2,
 nCOD_PRODUCTO  IN NUMBER,
 vNOM_PARAMETRO IN VARCHAR2,
 vVAL_PARAMETRO OUT VARCHAR2)
IS

BEGIN

   SELECT VAL_PARAMETRO
   INTO vVAL_PARAMETRO
   FROM GED_PARAMETROS
   WHERE COD_PRODUCTO=nCOD_PRODUCTO
   AND NOM_PARAMETRO=vNOM_PARAMETRO;

END;
/
SHOW ERRORS
