CREATE OR REPLACE FUNCTION        SP_FN_IND_OK (P_NUM_ORDEN NUMBER) return NUMBER
IS

 V_INDICADOR    NUMBER(1);
 V_CONTINDIC    NUMBER(2);

BEGIN
   SELECT COUNT(IND_OK)
   INTO V_CONTINDIC
   FROM SP_CHEQUEOS_ORDEN
   WHERE NUM_ORDEN = P_NUM_ORDEN
   AND IND_OK = 1 ;


   SELECT DECODE(V_CONTINDIC,0,0,1)
   INTO
   V_INDICADOR
   FROM DUAL;

   RETURN V_INDICADOR;

END;
/
SHOW ERRORS
