CREATE OR REPLACE PACKAGE VE_ACTUALIZADCTO_CARGO_PG IS




   PROCEDURE VE_ACTUALIZADCTO_CARGO_PR       (EV_TRANSAC   IN VARCHAR2,
  					      EV_NUMCARGO  IN VARCHAR2,
  				  	      EV_CODACTABO IN VARCHAR2
				             );

END VE_ACTUALIZADCTO_CARGO_PG;
/
SHOW ERRORS
