CREATE OR REPLACE PACKAGE VE_TIPOS_PG
IS
  TYPE  TIP_VE_MATRIZESTADOS_TD IS TABLE OF VE_MATRIZESTADOS_TD%ROWTYPE INDEX BY BINARY_INTEGER;
  TYPE  TIP_GA_VENTAS  IS TABLE OF GA_VENTAS%ROWTYPE INDEX BY BINARY_INTEGER;
  TYPE  TIP_GA_ABOCEL  IS TABLE OF GA_ABOCEL%ROWTYPE INDEX BY BINARY_INTEGER;
  TYPE TIP_VE_TIPCOMIS IS TABLE OF VE_TIPCOMIS%ROWTYPE INDEX BY BINARY_INTEGER;
END;


/
SHOW ERRORS
