/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.gte.integraciongte.ejb.session;

/**
 * Local home interface for IntegracionGTEFacade.
 * @generated 
 * @wtp generated
 */
public interface IntegracionGTEFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/IntegracionGTEFacadeLocal";
   public static final String JNDI_NAME="IntegracionGTEFacadeLocal";

   public com.tmmas.gte.integraciongte.ejb.session.IntegracionGTEFacadeLocal create()
      throws javax.ejb.CreateException;

}
