/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.gte.integraciongte.ejb.session;

/**
 * Home interface for IntegracionGTEFacade.
 * @generated 
 * @wtp generated
 */
public interface IntegracionGTEFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/IntegracionGTEFacade";
   public static final String JNDI_NAME="IntegracionGTEFacade";

   public com.tmmas.gte.integraciongte.ejb.session.IntegracionGTEFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
