/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.gte.integraciongte.ejb.session;

import com.tmmas.gte.integraciongtecommon.dto.ConsRenovacionDTO;
import com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO;
import com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException;
import com.tmmas.gte.integraciongteservice.srv.AbonadoDTOService;
import com.tmmas.gte.integraciongteservice.srv.AbonadoDTOServiceImpl;

/**
 * Remote interface for IntegracionGTEFacade.
 * @generated 
 * @wtp generated
 */
public interface IntegracionGTEFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.CarteraResponseDTO consultarSaldoPospago( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.DireccionRespOutDTO consultarDireccionTelefono( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.PlanTarifarioResponseOutDTO consultarPlanTarifario( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.SeguroResponseDTO consultarSeguroPorTelefono( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.LlamadasFacturadasOutDTO consultarLlamadasNoFacturadas( com.tmmas.gte.integraciongtecommon.dto.ConsLlamadaInDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.AltaPrepagoOutDTO consultarFechaAlta( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.ServicioSupleRespondeDTO consultarServiciosSuplementarios( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.FacturaResponseDTO consultasFacturasDeunCliente( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.FacturaOutDTO consultarFechaReporteConsumo( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.PagoOutDTO consultaPagosRealizados( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.ConsumoResponseOutDTO consultarConsumoMensajesCortos( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

    /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.RespBooleanDTO validarNumeroHibrido( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.ConsLinkFacturaResponseDTO consultarLinkFactura( com.tmmas.gte.integraciongtecommon.dto.ConsLinkFacturaDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.RespBooleanDTO validarNumPospago( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.RespBooleanDTO validarClienteTelefono( com.tmmas.gte.integraciongtecommon.dto.EsClieTelefDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.RespBooleanDTO validarTelIgualCli( com.tmmas.gte.integraciongtecommon.dto.EsTelefIgualClieDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.RespuestaDTO activarDesactivarSS( com.tmmas.gte.integraciongtecommon.dto.ActDesServSupleDto parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.ConsultaPukResponseDTO consultarPuk( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.RespBooleanDTO consultaNumeracion( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.ConsAvisoSiniestroResponseDTO consultarAvisoSiniestro( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.ConsAvisoSiniestroResponseDTO consultarFechaAvisoSiniestro( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.LstCliResponseDTO listarClientes( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.LstCliResponseDTO listarClientes( com.tmmas.gte.integraciongtecommon.dto.DatosLstCliCueDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.LstConceptoFacturaDTO consultarConceptosFactura( com.tmmas.gte.integraciongtecommon.dto.CodClienteDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.DatosClientePospHibrPrepDTO consultarDatosGenClienteTel( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.TecnologiaDTO consultarTecnologia( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.DatosClienteOutDTO consultarDatosGenClienteCod( com.tmmas.gte.integraciongtecommon.dto.CodClienteDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.FacturaResponseDTO obtenerUltimaFacturaPagada( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO inParam1 )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.FacturaResponseDTO consultarFacturasImpagasPorCliente( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.RespTipoClienteDTO consultarTipoCliente( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.PlanTarifarioResponseDTO consultarPlanesDisponibles( com.tmmas.gte.integraciongtecommon.dto.GrpCodPrestacionListDTO inParam0 )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.PlanTarifarioResponseDTO consultarPlanesDisponibles( com.tmmas.gte.integraciongtecommon.dto.GrupoPrestacionListDTO inParam0 )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.PlanTarifarioResponseDTO consultarPlanesDisponibles( com.tmmas.gte.integraciongtecommon.dto.AuditoriaDTO inParam0 )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.ConsPrestacionesResponseDTO consultarCodigosPrestacion( com.tmmas.gte.integraciongtecommon.dto.IdTipoPrestacionInDTO inParam0 )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.BloqueoResponseDTO consultaBloqueoTelefono( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.MinutosConsumidosDTO consultarMinutosConsumidos( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.RespBooleanDTO validarSoporteGprs( com.tmmas.gte.integraciongtecommon.dto.TerminalServicioDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.ComponentesResponseDTO consultarEstadoComponentes( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.SegmentoClienteResponseDTO obtenerSegmentoCliente( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.PrestacionResponseDTO consultarGruposPrestacion( com.tmmas.gte.integraciongtecommon.dto.AuditoriaDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.ConsultarTerminalResponseDTO consultarTerminal( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.ConsultarTipoAbonadoResponseDTO consultarTipoAbonado( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.FacturaNoCicloResponseDTO consultarFacturasNoCicloCliente( com.tmmas.gte.integraciongtecommon.dto.DistribuidorInDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.FacturaMesAnteriorResponseDTO consultaFacturaMesAnterior( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.DistribuidorResponseDTO consultarDatosDistribuidor( com.tmmas.gte.integraciongtecommon.dto.ConsDistribuidorInDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.DistribPedidoResponseDTO consultarDatosDistribuidor( com.tmmas.gte.integraciongtecommon.dto.DistribPedidoInDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.TipoServicioResponseDTO consultarTipoServicio( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.SaldoMorosidadDTO consultarSaldoClienteBloqueado( com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.LlamadasFacturadasOutDTO consultarLlamadasFacturadas( com.tmmas.gte.integraciongtecommon.dto.LlamadaClienteDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.TarjetaCreditoResponseDTO listarTarjetasDeCredito( com.tmmas.gte.integraciongtecommon.dto.AuditoriaDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.RespBooleanDTO registrarDatosTarjCredito( com.tmmas.gte.integraciongtecommon.dto.TarjetaDeCreditoInDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.BancoResponseDTO consultarBancosDisponibles( com.tmmas.gte.integraciongtecommon.dto.AuditoriaDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.MinutosLdiResponseDTO consultarMinutosLDI( com.tmmas.gte.integraciongtecommon.dto.MinutosLdiInDTO parametro )
      throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.gte.integraciongtecommon.dto.ConsRenovacionDTO consultarDatosRenovacion(com.tmmas.gte.integraciongtecommon.dto.NumeroTelefonoDTO parametro) 
   	  throws com.tmmas.gte.integraciongtecommon.exception.IntegracionGTEException, java.rmi.RemoteException;
   
}
