/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.gte.integraciongte.ws.session;

/**
 * Local home interface for IntegracionGTEWS.
 * @generated 
 * @wtp generated
 */
public interface IntegracionGTEWSLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/IntegracionGTEWSLocal";
   public static final String JNDI_NAME="IntegracionGTEWSLocal";

   public com.tmmas.gte.integraciongte.ws.session.IntegracionGTEWSLocal create()
      throws javax.ejb.CreateException;

}
