set serveroutput on size 1000000
DECLARE 
  V_CICLOFACT NUMBER(8);
  V_IND_TASADOR NUMBER(8);

BEGIN 
  V_CICLOFACT := &1;
  BEGIN
    FA_UTILFAC_PG.FA_HISTORICO_DE_LLAMADAS_PR( V_CICLOFACT );
  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Error en Renombrar Tabla para Ciclo:'||TO_CHAR(V_CICLOFACT));
      DBMS_OUTPUT.PUT_LINE('Error :'||SQLERRM);
  END;
END; 
/
exit
