SET TAB OFF LINES 132;
SET TRIMSPOOL ON;
SET PAGES 0;
--
COLUMN FA_HISTABOCELU FORMAT A25;
COLUMN FA_HISTABOBEEP FORMAT A25;
COLUMN FA_HISTDOCU    FORMAT A25;
COLUMN FA_HISTCONC    FORMAT A25;
SET HEADING OFF FEEDBACK OFF;
SPOOL ciclfact_&1..dat;
--
SELECT  COD_CICLFACT   ,
        FA_HISTABOCELU ,
        FA_HISTABOBEEP ,
        FA_HISTDOCU    ,
        FA_HISTCONC
FROM    FA_ENLACEHIST 
WHERE   COD_CICLFACT IN (SELECT UNIQUE COD_CICLFACT FROM OPS$XPFACTUR.XPF_LISTADO01 )
AND     COD_CICLFACT != 19010101;
SPOOL OFF;
EXIT
/