/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.suspvol.bean.ejb.session;

/**
 * Remote interface for SuspVolFacade.
 * @generated 
 * @wtp generated
 */
public interface SuspVolFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO obtenerDatosCliente( com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.AbonadoDTO obtenerDatosAbonado( com.tmmas.scl.framework.productDomain.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO obtenerDatosUsuarioAbonado( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.MensajeRetornoDTO ejecutaRestrccion( com.tmmas.scl.framework.ProductDomain.dto.RestriccionesDTO restricciones )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO obtenerInformacionUsuario( com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO usuarioSistema )
      throws com.tmmas.scl.framework.aplicationDomain.exception.AplicationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO aceptarPresupuesto( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PresupuestoDTO presup )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ResultadoRegCargosDTO parametrosRegistrarCargos( com.tmmas.scl.framework.productDomain.dataTransferObject.RegCargosDTO cargos )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.SuspensionAbonadoDTO[] obtenerSuspensionesAbonado( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.CausasSuspensionDTO[] obtenerCausasSuspension(  )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.SuspensionAbonadoDTO[] obtenerSuspensionesHistoricasAbonado( long numAbonado,java.sql.Date fecIni,java.sql.Date fecFin )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.FechasSuspensionDTO[] recuperarFechasSuspension( com.tmmas.scl.framework.commonDoman.dataTransferObject.ClienteOSSesionDTO sessionData )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void programarSuspension( com.tmmas.scl.framework.productDomain.dataTransferObject.SuspensionAbonadoDTO suspensionAbonado,com.tmmas.scl.framework.commonDoman.dataTransferObject.ClienteOSSesionDTO sessionData )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void modificarSuspension( com.tmmas.scl.framework.productDomain.dataTransferObject.SuspensionAbonadoDTO suspensionAbonado )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void anularSuspension( com.tmmas.scl.framework.productDomain.dataTransferObject.SuspensionAbonadoDTO suspensionAbonado )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.DatosGeneralesSuspensionDTO obtenerDatosGeneralesSuspension(  )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.PeriodoSuspencionAbonadoDTO[] obtenerPeriodosSuspensioAbonado( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void agregaPeriodoSuspension( com.tmmas.scl.framework.productDomain.dataTransferObject.PeriodoSuspencionAbonadoDTO periodoSuspensionAbonado )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void registrarSuspensionVoluntaria( com.tmmas.scl.operation.crm.fab.cusintman.suspvol.common.dataTransfertObject.RegistraSuspVoluntariaDTO registraDTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.OperadoraLocalDTO obtenerOperadoraLocal(  )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

}
