/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.suspvol.bean.ejb.session;

/**
 * Local home interface for SuspVolFacade.
 * @generated 
 * @wtp generated
 */
public interface SuspVolFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SuspVolFacadeLocal";
   public static final String JNDI_NAME="SuspVolFacadeLocal";

   public com.tmmas.scl.operation.crm.fab.cusintman.suspvol.bean.ejb.session.SuspVolFacadeLocal create()
      throws javax.ejb.CreateException;

}
