GRANT EXECUTE ON PF_CARGOS_PRODUCTOS_PG TO MAS_ADMIN_RO;

GRANT EXECUTE ON PF_CARGOS_PRODUCTOS_PG TO MAS_APPLICATION_RO;

GRANT EXECUTE ON PF_CARGOS_PRODUCTOS_PG TO MAS_SELECT_RO;

GRANT EXECUTE ON PF_CARGOS_PRODUCTOS_PG TO SISCEL;

GRANT EXECUTE ON PF_CARGOS_PRODUCTOS_PG TO SP_ACCENTURE;

GRANT EXECUTE ON PF_CARGOS_PRODUCTOS_PG TO SP_EVERIS;

GRANT EXECUTE ON PF_CARGOS_PRODUCTOS_PG TO SP_INDRA;
