GRANT EXECUTE ON PR_PROCESOS_PROD_TO_PG TO SISCEL ;
GRANT EXECUTE ON PR_PROCESOS_PROD_TO_PG TO SISCEL_VE ;
GRANT EXECUTE ON PR_PROCESOS_PROD_TO_PG TO MAS_SELECT_RO ;
GRANT EXECUTE ON PR_PROCESOS_PROD_TO_PG TO MAS_APPLICATION_RO ;
GRANT EXECUTE ON PR_PROCESOS_PROD_TO_PG TO MAS_ADMIN_RO ;

