GRANT EXECUTE ON PR_PROCESO_PRODUCTO_QT TO MAS_ADMIN_RO;

GRANT EXECUTE ON PR_PROCESO_PRODUCTO_QT TO MAS_APPLICATION_RO;

GRANT EXECUTE ON PR_PROCESO_PRODUCTO_QT TO MAS_SELECT_RO;

GRANT EXECUTE ON PR_PROCESO_PRODUCTO_QT TO SISCEL_ADMIN;

GRANT EXECUTE ON PR_PROCESO_PRODUCTO_QT TO SISCEL_PV;

GRANT EXECUTE ON PR_PROCESO_PRODUCTO_QT TO SISCEL_SELECT;
