GRANT EXECUTE ON PR_VALIDACONTRBENEF_PG TO MAS_ADMIN_RO
/
GRANT EXECUTE ON PR_VALIDACONTRBENEF_PG TO MAS_APPLICATION_RO
/
GRANT EXECUTE ON PR_VALIDACONTRBENEF_PG TO MAS_SELECT_RO
/
GRANT EXECUTE ON PR_VALIDACONTRBENEF_PG TO SISCEL
/
GRANT EXECUTE ON PR_VALIDACONTRBENEF_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PR_VALIDACONTRBENEF_PG TO SISCEL_IC
/
GRANT EXECUTE ON PR_VALIDACONTRBENEF_PG TO SISCEL_SELECT
/
