/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.servsup.bean.ejb.session;

/**
 * Home interface for SerSupFacade.
 * @generated 
 * @wtp generated
 */
public interface SerSupFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SerSupFacade";
   public static final String JNDI_NAME="SerSupFacade";

   public com.tmmas.scl.operation.crm.fab.cusintman.servsup.bean.ejb.session.SerSupFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
