/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.servsup.bean.ejb.session;

/**
 * Local interface for SerSupFacade.
 * @generated 
 * @wtp generated
 */
public interface SerSupFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
