/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.servsup.bean.ejb.session;

/**
 * Remote interface for SerSupFacade.
 * @generated 
 * @wtp generated
 */
public interface SerSupFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO obtenerDatosCliente( com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.AbonadoDTO obtenerDatosAbonado( com.tmmas.scl.framework.productDomain.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO obtenerDatosUsuarioAbonado( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.BodegaDTO[] obtenerBodegas( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sesion )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.TipoDeContratoDTO[] obtenerTiposDeContrato( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sessionDTO )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.MesesProrrogasDTO[] obtenerMesesProrroga(  )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO[] obtenerModalidadPago( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO Sesion,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO CausaCamSerie )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO[] obtenerModalidadPagoSimcard( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO Sesion,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO CausaCamSerie )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.TipoTerminalDTO[] obtenerTipoTerminal( com.tmmas.scl.framework.ProductDomain.dto.TecnologiaDTO tecnologia )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.CuotaDTO[] obtenerCuotas( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sesion,com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO modalidadPago )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void bloquearVendedor( com.tmmas.scl.framework.customerDomain.dto.VendedorDTO vendedor )
      throws com.tmmas.scl.framework.customerDomain.exception.CustomerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void desbloquearVendedor( com.tmmas.scl.framework.customerDomain.dto.VendedorDTO vendedor )
      throws com.tmmas.scl.framework.customerDomain.exception.CustomerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.UsosVentaDTO[] obtenerUsosVenta(  )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.CentralDTO[] obtenerCentralTecnologiaHlr( com.tmmas.scl.framework.ProductDomain.dto.SerieDTO serie,com.tmmas.scl.framework.ProductDomain.dto.TecnologiaDTO tecnologia )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void validaCausaCamSerie( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sesion,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO causaCamSerie )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.MensajeRetornoDTO ejecutaRestrccion( com.tmmas.scl.framework.ProductDomain.dto.RestriccionesDTO restricciones )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO obtenerInformacionUsuario( com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO usuarioSistema )
      throws com.tmmas.scl.framework.aplicationDomain.exception.AplicationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void reservaSimcard( java.lang.String accionProceso,com.tmmas.scl.framework.ProductDomain.dto.SerieDTO serie,com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO usuarioSistema,com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado,java.lang.String parametros,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO causa,com.tmmas.scl.framework.ProductDomain.dto.TipoTerminalDTO terminal,com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO modalidadPago )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, com.tmmas.scl.framework.customerDomain.exception.CustomerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SerieDTO recInfoSerie( com.tmmas.scl.framework.ProductDomain.dto.SerieDTO serie )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SiniestrosDTO[] recDatosSiniestroAboando( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SSuplementarioDTO[] obtenerServiciosDisplonibles( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado,com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sesion )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SSuplementarioDTO[] obtenerServiciosContratados( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado,long opcion )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.ReglasSSDTO[] getReglasdeValidacionSS( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado,com.tmmas.scl.framework.productDomain.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.framework.customerDomain.exception.CustomerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void actDesactSS( com.tmmas.scl.framework.commonDoman.dataTransferObject.ClienteOSSesionDTO sessionData,java.lang.String listServAct,java.lang.String listServDesac,java.lang.String montoTotal,com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO usuarioSistema,com.tmmas.scl.vendedor.dto.VendedorDTO vendedor,boolean oossComisionable,java.lang.String comentario )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void registrarServiciosSuplementariosAction( com.tmmas.scl.operation.crm.fab.cusintman.servsup.common.dataTransfertObject.RegistraServSuplemtDTO regServSuplemDTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO aceptarPresupuesto( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PresupuestoDTO presup )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ResultadoRegCargosDTO parametrosRegistrarCargos( com.tmmas.scl.framework.productDomain.dataTransferObject.RegCargosDTO cargos )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SSuplementarioDTO[] getServiciosBBContratados( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.GaServSuPlDTO getEstadoCorreoServSupl( com.tmmas.scl.framework.ProductDomain.dto.GaServSuPlDTO gaServSuPlDTO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.GaServSupDefDTO[] getObtieneListCodServPorDef( com.tmmas.scl.framework.ProductDomain.dto.GaServSupDefDTO gaServSupDefDTO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.GaAboMailTODTO[] getAbomailTOxNumAbonado( com.tmmas.scl.framework.ProductDomain.dto.GaAboMailTODTO gaAboMailTODTO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.ParametrosGeneralesDTO getParametroGeneral( com.tmmas.scl.framework.ProductDomain.dto.ParametrosGeneralesDTO entrada )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.OperadoraLocalDTO obtenerOperadoraLocal(  )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.DatosCentralDTO obtenerDatosCentral( int codCentral )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void reponerNumeracion( com.tmmas.scl.framework.ProductDomain.dto.NumeracionCelularDTO numeracionCelularVO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SeleccionNumeroCelularDTO[] obtenerNumeracionReservada( com.tmmas.scl.framework.ProductDomain.dto.DatosNumeracionDTO datosNumeracionDTO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String obtieneCategoria( com.tmmas.scl.framework.ProductDomain.dto.DatosNumeracionDTO datosNumeracionVO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String obtenerCeldaAbonado( long numAbonado )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.DatosNumeracionDTO obtieneNumeracionAutomatica( com.tmmas.scl.framework.ProductDomain.dto.DatosNumeracionDTO datosNumeracionDTO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SeleccionNumeroCelularRangoDTO[] obtenerNumeracionRango( com.tmmas.scl.framework.ProductDomain.dto.DatosNumeracionDTO datosNumeracionDTO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SeleccionNumeroCelularDTO[] obtenerNumeracionReutilizable( com.tmmas.scl.framework.ProductDomain.dto.DatosNumeracionDTO datosNumeracionDTO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void reservaNumeroCelular( com.tmmas.scl.framework.ProductDomain.dto.NumeracionCelularDTO numeracionCelularVO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void insertarNumeroCelularReservado( com.tmmas.scl.framework.ProductDomain.dto.NumeracionCelularDTO numeracionCelularVO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void desReservaNumeroCelular( com.tmmas.scl.framework.ProductDomain.dto.NumeracionCelularDTO numeracionCelularVO )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

}
