//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : P-TMM-08004
//  @ File Name : ConfiguracionGestionAbonadoDAO.java
//  @ Date : 09/09/2008
//  @ Author : hsegura
//
//



package com.tmmas.scl.framework.Sistema.dao;


public class ConfiguracionGestionAbonadoDAO extends ConfiguracionSistemaDAO {

}
