/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.bean.ejb.session;

/**
 * Local interface for CusRelManWSFacade.
 * @generated 
 * @wtp generated
 */
public interface CusRelManWSFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
