/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.smo.bean.ejb.session;

/**
 * Local home interface for SerManOpeWSFacade.
 * @generated 
 * @wtp generated
 */
public interface SerManOpeWSFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SerManOpeWSFacadeLocal";
   public static final String JNDI_NAME="SerManOpeWSFacadeLocal";

   public com.tmmas.scl.operations.smo.bean.ejb.session.SerManOpeWSFacadeLocal create()
      throws javax.ejb.CreateException;

}
