/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.wsportal.negocio.ejb.session;

/**
 * Local home interface for LlenadoFacade.
 * @generated 
 * @wtp generated
 */
public interface LlenadoFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LlenadoFacadeLocal";
   public static final String JNDI_NAME="LlenadoFacadeLocal";

   public com.tmmas.scl.wsportal.negocio.ejb.session.LlenadoFacadeLocal create()
      throws javax.ejb.CreateException;

}
