GRANT DELETE ON ADN_CAB_PLAN_STATUS_TO TO SISCEL_ADMIN
/
GRANT INSERT ON ADN_CAB_PLAN_STATUS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON ADN_CAB_PLAN_STATUS_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON ADN_CAB_PLAN_STATUS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON ADN_CAB_PLAN_STATUS_TO TO SISCEL_SELECT
/
GRANT SELECT ON ADN_CAB_PLAN_STATUS_TO TO SOLO_CONSULTA_SISCEL
/
