GRANT SELECT , INSERT , UPDATE , DELETE ON ADN_PROCESOS_HIBERNA_TT TO SISCEL_AL
/
GRANT SELECT                            ON ADN_PROCESOS_HIBERNA_TT TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON ADN_PROCESOS_HIBERNA_TT TO SISCEL_ADMIN
/