GRANT DELETE ON ADN_CELNUM_DEVUELTOS_TH TO SISCEL_ADMIN
/
GRANT INSERT ON ADN_CELNUM_DEVUELTOS_TH TO SISCEL_ADMIN
/
GRANT SELECT ON ADN_CELNUM_DEVUELTOS_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON ADN_CELNUM_DEVUELTOS_TH TO SISCEL_ADMIN
/
GRANT SELECT ON ADN_CELNUM_DEVUELTOS_TH TO SISCEL_SELECT
/
GRANT SELECT ON ADN_CELNUM_DEVUELTOS_TH TO SOLO_CONSULTA_SISCEL
/
