GRANT DELETE ON ADN_CONTAMINADOS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON ADN_CONTAMINADOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON ADN_CONTAMINADOS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON ADN_CONTAMINADOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON ADN_CONTAMINADOS_TD TO SISCEL_SELECT
/
GRANT SELECT ON ADN_CONTAMINADOS_TD TO SOLO_CONSULTA_SISCEL
/
