GRANT DELETE ON ADN_PORTADO_IN_TO TO SISCEL_ADMIN
/
GRANT INSERT ON ADN_PORTADO_IN_TO TO SISCEL_ADMIN
/
GRANT SELECT ON ADN_PORTADO_IN_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON ADN_PORTADO_IN_TO TO SISCEL_ADMIN
/
GRANT SELECT ON ADN_PORTADO_IN_TO TO SISCEL_SELECT
/
GRANT SELECT ON ADN_PORTADO_IN_TO TO SOLO_CONSULTA_SISCEL
/
