GRANT DELETE ON ADN_HCATEGORIA_TD TO SISCEL_ADMIN
/
GRANT INSERT ON ADN_HCATEGORIA_TD TO SISCEL_ADMIN
/
GRANT SELECT ON ADN_HCATEGORIA_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON ADN_HCATEGORIA_TD TO SISCEL_ADMIN
/
GRANT SELECT ON ADN_HCATEGORIA_TD TO SISCEL_SELECT
/
GRANT SELECT ON ADN_HCATEGORIA_TD TO SOLO_CONSULTA_SISCEL
/
