GRANT DELETE, INSERT, SELECT, UPDATE ON SISCEL.AL_AUDIT_CELNUM_REUTIL_TO TO SISCEL_ADMIN;
/
GRANT DELETE, INSERT, SELECT, UPDATE ON SISCEL.AL_AUDIT_CELNUM_REUTIL_TO TO SISCEL_AL;
/
GRANT DELETE, INSERT, SELECT, UPDATE ON SISCEL.AL_AUDIT_CELNUM_REUTIL_TO TO SISCEL_GA;
/
GRANT SELECT ON SISCEL.AL_AUDIT_CELNUM_REUTIL_TO TO SISCEL_SELECT;
/