GRANT EXECUTE  ON AL_ACTIVACION_TARJETAS_PG   TO  SISCEL_SELECT
/
GRANT EXECUTE  ON AL_ACTIVACION_TARJETAS_PG   TO  SISCEL_ADMIN
/
GRANT EXECUTE  ON AL_ACTIVACION_TARJETAS_PG   TO  SISCEL_PV
/
GRANT EXECUTE  ON AL_ACTIVACION_TARJETAS_PG   TO  SISCEL_GA
/
GRANT EXECUTE  ON AL_ACTIVACION_TARJETAS_PG   TO  SISCEL_GE
/