GRANT SELECT , INSERT , UPDATE , DELETE ON AL_ACTIVACION_ALTAMIRA_TO TO SISCEL_AL
/
GRANT SELECT , INSERT , UPDATE , DELETE ON AL_ACTIVACION_ALTAMIRA_TO TO ICONTABLE_SCL
/
GRANT SELECT                            ON AL_ACTIVACION_ALTAMIRA_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON AL_ACTIVACION_ALTAMIRA_TO TO SISCEL_ADMIN
/

