GRANT DELETE ON AL_CONTROL_PROCFTP_TO TO SISCEL_ADMIN
/
GRANT INSERT ON AL_CONTROL_PROCFTP_TO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_CONTROL_PROCFTP_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON AL_CONTROL_PROCFTP_TO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_CONTROL_PROCFTP_TO TO SISCEL_SELECT
/
GRANT SELECT ON AL_CONTROL_PROCFTP_TO TO SOLO_CONSULTA_SISCEL
/
