GRANT DELETE ON AL_DOCU_KARDEX TO SISCEL_ADMIN
/
GRANT INSERT ON AL_DOCU_KARDEX TO SISCEL_ADMIN
/
GRANT SELECT ON AL_DOCU_KARDEX TO SISCEL_ADMIN
/
GRANT UPDATE ON AL_DOCU_KARDEX TO SISCEL_ADMIN
/
GRANT DELETE ON AL_DOCU_KARDEX TO SISCEL_AL
/
GRANT INSERT ON AL_DOCU_KARDEX TO SISCEL_AL
/
GRANT SELECT ON AL_DOCU_KARDEX TO SISCEL_AL
/
GRANT UPDATE ON AL_DOCU_KARDEX TO SISCEL_AL
/
GRANT SELECT ON AL_DOCU_KARDEX TO SISCEL_SELECT
/
GRANT SELECT ON AL_DOCU_KARDEX TO SOLO_CONSULTA_SISCEL
/
