GRANT EXECUTE ON AL_DOCUMENTOS_PG TO MAS_REPORTES
/
GRANT EXECUTE ON AL_DOCUMENTOS_PG TO RA_SELECT_RO
/
GRANT EXECUTE ON AL_DOCUMENTOS_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON AL_DOCUMENTOS_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON AL_DOCUMENTOS_PG TO SISCEL_VE
/
