GRANT DELETE ON AL_DET_RESERVA_TO TO SISCEL_ADMIN
/
GRANT INSERT ON AL_DET_RESERVA_TO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_DET_RESERVA_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON AL_DET_RESERVA_TO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_DET_RESERVA_TO TO SISCEL_SELECT
/
GRANT SELECT ON AL_DET_RESERVA_TO TO SOLO_CONSULTA_SISCEL
/
