GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON SISCEL.AL_ESTADO_TRASPASO_TO TO SISCEL_ADMIN
/
GRANT DELETE, INSERT, SELECT, UPDATE ON SISCEL.AL_ESTADO_TRASPASO_TO TO SISCEL_GA
/
GRANT SELECT ON SISCEL.AL_ESTADO_TRASPASO_TO TO SISCEL_SELECT
/
GRANT ALTER, DELETE, INSERT, SELECT ON SISCEL.AL_ESTADO_TRASPASO_TO TO SISCEL_VE
/