GRANT SELECT ON AL_ERRORES_TEMP_TO TO EBZ_SISCEL
/
GRANT DELETE ON AL_ERRORES_TEMP_TO TO SISCEL_ADMIN
/
GRANT INSERT ON AL_ERRORES_TEMP_TO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_ERRORES_TEMP_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON AL_ERRORES_TEMP_TO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_ERRORES_TEMP_TO TO SISCEL_SELECT
/
GRANT SELECT ON AL_ERRORES_TEMP_TO TO SOLO_CONSULTA_SISCEL
/
