GRANT  EXECUTE   ON  AL_FOLIOS_PG  TO EBZ_SISCEL
/
GRANT  EXECUTE   ON  AL_FOLIOS_PG  TO MAS_REPORTES
/
GRANT  EXECUTE   ON  AL_FOLIOS_PG  TO RA_SELECT_RO
/
GRANT  EXECUTE   ON  AL_FOLIOS_PG  TO SISCEL_ADMIN
/
GRANT  EXECUTE   ON  AL_FOLIOS_PG  TO SISCEL_SELECT
/
GRANT  EXECUTE   ON  AL_FOLIOS_PG  TO SISCEL_VE
/
GRANT  EXECUTE   ON  AL_FOLIOS_PG  TO INTERNET_SELECT
/
GRANT  EXECUTE   ON  AL_FOLIOS_PG  TO INTERNET_SELECT
/
