GRANT EXECUTE ON AL_FN_PREFIJO_NUMERO TO EBZ_SISCEL
/
GRANT EXECUTE ON AL_FN_PREFIJO_NUMERO TO REPROA_SELECT
/
GRANT EXECUTE ON AL_FN_PREFIJO_NUMERO TO SISCEL_ADMIN
/
GRANT EXECUTE ON AL_FN_PREFIJO_NUMERO TO SISCEL_AL
/
GRANT EXECUTE ON AL_FN_PREFIJO_NUMERO TO SISCEL_GA
/
GRANT EXECUTE ON AL_FN_PREFIJO_NUMERO TO SISCEL_SELECT
/
