GRANT DELETE ON AL_HPMP_ARTICULO_TH TO SISCEL_ADMIN
/
GRANT INSERT ON AL_HPMP_ARTICULO_TH TO SISCEL_ADMIN
/
GRANT SELECT ON AL_HPMP_ARTICULO_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON AL_HPMP_ARTICULO_TH TO SISCEL_ADMIN
/
GRANT DELETE ON AL_HPMP_ARTICULO_TH TO SISCEL_AL
/
GRANT INSERT ON AL_HPMP_ARTICULO_TH TO SISCEL_AL
/
GRANT SELECT ON AL_HPMP_ARTICULO_TH TO SISCEL_AL
/
GRANT UPDATE ON AL_HPMP_ARTICULO_TH TO SISCEL_AL
/
GRANT SELECT ON AL_HPMP_ARTICULO_TH TO SISCEL_SELECT
/
