GRANT DELETE ON AL_MOTIVO_USUARIO_TD TO SISCEL_ADMIN
/
GRANT INSERT ON AL_MOTIVO_USUARIO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON AL_MOTIVO_USUARIO_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON AL_MOTIVO_USUARIO_TD TO SISCEL_ADMIN
/
GRANT DELETE ON AL_MOTIVO_USUARIO_TD TO SISCEL_AL
/
GRANT INSERT ON AL_MOTIVO_USUARIO_TD TO SISCEL_AL
/
GRANT SELECT ON AL_MOTIVO_USUARIO_TD TO SISCEL_AL
/
GRANT UPDATE ON AL_MOTIVO_USUARIO_TD TO SISCEL_AL
/
GRANT SELECT ON AL_MOTIVO_USUARIO_TD TO SISCEL_SELECT
/
