GRANT EXECUTE ON AL_OBTIENE_SUBLOCK_FN TO EBZ_SISCEL
/
GRANT EXECUTE ON AL_OBTIENE_SUBLOCK_FN TO SISCEL_ADMIN
/
GRANT EXECUTE ON AL_OBTIENE_SUBLOCK_FN TO SISCEL_AL
/
GRANT EXECUTE ON AL_OBTIENE_SUBLOCK_FN TO SISCEL_SELECT
/
