GRANT SELECT                            ON AL_PRECIOS_DEDUCIBLE_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON AL_PRECIOS_DEDUCIBLE_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON AL_PRECIOS_DEDUCIBLE_TO TO SISCEL_GE
/

