GRANT EXECUTE ON AL_POS_ACTIVACIONES_PG TO EBZ_SISCEL
/
GRANT EXECUTE ON AL_POS_ACTIVACIONES_PG TO FAC_SISCEL
/
GRANT EXECUTE ON AL_POS_ACTIVACIONES_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON AL_POS_ACTIVACIONES_PG TO SISCEL_AL
/
GRANT EXECUTE ON AL_POS_ACTIVACIONES_PG TO SISCEL_SELECT
/
