GRANT SELECT                            ON AL_PRECIOS_DEDUCIBLE_MAS_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON AL_PRECIOS_DEDUCIBLE_MAS_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON AL_PRECIOS_DEDUCIBLE_MAS_TD TO SISCEL_GE
/

