GRANT DELETE ON AL_PMP_ARTICULO TO SISCEL_ADMIN
/
GRANT INSERT ON AL_PMP_ARTICULO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_PMP_ARTICULO TO SISCEL_ADMIN
/
GRANT UPDATE ON AL_PMP_ARTICULO TO SISCEL_ADMIN
/
GRANT DELETE ON AL_PMP_ARTICULO TO SISCEL_AL
/
GRANT INSERT ON AL_PMP_ARTICULO TO SISCEL_AL
/
GRANT SELECT ON AL_PMP_ARTICULO TO SISCEL_AL
/
GRANT UPDATE ON AL_PMP_ARTICULO TO SISCEL_AL
/
GRANT SELECT ON AL_PMP_ARTICULO TO SISCEL_SELECT
/
GRANT SELECT ON AL_PMP_ARTICULO TO SOLO_CONSULTA_SISCEL
/
