GRANT EXECUTE ON AL_PAC_NUMERACION TO EBZ_SISCEL
/
GRANT EXECUTE ON AL_PAC_NUMERACION TO SISCEL_ADMIN
/
GRANT EXECUTE ON AL_PAC_NUMERACION TO SISCEL_AL
/
GRANT EXECUTE ON AL_PAC_NUMERACION TO SISCEL_FA
/
GRANT EXECUTE ON AL_PAC_NUMERACION TO SISCEL_SELECT
/
