GRANT ALTER ON AL_SEQ_KARDEX TO EBZ_SISCEL
/
GRANT SELECT ON AL_SEQ_KARDEX TO EBZ_SISCEL
/
GRANT SELECT ON AL_SEQ_KARDEX TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_KARDEX TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_KARDEX TO SISCEL_SELECT
/
