GRANT EXECUTE ON AL_SERIES_KIT_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON AL_SERIES_KIT_PG TO  SISCEL_AL
/
GRANT EXECUTE ON AL_SERIES_KIT_PG TO  SISCEL_CO
/
GRANT EXECUTE ON AL_SERIES_KIT_PG TO  SISCEL_FA
/
GRANT EXECUTE ON AL_SERIES_KIT_PG TO  SISCEL_GA
/
GRANT EXECUTE ON AL_SERIES_KIT_PG TO  SISCEL_GE
/
GRANT EXECUTE ON AL_SERIES_KIT_PG TO  SISCEL_SELECT
/
GRANT EXECUTE ON AL_SERIES_KIT_PG TO SISCEL_VE
/

