GRANT SELECT ON AL_SEQ_MVTO TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_MVTO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_MVTO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_MVTO TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_MVTO TO SISCEL_SELECT
/
