GRANT SELECT ON AL_SEQ_ORDEN_ING TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_ORDEN_ING TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_ORDEN_ING TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_ORDEN_ING TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_ORDEN_ING TO SISCEL_SELECT
/
