GRANT SELECT ON AL_SEQ_BOLETA TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_BOLETA TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_BOLETA TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_BOLETA TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_BOLETA TO SISCEL_SELECT
/
