GRANT SELECT ON AL_SEQ_ERRORES_WEB TO EBZ_SISCEL
/
GRANT SELECT ON AL_SEQ_ERRORES_WEB TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_ERRORES_WEB TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_ERRORES_WEB TO SISCEL_SELECT
/
