GRANT SELECT ON AL_SEQ_TIMBRADO TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_TIMBRADO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_TIMBRADO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_TIMBRADO TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_TIMBRADO TO SISCEL_SELECT
/
