GRANT SELECT ON AL_SEQ_ARTICULOS TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_ARTICULOS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_ARTICULOS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_ARTICULOS TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_ARTICULOS TO SISCEL_SELECT
/
