GRANT SELECT ON AL_SEQ_ATRIB TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_ATRIB TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_ATRIB TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_ATRIB TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_ATRIB TO SISCEL_SELECT
/
