GRANT SELECT ON AL_SEQ_NUMERACION TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_NUMERACION TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_NUMERACION TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_NUMERACION TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_NUMERACION TO SISCEL_SELECT
/
