GRANT EXECUTE ON AL_SERVICIOS_ALMACENES_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON AL_SERVICIOS_ALMACENES_PG TO SISCEL_GA
/
GRANT EXECUTE ON AL_SERVICIOS_ALMACENES_PG TO SISCEL_PV
/
GRANT EXECUTE ON AL_SERVICIOS_ALMACENES_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON AL_SERVICIOS_ALMACENES_PG TO SISCEL_VE
/
