GRANT SELECT ON AL_SEQ_TRASPASO_MASIVO TO EBZ_SISCEL
/
GRANT SELECT ON AL_SEQ_TRASPASO_MASIVO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_TRASPASO_MASIVO TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_TRASPASO_MASIVO TO SISCEL_SELECT
/
