GRANT SELECT ON AL_SEQ_PETICION_TRAS TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_PETICION_TRAS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_PETICION_TRAS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_PETICION_TRAS TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_PETICION_TRAS TO SISCEL_SELECT
/
