GRANT SELECT ON AL_SEQ_LISTAS_CONSIG TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_LISTAS_CONSIG TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_LISTAS_CONSIG TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_LISTAS_CONSIG TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_LISTAS_CONSIG TO SISCEL_SELECT
/
