GRANT SELECT ON AL_SEQ_DEVOLUCION TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_DEVOLUCION TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_DEVOLUCION TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_DEVOLUCION TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_DEVOLUCION TO SISCEL_GA
/
GRANT SELECT ON AL_SEQ_DEVOLUCION TO SISCEL_SELECT
/
