GRANT SELECT,INSERT,UPDATE,DELETE ON AL_SERIESAVL_TO  TO SISCEL_ADMIN
/
GRANT SELECT,INSERT,UPDATE,DELETE ON AL_SERIESAVL_TO  TO SISCEL_AL
/
GRANT   SELECT                                ON AL_SERIESAVL_TO  TO SISCEL_SELECT
/

