GRANT SELECT ON AL_SEQ_DEVPROV TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_DEVPROV TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_DEVPROV TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_DEVPROV TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_DEVPROV TO SISCEL_SELECT
/
