GRANT SELECT ON AL_SEQ_LOG TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_LOG TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_LOG TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_LOG TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_LOG TO SISCEL_SELECT
/
