GRANT SELECT ON AL_SEQ_ALARMAS TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_ALARMAS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_ALARMAS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_ALARMAS TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_ALARMAS TO SISCEL_SELECT
/
