GRANT SELECT ON AL_SEQ_INTERVBPL TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_INTERVBPL TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_INTERVBPL TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_INTERVBPL TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_INTERVBPL TO SISCEL_SELECT
/
