GRANT SELECT ON AL_SEQ_EXTRAS TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_EXTRAS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_EXTRAS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_EXTRAS TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_EXTRAS TO SISCEL_SELECT
/
