GRANT SELECT ON AL_SEQ_GUIAS TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_GUIAS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_GUIAS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_GUIAS TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_GUIAS TO SISCEL_SELECT
/
