GRANT ALTER ON AL_SEQ_CLUB TO EBZ_SISCEL
/
GRANT SELECT ON AL_SEQ_CLUB TO EBZ_SISCEL
/
GRANT SELECT ON AL_SEQ_CLUB TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_CLUB TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_CLUB TO SISCEL_SELECT
/
