GRANT DELETE ON AL_STOCK_CONTROL_TO TO SISCEL_ADMIN
/
GRANT INSERT ON AL_STOCK_CONTROL_TO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_STOCK_CONTROL_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON AL_STOCK_CONTROL_TO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_STOCK_CONTROL_TO TO SISCEL_SELECT
/
