GRANT SELECT ON AL_SEQ_TRASPASO TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_TRASPASO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_TRASPASO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_TRASPASO TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_TRASPASO TO SISCEL_SELECT
/
