GRANT SELECT ON AL_SEQ_AFIJO TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_AFIJO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_AFIJO TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_AFIJO TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_AFIJO TO SISCEL_SELECT
/
