GRANT SELECT ON AL_SEQ_INFCONSIG TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_INFCONSIG TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_INFCONSIG TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_INFCONSIG TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_INFCONSIG TO SISCEL_SELECT
/
