GRANT SELECT ON AL_SEQ_CIERRE TO EBZ_SISCEL
/
GRANT ALTER ON AL_SEQ_CIERRE TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_CIERRE TO SISCEL_ADMIN
/
GRANT SELECT ON AL_SEQ_CIERRE TO SISCEL_AL
/
GRANT SELECT ON AL_SEQ_CIERRE TO SISCEL_SELECT
/
