GRANT DELETE ON AL_VDOCUM_ASIGNADOS TO SISCEL_ADMIN
/
GRANT INSERT ON AL_VDOCUM_ASIGNADOS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_VDOCUM_ASIGNADOS TO SISCEL_ADMIN
/
GRANT UPDATE ON AL_VDOCUM_ASIGNADOS TO SISCEL_ADMIN
/
GRANT SELECT ON AL_VDOCUM_ASIGNADOS TO SISCEL_AL
/
GRANT SELECT ON AL_VDOCUM_ASIGNADOS TO SISCEL_SELECT
/
GRANT SELECT ON AL_VDOCUM_ASIGNADOS TO SOLO_CONSULTA_SISCEL
/
