GRANT DELETE, INSERT, SELECT, UPDATE ON AL_VHCABECERA_ORDENES TO EBZ_SISCEL
/
GRANT DELETE, INSERT, SELECT, UPDATE ON AL_VHCABECERA_ORDENES TO SISCEL_ADMIN
/
GRANT DELETE, INSERT, SELECT, UPDATE ON AL_VHCABECERA_ORDENES TO SISCEL_AL
/
GRANT SELECT                         ON AL_VHCABECERA_ORDENES TO SISCEL_SELECT
/
GRANT SELECT                         ON AL_VHCABECERA_ORDENES TO SOLO_CONSULTA_SISCEL
/
