GRANT  EXECUTE   ON BP_BENEFICIOS_PROMOCIONES_PG   TO SISCEL_ADMIN
/
GRANT  EXECUTE   ON BP_BENEFICIOS_PROMOCIONES_PG   TO SISCEL_SELECT
/
GRANT  EXECUTE   ON BP_BENEFICIOS_PROMOCIONES_PG   TO SISCEL_BP
/

