GRANT DELETE ON BP_CAMPANAS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON BP_CAMPANAS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON BP_CAMPANAS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON BP_CAMPANAS_TD TO SISCEL_ADMIN
/
GRANT DELETE ON BP_CAMPANAS_TD TO SISCEL_BP
/
GRANT INSERT ON BP_CAMPANAS_TD TO SISCEL_BP
/
GRANT SELECT ON BP_CAMPANAS_TD TO SISCEL_BP
/
GRANT UPDATE ON BP_CAMPANAS_TD TO SISCEL_BP
/
GRANT SELECT ON BP_CAMPANAS_TD TO SISCEL_SELECT
/
GRANT SELECT ON BP_CAMPANAS_TD TO SOLO_CONSULTA_SISCEL
/
