GRANT DELETE ON BP_CARGA_MASIVA_TO TO SISCEL_ADMIN
/
GRANT INSERT ON BP_CARGA_MASIVA_TO TO SISCEL_ADMIN
/
GRANT SELECT ON BP_CARGA_MASIVA_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON BP_CARGA_MASIVA_TO TO SISCEL_ADMIN
/
GRANT DELETE ON BP_CARGA_MASIVA_TO TO SISCEL_BP
/
GRANT INSERT ON BP_CARGA_MASIVA_TO TO SISCEL_BP
/
GRANT SELECT ON BP_CARGA_MASIVA_TO TO SISCEL_BP
/
GRANT UPDATE ON BP_CARGA_MASIVA_TO TO SISCEL_BP
/
GRANT SELECT ON BP_CARGA_MASIVA_TO TO SISCEL_SELECT
/
