GRANT EXECUTE ON BP_PROMOCIONES_PG TO EBZ_SISCEL
/
GRANT EXECUTE ON BP_PROMOCIONES_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON BP_PROMOCIONES_PG TO SISCEL_BP
/
GRANT EXECUTE ON BP_PROMOCIONES_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON BP_PROMOCIONES_PG TO TOL_SISCEL
/
