GRANT ALTER ON BP_SEC_BENEFICIO TO EBZ_SISCEL
/
GRANT SELECT ON BP_SEC_BENEFICIO TO EBZ_SISCEL
/
GRANT SELECT ON BP_SEC_BENEFICIO TO SISCEL_ADMIN
/
GRANT SELECT ON BP_SEC_BENEFICIO TO SISCEL_BP
/
GRANT SELECT ON BP_SEC_BENEFICIO TO SISCEL_SELECT
/
