GRANT SELECT                            ON BP_TOL_DETDESCUENTO_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON BP_TOL_DETDESCUENTO_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON BP_TOL_DETDESCUENTO_TD TO SISCEL_BP
/

