GRANT DELETE ON BPD_TXTQUERYS TO SISCEL_ADMIN
/
GRANT INSERT ON BPD_TXTQUERYS TO SISCEL_ADMIN
/
GRANT SELECT ON BPD_TXTQUERYS TO SISCEL_ADMIN
/
GRANT UPDATE ON BPD_TXTQUERYS TO SISCEL_ADMIN
/
GRANT DELETE ON BPD_TXTQUERYS TO SISCEL_BP
/
GRANT INSERT ON BPD_TXTQUERYS TO SISCEL_BP
/
GRANT SELECT ON BPD_TXTQUERYS TO SISCEL_BP
/
GRANT UPDATE ON BPD_TXTQUERYS TO SISCEL_BP
/
GRANT SELECT ON BPD_TXTQUERYS TO SISCEL_SELECT
/
GRANT SELECT ON BPD_TXTQUERYS TO SOLO_CONSULTA_SISCEL
/
