GRANT EXECUTE ON CA_FN_VBVALIDAOOSS TO EBZ_SISCEL
/
GRANT EXECUTE ON CA_FN_VBVALIDAOOSS TO SISCEL_ADMIN
/
GRANT EXECUTE ON CA_FN_VBVALIDAOOSS TO SISCEL_CA
/
GRANT EXECUTE ON CA_FN_VBVALIDAOOSS TO SISCEL_RE
/
GRANT EXECUTE ON CA_FN_VBVALIDAOOSS TO SISCEL_SELECT
/
