GRANT EXECUTE ON CA_PR_MUL_IDIOMA_TIPINCIDENCIA TO EBZ_SISCEL
/
GRANT EXECUTE ON CA_PR_MUL_IDIOMA_TIPINCIDENCIA TO SISCEL_ADMIN
/
GRANT EXECUTE ON CA_PR_MUL_IDIOMA_TIPINCIDENCIA TO SISCEL_CA
/
GRANT EXECUTE ON CA_PR_MUL_IDIOMA_TIPINCIDENCIA TO SISCEL_RE
/
GRANT EXECUTE ON CA_PR_MUL_IDIOMA_TIPINCIDENCIA TO SISCEL_SELECT
/
