GRANT SELECT ON CA_SEQ_PENALIZ TO EBZ_SISCEL
/
GRANT ALTER ON CA_SEQ_PENALIZ TO SISCEL_ADMIN
/
GRANT SELECT ON CA_SEQ_PENALIZ TO SISCEL_ADMIN
/
GRANT SELECT ON CA_SEQ_PENALIZ TO SISCEL_CA
/
GRANT SELECT ON CA_SEQ_PENALIZ TO SISCEL_SELECT
/
