GRANT SELECT ON CA_SEQ_EXPLICA TO EBZ_SISCEL
/
GRANT ALTER ON CA_SEQ_EXPLICA TO SISCEL_ADMIN
/
GRANT SELECT ON CA_SEQ_EXPLICA TO SISCEL_ADMIN
/
GRANT SELECT ON CA_SEQ_EXPLICA TO SISCEL_CA
/
GRANT SELECT ON CA_SEQ_EXPLICA TO SISCEL_SELECT
/
