GRANT SELECT ON CA_SEQ_ALARMA TO EBZ_SISCEL
/
GRANT ALTER ON CA_SEQ_ALARMA TO SISCEL_ADMIN
/
GRANT SELECT ON CA_SEQ_ALARMA TO SISCEL_ADMIN
/
GRANT SELECT ON CA_SEQ_ALARMA TO SISCEL_CA
/
GRANT SELECT ON CA_SEQ_ALARMA TO SISCEL_SELECT
/
