GRANT SELECT ON CA_SEQ_ERRORES TO EBZ_SISCEL
/
GRANT ALTER ON CA_SEQ_ERRORES TO SISCEL_ADMIN
/
GRANT SELECT ON CA_SEQ_ERRORES TO SISCEL_ADMIN
/
GRANT SELECT ON CA_SEQ_ERRORES TO SISCEL_CA
/
GRANT SELECT ON CA_SEQ_ERRORES TO SISCEL_SELECT
/
