GRANT SELECT ON CA_SEQ_PROCEDURES TO EBZ_SISCEL
/
GRANT ALTER ON CA_SEQ_PROCEDURES TO SISCEL_ADMIN
/
GRANT SELECT ON CA_SEQ_PROCEDURES TO SISCEL_ADMIN
/
GRANT SELECT ON CA_SEQ_PROCEDURES TO SISCEL_CA
/
GRANT SELECT ON CA_SEQ_PROCEDURES TO SISCEL_SELECT
/
