GRANT EXECUTE ON CB_P_CASCADA_ALTA TO EBZ_SISCEL
/
GRANT EXECUTE ON CB_P_CASCADA_ALTA TO SISCEL_ADMIN
/
GRANT EXECUTE ON CB_P_CASCADA_ALTA TO SISCEL_SELECT
/
GRANT EXECUTE ON CB_P_CASCADA_ALTA TO SISCEL_VE
/
