GRANT EXECUTE ON CB_P_CASCADA_BAJA TO EBZ_SISCEL
/
GRANT EXECUTE ON CB_P_CASCADA_BAJA TO SISCEL_ADMIN
/
GRANT EXECUTE ON CB_P_CASCADA_BAJA TO SISCEL_SELECT
/
GRANT EXECUTE ON CB_P_CASCADA_BAJA TO SISCEL_VE
/
