GRANT EXECUTE ON CE_APLICA_PAGO_QUIOSCO_PR TO EBZ_SISCEL
/
GRANT EXECUTE ON CE_APLICA_PAGO_QUIOSCO_PR TO OPS$XPCOBROS
/
GRANT EXECUTE ON CE_APLICA_PAGO_QUIOSCO_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON CE_APLICA_PAGO_QUIOSCO_PR TO SISCEL_CO
/
GRANT EXECUTE ON CE_APLICA_PAGO_QUIOSCO_PR TO SISCEL_SELECT
/
