GRANT EXECUTE ON CE_APLICA_PAGO_PR TO EBZ_SISCEL
/
GRANT EXECUTE ON CE_APLICA_PAGO_PR TO OPS$CGUALDRO
/
GRANT EXECUTE ON CE_APLICA_PAGO_PR TO OPS$XPCOBROS
/
GRANT EXECUTE ON CE_APLICA_PAGO_PR TO OPS$XPGESCOB
/
GRANT EXECUTE ON CE_APLICA_PAGO_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON CE_APLICA_PAGO_PR TO SISCEL_CO
/
GRANT EXECUTE ON CE_APLICA_PAGO_PR TO SISCEL_SELECT
/
