GRANT EXECUTE ON CE_P_PERIODO_FACTURACION TO EBZ_SISCEL
/
GRANT EXECUTE ON CE_P_PERIODO_FACTURACION TO SISCEL_ADMIN
/
GRANT EXECUTE ON CE_P_PERIODO_FACTURACION TO SISCEL_FA
/
GRANT EXECUTE ON CE_P_PERIODO_FACTURACION TO SISCEL_SELECT
/
