GRANT EXECUTE ON CE_P_CALCULA_PERIODOS TO EBZ_SISCEL
/
GRANT EXECUTE ON CE_P_CALCULA_PERIODOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON CE_P_CALCULA_PERIODOS TO SISCEL_CE
/
GRANT EXECUTE ON CE_P_CALCULA_PERIODOS TO SISCEL_SELECT
/
