GRANT EXECUTE ON CE_P_CMD_COMVERSE TO EBZ_SISCEL
/
GRANT EXECUTE ON CE_P_CMD_COMVERSE TO SISCEL_ADMIN
/
GRANT EXECUTE ON CE_P_CMD_COMVERSE TO SISCEL_FA
/
GRANT EXECUTE ON CE_P_CMD_COMVERSE TO SISCEL_SELECT
/
