GRANT EXECUTE ON CE_P_CTRPROCESOS TO EBZ_SISCEL
/
GRANT EXECUTE ON CE_P_CTRPROCESOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON CE_P_CTRPROCESOS TO SISCEL_FA
/
GRANT EXECUTE ON CE_P_CTRPROCESOS TO SISCEL_SELECT
/
