GRANT EXECUTE ON CE_P_CIERRE_TRANS_OK TO EBZ_SISCEL
/
GRANT EXECUTE ON CE_P_CIERRE_TRANS_OK TO SISCEL_ADMIN
/
GRANT EXECUTE ON CE_P_CIERRE_TRANS_OK TO SISCEL_FA
/
GRANT EXECUTE ON CE_P_CIERRE_TRANS_OK TO SISCEL_SELECT
/
