GRANT EXECUTE ON CE_P_NOTACREDITOPARCIAL TO EBZ_SISCEL
/
GRANT EXECUTE ON CE_P_NOTACREDITOPARCIAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON CE_P_NOTACREDITOPARCIAL TO SISCEL_CE
/
GRANT EXECUTE ON CE_P_NOTACREDITOPARCIAL TO SISCEL_SELECT
/
