GRANT EXECUTE ON CE_P_RESCATA_CLAVE TO EBZ_SISCEL
/
GRANT EXECUTE ON CE_P_RESCATA_CLAVE TO SISCEL_ADMIN
/
GRANT EXECUTE ON CE_P_RESCATA_CLAVE TO SISCEL_FA
/
GRANT EXECUTE ON CE_P_RESCATA_CLAVE TO SISCEL_SELECT
/
