GRANT SELECT ON CES_SEQ_NUMRECARGA TO EBZ_SISCEL
/
GRANT SELECT ON CES_SEQ_NUMRECARGA TO SISCEL_ADMIN
/
GRANT SELECT ON CES_SEQ_NUMRECARGA TO SISCEL_CE
/
GRANT SELECT ON CES_SEQ_NUMRECARGA TO SISCEL_FA
/
GRANT SELECT ON CES_SEQ_NUMRECARGA TO SISCEL_SELECT
/
