GRANT ALTER ON CES_PAGOS TO EBZ_SISCEL
/
GRANT SELECT ON CES_PAGOS TO EBZ_SISCEL
/
GRANT SELECT ON CES_PAGOS TO SISCEL_ADMIN
/
GRANT SELECT ON CES_PAGOS TO SISCEL_CE
/
GRANT SELECT ON CES_PAGOS TO SISCEL_SELECT
/
