GRANT SELECT ON CES_CONCILIACION TO EBZ_SISCEL
/
GRANT SELECT ON CES_CONCILIACION TO SISCEL_ADMIN
/
GRANT SELECT ON CES_CONCILIACION TO SISCEL_CE
/
GRANT SELECT ON CES_CONCILIACION TO SISCEL_SELECT
/
