GRANT SELECT ON CES_GRUPOCOMIS TO EBZ_SISCEL
/
GRANT SELECT ON CES_GRUPOCOMIS TO SISCEL_ADMIN
/
GRANT SELECT ON CES_GRUPOCOMIS TO SISCEL_CE
/
GRANT SELECT ON CES_GRUPOCOMIS TO SISCEL_FA
/
GRANT SELECT ON CES_GRUPOCOMIS TO SISCEL_SELECT
/
