GRANT EXECUTE ON CI_FN_OBTIENE_MODDIR_MPR TO EBZ_SISCEL
/
GRANT EXECUTE ON CI_FN_OBTIENE_MODDIR_MPR TO SISCEL_ADMIN
/
GRANT EXECUTE ON CI_FN_OBTIENE_MODDIR_MPR TO SISCEL_RE
/
GRANT EXECUTE ON CI_FN_OBTIENE_MODDIR_MPR TO SISCEL_SELECT
/
