GRANT EXECUTE ON CI_FN_ENC_SUBTEL_MPR TO EBZ_SISCEL
/
GRANT EXECUTE ON CI_FN_ENC_SUBTEL_MPR TO SISCEL_ADMIN
/
GRANT EXECUTE ON CI_FN_ENC_SUBTEL_MPR TO SISCEL_RE
/
GRANT EXECUTE ON CI_FN_ENC_SUBTEL_MPR TO SISCEL_SELECT
/
