GRANT EXECUTE ON CI_FN_ENC_SUBTEL_TMC TO EBZ_SISCEL
/
GRANT EXECUTE ON CI_FN_ENC_SUBTEL_TMC TO SISCEL_ADMIN
/
GRANT EXECUTE ON CI_FN_ENC_SUBTEL_TMC TO SISCEL_RE
/
GRANT EXECUTE ON CI_FN_ENC_SUBTEL_TMC TO SISCEL_SELECT
/
