GRANT EXECUTE ON CI_FN_OBTIENE_MODDIR_TMC TO EBZ_SISCEL
/
GRANT EXECUTE ON CI_FN_OBTIENE_MODDIR_TMC TO SISCEL_ADMIN
/
GRANT EXECUTE ON CI_FN_OBTIENE_MODDIR_TMC TO SISCEL_RE
/
GRANT EXECUTE ON CI_FN_OBTIENE_MODDIR_TMC TO SISCEL_SELECT
/
