GRANT EXECUTE ON CI_FN_DATOS_OPERADOR_MPR TO EBZ_SISCEL
/
GRANT EXECUTE ON CI_FN_DATOS_OPERADOR_MPR TO SISCEL_ADMIN
/
GRANT EXECUTE ON CI_FN_DATOS_OPERADOR_MPR TO SISCEL_RE
/
GRANT EXECUTE ON CI_FN_DATOS_OPERADOR_MPR TO SISCEL_SELECT
/
