GRANT EXECUTE ON CI_FN_SUBTELREPORTE_TMC TO EBZ_SISCEL
/
GRANT EXECUTE ON CI_FN_SUBTELREPORTE_TMC TO SISCEL_ADMIN
/
GRANT EXECUTE ON CI_FN_SUBTELREPORTE_TMC TO SISCEL_GE
/
GRANT EXECUTE ON CI_FN_SUBTELREPORTE_TMC TO SISCEL_SELECT
/
