GRANT SELECT ON CI_SEQ_NUMATTECLI TO EBZ_SISCEL
/
GRANT SELECT ON CI_SEQ_NUMATTECLI TO SISCEL_ADMIN
/
GRANT SELECT ON CI_SEQ_NUMATTECLI TO SISCEL_RE
/
GRANT SELECT ON CI_SEQ_NUMATTECLI TO SISCEL_SELECT
/
