GRANT ALTER ON CM_CRITERIOS_SQ TO PUBLIC
/
GRANT SELECT ON CM_CRITERIOS_SQ TO PUBLIC
/
GRANT SELECT ON CM_CRITERIOS_SQ TO SISCEL_ADMIN
/
GRANT SELECT ON CM_CRITERIOS_SQ TO SISCEL_SELECT
/
GRANT SELECT ON CM_CRITERIOS_SQ TO SISCEL_VE
/
