GRANT DELETE ON CM_CONVENIOS_TO TO SISCEL_ADMIN
/
GRANT INSERT ON CM_CONVENIOS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CM_CONVENIOS_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON CM_CONVENIOS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CM_CONVENIOS_TO TO SISCEL_SELECT
/
GRANT DELETE ON CM_CONVENIOS_TO TO SISCEL_VE
/
GRANT INSERT ON CM_CONVENIOS_TO TO SISCEL_VE
/
GRANT SELECT ON CM_CONVENIOS_TO TO SISCEL_VE
/
GRANT UPDATE ON CM_CONVENIOS_TO TO SISCEL_VE
/
GRANT SELECT ON CM_CONVENIOS_TO TO SOLO_CONSULTA_SISCEL
/
