GRANT DELETE ON CM_CAMPOS_UNIVERSO_TD TO SISCEL_ADMIN
/
GRANT INSERT ON CM_CAMPOS_UNIVERSO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CM_CAMPOS_UNIVERSO_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON CM_CAMPOS_UNIVERSO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CM_CAMPOS_UNIVERSO_TD TO SISCEL_SELECT
/
GRANT DELETE ON CM_CAMPOS_UNIVERSO_TD TO SISCEL_VE
/
GRANT INSERT ON CM_CAMPOS_UNIVERSO_TD TO SISCEL_VE
/
GRANT SELECT ON CM_CAMPOS_UNIVERSO_TD TO SISCEL_VE
/
GRANT UPDATE ON CM_CAMPOS_UNIVERSO_TD TO SISCEL_VE
/
