GRANT DELETE ON CM_CATEGRESULTADOSRET_TD TO SISCEL_ADMIN
/
GRANT INSERT ON CM_CATEGRESULTADOSRET_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CM_CATEGRESULTADOSRET_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON CM_CATEGRESULTADOSRET_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CM_CATEGRESULTADOSRET_TD TO SISCEL_SELECT
/
