GRANT DELETE ON CM_PERMANENCIARET_TD TO SISCEL_ADMIN
/
GRANT INSERT ON CM_PERMANENCIARET_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CM_PERMANENCIARET_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON CM_PERMANENCIARET_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CM_PERMANENCIARET_TD TO SISCEL_SELECT
/
