GRANT DELETE ON CM_RETENCIONES_TH TO SISCEL_ADMIN
/
GRANT INSERT ON CM_RETENCIONES_TH TO SISCEL_ADMIN
/
GRANT SELECT ON CM_RETENCIONES_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON CM_RETENCIONES_TH TO SISCEL_ADMIN
/
GRANT SELECT ON CM_RETENCIONES_TH TO SISCEL_SELECT
/
