GRANT ALTER ON CMS_MATRICES TO EBZ_SISCEL
/
GRANT SELECT ON CMS_MATRICES TO EBZ_SISCEL
/
GRANT SELECT ON CMS_MATRICES TO SISCEL_ADMIN
/
GRANT SELECT ON CMS_MATRICES TO SISCEL_SELECT
/
GRANT SELECT ON CMS_MATRICES TO SISCEL_VE
/
