GRANT ALTER ON CMS_NUM_META TO EBZ_SISCEL
/
GRANT SELECT ON CMS_NUM_META TO EBZ_SISCEL
/
GRANT SELECT ON CMS_NUM_META TO SISCEL_ADMIN
/
GRANT SELECT ON CMS_NUM_META TO SISCEL_SELECT
/
GRANT SELECT ON CMS_NUM_META TO SISCEL_VE
/
