GRANT EXECUTE ON CO_AUDITORIA_PG TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_AUDITORIA_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_AUDITORIA_PG TO SISCEL_CO
/
GRANT EXECUTE ON CO_AUDITORIA_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON CO_AUDITORIA_PG TO SOLO_CONSULTA_SISCEL
/
