GRANT EXECUTE ON CO_APLICA_PAGOSPAC TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_APLICA_PAGOSPAC TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_APLICA_PAGOSPAC TO SISCEL_CO
/
GRANT EXECUTE ON CO_APLICA_PAGOSPAC TO SISCEL_SELECT
/
