GRANT EXECUTE ON CO_APLICA_PAGOS_NORMALES TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_APLICA_PAGOS_NORMALES TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_APLICA_PAGOS_NORMALES TO SISCEL_CO
/
GRANT EXECUTE ON CO_APLICA_PAGOS_NORMALES TO SISCEL_SELECT
/
