GRANT EXECUTE ON CO_APLICA_PAGO_DISTRIBUIDOR_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_APLICA_PAGO_DISTRIBUIDOR_PG TO SISCEL_CO
/
GRANT EXECUTE ON CO_APLICA_PAGO_DISTRIBUIDOR_PG TO SISCEL_FA
/
GRANT EXECUTE ON CO_APLICA_PAGO_DISTRIBUIDOR_PG TO SISCEL_GE
/
GRANT EXECUTE ON CO_APLICA_PAGO_DISTRIBUIDOR_PG TO SISCEL_RE
/
GRANT EXECUTE ON CO_APLICA_PAGO_DISTRIBUIDOR_PG TO SISCEL_SELECT
/
