GRANT DELETE ON CO_BCOS_ASOC_TD TO SISCEL_ADMIN
/
GRANT INSERT ON CO_BCOS_ASOC_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_BCOS_ASOC_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_BCOS_ASOC_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_BCOS_ASOC_TD TO SISCEL_SELECT
/
GRANT SELECT ON CO_BCOS_ASOC_TD TO SOLO_CONSULTA_SISCEL
/
