GRANT EXECUTE ON CO_BAJAS_ABO TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_BAJAS_ABO TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_BAJAS_ABO TO SISCEL_CO
/
GRANT EXECUTE ON CO_BAJAS_ABO TO SISCEL_GA
/
GRANT EXECUTE ON CO_BAJAS_ABO TO SISCEL_SELECT
/
