GRANT DELETE ON CO_CLIEPROCESO_TO TO SISCEL_ADMIN
/
GRANT INSERT ON CO_CLIEPROCESO_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_CLIEPROCESO_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_CLIEPROCESO_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_CLIEPROCESO_TO TO SISCEL_SELECT
/
