GRANT SELECT ON CO_CATEGORIAS_TD TO MAS_REPORTES
/
GRANT SELECT ON CO_CATEGORIAS_TD TO RA_SELECT_RO
/
GRANT SELECT ON CO_CATEGORIAS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_CATEGORIAS_TD TO SISCEL_CO
/
GRANT SELECT ON CO_CATEGORIAS_TD TO SISCEL_SELECT
/

