GRANT   SELECT                          ON CO_COBEX_INMUNE_TO TO SISCEL_SELECT
/
GRANT   SELECT, INSERT, UPDATE, DELETE  ON CO_COBEX_INMUNE_TO TO SISCEL_ADMIN
/
GRANT   SELECT, INSERT, UPDATE, DELETE  ON CO_COBEX_INMUNE_TO TO SISCEL_CO
/

