GRANT EXECUTE ON CO_CASTIGOS_EXTERNOS TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_CASTIGOS_EXTERNOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_CASTIGOS_EXTERNOS TO SISCEL_CO
/
GRANT EXECUTE ON CO_CASTIGOS_EXTERNOS TO SISCEL_SELECT
/
