GRANT EXECUTE ON CO_CALC_INTERCOBRANZA TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_CALC_INTERCOBRANZA TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_CALC_INTERCOBRANZA TO SISCEL_CO
/
GRANT EXECUTE ON CO_CALC_INTERCOBRANZA TO SISCEL_SELECT
/
