GRANT DELETE ON CO_CARGOS_CAJA_TD TO SISCEL_ADMIN
/
GRANT INSERT ON CO_CARGOS_CAJA_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_CARGOS_CAJA_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_CARGOS_CAJA_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_CARGOS_CAJA_TD TO SISCEL_SELECT
/
GRANT SELECT ON CO_CARGOS_CAJA_TD TO SOLO_CONSULTA_SISCEL
/
