GRANT EXECUTE ON CO_CALC_INTERFINAN TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_CALC_INTERFINAN TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_CALC_INTERFINAN TO SISCEL_CO
/
GRANT EXECUTE ON CO_CALC_INTERFINAN TO SISCEL_SELECT
/
