GRANT EXECUTE ON CO_DELETECO_PAGOSCONC TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_DELETECO_PAGOSCONC TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_DELETECO_PAGOSCONC TO SISCEL_CO
/
GRANT EXECUTE ON CO_DELETECO_PAGOSCONC TO SISCEL_SELECT
/
