GRANT DELETE ON CO_DET_ANOMALIAS_TO TO SISCEL_ADMIN
/
GRANT INSERT ON CO_DET_ANOMALIAS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_DET_ANOMALIAS_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_DET_ANOMALIAS_TO TO SISCEL_ADMIN
/
GRANT DELETE ON CO_DET_ANOMALIAS_TO TO SISCEL_CO
/
GRANT INSERT ON CO_DET_ANOMALIAS_TO TO SISCEL_CO
/
GRANT SELECT ON CO_DET_ANOMALIAS_TO TO SISCEL_CO
/
GRANT UPDATE ON CO_DET_ANOMALIAS_TO TO SISCEL_CO
/
GRANT SELECT ON CO_DET_ANOMALIAS_TO TO SISCEL_SELECT
/
