GRANT EXECUTE ON CO_DEPOSITO_VALORES TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_DEPOSITO_VALORES TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_DEPOSITO_VALORES TO SISCEL_CO
/
GRANT EXECUTE ON CO_DEPOSITO_VALORES TO SISCEL_SELECT
/
