GRANT DELETE ON CO_DESCPROC_TD TO SISCEL_ADMIN
/
GRANT INSERT ON CO_DESCPROC_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_DESCPROC_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_DESCPROC_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_DESCPROC_TD TO SISCEL_SELECT
/
