GRANT EXECUTE ON CO_DELETECO_CANCELADOS TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_DELETECO_CANCELADOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_DELETECO_CANCELADOS TO SISCEL_CO
/
GRANT EXECUTE ON CO_DELETECO_CANCELADOS TO SISCEL_SELECT
/
