GRANT EXECUTE ON CO_DESPAGCONSUMO TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_DESPAGCONSUMO TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_DESPAGCONSUMO TO SISCEL_CO
/
GRANT EXECUTE ON CO_DESPAGCONSUMO TO SISCEL_SELECT
/
