GRANT EXECUTE ON CO_DESAPLICA_PAGO TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_DESAPLICA_PAGO TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_DESAPLICA_PAGO TO SISCEL_CO
/
GRANT EXECUTE ON CO_DESAPLICA_PAGO TO SISCEL_SELECT
/
