GRANT EXECUTE ON CO_DIAS_HABILES TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_DIAS_HABILES TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_DIAS_HABILES TO SISCEL_CO
/
GRANT EXECUTE ON CO_DIAS_HABILES TO SISCEL_SELECT
/
