GRANT EXECUTE ON CO_DESAPLICA_CAJA TO CER_CPU
/
GRANT EXECUTE ON CO_DESAPLICA_CAJA TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_DESAPLICA_CAJA TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_DESAPLICA_CAJA TO SISCEL_CO
/
GRANT EXECUTE ON CO_DESAPLICA_CAJA TO SISCEL_SELECT
/
