GRANT DELETE ON CO_EMPRESAS_NT TO SISCEL_ADMIN
/
GRANT INSERT ON CO_EMPRESAS_NT TO SISCEL_ADMIN
/
GRANT SELECT ON CO_EMPRESAS_NT TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_EMPRESAS_NT TO SISCEL_ADMIN
/
GRANT DELETE ON CO_EMPRESAS_NT TO SISCEL_CO
/
GRANT INSERT ON CO_EMPRESAS_NT TO SISCEL_CO
/
GRANT SELECT ON CO_EMPRESAS_NT TO SISCEL_CO
/
GRANT UPDATE ON CO_EMPRESAS_NT TO SISCEL_CO
/
GRANT SELECT ON CO_EMPRESAS_NT TO SISCEL_SELECT
/
GRANT SELECT ON CO_EMPRESAS_NT TO SOLO_CONSULTA_SISCEL
/
