GRANT EXECUTE ON CO_EXCLUIDOS_ACCIONES_SN_PG TO FAC_SISCEL
/
GRANT EXECUTE ON CO_EXCLUIDOS_ACCIONES_SN_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_EXCLUIDOS_ACCIONES_SN_PG TO SISCEL_CO
/
GRANT EXECUTE ON CO_EXCLUIDOS_ACCIONES_SN_PG TO SISCEL_SELECT
/
