GRANT  SELECT                           ON CO_ENTIDAD_RANGO_TD TO SISCEL_SELECT
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON CO_ENTIDAD_RANGO_TD TO SISCEL_ADMIN
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON CO_ENTIDAD_RANGO_TD TO SISCEL_CO
/

