GRANT EXECUTE ON CO_EXT_CIERRE_CONTABLE TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_EXT_CIERRE_CONTABLE TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_EXT_CIERRE_CONTABLE TO SISCEL_CO
/
GRANT EXECUTE ON CO_EXT_CIERRE_CONTABLE TO SISCEL_SELECT
/
