GRANT EXECUTE ON CO_EMI_MISCELANEA TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_EMI_MISCELANEA TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_EMI_MISCELANEA TO SISCEL_CO
/
GRANT EXECUTE ON CO_EMI_MISCELANEA TO SISCEL_SELECT
/
