GRANT DELETE ON CO_FILTROS_COBEXT_TO TO SISCEL_ADMIN
/
GRANT INSERT ON CO_FILTROS_COBEXT_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_FILTROS_COBEXT_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_FILTROS_COBEXT_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_FILTROS_COBEXT_TO TO SISCEL_SELECT
/
