GRANT EXECUTE ON CO_FGETTIPPLANCELULAR TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_FGETTIPPLANCELULAR TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_FGETTIPPLANCELULAR TO SISCEL_CO
/
GRANT EXECUTE ON CO_FGETTIPPLANCELULAR TO SISCEL_SELECT
/
