GRANT EXECUTE ON CO_FN_CAJON_COBRANZA TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_FN_CAJON_COBRANZA TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_FN_CAJON_COBRANZA TO SISCEL_CO
/
GRANT EXECUTE ON CO_FN_CAJON_COBRANZA TO SISCEL_SELECT
/
