GRANT  SELECT, INSERT, UPDATE, DELETE     ON CO_GESTION  TO SISCEL_SELECT
/
GRANT  SELECT, INSERT, UPDATE, DELETE     ON CO_GESTION  TO SISCEL_ADMIN
/
GRANT SELECT, INSERT, UPDATE, DELETE      ON CO_GESTION TO SISCEL_CO
/