GRANT DELETE ON CO_HISTCAJDIA TO SISCEL_ADMIN
/
GRANT INSERT ON CO_HISTCAJDIA TO SISCEL_ADMIN
/
GRANT SELECT ON CO_HISTCAJDIA TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_HISTCAJDIA TO SISCEL_ADMIN
/
GRANT DELETE ON CO_HISTCAJDIA TO SISCEL_CO
/
GRANT INSERT ON CO_HISTCAJDIA TO SISCEL_CO
/
GRANT SELECT ON CO_HISTCAJDIA TO SISCEL_CO
/
GRANT UPDATE ON CO_HISTCAJDIA TO SISCEL_CO
/
GRANT SELECT ON CO_HISTCAJDIA TO SISCEL_SELECT
/
GRANT SELECT ON CO_HISTCAJDIA TO SOLO_CONSULTA_SISCEL
/
