GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_REGU3 TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_REGU3 TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_REGU3 TO SISCEL_CO
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_REGU3 TO SISCEL_SELECT
/
