GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_DEPEXT TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_DEPEXT TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_DEPEXT TO SISCEL_CO
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_DEPEXT TO SISCEL_SELECT
/
