GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_PAGFIC TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_PAGFIC TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_PAGFIC TO SISCEL_CO
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_PAGFIC TO SISCEL_SELECT
/
