GRANT DELETE ON CO_INSTANCIA_TO TO SISCEL_ADMIN
/
GRANT INSERT ON CO_INSTANCIA_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_INSTANCIA_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_INSTANCIA_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_INSTANCIA_TO TO SISCEL_SELECT
/
