GRANT EXECUTE ON CO_INDEMNIZACION_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_INDEMNIZACION_PG TO SISCEL_CO
/
GRANT EXECUTE ON CO_INDEMNIZACION_PG TO SISCEL_GA
/
GRANT EXECUTE ON CO_INDEMNIZACION_PG TO SISCEL_PV
/
GRANT EXECUTE ON CO_INDEMNIZACION_PG TO SISCEL_SELECT
/
