GRANT EXECUTE ON CO_IMPUTACION_CASCONT TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_IMPUTACION_CASCONT TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_IMPUTACION_CASCONT TO SISCEL_CO
/
GRANT EXECUTE ON CO_IMPUTACION_CASCONT TO SISCEL_SELECT
/
