GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_GRP TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_GRP TO SISCEL_CO
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_GRP TO SISCEL_FA
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_GRP TO SISCEL_SELECT
/
