GRANT ALTER ON CO_INTERESES TO EBZ_SISCEL
/
GRANT INDEX ON CO_INTERESES TO EBZ_SISCEL
/
GRANT REFERENCES ON CO_INTERESES TO EBZ_SISCEL
/
GRANT SELECT ON CO_INTERESES TO EBZ_SISCEL
/
GRANT SELECT ON CO_INTERESES TO MAS_REPORTES
/
GRANT SELECT ON CO_INTERESES TO RA_SELECT_RO
/
GRANT SELECT ON CO_INTERESES TO SISCEL_ADMIN
/
GRANT SELECT ON CO_INTERESES TO SISCEL_CO
/
GRANT SELECT ON CO_INTERESES TO SISCEL_SELECT
/
GRANT SELECT ON CO_INTERESES TO SOLO_CONSULTA_SISCEL
/
