GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_PAC TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_PAC TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_PAC TO SISCEL_CO
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_PAC TO SISCEL_SELECT
/
