GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_ANOMEXT TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_ANOMEXT TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_ANOMEXT TO SISCEL_CO
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_ANOMEXT TO SISCEL_SELECT
/
