GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_CARTERA TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_CARTERA TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_CARTERA TO SISCEL_CO
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_CARTERA TO SISCEL_SELECT
/
