GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_CAJAS TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_CAJAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_CAJAS TO SISCEL_CO
/
GRANT EXECUTE ON CO_IMPUTACION_CONTABLE_CAJAS TO SISCEL_SELECT
/
