GRANT DELETE ON CO_MATRIZ_INSTANCIAS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON CO_MATRIZ_INSTANCIAS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_MATRIZ_INSTANCIAS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_MATRIZ_INSTANCIAS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_MATRIZ_INSTANCIAS_TD TO SISCEL_SELECT
/
