GRANT EXECUTE  ON CO_OBTIENE_CELULAR_CLIENTE_FN   TO SISCEL_SELECT
/
GRANT EXECUTE  ON CO_OBTIENE_CELULAR_CLIENTE_FN   TO SISCEL_ADMIN
/
GRANT EXECUTE  ON CO_OBTIENE_CELULAR_CLIENTE_FN   TO SISCEL_CO
/
