GRANT EXECUTE ON CO_P_COB_EXT_PTR TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_P_COB_EXT_PTR TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_P_COB_EXT_PTR TO SISCEL_CO
/
GRANT EXECUTE ON CO_P_COB_EXT_PTR TO SISCEL_SELECT
/
