GRANT   SELECT                          ON CO_PARAM_COBEX_TO TO SISCEL_SELECT
/
GRANT   SELECT, INSERT, UPDATE, DELETE  ON CO_PARAM_COBEX_TO TO SISCEL_ADMIN
/
GRANT   SELECT, INSERT, UPDATE, DELETE  ON CO_PARAM_COBEX_TO TO SISCEL_CO
/

