GRANT EXECUTE ON CO_P_COMIS_RECUPERO_MPR TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_P_COMIS_RECUPERO_MPR TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_P_COMIS_RECUPERO_MPR TO SISCEL_CO
/
GRANT EXECUTE ON CO_P_COMIS_RECUPERO_MPR TO SISCEL_SELECT
/
