GRANT EXECUTE ON CO_P_APLICA_PRORROGA TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_P_APLICA_PRORROGA TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_P_APLICA_PRORROGA TO SISCEL_CO
/
GRANT EXECUTE ON CO_P_APLICA_PRORROGA TO SISCEL_SELECT
/
