GRANT EXECUTE ON CO_P_APLICA_CONVENIO TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_P_APLICA_CONVENIO TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_P_APLICA_CONVENIO TO SISCEL_CO
/
GRANT EXECUTE ON CO_P_APLICA_CONVENIO TO SISCEL_SELECT
/
