GRANT EXECUTE ON CO_P_DEPOSITO_DOCUMENTOS TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_P_DEPOSITO_DOCUMENTOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_P_DEPOSITO_DOCUMENTOS TO SISCEL_CO
/
GRANT EXECUTE ON CO_P_DEPOSITO_DOCUMENTOS TO SISCEL_SELECT
/
