GRANT EXECUTE ON CO_P_COB_EXT_TMC TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_P_COB_EXT_TMC TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_P_COB_EXT_TMC TO SISCEL_CO
/
GRANT EXECUTE ON CO_P_COB_EXT_TMC TO SISCEL_SELECT
/
