GRANT EXECUTE ON CO_P_APLICA_CAMBIO TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_P_APLICA_CAMBIO TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_P_APLICA_CAMBIO TO SISCEL_CO
/
GRANT EXECUTE ON CO_P_APLICA_CAMBIO TO SISCEL_SELECT
/
