GRANT EXECUTE ON CO_P_COB_EXT_TMM TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_P_COB_EXT_TMM TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_P_COB_EXT_TMM TO SISCEL_CO
/
GRANT EXECUTE ON CO_P_COB_EXT_TMM TO SISCEL_SELECT
/
