GRANT DELETE ON CO_PREFTARJETAS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON CO_PREFTARJETAS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_PREFTARJETAS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_PREFTARJETAS_TD TO SISCEL_ADMIN
/
GRANT DELETE ON CO_PREFTARJETAS_TD TO SISCEL_CO
/
GRANT INSERT ON CO_PREFTARJETAS_TD TO SISCEL_CO
/
GRANT SELECT ON CO_PREFTARJETAS_TD TO SISCEL_CO
/
GRANT UPDATE ON CO_PREFTARJETAS_TD TO SISCEL_CO
/
GRANT SELECT ON CO_PREFTARJETAS_TD TO SISCEL_SELECT
/
