GRANT DELETE ON CO_PL_COMISION TO SISCEL_ADMIN
/
GRANT INSERT ON CO_PL_COMISION TO SISCEL_ADMIN
/
GRANT SELECT ON CO_PL_COMISION TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_PL_COMISION TO SISCEL_ADMIN
/
GRANT DELETE ON CO_PL_COMISION TO SISCEL_CO
/
GRANT INSERT ON CO_PL_COMISION TO SISCEL_CO
/
GRANT SELECT ON CO_PL_COMISION TO SISCEL_CO
/
GRANT UPDATE ON CO_PL_COMISION TO SISCEL_CO
/
GRANT SELECT ON CO_PL_COMISION TO SISCEL_SELECT
/
GRANT SELECT ON CO_PL_COMISION TO SOLO_CONSULTA_SISCEL
/
