GRANT EXECUTE ON CO_P_APLICA_PRORROGA_SIN TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_P_APLICA_PRORROGA_SIN TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_P_APLICA_PRORROGA_SIN TO SISCEL_CO
/
GRANT EXECUTE ON CO_P_APLICA_PRORROGA_SIN TO SISCEL_SELECT
/
