GRANT DELETE ON CO_PARAMETROS_UNIX_TO TO SISCEL_ADMIN
/
GRANT INSERT ON CO_PARAMETROS_UNIX_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_PARAMETROS_UNIX_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_PARAMETROS_UNIX_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_PARAMETROS_UNIX_TO TO SISCEL_SELECT
/
