GRANT EXECUTE ON CO_PAC_DOCTOSCLIENTE TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_PAC_DOCTOSCLIENTE TO INTERNET_SELECT
/
GRANT EXECUTE ON CO_PAC_DOCTOSCLIENTE TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_PAC_DOCTOSCLIENTE TO SISCEL_CO
/
GRANT EXECUTE ON CO_PAC_DOCTOSCLIENTE TO SISCEL_SELECT
/
