GRANT EXECUTE ON CO_P_CALC_COMISIONES TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_P_CALC_COMISIONES TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_P_CALC_COMISIONES TO SISCEL_CO
/
GRANT EXECUTE ON CO_P_CALC_COMISIONES TO SISCEL_SELECT
/
