GRANT EXECUTE ON CO_P_CASTIGO_CONTABLE TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_P_CASTIGO_CONTABLE TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_P_CASTIGO_CONTABLE TO SISCEL_CO
/
GRANT EXECUTE ON CO_P_CASTIGO_CONTABLE TO SISCEL_SELECT
/
