GRANT  SELECT                           ON CO_RANGOS_COBEX_TD TO SISCEL_SELECT
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON CO_RANGOS_COBEX_TD TO SISCEL_ADMIN
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON CO_RANGOS_COBEX_TD TO SISCEL_CO
/

