GRANT SELECT ON CO_SEQ_CARTAPAGO TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_CARTAPAGO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_CARTAPAGO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_CARTAPAGO TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_CARTAPAGO TO SISCEL_SELECT
/
