GRANT ALTER ON CO_SEQ_IMPUT_CASCON TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_IMPUT_CASCON TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_IMPUT_CASCON TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_IMPUT_CASCON TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_IMPUT_CASCON TO SISCEL_SELECT
/
