GRANT DELETE ON CO_SALDOCONS_TO TO SISCEL_ADMIN
/
GRANT INSERT ON CO_SALDOCONS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SALDOCONS_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_SALDOCONS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SALDOCONS_TO TO SISCEL_SELECT
/
