GRANT ALTER ON CO_SEQ_REGULARIZA TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_REGULARIZA TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_REGULARIZA TO OPS$CGUALDRO
/
GRANT SELECT ON CO_SEQ_REGULARIZA TO OPS$XPCOBROS
/
GRANT SELECT ON CO_SEQ_REGULARIZA TO OPS$XPGESCOB
/
GRANT SELECT ON CO_SEQ_REGULARIZA TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_REGULARIZA TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_REGULARIZA TO SISCEL_SELECT
/
