GRANT SELECT ON CO_SEQ_PAGO TO SISCEL_CO;
GRANT SELECT ON CO_SEQ_PAGO TO SISCEL_SELECT;
GRANT SELECT ON CO_SEQ_PAGO TO IRF_SISCEL;
GRANT SELECT ON CO_SEQ_PAGO TO EBZ_SISCEL;
GRANT SELECT ON CO_SEQ_PAGO TO SISCEL_ADMIN;
GRANT ALTER ON CO_SEQ_PAGO TO SISCEL_ADMIN;
GRANT SELECT ON CO_SEQ_PAGO TO QUETOL;
GRANT SELECT ON CO_SEQ_PAGO TO TOL_SISCEL;
