GRANT SELECT ON CO_SEQ_PAGOS_NA TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_PAGOS_NA TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_PAGOS_NA TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_PAGOS_NA TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_PAGOS_NA TO SISCEL_SELECT
/
