GRANT SELECT ON CO_SEQ_PAGOCUOTA TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_PAGOCUOTA TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_PAGOCUOTA TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_PAGOCUOTA TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_PAGOCUOTA TO SISCEL_SELECT
/
