GRANT SELECT ON CO_SEQ_ENTIDAD TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_ENTIDAD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_ENTIDAD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_ENTIDAD TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_ENTIDAD TO SISCEL_SELECT
/
