GRANT EXECUTE ON CO_SALDO_VENCIDO_CLIENTE TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_SALDO_VENCIDO_CLIENTE TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_SALDO_VENCIDO_CLIENTE TO SISCEL_CO
/
GRANT EXECUTE ON CO_SALDO_VENCIDO_CLIENTE TO SISCEL_SELECT
/
