GRANT EXECUTE ON CO_SERVICIOS_COBRANZA_PG TO FAC_SISCEL
/
GRANT EXECUTE ON CO_SERVICIOS_COBRANZA_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_SERVICIOS_COBRANZA_PG TO SISCEL_CO
/
GRANT EXECUTE ON CO_SERVICIOS_COBRANZA_PG TO SISCEL_SELECT
/
