GRANT SELECT ON CO_SEQ_NCI TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_NCI TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_NCI TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_NCI TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_NCI TO SISCEL_SELECT
/
