GRANT SELECT ON CO_SEQ_PAGARE TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_PAGARE TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_PAGARE TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_PAGARE TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_PAGARE TO SISCEL_SELECT
/
