GRANT SELECT ON CO_SEQ_PAGOCHEQUE TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_PAGOCHEQUE TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_PAGOCHEQUE TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_PAGOCHEQUE TO SISCEL_SELECT
/
