GRANT SELECT ON CO_SEQ_TRANSACINT TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_TRANSACINT TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_TRANSACINT TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_TRANSACINT TO SISCEL_SELECT
/
