GRANT SELECT ON CO_SEQ_COBEXTERNA TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_COBEXTERNA TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_COBEXTERNA TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_COBEXTERNA TO SISCEL_SELECT
/
