GRANT ALTER ON CO_SEQ_ARCH_OFA TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_ARCH_OFA TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_ARCH_OFA TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_ARCH_OFA TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_ARCH_OFA TO SISCEL_SELECT
/
