GRANT SELECT ON CO_SEQ_CLICHEQUE TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_CLICHEQUE TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_CLICHEQUE TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_CLICHEQUE TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_CLICHEQUE TO SISCEL_SELECT
/
