GRANT SELECT ON CO_SEQ_PROCESOSR TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_PROCESOSR TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_PROCESOSR TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_PROCESOSR TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_PROCESOSR TO SISCEL_SELECT
/
