GRANT SELECT ON CO_SEQ_CASTCONTABLE TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_CASTCONTABLE TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_CASTCONTABLE TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_CASTCONTABLE TO SISCEL_SELECT
/
