GRANT SELECT ON CO_SEQ_PAGOCARRIER TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_PAGOCARRIER TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_PAGOCARRIER TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_PAGOCARRIER TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_PAGOCARRIER TO SISCEL_SELECT
/
