GRANT SELECT ON CO_SEQ_COMPAGO TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_COMPAGO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_COMPAGO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_COMPAGO TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_COMPAGO TO SISCEL_SELECT
/
