GRANT SELECT ON CO_SEQ_RECEXT TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_RECEXT TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_RECEXT TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_RECEXT TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_RECEXT TO SISCEL_SELECT
/
