GRANT SELECT ON CO_SEQ_EVALUADOR TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_EVALUADOR TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_EVALUADOR TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_EVALUADOR TO SISCEL_SELECT
/
