GRANT SELECT ON CO_SEQ_RESPALDO TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_RESPALDO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_RESPALDO TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_RESPALDO TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_RESPALDO TO SISCEL_SELECT
/
