GRANT SELECT ON CO_SEQ_SOLICITUD TO EBZ_SISCEL
/
GRANT SELECT ON CO_SEQ_SOLICITUD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_SOLICITUD TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_SOLICITUD TO SISCEL_SELECT
/
