GRANT SELECT ON CO_SEQ_NDI TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_NDI TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_NDI TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_NDI TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_NDI TO SISCEL_SELECT
/
