GRANT SELECT ON CO_SEQ_RECAUDAEXT TO EBZ_SISCEL
/
GRANT ALTER ON CO_SEQ_RECAUDAEXT TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_RECAUDAEXT TO SISCEL_ADMIN
/
GRANT SELECT ON CO_SEQ_RECAUDAEXT TO SISCEL_CO
/
GRANT SELECT ON CO_SEQ_RECAUDAEXT TO SISCEL_SELECT
/
