GRANT SELECT ON CO_TASAS_TD TO MAS_REPORTES
/
GRANT SELECT ON CO_TASAS_TD TO RA_SELECT_RO
/
GRANT DELETE ON CO_TASAS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON CO_TASAS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON CO_TASAS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON CO_TASAS_TD TO SISCEL_ADMIN
/
GRANT DELETE ON CO_TASAS_TD TO SISCEL_CO
/
GRANT INSERT ON CO_TASAS_TD TO SISCEL_CO
/
GRANT SELECT ON CO_TASAS_TD TO SISCEL_CO
/
GRANT UPDATE ON CO_TASAS_TD TO SISCEL_CO
/
GRANT SELECT ON CO_TASAS_TD TO SISCEL_SELECT
/
