GRANT EXECUTE ON CO_UPDATECO_CARTERA TO EBZ_SISCEL
/
GRANT EXECUTE ON CO_UPDATECO_CARTERA TO SISCEL_ADMIN
/
GRANT EXECUTE ON CO_UPDATECO_CARTERA TO SISCEL_CO
/
GRANT EXECUTE ON CO_UPDATECO_CARTERA TO SISCEL_SELECT
/
