GRANT ALTER ON COS_SEQ_MOVCAJA TO EBZ_SISCEL
/
GRANT SELECT ON COS_SEQ_MOVCAJA TO EBZ_SISCEL
/
GRANT SELECT ON COS_SEQ_MOVCAJA TO SISCEL_ADMIN
/
GRANT SELECT ON COS_SEQ_MOVCAJA TO SISCEL_CO
/
GRANT SELECT ON COS_SEQ_MOVCAJA TO SISCEL_SELECT
/
