GRANT ALTER ON COS_SEQ_ENVIODOCUM TO EBZ_SISCEL
/
GRANT SELECT ON COS_SEQ_ENVIODOCUM TO EBZ_SISCEL
/
GRANT SELECT ON COS_SEQ_ENVIODOCUM TO SISCEL_ADMIN
/
GRANT SELECT ON COS_SEQ_ENVIODOCUM TO SISCEL_CO
/
GRANT SELECT ON COS_SEQ_ENVIODOCUM TO SISCEL_SELECT
/
