GRANT EXECUTE ON CR_FN_ATELEM_COLS_CEL_MPR TO EBZ_SISCEL
/
GRANT EXECUTE ON CR_FN_ATELEM_COLS_CEL_MPR TO SISCEL_ADMIN
/
GRANT EXECUTE ON CR_FN_ATELEM_COLS_CEL_MPR TO SISCEL_CA
/
GRANT EXECUTE ON CR_FN_ATELEM_COLS_CEL_MPR TO SISCEL_SELECT
/
