GRANT EXECUTE ON CR_FN_ARCH_ABOBEEP_NUMCOL_TMC TO EBZ_SISCEL
/
GRANT EXECUTE ON CR_FN_ARCH_ABOBEEP_NUMCOL_TMC TO SISCEL_ADMIN
/
GRANT EXECUTE ON CR_FN_ARCH_ABOBEEP_NUMCOL_TMC TO SISCEL_CA
/
GRANT EXECUTE ON CR_FN_ARCH_ABOBEEP_NUMCOL_TMC TO SISCEL_SELECT
/
