GRANT ALTER ON CR_SEQ_DEVOLUCIONES TO EBZ_SISCEL
/
GRANT SELECT ON CR_SEQ_DEVOLUCIONES TO EBZ_SISCEL
/
GRANT SELECT ON CR_SEQ_DEVOLUCIONES TO SISCEL_ADMIN
/
GRANT SELECT ON CR_SEQ_DEVOLUCIONES TO SISCEL_CA
/
GRANT SELECT ON CR_SEQ_DEVOLUCIONES TO SISCEL_SELECT
/
