GRANT ALTER ON CR_SEQ_INGCORRESP TO EBZ_SISCEL
/
GRANT SELECT ON CR_SEQ_INGCORRESP TO EBZ_SISCEL
/
GRANT SELECT ON CR_SEQ_INGCORRESP TO SISCEL_ADMIN
/
GRANT SELECT ON CR_SEQ_INGCORRESP TO SISCEL_CA
/
GRANT SELECT ON CR_SEQ_INGCORRESP TO SISCEL_SELECT
/
