GRANT EXECUTE ON ER_P_ESTADISTICA TO EBZ_SISCEL
/
GRANT EXECUTE ON ER_P_ESTADISTICA TO SISCEL_ADMIN
/
GRANT EXECUTE ON ER_P_ESTADISTICA TO SISCEL_ER
/
GRANT EXECUTE ON ER_P_ESTADISTICA TO SISCEL_SELECT
/
