GRANT EXECUTE ON ER_P_INTERFACE_PLATAFORMA TO EBZ_SISCEL
/
GRANT EXECUTE ON ER_P_INTERFACE_PLATAFORMA TO SISCEL_ADMIN
/
GRANT EXECUTE ON ER_P_INTERFACE_PLATAFORMA TO SISCEL_CO
/
GRANT EXECUTE ON ER_P_INTERFACE_PLATAFORMA TO SISCEL_SELECT
/
