GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_WEB_PG TO CER_CPU
/
GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_WEB_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_WEB_PG TO SISCEL_ER
/
GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_WEB_PG TO SISCEL_GA
/
GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_WEB_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_WEB_PG TO SISCEL_VE
/
