GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_PG TO CER_CPU
/
GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_PG TO SISCEL_GA
/
GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_PG TO SISCEL_PV
/
GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON ER_SERVICIOS_EVALRIESGO_PG TO SISCEL_VE
/
