GRANT DELETE ON ERD_PUNTAJE_TD TO SISCEL_ADMIN
/
GRANT INSERT ON ERD_PUNTAJE_TD TO SISCEL_ADMIN
/
GRANT SELECT ON ERD_PUNTAJE_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON ERD_PUNTAJE_TD TO SISCEL_ADMIN
/
GRANT DELETE ON ERD_PUNTAJE_TD TO SISCEL_ER
/
GRANT INSERT ON ERD_PUNTAJE_TD TO SISCEL_ER
/
GRANT SELECT ON ERD_PUNTAJE_TD TO SISCEL_ER
/
GRANT UPDATE ON ERD_PUNTAJE_TD TO SISCEL_ER
/
GRANT SELECT ON ERD_PUNTAJE_TD TO SISCEL_SELECT
/
