GRANT DELETE ON ERRORES_SIXBELL_SCL TO PUBLIC
/
GRANT INSERT ON ERRORES_SIXBELL_SCL TO PUBLIC
/
GRANT SELECT ON ERRORES_SIXBELL_SCL TO PUBLIC
/
GRANT UPDATE ON ERRORES_SIXBELL_SCL TO PUBLIC
/
GRANT SELECT ON ERRORES_SIXBELL_SCL TO SOLO_CONSULTA_SISCEL
/
