GRANT DELETE ON ERT_DATOS_DETALLE_TO TO SISCEL_ADMIN
/
GRANT INSERT ON ERT_DATOS_DETALLE_TO TO SISCEL_ADMIN
/
GRANT SELECT ON ERT_DATOS_DETALLE_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON ERT_DATOS_DETALLE_TO TO SISCEL_ADMIN
/
GRANT SELECT ON ERT_DATOS_DETALLE_TO TO SISCEL_SELECT
/
