GRANT DELETE ON ERT_DATOS_CONSULTA_TH TO SISCEL_ADMIN
/
GRANT INSERT ON ERT_DATOS_CONSULTA_TH TO SISCEL_ADMIN
/
GRANT SELECT ON ERT_DATOS_CONSULTA_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON ERT_DATOS_CONSULTA_TH TO SISCEL_ADMIN
/
GRANT DELETE ON ERT_DATOS_CONSULTA_TH TO SISCEL_ER
/
GRANT INSERT ON ERT_DATOS_CONSULTA_TH TO SISCEL_ER
/
GRANT SELECT ON ERT_DATOS_CONSULTA_TH TO SISCEL_ER
/
GRANT UPDATE ON ERT_DATOS_CONSULTA_TH TO SISCEL_ER
/
GRANT SELECT ON ERT_DATOS_CONSULTA_TH TO SISCEL_SELECT
/
