GRANT DELETE ON ERT_DATOS_CONSULTA_TO TO SISCEL_ADMIN
/
GRANT INSERT ON ERT_DATOS_CONSULTA_TO TO SISCEL_ADMIN
/
GRANT SELECT ON ERT_DATOS_CONSULTA_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON ERT_DATOS_CONSULTA_TO TO SISCEL_ADMIN
/
GRANT DELETE ON ERT_DATOS_CONSULTA_TO TO SISCEL_ER
/
GRANT INSERT ON ERT_DATOS_CONSULTA_TO TO SISCEL_ER
/
GRANT SELECT ON ERT_DATOS_CONSULTA_TO TO SISCEL_ER
/
GRANT UPDATE ON ERT_DATOS_CONSULTA_TO TO SISCEL_ER
/
GRANT SELECT ON ERT_DATOS_CONSULTA_TO TO SISCEL_SELECT
/
