GRANT SELECT , INSERT , UPDATE , DELETE ON EV_ESTADOSSCORING_TO TO SISCEL_VE
/
GRANT SELECT                            ON EV_ESTADOSSCORING_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON EV_ESTADOSSCORING_TO TO SISCEL_ADMIN
/

