GRANT SELECT ON EV_PA_SCORING_TO TO MAS_PRODUCT_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON EV_PA_SCORING_TO TO SISCEL_ADMIN;

GRANT SELECT ON EV_PA_SCORING_TO TO SISCEL_SELECT;

GRANT DELETE, INSERT, SELECT, UPDATE ON EV_PA_SCORING_TO TO SISCEL_VE;
