GRANT SELECT , INSERT , UPDATE , DELETE ON EV_SOLSCORING_VENTA_TO TO SISCEL_VE
/
GRANT SELECT                            ON EV_SOLSCORING_VENTA_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON EV_SOLSCORING_VENTA_TO TO SISCEL_ADMIN
/

