GRANT SELECT , INSERT , UPDATE , DELETE ON EV_SS_SCORING_TO TO SISCEL_VE
/
GRANT SELECT                            ON EV_SS_SCORING_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON EV_SS_SCORING_TO TO SISCEL_ADMIN
/

