GRANT EXECUTE ON F_CARGO_PRESUPUESTO TO EBZ_SISCEL
/
GRANT EXECUTE ON F_CARGO_PRESUPUESTO TO SISCEL_ADMIN
/
GRANT EXECUTE ON F_CARGO_PRESUPUESTO TO SISCEL_GA
/
GRANT EXECUTE ON F_CARGO_PRESUPUESTO TO SISCEL_SELECT
/
