GRANT EXECUTE ON F_IMPUESTOS_CARGO TO EBZ_SISCEL
/
GRANT EXECUTE ON F_IMPUESTOS_CARGO TO SISCEL_ADMIN
/
GRANT EXECUTE ON F_IMPUESTOS_CARGO TO SISCEL_GA
/
GRANT EXECUTE ON F_IMPUESTOS_CARGO TO SISCEL_SELECT
/
