GRANT EXECUTE ON FA_AUDITORIA_PG TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_AUDITORIA_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_AUDITORIA_PG TO SISCEL_FA
/
GRANT EXECUTE ON FA_AUDITORIA_PG TO SISCEL_GE
/
GRANT EXECUTE ON FA_AUDITORIA_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON FA_AUDITORIA_PG TO SOLO_CONSULTA_SISCEL
/
