GRANT EXECUTE ON FA_BALANCE_CLI_PG TO FAC_SISCEL
/
GRANT EXECUTE ON FA_BALANCE_CLI_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_BALANCE_CLI_PG TO SISCEL_FA
/
GRANT EXECUTE ON FA_BALANCE_CLI_PG TO SISCEL_SELECT
/
