GRANT EXECUTE ON FA_CONCEPTOS_FACT TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_CONCEPTOS_FACT TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_CONCEPTOS_FACT TO SISCEL_FA
/
GRANT EXECUTE ON FA_CONCEPTOS_FACT TO SISCEL_SELECT
/
