GRANT EXECUTE ON FA_CARGOS_REC_QT TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_CARGOS_REC_QT TO SISCEL_FA
/
GRANT EXECUTE ON FA_CARGOS_REC_QT TO SISCEL_PV
/
GRANT EXECUTE ON FA_CARGOS_REC_QT TO SISCEL_SELECT
/
