GRANT DELETE ON FA_CLIENTE_TO TO SISCEL_ADMIN
/
GRANT INSERT ON FA_CLIENTE_TO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_CLIENTE_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON FA_CLIENTE_TO TO SISCEL_ADMIN
/
GRANT DELETE ON FA_CLIENTE_TO TO SISCEL_FA
/
GRANT INSERT ON FA_CLIENTE_TO TO SISCEL_FA
/
GRANT SELECT ON FA_CLIENTE_TO TO SISCEL_FA
/
GRANT UPDATE ON FA_CLIENTE_TO TO SISCEL_FA
/
GRANT SELECT ON FA_CLIENTE_TO TO SISCEL_SELECT
/
