GRANT SELECT , INSERT , UPDATE , DELETE ON FA_CLIENTEJOB_TO TO SISCEL_FA
/
GRANT SELECT                            ON FA_CLIENTEJOB_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_CLIENTEJOB_TO TO SISCEL_ADMIN
/

