GRANT SELECT , INSERT , UPDATE , DELETE ON FA_CRITERIOSFACT_TD TO SISCEL_FA
/
GRANT SELECT                            ON FA_CRITERIOSFACT_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_CRITERIOSFACT_TD TO SISCEL_ADMIN
/

