GRANT EXECUTE ON FA_CARGOS_SB_PG TO CER_CPU
/
GRANT EXECUTE ON FA_CARGOS_SB_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_CARGOS_SB_PG TO SISCEL_CPU
/
GRANT EXECUTE ON FA_CARGOS_SB_PG TO SISCEL_FA
/
GRANT EXECUTE ON FA_CARGOS_SB_PG TO SISCEL_PV
/
GRANT EXECUTE ON FA_CARGOS_SB_PG TO SISCEL_SELECT
/
