GRANT SELECT                                                     ON FA_CORIG_CDESC_CDEST_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_CORIG_CDESC_CDEST_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_CORIG_CDESC_CDEST_TD TO SISCEL_FA
/

