GRANT  SELECT                                  ON FA_CLIENTESCOURRIER TO SISCEL_SELECT
/
GRANT  SELECT, INSERT, UPDATE, DELETE          ON FA_CLIENTESCOURRIER TO SISCEL_ADMIN
/
GRANT  SELECT, INSERT, UPDATE, DELETE          ON FA_CLIENTESCOURRIER TO SISCEL_FA
/

