GRANT DELETE ON FA_CARGOS_TO TO SISCEL_ADMIN
/
GRANT INSERT ON FA_CARGOS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_CARGOS_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON FA_CARGOS_TO TO SISCEL_ADMIN
/
GRANT DELETE ON FA_CARGOS_TO TO SISCEL_PV
/
GRANT INSERT ON FA_CARGOS_TO TO SISCEL_PV
/
GRANT SELECT ON FA_CARGOS_TO TO SISCEL_PV
/
GRANT UPDATE ON FA_CARGOS_TO TO SISCEL_PV
/
GRANT SELECT ON FA_CARGOS_TO TO SISCEL_SELECT
/
