GRANT  SELECT                           ON FA_COURRIERDISTRIB TO SISCEL_SELECT
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON FA_COURRIERDISTRIB TO SISCEL_ADMIN
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON FA_COURRIERDISTRIB TO SISCEL_FA
/

