GRANT EXECUTE ON FA_CONCEPTOS_SP_PG TO CER_CPU
/
GRANT EXECUTE ON FA_CONCEPTOS_SP_PG TO MAS_PRODUCT_DML
/
GRANT EXECUTE ON FA_CONCEPTOS_SP_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_CONCEPTOS_SP_PG TO SISCEL_CPU
/
GRANT EXECUTE ON FA_CONCEPTOS_SP_PG TO SISCEL_FA
/
GRANT EXECUTE ON FA_CONCEPTOS_SP_PG TO SISCEL_PV
/
GRANT EXECUTE ON FA_CONCEPTOS_SP_PG TO SISCEL_SELECT
/
