GRANT SELECT ON FA_DETIMPTOSTIPO_TO   TO SISCEL_SELECT, SISCEL_ADMIN, SISCEL_FA
/
GRANT INSERT ON FA_DETIMPTOSTIPO_TO   TO SISCEL_ADMIN, SISCEL_FA
/
GRANT UPDATE ON FA_DETIMPTOSTIPO_TO   TO SISCEL_ADMIN, SISCEL_FA
/
GRANT DELETE ON FA_DETIMPTOSTIPO_TO   TO SISCEL_ADMIN, SISCEL_FA
/