GRANT EXECUTE ON FA_DCTO_CLTE_SN_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_DCTO_CLTE_SN_PG TO SISCEL_FA
/
GRANT EXECUTE ON FA_DCTO_CLTE_SN_PG TO SISCEL_IC
/
GRANT EXECUTE ON FA_DCTO_CLTE_SN_PG TO SISCEL_PV
/
GRANT EXECUTE ON FA_DCTO_CLTE_SN_PG TO SISCEL_SELECT
/
