GRANT SELECT                                                     ON FA_ENC_FACTURACION_DIF_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_ENC_FACTURACION_DIF_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_ENC_FACTURACION_DIF_TO TO SISCEL_FA
/

