GRANT EXECUTE ON FA_FN_CODMONFACT TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_FN_CODMONFACT TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_FN_CODMONFACT TO SISCEL_FA
/
GRANT EXECUTE ON FA_FN_CODMONFACT TO SISCEL_SELECT
/
