GRANT EXECUTE ON FA_FOLIACION_PG TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_FOLIACION_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_FOLIACION_PG TO SISCEL_FA
/
GRANT EXECUTE ON FA_FOLIACION_PG TO SISCEL_SELECT
/
