GRANT DELETE ON FA_FACTDOCU_50108 TO OPS$XPFACTUR
/
GRANT INSERT ON FA_FACTDOCU_50108 TO OPS$XPFACTUR
/
GRANT SELECT ON FA_FACTDOCU_50108 TO OPS$XPFACTUR
/
GRANT UPDATE ON FA_FACTDOCU_50108 TO OPS$XPFACTUR
/
GRANT SELECT ON FA_FACTDOCU_50108 TO SISCEL_SELECT
/
