GRANT DELETE ON FA_FACTABON_50508 TO OPS$XPFACTUR
/
GRANT INSERT ON FA_FACTABON_50508 TO OPS$XPFACTUR
/
GRANT SELECT ON FA_FACTABON_50508 TO OPS$XPFACTUR
/
GRANT UPDATE ON FA_FACTABON_50508 TO OPS$XPFACTUR
/
GRANT SELECT ON FA_FACTABON_50508 TO SISCEL_SELECT
/
