GRANT DELETE ON FA_FACTECNO_TO_90308 TO OPS$XPFACTUR
/
GRANT INSERT ON FA_FACTECNO_TO_90308 TO OPS$XPFACTUR
/
GRANT SELECT ON FA_FACTECNO_TO_90308 TO OPS$XPFACTUR
/
GRANT UPDATE ON FA_FACTECNO_TO_90308 TO OPS$XPFACTUR
/
GRANT DELETE ON FA_FACTECNO_TO_90308 TO SISCEL_FA
/
GRANT INSERT ON FA_FACTECNO_TO_90308 TO SISCEL_FA
/
GRANT SELECT ON FA_FACTECNO_TO_90308 TO SISCEL_FA
/
GRANT UPDATE ON FA_FACTECNO_TO_90308 TO SISCEL_FA
/
GRANT SELECT ON FA_FACTECNO_TO_90308 TO SISCEL_SELECT
/
