GRANT DELETE ON FA_FACTECNO_TO_50208 TO OPS$XPFACTUR
/
GRANT INSERT ON FA_FACTECNO_TO_50208 TO OPS$XPFACTUR
/
GRANT SELECT ON FA_FACTECNO_TO_50208 TO OPS$XPFACTUR
/
GRANT UPDATE ON FA_FACTECNO_TO_50208 TO OPS$XPFACTUR
/
GRANT SELECT ON FA_FACTECNO_TO_50208 TO SISCEL_SELECT
/
