GRANT DELETE ON FA_FACTCLIE_10209 TO OPS$XPFACTUR
/
GRANT INSERT ON FA_FACTCLIE_10209 TO OPS$XPFACTUR
/
GRANT SELECT ON FA_FACTCLIE_10209 TO OPS$XPFACTUR
/
GRANT UPDATE ON FA_FACTCLIE_10209 TO OPS$XPFACTUR
/
GRANT SELECT ON FA_FACTCLIE_10209 TO SISCEL_SELECT
/
