GRANT DELETE ON FA_FACTCONC_10508 TO OPS$XPFACTUR
/
GRANT INSERT ON FA_FACTCONC_10508 TO OPS$XPFACTUR
/
GRANT SELECT ON FA_FACTCONC_10508 TO OPS$XPFACTUR
/
GRANT UPDATE ON FA_FACTCONC_10508 TO OPS$XPFACTUR
/
GRANT SELECT ON FA_FACTCONC_10508 TO SISCEL_SELECT
/
