GRANT EXECUTE ON FA_INS_INTERFACT TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_INS_INTERFACT TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_INS_INTERFACT TO SISCEL_FA
/
GRANT EXECUTE ON FA_INS_INTERFACT TO SISCEL_SELECT
/
