GRANT EXECUTE ON FA_PACK_PASOH_MAIN TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PACK_PASOH_MAIN TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PACK_PASOH_MAIN TO SISCEL_FA
/
GRANT EXECUTE ON FA_PACK_PASOH_MAIN TO SISCEL_SELECT
/
