GRANT EXECUTE ON FA_PRE_NOTACREDPARCIAL TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PRE_NOTACREDPARCIAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PRE_NOTACREDPARCIAL TO SISCEL_CO
/
GRANT EXECUTE ON FA_PRE_NOTACREDPARCIAL TO SISCEL_FA
/
GRANT EXECUTE ON FA_PRE_NOTACREDPARCIAL TO SISCEL_GA
/
GRANT EXECUTE ON FA_PRE_NOTACREDPARCIAL TO SISCEL_SELECT
/
