GRANT EXECUTE ON FA_PAC_ARREGLO TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PAC_ARREGLO TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PAC_ARREGLO TO SISCEL_CO
/
GRANT EXECUTE ON FA_PAC_ARREGLO TO SISCEL_FA
/
GRANT EXECUTE ON FA_PAC_ARREGLO TO SISCEL_SELECT
/
