GRANT EXECUTE ON FA_PRE_NOTACREDINTER TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PRE_NOTACREDINTER TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PRE_NOTACREDINTER TO SISCEL_CO
/
GRANT EXECUTE ON FA_PRE_NOTACREDINTER TO SISCEL_FA
/
GRANT EXECUTE ON FA_PRE_NOTACREDINTER TO SISCEL_GA
/
GRANT EXECUTE ON FA_PRE_NOTACREDINTER TO SISCEL_SELECT
/
