GRANT EXECUTE ON FA_PROC_RANGO TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PROC_RANGO TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PROC_RANGO TO SISCEL_FA
/
GRANT EXECUTE ON FA_PROC_RANGO TO SISCEL_GA
/
GRANT EXECUTE ON FA_PROC_RANGO TO SISCEL_SELECT
/
