GRANT EXECUTE ON FA_PROC_ACTUALIZA TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PROC_ACTUALIZA TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PROC_ACTUALIZA TO SISCEL_FA
/
GRANT EXECUTE ON FA_PROC_ACTUALIZA TO SISCEL_GA
/
GRANT EXECUTE ON FA_PROC_ACTUALIZA TO SISCEL_SELECT
/
