GRANT EXECUTE ON FA_PROC_GENCUOTA TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PROC_GENCUOTA TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PROC_GENCUOTA TO SISCEL_GA
/
GRANT EXECUTE ON FA_PROC_GENCUOTA TO SISCEL_SELECT
/
