GRANT EXECUTE ON FA_PROC_PRE_NCBAJAS TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PROC_PRE_NCBAJAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PROC_PRE_NCBAJAS TO SISCEL_FA
/
GRANT EXECUTE ON FA_PROC_PRE_NCBAJAS TO SISCEL_SELECT
/
