GRANT EXECUTE ON FA_PROC_CUOTA TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PROC_CUOTA TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PROC_CUOTA TO SISCEL_AL
/
GRANT EXECUTE ON FA_PROC_CUOTA TO SISCEL_FA
/
GRANT EXECUTE ON FA_PROC_CUOTA TO SISCEL_GA
/
GRANT EXECUTE ON FA_PROC_CUOTA TO SISCEL_SELECT
/
