GRANT EXECUTE ON FA_PROC_INS_CUOTA TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PROC_INS_CUOTA TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PROC_INS_CUOTA TO SISCEL_GA
/
GRANT EXECUTE ON FA_PROC_INS_CUOTA TO SISCEL_SELECT
/
