GRANT SELECT                            ON FA_PREFOLIADOS TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_PREFOLIADOS TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_PREFOLIADOS TO SISCEL_FA
/

