GRANT EXECUTE ON FA_PROC_CALCULA TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PROC_CALCULA TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PROC_CALCULA TO SISCEL_GA
/
GRANT EXECUTE ON FA_PROC_CALCULA TO SISCEL_SELECT
/
