GRANT EXECUTE ON FA_PROC_CUOTA2 TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PROC_CUOTA2 TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PROC_CUOTA2 TO SISCEL_FA
/
GRANT EXECUTE ON FA_PROC_CUOTA2 TO SISCEL_GA
/
GRANT EXECUTE ON FA_PROC_CUOTA2 TO SISCEL_SELECT
/
