GRANT EXECUTE ON FA_PROC_CONCEPTO TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PROC_CONCEPTO TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PROC_CONCEPTO TO SISCEL_FA
/
GRANT EXECUTE ON FA_PROC_CONCEPTO TO SISCEL_GA
/
GRANT EXECUTE ON FA_PROC_CONCEPTO TO SISCEL_SELECT
/
