GRANT EXECUTE ON FA_PROC_TRASPASO TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PROC_TRASPASO TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PROC_TRASPASO TO SISCEL_FA
/
GRANT EXECUTE ON FA_PROC_TRASPASO TO SISCEL_GA
/
GRANT EXECUTE ON FA_PROC_TRASPASO TO SISCEL_SELECT
/
