GRANT EXECUTE ON FA_PAC_PAGARE TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_PAC_PAGARE TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_PAC_PAGARE TO SISCEL_CO
/
GRANT EXECUTE ON FA_PAC_PAGARE TO SISCEL_FA
/
GRANT EXECUTE ON FA_PAC_PAGARE TO SISCEL_SELECT
/
