GRANT SELECT                            ON FA_PARAMDIR_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_PARAMDIR_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_PARAMDIR_TO TO SISCEL_FA
/

