GRANT SELECT                            ON FA_PARAM_IMPRESION_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_PARAM_IMPRESION_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_PARAM_IMPRESION_TD TO SISCEL_FA
/

