GRANT EXECUTE ON FA_REGENERA_FACTURA_FN TO EBZ_SISCEL
/
GRANT EXECUTE ON FA_REGENERA_FACTURA_FN TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_REGENERA_FACTURA_FN TO SISCEL_FA
/
GRANT EXECUTE ON FA_REGENERA_FACTURA_FN TO SISCEL_SELECT
/
