GRANT DELETE ON FA_REPDETALLE_TO TO SISCEL_ADMIN
/
GRANT INSERT ON FA_REPDETALLE_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON FA_REPDETALLE_TO TO SISCEL_ADMIN
/
GRANT DELETE ON FA_REPDETALLE_TO TO SISCEL_FA
/
GRANT INSERT ON FA_REPDETALLE_TO TO SISCEL_FA
/
GRANT SELECT ON FA_REPDETALLE_TO TO SISCEL_FA
/
GRANT UPDATE ON FA_REPDETALLE_TO TO SISCEL_FA
/
GRANT SELECT ON FA_REPDETALLE_TO TO SISCEL_SELECT
/
GRANT SELECT ON FA_REPDETALLE_TO TO SOLO_CONSULTA_SISCEL
/
