GRANT SELECT ON FA_SEQ_CUOTAS TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_CUOTAS TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CUOTAS TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CUOTAS TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_CUOTAS TO SISCEL_SELECT
/
