GRANT SELECT ON FA_SEQ_MISCELANEA TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_MISCELANEA TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_MISCELANEA TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_MISCELANEA TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_MISCELANEA TO SISCEL_SELECT
/
