GRANT SELECT ON FA_SEQ_LIQUIDACION TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_LIQUIDACION TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_LIQUIDACION TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_LIQUIDACION TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_LIQUIDACION TO SISCEL_SELECT
/
