GRANT SELECT ON FA_SEQ_TFN TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_TFN TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_TFN TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_TFN TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_TFN TO SISCEL_SELECT
/
