GRANT SELECT ON FA_SEQ_PROCPASOCOB TO EBZ_SISCEL
/
GRANT SELECT ON FA_SEQ_PROCPASOCOB TO SISCEL_ADMIN
/
GRANT ALTER ON FA_SEQ_PROCPASOCOB TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_PROCPASOCOB TO SISCEL_FA
/
GRANT ALTER ON FA_SEQ_PROCPASOCOB TO SISCEL_SELECT
/
GRANT SELECT ON FA_SEQ_PROCPASOCOB TO SISCEL_SELECT
/
