GRANT SELECT ON FA_SEQ_CTLINFORMES TO EBZ_SISCEL
/
GRANT SELECT ON FA_SEQ_CTLINFORMES TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CTLINFORMES TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_CTLINFORMES TO SISCEL_SELECT
/
