GRANT SELECT ON FA_SEQ_PAC TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_PAC TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_PAC TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_PAC TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_PAC TO SISCEL_SELECT
/
