GRANT SELECT ON FA_SEQ_IND_ORDENTOTAL TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_IND_ORDENTOTAL TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_IND_ORDENTOTAL TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_IND_ORDENTOTAL TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_IND_ORDENTOTAL TO SISCEL_SELECT
/
