GRANT SELECT ON FA_SEQ_CREDITO TO EBZ_SISCEL
/
GRANT SELECT ON FA_SEQ_CREDITO TO REPROA_SELECT
/
GRANT ALTER ON FA_SEQ_CREDITO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CREDITO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CREDITO TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_CREDITO TO SISCEL_SELECT
/
