GRANT SELECT ON FA_SEQ_CLIENTE TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_CLIENTE TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CLIENTE TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CLIENTE TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_CLIENTE TO SISCEL_SELECT
/
