GRANT SELECT ON FA_SEQ_NCPARCIAL TO EBZ_SISCEL
/
GRANT SELECT ON FA_SEQ_NCPARCIAL TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_NCPARCIAL TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_NCPARCIAL TO SISCEL_SELECT
/
