GRANT SELECT ON FA_SEQ_NUMPRO TO EBZ_SISCEL
/
GRANT SELECT ON FA_SEQ_NUMPRO TO REPROA_SELECT
/
GRANT ALTER ON FA_SEQ_NUMPRO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_NUMPRO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_NUMPRO TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_NUMPRO TO SISCEL_GA
/
GRANT SELECT ON FA_SEQ_NUMPRO TO SISCEL_SELECT
/
