GRANT SELECT ON FA_SEQ_RENTA_PHONE TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_RENTA_PHONE TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_RENTA_PHONE TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_RENTA_PHONE TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_RENTA_PHONE TO SISCEL_SELECT
/
