GRANT SELECT ON FA_SEQ_CICLO TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_CICLO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CICLO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CICLO TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_CICLO TO SISCEL_SELECT
/
