GRANT SELECT ON FA_SEQ_ACUMULADO TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_ACUMULADO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_ACUMULADO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_ACUMULADO TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_ACUMULADO TO SISCEL_SELECT
/
