GRANT SELECT ON FA_SEQ_ORDEN TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_ORDEN TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_ORDEN TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_ORDEN TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_ORDEN TO SISCEL_SELECT
/
