GRANT SELECT ON FA_SEQ_DEBITO TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_DEBITO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_DEBITO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_DEBITO TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_DEBITO TO SISCEL_SELECT
/
