GRANT ALTER ON FA_SEQ_FOLNCCONSIG TO EBZ_SISCEL
/
GRANT SELECT ON FA_SEQ_FOLNCCONSIG TO EBZ_SISCEL
/
GRANT SELECT ON FA_SEQ_FOLNCCONSIG TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_FOLNCCONSIG TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_FOLNCCONSIG TO SISCEL_SELECT
/
