GRANT SELECT ON FA_SEQ_CONTADO TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_CONTADO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CONTADO TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CONTADO TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_CONTADO TO SISCEL_SELECT
/
