GRANT ALTER ON FA_SEQ_FOLCONSIG TO EBZ_SISCEL
/
GRANT SELECT ON FA_SEQ_FOLCONSIG TO EBZ_SISCEL
/
GRANT SELECT ON FA_SEQ_FOLCONSIG TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_FOLCONSIG TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_FOLCONSIG TO SISCEL_SELECT
/
