GRANT EXECUTE ON FA_SERVICIOS_FACTURACION_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON FA_SERVICIOS_FACTURACION_PG TO SISCEL_GA
/
GRANT EXECUTE ON FA_SERVICIOS_FACTURACION_PG TO SISCEL_PV
/
GRANT EXECUTE ON FA_SERVICIOS_FACTURACION_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON FA_SERVICIOS_FACTURACION_PG TO SISCEL_VE
/
