GRANT SELECT ON FA_SEQ_BAJA TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_BAJA TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_BAJA TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_BAJA TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_BAJA TO SISCEL_SELECT
/
