GRANT SELECT ON FA_SEQ_CONCE TO EBZ_SISCEL
/
GRANT ALTER ON FA_SEQ_CONCE TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CONCE TO SISCEL_ADMIN
/
GRANT SELECT ON FA_SEQ_CONCE TO SISCEL_FA
/
GRANT SELECT ON FA_SEQ_CONCE TO SISCEL_SELECT
/
