GRANT DELETE ON FA_TIPDOCDIREC_TD TO SISCEL_ADMIN
/
GRANT INSERT ON FA_TIPDOCDIREC_TD TO SISCEL_ADMIN
/
GRANT SELECT ON FA_TIPDOCDIREC_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON FA_TIPDOCDIREC_TD TO SISCEL_ADMIN
/
GRANT SELECT ON FA_TIPDOCDIREC_TD TO SISCEL_SELECT
/
GRANT SELECT ON FA_TIPDOCDIREC_TD TO SOLO_CONSULTA_SISCEL
/
