GRANT SELECT , INSERT , UPDATE , DELETE ON FA_TRAZAPROC_JOB_TO TO SISCEL_FA
/
GRANT SELECT                            ON FA_TRAZAPROC_JOB_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_TRAZAPROC_JOB_TO TO SISCEL_ADMIN
/

