GRANT DELETE ON FA_TIPO_REPORTE_TD TO SISCEL_ADMIN
/
GRANT INSERT ON FA_TIPO_REPORTE_TD TO SISCEL_ADMIN
/
GRANT SELECT ON FA_TIPO_REPORTE_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON FA_TIPO_REPORTE_TD TO SISCEL_ADMIN
/
GRANT DELETE ON FA_TIPO_REPORTE_TD TO SISCEL_FA
/
GRANT INSERT ON FA_TIPO_REPORTE_TD TO SISCEL_FA
/
GRANT SELECT ON FA_TIPO_REPORTE_TD TO SISCEL_FA
/
GRANT UPDATE ON FA_TIPO_REPORTE_TD TO SISCEL_FA
/
GRANT SELECT ON FA_TIPO_REPORTE_TD TO SISCEL_SELECT
/
