GRANT SELECT , INSERT , UPDATE , DELETE ON FA_TASA_CAMBIO_TO TO SISCEL_FA
/
GRANT SELECT                            ON FA_TASA_CAMBIO_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_TASA_CAMBIO_TO TO SISCEL_ADMIN
/

