GRANT SELECT , INSERT , UPDATE , DELETE ON FA_TASA_CAMBIO_TD TO SISCEL_FA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_TASA_CAMBIO_TD TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_TASA_CAMBIO_TD TO SISCEL_VE
/
GRANT SELECT                            ON FA_TASA_CAMBIO_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON FA_TASA_CAMBIO_TD TO SISCEL_PV
/

