GRANT DELETE ON FACT_CICLO_CONTAB TO PUBLIC
/
GRANT INSERT ON FACT_CICLO_CONTAB TO PUBLIC
/
GRANT SELECT ON FACT_CICLO_CONTAB TO PUBLIC
/
GRANT UPDATE ON FACT_CICLO_CONTAB TO PUBLIC
/
GRANT SELECT ON FACT_CICLO_CONTAB TO SOLO_CONSULTA_SISCEL
/
