GRANT ALTER ON FAS_PRESUPTEMP TO EBZ_SISCEL
/
GRANT SELECT ON FAS_PRESUPTEMP TO EBZ_SISCEL
/
GRANT SELECT ON FAS_PRESUPTEMP TO SISCEL_ADMIN
/
GRANT SELECT ON FAS_PRESUPTEMP TO SISCEL_FA
/
GRANT SELECT ON FAS_PRESUPTEMP TO SISCEL_SELECT
/
