GRANT SELECT ON FAS_SEQ_CUADRANDESC TO EBZ_SISCEL
/
GRANT SELECT ON FAS_SEQ_CUADRANDESC TO SISCEL_ADMIN
/
GRANT SELECT ON FAS_SEQ_CUADRANDESC TO SISCEL_FA
/
GRANT SELECT ON FAS_SEQ_CUADRANDESC TO SISCEL_SELECT
/
