GRANT SELECT ON FAS_IMPTIPSUBGRUPOS TO EBZ_SISCEL
/
GRANT SELECT ON FAS_IMPTIPSUBGRUPOS TO SISCEL_ADMIN
/
GRANT SELECT ON FAS_IMPTIPSUBGRUPOS TO SISCEL_FA
/
GRANT SELECT ON FAS_IMPTIPSUBGRUPOS TO SISCEL_SELECT
/
