GRANT SELECT ON FAS_IMPSUBGRUPOS TO EBZ_SISCEL
/
GRANT SELECT ON FAS_IMPSUBGRUPOS TO SISCEL_ADMIN
/
GRANT SELECT ON FAS_IMPSUBGRUPOS TO SISCEL_FA
/
GRANT SELECT ON FAS_IMPSUBGRUPOS TO SISCEL_SELECT
/
