GRANT SELECT ON FAS_IMPTIPGRUPOS TO EBZ_SISCEL
/
GRANT SELECT ON FAS_IMPTIPGRUPOS TO SISCEL_ADMIN
/
GRANT SELECT ON FAS_IMPTIPGRUPOS TO SISCEL_FA
/
GRANT SELECT ON FAS_IMPTIPGRUPOS TO SISCEL_SELECT
/
