GRANT SELECT ON FAS_SEQ_GRUPOAPLI TO EBZ_SISCEL
/
GRANT SELECT ON FAS_SEQ_GRUPOAPLI TO SISCEL_ADMIN
/
GRANT SELECT ON FAS_SEQ_GRUPOAPLI TO SISCEL_FA
/
GRANT SELECT ON FAS_SEQ_GRUPOAPLI TO SISCEL_SELECT
/
