GRANT SELECT ON FAS_SEQ_GRUPOEVAL TO EBZ_SISCEL
/
GRANT SELECT ON FAS_SEQ_GRUPOEVAL TO SISCEL_ADMIN
/
GRANT SELECT ON FAS_SEQ_GRUPOEVAL TO SISCEL_FA
/
GRANT SELECT ON FAS_SEQ_GRUPOEVAL TO SISCEL_SELECT
/
