GRANT SELECT ON FAS_IMPFORMULARIOS TO EBZ_SISCEL
/
GRANT SELECT ON FAS_IMPFORMULARIOS TO SISCEL_ADMIN
/
GRANT SELECT ON FAS_IMPFORMULARIOS TO SISCEL_FA
/
GRANT SELECT ON FAS_IMPFORMULARIOS TO SISCEL_SELECT
/
