GRANT EXECUTE ON FN_CODTECNOLOGIA TO EBZ_SISCEL
/
GRANT EXECUTE ON FN_CODTECNOLOGIA TO SISCEL_ADMIN
/
GRANT EXECUTE ON FN_CODTECNOLOGIA TO SISCEL_GA
/
GRANT EXECUTE ON FN_CODTECNOLOGIA TO SISCEL_SELECT
/
