GRANT EXECUTE ON FN_OBTIENE_OPERCLIENTE TO EBZ_SISCEL
/
GRANT EXECUTE ON FN_OBTIENE_OPERCLIENTE TO SISCEL_ADMIN
/
GRANT EXECUTE ON FN_OBTIENE_OPERCLIENTE TO SISCEL_GA
/
GRANT EXECUTE ON FN_OBTIENE_OPERCLIENTE TO SISCEL_SELECT
/
