GRANT EXECUTE ON FN_OBTIENE_PLAZACLIENTE TO EBZ_SISCEL
/
GRANT EXECUTE ON FN_OBTIENE_PLAZACLIENTE TO QUETOL
/
GRANT EXECUTE ON FN_OBTIENE_PLAZACLIENTE TO SISCEL_ADMIN
/
GRANT EXECUTE ON FN_OBTIENE_PLAZACLIENTE TO SISCEL_GA
/
GRANT EXECUTE ON FN_OBTIENE_PLAZACLIENTE TO SISCEL_GE
/
GRANT EXECUTE ON FN_OBTIENE_PLAZACLIENTE TO SISCEL_SELECT
/
