GRANT EXECUTE ON FN_RECUPERA_NUM_MIN_ANT TO EBZ_SISCEL
/
GRANT EXECUTE ON FN_RECUPERA_NUM_MIN_ANT TO SISCEL_ADMIN
/
GRANT EXECUTE ON FN_RECUPERA_NUM_MIN_ANT TO SISCEL_GA
/
GRANT EXECUTE ON FN_RECUPERA_NUM_MIN_ANT TO SISCEL_SELECT
/
