GRANT EXECUTE ON FN_RECUPERA_IMSI TO EBZ_SISCEL
/
GRANT EXECUTE ON FN_RECUPERA_IMSI TO SISCEL_ADMIN
/
GRANT EXECUTE ON FN_RECUPERA_IMSI TO SISCEL_GA
/
GRANT EXECUTE ON FN_RECUPERA_IMSI TO SISCEL_SELECT
/
