GRANT EXECUTE ON FN_VERIFICAPLAZA_NEWHOME TO EBZ_SISCEL
/
GRANT EXECUTE ON FN_VERIFICAPLAZA_NEWHOME TO SISCEL_ADMIN
/
GRANT EXECUTE ON FN_VERIFICAPLAZA_NEWHOME TO SISCEL_GA
/
GRANT EXECUTE ON FN_VERIFICAPLAZA_NEWHOME TO SISCEL_SELECT
/
