GRANT EXECUTE ON FN_VERIFICA_PLAZAS_CLIENTES TO EBZ_SISCEL
/
GRANT EXECUTE ON FN_VERIFICA_PLAZAS_CLIENTES TO SISCEL_ADMIN
/
GRANT EXECUTE ON FN_VERIFICA_PLAZAS_CLIENTES TO SISCEL_GA
/
GRANT EXECUTE ON FN_VERIFICA_PLAZAS_CLIENTES TO SISCEL_SELECT
/
