GRANT EXECUTE ON FN_VERIF_HOMEABO_PLAZACLI TO EBZ_SISCEL
/
GRANT EXECUTE ON FN_VERIF_HOMEABO_PLAZACLI TO SISCEL_ADMIN
/
GRANT EXECUTE ON FN_VERIF_HOMEABO_PLAZACLI TO SISCEL_GA
/
GRANT EXECUTE ON FN_VERIF_HOMEABO_PLAZACLI TO SISCEL_SELECT
/
