GRANT EXECUTE ON FN_VERIFICA_HOMEPLAZA TO EBZ_SISCEL
/
GRANT EXECUTE ON FN_VERIFICA_HOMEPLAZA TO SISCEL_ADMIN
/
GRANT EXECUTE ON FN_VERIFICA_HOMEPLAZA TO SISCEL_GA
/
GRANT EXECUTE ON FN_VERIFICA_HOMEPLAZA TO SISCEL_SELECT
/
