GRANT EXECUTE ON FN_VAL_MIGTECNOLOGIA TO EBZ_SISCEL
/
GRANT EXECUTE ON FN_VAL_MIGTECNOLOGIA TO SISCEL_ADMIN
/
GRANT EXECUTE ON FN_VAL_MIGTECNOLOGIA TO SISCEL_PV
/
GRANT EXECUTE ON FN_VAL_MIGTECNOLOGIA TO SISCEL_SELECT
/
