GRANT EXECUTE ON FRECUPERSIMCARD_FN TO EBZ_SISCEL
/
GRANT EXECUTE ON FRECUPERSIMCARD_FN TO MAS_SERVICE_DML
/
GRANT EXECUTE ON FRECUPERSIMCARD_FN TO SISCEL_ADMIN
/
GRANT EXECUTE ON FRECUPERSIMCARD_FN TO SISCEL_GSM
/
GRANT EXECUTE ON FRECUPERSIMCARD_FN TO SISCEL_SELECT
/
