GRANT SELECT ON GA_AUT_RENOVA_SQ TO SISCEL_ADMIN
/
GRANT SELECT ON GA_AUT_RENOVA_SQ TO SISCEL_GA
/
GRANT SELECT ON GA_AUT_RENOVA_SQ TO SISCEL_PV
/
GRANT SELECT ON GA_AUT_RENOVA_SQ TO SISCEL_SELECT
/

