GRANT SELECT                            ON GA_ABONIVEL_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_ABONIVEL_TO TO SISCEL_VE
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_ABONIVEL_TO TO SISCEL_PV
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_ABONIVEL_TO TO SISCEL_GA
/

