GRANT    SELECT                           ON GA_AUTORIZA_RENOVA_TO TO SISCEL_SELECT
/
GRANT    SELECT, INSERT, UPDATE, DELETE   ON GA_AUTORIZA_RENOVA_TO TO SISCEL_ADMIN
/
GRANT    SELECT, INSERT, UPDATE, DELETE   ON GA_AUTORIZA_RENOVA_TO TO SISCEL_PV
/

