GRANT EXECUTE ON GA_CONS_ATLANTIDA_PG TO FAC_SISCEL
/
GRANT EXECUTE ON GA_CONS_ATLANTIDA_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_CONS_ATLANTIDA_PG TO SISCEL_GA
/
GRANT EXECUTE ON GA_CONS_ATLANTIDA_PG TO SISCEL_SELECT
/
