GRANT    SELECT                                      ON GA_CAUSAL_CAMBIO_TD TO SISCEL_SELECT
/
GRANT    SELECT, INSERT, UPDATE, DELETE              ON GA_CAUSAL_CAMBIO_TD TO SISCEL_ADMIN
/
GRANT    SELECT, INSERT, UPDATE, DELETE              ON GA_CAUSAL_CAMBIO_TD TO SISCEL_PV
/

