GRANT SELECT                             ON GA_CAUSAEIR_TO TO SISCEL_SELECT
/
GRANT SELECT, INSERT,UPDATE,DELETE       ON GA_CAUSAEIR_TO TO SISCEL_ADMIN
/
GRANT SELECT, INSERT,UPDATE,DELETE       ON GA_CAUSAEIR_TO TO SISCEL_PV
/

