GRANT SELECT                            ON GA_CONTACTO_ABONADO_TH TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_CONTACTO_ABONADO_TH TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_CONTACTO_ABONADO_TH TO SISCEL_VE
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_CONTACTO_ABONADO_TH TO SISCEL_IC
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_CONTACTO_ABONADO_TH TO SISCEL_PV
/

