GRANT SELECT                            ON GA_COBROS_ADELANTADOS_TH TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_COBROS_ADELANTADOS_TH TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_COBROS_ADELANTADOS_TH TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_COBROS_ADELANTADOS_TH TO SISCEL_FA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_COBROS_ADELANTADOS_TH TO SISCEL_PV
/
