GRANT SELECT                            ON GA_DOC_DIGITALIZADOS_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_DOC_DIGITALIZADOS_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_DOC_DIGITALIZADOS_TO TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_DOC_DIGITALIZADOS_TO TO SISCEL_PV
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_DOC_DIGITALIZADOS_TO TO SISCEL_VE
/

