GRANT DELETE, INSERT, SELECT, UPDATE ON GA_DESC_EVENTO_TD TO SISCEL_ADMIN;

GRANT DELETE, INSERT, SELECT, UPDATE ON GA_DESC_EVENTO_TD TO SISCEL_GE;

GRANT SELECT ON GA_DESC_EVENTO_TD TO SISCEL_SELECT;