GRANT EXECUTE  ON GA_DISTRIBUCION_BOLSA_PG  TO SISCEL_SELECT
/
GRANT EXECUTE  ON GA_DISTRIBUCION_BOLSA_PG  TO SISCEL_ADMIN
/
GRANT EXECUTE  ON GA_DISTRIBUCION_BOLSA_PG  TO SISCEL_GA
/
GRANT EXECUTE  ON GA_DISTRIBUCION_BOLSA_PG  TO SISCEL_VE
/
GRANT EXECUTE  ON GA_DISTRIBUCION_BOLSA_PG  TO SISCEL_PV
/

