GRANT SELECT                            ON GA_DATABONADO_TH TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_DATABONADO_TH TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_DATABONADO_TH TO SISCEL_GA
/

