GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON SISCEL.GA_DATOSCLIENTE_TSE_TD TO SISCEL_ADMIN;

GRANT DELETE, INSERT, SELECT, UPDATE ON SISCEL.GA_DATOSCLIENTE_TSE_TD TO SISCEL_GA;

GRANT SELECT ON SISCEL.GA_DATOSCLIENTE_TSE_TD TO SISCEL_SELECT;

GRANT ALTER, DELETE, INSERT, SELECT ON SISCEL.GA_DATOSCLIENTE_TSE_TD TO SISCEL_VE;
