GRANT EXECUTE ON GA_EXTRA_TIEMPO_PG TO FAC_SISCEL
/
GRANT EXECUTE ON GA_EXTRA_TIEMPO_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_EXTRA_TIEMPO_PG TO SISCEL_GA
/
GRANT EXECUTE ON GA_EXTRA_TIEMPO_PG TO SISCEL_SELECT
/
