GRANT EXECUTE ON GA_FN_OBT_CONT_TELEF_TMC TO EBZ_SISCEL
/
GRANT EXECUTE ON GA_FN_OBT_CONT_TELEF_TMC TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_FN_OBT_CONT_TELEF_TMC TO SISCEL_GA
/
GRANT EXECUTE ON GA_FN_OBT_CONT_TELEF_TMC TO SISCEL_SELECT
/
