GRANT EXECUTE ON GA_FN_OBT_CONT_TELEF_MPR TO EBZ_SISCEL
/
GRANT EXECUTE ON GA_FN_OBT_CONT_TELEF_MPR TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_FN_OBT_CONT_TELEF_MPR TO SISCEL_GA
/
GRANT EXECUTE ON GA_FN_OBT_CONT_TELEF_MPR TO SISCEL_SELECT
/
