GRANT DELETE ON GA_HRESERVA TO SISCEL_ADMIN
/
GRANT INSERT ON GA_HRESERVA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_HRESERVA TO SISCEL_ADMIN
/
GRANT UPDATE ON GA_HRESERVA TO SISCEL_ADMIN
/
GRANT DELETE ON GA_HRESERVA TO SISCEL_GA
/
GRANT INSERT ON GA_HRESERVA TO SISCEL_GA
/
GRANT SELECT ON GA_HRESERVA TO SISCEL_GA
/
GRANT UPDATE ON GA_HRESERVA TO SISCEL_GA
/
GRANT SELECT ON GA_HRESERVA TO SISCEL_SELECT
/
GRANT SELECT ON GA_HRESERVA TO SOLO_CONSULTA_SISCEL
/
