GRANT  SELECT                           ON GA_IMPRESION_DOC_TD TO SISCEL_SELECT
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON GA_IMPRESION_DOC_TD TO SISCEL_ADMIN
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON GA_IMPRESION_DOC_TD TO SISCEL_PV
/

