GRANT SELECT                            ON GA_LNVEN_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_LNVEN_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_LNVEN_TO TO SISCEL_GA
/

