GRANT SELECT                            ON GA_LNCLI_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_LNCLI_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_LNCLI_TO TO SISCEL_GA
/

