GRANT    SELECT                               ON GA_LISTACAUSAEIR_TD TO SISCEL_SELECT
/
GRANT    SELECT,INSERT,UPDATE,DELETE                          ON GA_LISTACAUSAEIR_TD TO SISCEL_ADMIN
/
GRANT    SELECT,INSERT,UPDATE,DELETE                           ON GA_LISTACAUSAEIR_TD TO SISCEL_PV
/

