GRANT DELETE ON GA_NUMCEL_PERSONAL_TO TO SISCEL_ADMIN
/
GRANT INSERT ON GA_NUMCEL_PERSONAL_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GA_NUMCEL_PERSONAL_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON GA_NUMCEL_PERSONAL_TO TO SISCEL_ADMIN
/
GRANT DELETE ON GA_NUMCEL_PERSONAL_TO TO SISCEL_GA
/
GRANT INSERT ON GA_NUMCEL_PERSONAL_TO TO SISCEL_GA
/
GRANT SELECT ON GA_NUMCEL_PERSONAL_TO TO SISCEL_GA
/
GRANT UPDATE ON GA_NUMCEL_PERSONAL_TO TO SISCEL_GA
/
GRANT SELECT ON GA_NUMCEL_PERSONAL_TO TO SISCEL_SELECT
/
