GRANT EXECUTE ON GA_NUMCEL_PERSONAL_PG TO CER_CPU
/
GRANT EXECUTE ON GA_NUMCEL_PERSONAL_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_NUMCEL_PERSONAL_PG TO SISCEL_CPU
/
GRANT EXECUTE ON GA_NUMCEL_PERSONAL_PG TO SISCEL_GA
/
GRANT EXECUTE ON GA_NUMCEL_PERSONAL_PG TO SISCEL_SELECT
/
