GRANT SELECT                            ON GA_NUMSMS_TH TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_NUMSMS_TH TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_NUMSMS_TH TO SISCEL_VE
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_NUMSMS_TH TO SISCEL_PV
/

