GRANT SELECT                            ON GA_NIVELPRESTACION_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_NIVELPRESTACION_TD TO SISCEL_VE
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_NIVELPRESTACION_TD TO SISCEL_PV
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_NIVELPRESTACION_TD TO SISCEL_GA
/

