GRANT EXECUTE ON GA_PAC_INTERAL TO EBZ_SISCEL
/
GRANT EXECUTE ON GA_PAC_INTERAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_PAC_INTERAL TO SISCEL_AL
/
GRANT EXECUTE ON GA_PAC_INTERAL TO SISCEL_GA
/
GRANT EXECUTE ON GA_PAC_INTERAL TO SISCEL_SELECT
/
