GRANT SELECT , INSERT , UPDATE , DELETE ON GA_PERFIL_AA_TD TO SISCEL_IC
/
GRANT SELECT                            ON GA_PERFIL_AA_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_PERFIL_AA_TD TO SISCEL_ADMIN
/

