GRANT EXECUTE ON GA_P_CATCUENTAS TO EBZ_SISCEL
/
GRANT EXECUTE ON GA_P_CATCUENTAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_P_CATCUENTAS TO SISCEL_GA
/
GRANT EXECUTE ON GA_P_CATCUENTAS TO SISCEL_SELECT
/
