GRANT SELECT , INSERT , UPDATE , DELETE ON GA_PERFIL_CELULAR_TO TO SISCEL_IC
/
GRANT SELECT                            ON GA_PERFIL_CELULAR_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_PERFIL_CELULAR_TO TO SISCEL_ADMIN
/

