GRANT EXECUTE ON GA_PE_BAJA_STB TO EBZ_SISCEL
/
GRANT EXECUTE ON GA_PE_BAJA_STB TO OPS$XPABONAD
/
GRANT EXECUTE ON GA_PE_BAJA_STB TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_PE_BAJA_STB TO SISCEL_GA
/
GRANT EXECUTE ON GA_PE_BAJA_STB TO SISCEL_SELECT
/
