GRANT EXECUTE ON GA_PR_ACT_PLANTILLAS_KIT TO EBZ_SISCEL
/
GRANT EXECUTE ON GA_PR_ACT_PLANTILLAS_KIT TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_PR_ACT_PLANTILLAS_KIT TO SISCEL_GE
/
GRANT EXECUTE ON GA_PR_ACT_PLANTILLAS_KIT TO SISCEL_SELECT
/
