GRANT EXECUTE ON GA_P_CUENTA_PEX TO EBZ_SISCEL
/
GRANT EXECUTE ON GA_P_CUENTA_PEX TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_P_CUENTA_PEX TO SISCEL_GA
/
GRANT EXECUTE ON GA_P_CUENTA_PEX TO SISCEL_SELECT
/
