GRANT EXECUTE ON GA_P_CATCUENTAS_QUIOSCO TO EBZ_SISCEL
/
GRANT EXECUTE ON GA_P_CATCUENTAS_QUIOSCO TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_P_CATCUENTAS_QUIOSCO TO SISCEL_GA
/
GRANT EXECUTE ON GA_P_CATCUENTAS_QUIOSCO TO SISCEL_SELECT
/
