GRANT SELECT                            ON GA_PORCENTAJE_COBROS_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_PORCENTAJE_COBROS_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_PORCENTAJE_COBROS_TD TO SISCEL_GA
/

