GRANT EXECUTE ON GA_REG_ATENCION_CLIENTE_NG_PG TO FAC_SISCEL
/
GRANT EXECUTE ON GA_REG_ATENCION_CLIENTE_NG_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_REG_ATENCION_CLIENTE_NG_PG TO SISCEL_GA
/
GRANT EXECUTE ON GA_REG_ATENCION_CLIENTE_NG_PG TO SISCEL_SELECT
/
