GRANT SELECT                            ON GA_RANGOS_FIJOS_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_RANGOS_FIJOS_TO TO SISCEL_VE
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_RANGOS_FIJOS_TO TO SISCEL_PV
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_RANGOS_FIJOS_TO TO SISCEL_AL
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_RANGOS_FIJOS_TO TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_RANGOS_FIJOS_TO TO SISCEL_IC
/

