GRANT EXECUTE ON GA_REGISTRO_ACCESO_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON GA_REGISTRO_ACCESO_PG TO  SISCEL_ADMIN
/
GRANT EXECUTE ON GA_REGISTRO_ACCESO_PG TO  SISCEL_GA
/
GRANT EXECUTE ON GA_REGISTRO_ACCESO_PG TO SISCEL_VE
/