GRANT SELECT ON GA_REPOSITORIO_SQ TO SISCEL_SELECT
/
GRANT SELECT ON GA_REPOSITORIO_SQ TO SISCEL_ADMIN
/
GRANT SELECT ON GA_REPOSITORIO_SQ TO SISCEL_GA
/
GRANT SELECT ON GA_REPOSITORIO_SQ TO SISCEL_PV
/

