GRANT DELETE ON GA_SERVSUPL_COB_TH TO SISCEL_ADMIN
/
GRANT INSERT ON GA_SERVSUPL_COB_TH TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SERVSUPL_COB_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON GA_SERVSUPL_COB_TH TO SISCEL_ADMIN
/
GRANT DELETE ON GA_SERVSUPL_COB_TH TO SISCEL_PV
/
GRANT INSERT ON GA_SERVSUPL_COB_TH TO SISCEL_PV
/
GRANT SELECT ON GA_SERVSUPL_COB_TH TO SISCEL_PV
/
GRANT UPDATE ON GA_SERVSUPL_COB_TH TO SISCEL_PV
/
GRANT SELECT ON GA_SERVSUPL_COB_TH TO SISCEL_SELECT
/
