GRANT SELECT ON GA_SEQ_FICHERO TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_FICHERO TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_FICHERO TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_FICHERO TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_FICHERO TO SISCEL_SELECT
/
