GRANT EXECUTE ON GA_SERVICIOS_ARTPLAN_PG TO FAC_SISCEL
/
GRANT EXECUTE ON GA_SERVICIOS_ARTPLAN_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_SERVICIOS_ARTPLAN_PG TO SISCEL_PV
/
GRANT EXECUTE ON GA_SERVICIOS_ARTPLAN_PG TO SISCEL_SELECT
/
