GRANT SELECT ON GA_SEQ_NUMDIASNUM TO EBZ_SISCEL
/
GRANT SELECT ON GA_SEQ_NUMDIASNUM TO OPS$XPFACTUR
/
GRANT ALTER ON GA_SEQ_NUMDIASNUM TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMDIASNUM TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMDIASNUM TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_NUMDIASNUM TO SISCEL_SELECT
/
