GRANT SELECT ON GA_SEQ_APLITREK TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_APLITREK TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_APLITREK TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_APLITREK TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_APLITREK TO SISCEL_SELECT
/
