GRANT SELECT ON GA_SEQ_VENTA TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_VENTA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_VENTA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_VENTA TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_VENTA TO SISCEL_SELECT
/
