GRANT SELECT ON GA_SEQ_EMPRESA TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_EMPRESA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_EMPRESA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_EMPRESA TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_EMPRESA TO SISCEL_SELECT
/
