GRANT SELECT ON GA_SEQ_CONTCEL TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_CONTCEL TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_CONTCEL TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_CONTCEL TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_CONTCEL TO SISCEL_SELECT
/
