GRANT EXECUTE ON GA_SOL_DESCUENTO_QT TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_SOL_DESCUENTO_QT TO SISCEL_GA
/
GRANT EXECUTE ON GA_SOL_DESCUENTO_QT TO SISCEL_PV
/
GRANT EXECUTE ON GA_SOL_DESCUENTO_QT TO SISCEL_SELECT
/
GRANT EXECUTE ON GA_SOL_DESCUENTO_QT TO SISCEL_VE
/
