GRANT SELECT ON GA_SEQ_NUMVENTA TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_NUMVENTA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMVENTA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMVENTA TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_NUMVENTA TO SISCEL_SELECT
/
