GRANT SELECT ON GA_SEQ_ALQUILER TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_ALQUILER TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_ALQUILER TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_ALQUILER TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_ALQUILER TO SISCEL_SELECT
/
