GRANT SELECT                     ON GA_SERV911CARGO_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT, DELETE, UPDATE   ON GA_SERV911CARGO_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT, DELETE, UPDATE   ON GA_SERV911CARGO_TD TO SISCEL_PV
/

