GRANT SELECT ON GA_SEQ_CONTTREK TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_CONTTREK TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_CONTTREK TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_CONTTREK TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_CONTTREK TO SISCEL_SELECT
/
