GRANT SELECT ON GA_SEQ_USUARIOS TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_USUARIOS TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_USUARIOS TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_USUARIOS TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_USUARIOS TO SISCEL_SELECT
/
