GRANT SELECT                            ON GA_SOLICVENTA_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_SOLICVENTA_TO TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_SOLICVENTA_TO TO SISCEL_VE
/

