GRANT SELECT ON GA_SEQ_NUMSOLROA TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_NUMSOLROA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMSOLROA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMSOLROA TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_NUMSOLROA TO SISCEL_SELECT
/
