GRANT SELECT ON GA_SEQ_ATLETI TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_ATLETI TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_ATLETI TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_ATLETI TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_ATLETI TO SISCEL_SELECT
/
