GRANT SELECT ON GA_SEQ_PACK TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_PACK TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_PACK TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_PACK TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_PACK TO SISCEL_SELECT
/
