GRANT SELECT ON GA_SEQ_VENTAS TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_VENTAS TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_VENTAS TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_VENTAS TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_VENTAS TO SISCEL_SELECT
/
