GRANT SELECT ON GA_SEQ_CONTBEEP TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_CONTBEEP TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_CONTBEEP TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_CONTBEEP TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_CONTBEEP TO SISCEL_SELECT
/
