GRANT EXECUTE ON GA_SERVICIOS_ABONADOS_PG TO FAC_SISCEL
/
GRANT EXECUTE ON GA_SERVICIOS_ABONADOS_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_SERVICIOS_ABONADOS_PG TO SISCEL_GA
/
GRANT EXECUTE ON GA_SERVICIOS_ABONADOS_PG TO SISCEL_SELECT
/
