GRANT SELECT                            ON GA_SERIES_LN_OOP_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_SERIES_LN_OOP_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_SERIES_LN_OOP_TO TO SISCEL_GA
/

