GRANT SELECT ON GA_SEQ_GRPSERV TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_GRPSERV TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_GRPSERV TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_GRPSERV TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_GRPSERV TO SISCEL_SELECT
/
