GRANT SELECT ON GA_SEQ_NUMROA TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_NUMROA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMROA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMROA TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_NUMROA TO SISCEL_SELECT
/
