GRANT SELECT ON GA_SEQ_ESTADIA TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_ESTADIA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_ESTADIA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_ESTADIA TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_ESTADIA TO SISCEL_SELECT
/
