GRANT SELECT ON GA_SEQ_NUMABO TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_NUMABO TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMABO TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMABO TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_NUMABO TO SISCEL_SELECT
/
