GRANT SELECT ON GA_SEQ_CUENTAS TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_CUENTAS TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_CUENTAS TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_CUENTAS TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_CUENTAS TO SISCEL_SELECT
/
