GRANT SELECT ON GA_SEQ_NUMGRPBEEP TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_NUMGRPBEEP TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMGRPBEEP TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMGRPBEEP TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_NUMGRPBEEP TO SISCEL_SELECT
/
