GRANT SELECT ON GA_SEQ_TRANSACABO TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_TRANSACABO TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_TRANSACABO TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_TRANSACABO TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_TRANSACABO TO SISCEL_SELECT
/
