GRANT SELECT ON GA_SEQ_DEVCLTE TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_DEVCLTE TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_DEVCLTE TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_DEVCLTE TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_DEVCLTE TO SISCEL_SELECT
/
