GRANT SELECT ON GA_SEQ_NUMSIXBELL TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_NUMSIXBELL TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMSIXBELL TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_NUMSIXBELL TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_NUMSIXBELL TO SISCEL_SELECT
/
