GRANT SELECT ON GA_SEQ_CONSULTA TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_CONSULTA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_CONSULTA TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_CONSULTA TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_CONSULTA TO SISCEL_SELECT
/
