GRANT SELECT ON GA_SEQ_MOVPREPAGO TO EBZ_SISCEL
/
GRANT SELECT ON GA_SEQ_MOVPREPAGO TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_MOVPREPAGO TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_MOVPREPAGO TO SISCEL_SELECT
/
