GRANT SELECT ON GA_SEQ_SINIESTROS TO EBZ_SISCEL
/
GRANT ALTER ON GA_SEQ_SINIESTROS TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_SINIESTROS TO SISCEL_ADMIN
/
GRANT SELECT ON GA_SEQ_SINIESTROS TO SISCEL_GA
/
GRANT SELECT ON GA_SEQ_SINIESTROS TO SISCEL_SELECT
/
