GRANT SELECT                            ON GA_TIPDOC_DIGITALIZADOS_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_TIPDOC_DIGITALIZADOS_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_TIPDOC_DIGITALIZADOS_TD TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_TIPDOC_DIGITALIZADOS_TD TO SISCEL_PV
/

