GRANT DELETE, INSERT, SELECT, UPDATE ON GA_TRAZA_USUARIO_TO TO SISCEL_ADMIN
/
GRANT DELETE, INSERT, SELECT, UPDATE ON GA_TRAZA_USUARIO_TO TO SISCEL_GE
/
GRANT SELECT ON GA_TRAZA_USUARIO_TO TO SISCEL_SELECT
/