GRANT SELECT ON GA_TIPDOC_DIGITALIZADOS_SQ TO SISCEL_SELECT
/
GRANT SELECT ON GA_TIPDOC_DIGITALIZADOS_SQ TO SISCEL_ADMIN
/
GRANT SELECT ON GA_TIPDOC_DIGITALIZADOS_SQ TO SISCEL_GA
/
GRANT SELECT ON GA_TIPDOC_DIGITALIZADOS_SQ TO SISCEL_PV
/

