GRANT SELECT , INSERT , UPDATE , DELETE ON GA_TIP_OPERADORES_TD TO SISCEL_GA
/
GRANT SELECT                            ON GA_TIP_OPERADORES_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_TIP_OPERADORES_TD TO SISCEL_ADMIN
/

