GRANT SELECT                            ON GA_TIPOSEGURO_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_TIPOSEGURO_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_TIPOSEGURO_TD TO SISCEL_GA
/

