GRANT SELECT                            ON GA_TIPO_LISTA_LN_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_TIPO_LISTA_LN_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GA_TIPO_LISTA_LN_TD TO SISCEL_GA
/

