GRANT EXECUTE ON GA_VALIDA_AUTENTICACION_PR TO EBZ_SISCEL
/
GRANT EXECUTE ON GA_VALIDA_AUTENTICACION_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_VALIDA_AUTENTICACION_PR TO SISCEL_GA
/
GRANT EXECUTE ON GA_VALIDA_AUTENTICACION_PR TO SISCEL_SELECT
/
