GRANT DELETE ON GAD_SERVSUP_ART TO SISCEL_ADMIN
/
GRANT INSERT ON GAD_SERVSUP_ART TO SISCEL_ADMIN
/
GRANT SELECT ON GAD_SERVSUP_ART TO SISCEL_ADMIN
/
GRANT UPDATE ON GAD_SERVSUP_ART TO SISCEL_ADMIN
/
GRANT DELETE ON GAD_SERVSUP_ART TO SISCEL_GA
/
GRANT INSERT ON GAD_SERVSUP_ART TO SISCEL_GA
/
GRANT SELECT ON GAD_SERVSUP_ART TO SISCEL_GA
/
GRANT UPDATE ON GAD_SERVSUP_ART TO SISCEL_GA
/
GRANT SELECT ON GAD_SERVSUP_ART TO SISCEL_SELECT
/
GRANT SELECT ON GAD_SERVSUP_ART TO SOLO_CONSULTA_SISCEL
/
