GRANT ALTER ON GAS_CATEG_NUMPOSTULACION TO EBZ_SISCEL
/
GRANT SELECT ON GAS_CATEG_NUMPOSTULACION TO EBZ_SISCEL
/
GRANT SELECT ON GAS_CATEG_NUMPOSTULACION TO SISCEL_ADMIN
/
GRANT SELECT ON GAS_CATEG_NUMPOSTULACION TO SISCEL_GA
/
GRANT SELECT ON GAS_CATEG_NUMPOSTULACION TO SISCEL_SELECT
/
