GRANT DELETE ON GAT_CARGA_CTASEG_TMP_TO TO SISCEL_ADMIN
/
GRANT INSERT ON GAT_CARGA_CTASEG_TMP_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GAT_CARGA_CTASEG_TMP_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON GAT_CARGA_CTASEG_TMP_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GAT_CARGA_CTASEG_TMP_TO TO SISCEL_SELECT
/
