GRANT DELETE ON GAT_RASTREO TO SISCEL_ADMIN
/
GRANT INSERT ON GAT_RASTREO TO SISCEL_ADMIN
/
GRANT SELECT ON GAT_RASTREO TO SISCEL_ADMIN
/
GRANT UPDATE ON GAT_RASTREO TO SISCEL_ADMIN
/
GRANT DELETE ON GAT_RASTREO TO SISCEL_GA
/
GRANT INSERT ON GAT_RASTREO TO SISCEL_GA
/
GRANT SELECT ON GAT_RASTREO TO SISCEL_GA
/
GRANT UPDATE ON GAT_RASTREO TO SISCEL_GA
/
GRANT SELECT ON GAT_RASTREO TO SISCEL_SELECT
/
GRANT SELECT ON GAT_RASTREO TO SOLO_CONSULTA_SISCEL
/
