GRANT DELETE ON GC_BITACORA_TO TO SISCEL_ADMIN
/
GRANT INSERT ON GC_BITACORA_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GC_BITACORA_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON GC_BITACORA_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GC_BITACORA_TO TO SISCEL_SELECT
/
GRANT SELECT ON GC_BITACORA_TO TO SOLO_CONSULTA_SISCEL
/
