GRANT REFERENCES ON GC_CODIGOS_TD TO FAC_SISCEL
/
GRANT SELECT ON GC_CODIGOS_TD TO FAC_SISCEL
/
GRANT DELETE ON GC_CODIGOS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON GC_CODIGOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GC_CODIGOS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON GC_CODIGOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GC_CODIGOS_TD TO SISCEL_SELECT
/
GRANT SELECT ON GC_CODIGOS_TD TO SOLO_CONSULTA_SISCEL
/
