GRANT DELETE ON GC_DATOS_ADIC_APUNTE_TO TO SISCEL_ADMIN
/
GRANT INSERT ON GC_DATOS_ADIC_APUNTE_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GC_DATOS_ADIC_APUNTE_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON GC_DATOS_ADIC_APUNTE_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GC_DATOS_ADIC_APUNTE_TO TO SISCEL_SELECT
/
GRANT SELECT ON GC_DATOS_ADIC_APUNTE_TO TO SOLO_CONSULTA_SISCEL
/
