GRANT DELETE ON GC_MENSAJES_TD TO SISCEL_ADMIN
/
GRANT INSERT ON GC_MENSAJES_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GC_MENSAJES_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON GC_MENSAJES_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GC_MENSAJES_TD TO SISCEL_SELECT
/
GRANT SELECT ON GC_MENSAJES_TD TO SOLO_CONSULTA_SISCEL
/
