GRANT REFERENCES ON GC_TAREA_APUNTE_TO TO FAC_SISCEL
/
GRANT SELECT ON GC_TAREA_APUNTE_TO TO FAC_SISCEL
/
GRANT DELETE ON GC_TAREA_APUNTE_TO TO SISCEL_ADMIN
/
GRANT INSERT ON GC_TAREA_APUNTE_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GC_TAREA_APUNTE_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON GC_TAREA_APUNTE_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GC_TAREA_APUNTE_TO TO SISCEL_SELECT
/
GRANT SELECT ON GC_TAREA_APUNTE_TO TO SOLO_CONSULTA_SISCEL
/
