GRANT DELETE ON GC_TAREA_TRIPLETA_TD TO SISCEL_ADMIN
/
GRANT INSERT ON GC_TAREA_TRIPLETA_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GC_TAREA_TRIPLETA_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON GC_TAREA_TRIPLETA_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GC_TAREA_TRIPLETA_TD TO SISCEL_SELECT
/
GRANT SELECT ON GC_TAREA_TRIPLETA_TD TO SOLO_CONSULTA_SISCEL
/
