GRANT DELETE, INSERT, SELECT, UPDATE ON GE_ASOCPRESTACIONES_TD TO SISCEL_ADMIN;

GRANT DELETE, INSERT, SELECT, UPDATE ON GE_ASOCPRESTACIONES_TD TO SISCEL_GE;

GRANT SELECT ON GE_ASOCPRESTACIONES_TD TO SISCEL_SELECT;

SHOW ERRORS