GRANT SELECT                            ON GE_CATEGORIAS_TH TO SISCEL_SELECT
/
GRANT SELECT, INSERT, UPDATE, DELETE    ON GE_CATEGORIAS_TH TO SISCEL_VE
/
GRANT SELECT, INSERT, UPDATE, DELETE    ON GE_CATEGORIAS_TH TO SISCEL_PV
/

