GRANT DELETE ON GE_CATRIBDOCUM TO SISCEL_ADMIN
/
GRANT INSERT ON GE_CATRIBDOCUM TO SISCEL_ADMIN
/
GRANT SELECT ON GE_CATRIBDOCUM TO SISCEL_ADMIN
/
GRANT UPDATE ON GE_CATRIBDOCUM TO SISCEL_ADMIN
/
GRANT DELETE ON GE_CATRIBDOCUM TO SISCEL_GE
/
GRANT INSERT ON GE_CATRIBDOCUM TO SISCEL_GE
/
GRANT SELECT ON GE_CATRIBDOCUM TO SISCEL_GE
/
GRANT UPDATE ON GE_CATRIBDOCUM TO SISCEL_GE
/
GRANT SELECT ON GE_CATRIBDOCUM TO SISCEL_SELECT
/
GRANT SELECT ON GE_CATRIBDOCUM TO SOLO_CONSULTA_SISCEL
/
