GRANT SELECT                            ON GE_CLIENTE_TASA_OPP_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CLIENTE_TASA_OPP_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CLIENTE_TASA_OPP_TO TO SISCEL_GE
/

