GRANT SELECT                            ON GE_CLILOCPADREHIJO_TH TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CLILOCPADREHIJO_TH TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CLILOCPADREHIJO_TH TO SISCEL_GA
/

