GRANT SELECT                            ON GE_CLIENTE_TASA_TH TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CLIENTE_TASA_TH TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CLIENTE_TASA_TH TO SISCEL_GE
/

