GRANT  SELECT                           ON GE_COLOR_TD TO SISCEL_SELECT
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON GE_COLOR_TD TO SISCEL_VE
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON GE_COLOR_TD TO SISCEL_PV
/

