GRANT SELECT                            ON GE_CLIENTE_TASA_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CLIENTE_TASA_TO TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CLIENTE_TASA_TO TO SISCEL_FA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CLIENTE_TASA_TO TO SISCEL_VE
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CLIENTE_TASA_TO TO SISCEL_PV
/

