GRANT EXECUTE ON GE_CARTA_10120_QT TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_CARTA_10120_QT TO SISCEL_GE
/
GRANT EXECUTE ON GE_CARTA_10120_QT TO SISCEL_PV
/
GRANT EXECUTE ON GE_CARTA_10120_QT TO SISCEL_SELECT
/
