GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CARGOS_SOBRESCRITOS_TO TO SISCEL_VE
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CARGOS_SOBRESCRITOS_TO TO SISCEL_PV
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CARGOS_SOBRESCRITOS_TO TO SISCEL_FA
/
GRANT SELECT ON GE_CARGOS_SOBRESCRITOS_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_CARGOS_SOBRESCRITOS_TO TO SISCEL_ADMIN
/