GRANT EXECUTE ON GE_CARTA_PG TO CER_CPU
/
GRANT EXECUTE ON GE_CARTA_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_CARTA_PG TO SISCEL_CPU
/
GRANT EXECUTE ON GE_CARTA_PG TO SISCEL_PV
/
GRANT EXECUTE ON GE_CARTA_PG TO SISCEL_SELECT
/
