GRANT SELECT                            ON GE_DOCUMMOTIV_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_DOCUMMOTIV_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_DOCUMMOTIV_TO TO SISCEL_FA
/

