GRANT DELETE ON GE_EJECUTA_PROCESO_TD TO SISCEL_ADMIN
/
GRANT INSERT ON GE_EJECUTA_PROCESO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GE_EJECUTA_PROCESO_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON GE_EJECUTA_PROCESO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GE_EJECUTA_PROCESO_TD TO SISCEL_SELECT
/
GRANT SELECT ON GE_EJECUTA_PROCESO_TD TO SOLO_CONSULTA_SISCEL
/
