GRANT EXECUTE ON GE_EJECUTA_PERFILES_FN TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_EJECUTA_PERFILES_FN TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_EJECUTA_PERFILES_FN TO SISCEL_GE
/
GRANT EXECUTE ON GE_EJECUTA_PERFILES_FN TO SISCEL_SELECT
/
