GRANT EXECUTE ON GE_FN_TO_FORMATOCELULAR TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_TO_FORMATOCELULAR TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_TO_FORMATOCELULAR TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_TO_FORMATOCELULAR TO SISCEL_SELECT
/
