GRANT EXECUTE ON GE_FN_VALIDA_IDENTCLIE_TMM TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_VALIDA_IDENTCLIE_TMM TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_VALIDA_IDENTCLIE_TMM TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_VALIDA_IDENTCLIE_TMM TO SISCEL_SELECT
/
