GRANT EXECUTE ON GE_FN_ELIM_IDIOMA_ALT TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_ELIM_IDIOMA_ALT TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_ELIM_IDIOMA_ALT TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_ELIM_IDIOMA_ALT TO SISCEL_SELECT
/
