GRANT EXECUTE ON GE_FN_CONSISTENCIA_IDIOMA TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_CONSISTENCIA_IDIOMA TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_CONSISTENCIA_IDIOMA TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_CONSISTENCIA_IDIOMA TO SISCEL_SELECT
/
