GRANT EXECUTE ON GE_FN_IDIOMA_LOCAL TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_IDIOMA_LOCAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_IDIOMA_LOCAL TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_IDIOMA_LOCAL TO SISCEL_SELECT
/
GRANT EXECUTE ON GE_FN_IDIOMA_LOCAL TO TOL_SISCEL
/
