GRANT EXECUTE ON GE_FN_CONSUMOFOLIO_SCL TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_CONSUMOFOLIO_SCL TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_CONSUMOFOLIO_SCL TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_CONSUMOFOLIO_SCL TO SISCEL_SELECT
/
