GRANT SELECT                            ON GE_FACTORCLASIF_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_FACTORCLASIF_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_FACTORCLASIF_TD TO SISCEL_GA
/

