GRANT EXECUTE ON GE_FN_VALIDA_IDENTCLIE_MPR TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_VALIDA_IDENTCLIE_MPR TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_VALIDA_IDENTCLIE_MPR TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_VALIDA_IDENTCLIE_MPR TO SISCEL_SELECT
/
