GRANT EXECUTE ON GE_FN_FORMATEA_IDENTCLIE_TMC TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_FORMATEA_IDENTCLIE_TMC TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_FORMATEA_IDENTCLIE_TMC TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_FORMATEA_IDENTCLIE_TMC TO SISCEL_SELECT
/
