GRANT EXECUTE ON GE_FN_DIAS_HIBERNACION TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_DIAS_HIBERNACION TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_DIAS_HIBERNACION TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_DIAS_HIBERNACION TO SISCEL_SELECT
/
