GRANT EXECUTE ON GE_FN_GLOSA_IDIOMA TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_GLOSA_IDIOMA TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_GLOSA_IDIOMA TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_GLOSA_IDIOMA TO SISCEL_SELECT
/
