GRANT EXECUTE ON GE_FN_LARGO_DESIDIOMA TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_LARGO_DESIDIOMA TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_LARGO_DESIDIOMA TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_LARGO_DESIDIOMA TO SISCEL_SELECT
/
