GRANT EXECUTE ON GE_FN_OBTIENE_DIRCLIE TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_OBTIENE_DIRCLIE TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_OBTIENE_DIRCLIE TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_OBTIENE_DIRCLIE TO SISCEL_SELECT
/
