GRANT EXECUTE ON GE_FN_IDIOMA_CLIENTE TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_IDIOMA_CLIENTE TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_IDIOMA_CLIENTE TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_IDIOMA_CLIENTE TO SISCEL_SELECT
/
