GRANT EXECUTE ON GE_FN_DEVVALPARAM TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_DEVVALPARAM TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_DEVVALPARAM TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_DEVVALPARAM TO SISCEL_SELECT
/
