GRANT EXECUTE ON GE_FN_EJECUTA_RUTINA TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_EJECUTA_RUTINA TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_EJECUTA_RUTINA TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_EJECUTA_RUTINA TO SISCEL_SELECT
/
