GRANT EXECUTE ON GE_FN_CONVERSION_MONEDA TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_FN_CONVERSION_MONEDA TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_FN_CONVERSION_MONEDA TO SISCEL_GE
/
GRANT EXECUTE ON GE_FN_CONVERSION_MONEDA TO SISCEL_SELECT
/
