GRANT SELECT                            ON GE_JUSTDOCUM_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_JUSTDOCUM_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_JUSTDOCUM_TO TO SISCEL_FA
/

