GRANT SELECT                            ON GE_MTOPREAUTOCLI_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_MTOPREAUTOCLI_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_MTOPREAUTOCLI_TO TO SISCEL_GA
/

