GRANT SELECT                            ON GE_MTOPREAUTOCLI_TH TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_MTOPREAUTOCLI_TH TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_MTOPREAUTOCLI_TH TO SISCEL_GA
/

