GRANT EXECUTE ON GE_OVERRIDE_PG TO SISCEL_VE
/
GRANT EXECUTE ON GE_OVERRIDE_PG TO SISCEL_PV
/
GRANT EXECUTE ON GE_OVERRIDE_PG TO SISCEL_FA
/
GRANT EXECUTE ON GE_OVERRIDE_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON GE_OVERRIDE_PG TO SISCEL_ADMIN
/