GRANT DELETE ON GE_PLAZAS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON GE_PLAZAS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GE_PLAZAS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON GE_PLAZAS_TD TO SISCEL_ADMIN
/
GRANT DELETE ON GE_PLAZAS_TD TO SISCEL_GE
/
GRANT INSERT ON GE_PLAZAS_TD TO SISCEL_GE
/
GRANT SELECT ON GE_PLAZAS_TD TO SISCEL_GE
/
GRANT UPDATE ON GE_PLAZAS_TD TO SISCEL_GE
/
GRANT SELECT ON GE_PLAZAS_TD TO SISCEL_SELECT
/
GRANT SELECT ON GE_PLAZAS_TD TO SOLO_CONSULTA_SISCEL
/
