GRANT DELETE ON GE_PROCESOS_TD TO EBZ_SISCEL
/
GRANT INSERT ON GE_PROCESOS_TD TO EBZ_SISCEL
/
GRANT SELECT ON GE_PROCESOS_TD TO EBZ_SISCEL
/
GRANT UPDATE ON GE_PROCESOS_TD TO EBZ_SISCEL
/
GRANT DELETE ON GE_PROCESOS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON GE_PROCESOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GE_PROCESOS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON GE_PROCESOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GE_PROCESOS_TD TO SISCEL_SELECT
/
GRANT SELECT ON GE_PROCESOS_TD TO SOLO_CONSULTA_SISCEL
/
