GRANT EXECUTE ON GE_PR_MULTIIDIOMA_CATEGRECL TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_PR_MULTIIDIOMA_CATEGRECL TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_PR_MULTIIDIOMA_CATEGRECL TO SISCEL_GE
/
GRANT EXECUTE ON GE_PR_MULTIIDIOMA_CATEGRECL TO SISCEL_SELECT
/
