GRANT SELECT                            ON GE_PARAM_SERV_INT_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_PARAM_SERV_INT_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_PARAM_SERV_INT_TO TO SISCEL_GE
/

