GRANT SELECT                            ON GE_PUNTOACCESO_INT_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_PUNTOACCESO_INT_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_PUNTOACCESO_INT_TD TO SISCEL_GE
/

