GRANT EXECUTE ON GE_PR_INSPLANTILLAOBJETOS TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_PR_INSPLANTILLAOBJETOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_PR_INSPLANTILLAOBJETOS TO SISCEL_GE
/
GRANT EXECUTE ON GE_PR_INSPLANTILLAOBJETOS TO SISCEL_SELECT
/
