GRANT EXECUTE ON GE_PK_ARREGLOPR TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_PK_ARREGLOPR TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_PK_ARREGLOPR TO SISCEL_GE
/
GRANT EXECUTE ON GE_PK_ARREGLOPR TO SISCEL_SELECT
/
