GRANT EXECUTE ON GE_PAC_ARREGLOPR TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_PAC_ARREGLOPR TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_PAC_ARREGLOPR TO SISCEL_PV
/
GRANT EXECUTE ON GE_PAC_ARREGLOPR TO SISCEL_SELECT
/
