GRANT SELECT                            ON GE_PRESTACIONES_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_PRESTACIONES_TD TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON GE_PRESTACIONES_TD TO SISCEL_GE
/

