GRANT EXECUTE ON GE_PR_INSPLANTILLARUTINAS TO EBZ_SISCEL
/
GRANT EXECUTE ON GE_PR_INSPLANTILLARUTINAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_PR_INSPLANTILLARUTINAS TO SISCEL_GE
/
GRANT EXECUTE ON GE_PR_INSPLANTILLARUTINAS TO SISCEL_SELECT
/
