GRANT DELETE ON GE_RANGOS_TO TO SISCEL_ADMIN
/
GRANT INSERT ON GE_RANGOS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GE_RANGOS_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON GE_RANGOS_TO TO SISCEL_ADMIN
/
GRANT DELETE ON GE_RANGOS_TO TO SISCEL_GA
/
GRANT INSERT ON GE_RANGOS_TO TO SISCEL_GA
/
GRANT SELECT ON GE_RANGOS_TO TO SISCEL_GA
/
GRANT UPDATE ON GE_RANGOS_TO TO SISCEL_GA
/
GRANT SELECT ON GE_RANGOS_TO TO SISCEL_SELECT
/
GRANT SELECT ON GE_RANGOS_TO TO SOLO_CONSULTA_SISCEL
/
