GRANT EXECUTE ON GE_SEQ_CLIENTES_FN TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_SEQ_CLIENTES_FN TO SISCEL_GA
/
GRANT EXECUTE ON GE_SEQ_CLIENTES_FN TO SISCEL_GE
/
GRANT EXECUTE ON GE_SEQ_CLIENTES_FN TO SISCEL_PV
/
GRANT EXECUTE ON GE_SEQ_CLIENTES_FN TO SISCEL_SELECT
/
GRANT EXECUTE ON GE_SEQ_CLIENTES_FN TO SISCEL_VE
/
