GRANT SELECT ON GE_SEQ_USUARIOS TO EBZ_SISCEL
/
GRANT ALTER ON GE_SEQ_USUARIOS TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_USUARIOS TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_USUARIOS TO SISCEL_GE
/
GRANT SELECT ON GE_SEQ_USUARIOS TO SISCEL_SELECT
/
