GRANT SELECT ON GE_SEQ_PAQUETES TO EBZ_SISCEL
/
GRANT ALTER ON GE_SEQ_PAQUETES TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_PAQUETES TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_PAQUETES TO SISCEL_GE
/
GRANT SELECT ON GE_SEQ_PAQUETES TO SISCEL_SELECT
/
