GRANT SELECT ON GE_SEQ_DIRECCIONES TO EBZ_SISCEL
/
GRANT ALTER ON GE_SEQ_DIRECCIONES TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_DIRECCIONES TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_DIRECCIONES TO SISCEL_GA
/
GRANT SELECT ON GE_SEQ_DIRECCIONES TO SISCEL_GE
/
GRANT SELECT ON GE_SEQ_DIRECCIONES TO SISCEL_SELECT
/
