GRANT DELETE ON GE_SEG_LISTAPROC_TD TO SISCEL_ADMIN
/
GRANT INSERT ON GE_SEG_LISTAPROC_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEG_LISTAPROC_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON GE_SEG_LISTAPROC_TD TO SISCEL_ADMIN
/
GRANT DELETE ON GE_SEG_LISTAPROC_TD TO SISCEL_GE
/
GRANT INSERT ON GE_SEG_LISTAPROC_TD TO SISCEL_GE
/
GRANT SELECT ON GE_SEG_LISTAPROC_TD TO SISCEL_GE
/
GRANT UPDATE ON GE_SEG_LISTAPROC_TD TO SISCEL_GE
/
GRANT SELECT ON GE_SEG_LISTAPROC_TD TO SISCEL_SELECT
/
