GRANT SELECT ON GE_SEQ_CAMPO TO EBZ_SISCEL
/
GRANT ALTER ON GE_SEQ_CAMPO TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_CAMPO TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_CAMPO TO SISCEL_GE
/
GRANT SELECT ON GE_SEQ_CAMPO TO SISCEL_SELECT
/
