GRANT SELECT ON GE_SEQ_CONSULTASQL TO EBZ_SISCEL
/
GRANT ALTER ON GE_SEQ_CONSULTASQL TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_CONSULTASQL TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_CONSULTASQL TO SISCEL_GE
/
GRANT SELECT ON GE_SEQ_CONSULTASQL TO SISCEL_SELECT
/
