GRANT SELECT ON GE_SEQ_ESTADISTICA TO EBZ_SISCEL
/
GRANT ALTER ON GE_SEQ_ESTADISTICA TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_ESTADISTICA TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_ESTADISTICA TO SISCEL_GE
/
GRANT SELECT ON GE_SEQ_ESTADISTICA TO SISCEL_SELECT
/
