GRANT DELETE ON GE_SECTORES_USUARIOS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON GE_SECTORES_USUARIOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SECTORES_USUARIOS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON GE_SECTORES_USUARIOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SECTORES_USUARIOS_TD TO SISCEL_SELECT
/
GRANT SELECT ON GE_SECTORES_USUARIOS_TD TO SOLO_CONSULTA_SISCEL
/
