GRANT EXECUTE ON GE_SCHEDULER_PG TO MAS_REPORTES
/
GRANT EXECUTE ON GE_SCHEDULER_PG TO RA_SELECT_RO
/
GRANT EXECUTE ON GE_SCHEDULER_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_SCHEDULER_PG TO SISCEL_SELECT
/
