GRANT SELECT ON GE_SEQ_CONSULTA TO EBZ_SISCEL
/
GRANT ALTER ON GE_SEQ_CONSULTA TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_CONSULTA TO SISCEL_ADMIN
/
GRANT SELECT ON GE_SEQ_CONSULTA TO SISCEL_GE
/
GRANT SELECT ON GE_SEQ_CONSULTA TO SISCEL_SELECT
/
