GRANT EXECUTE ON GE_TIPIDENT_PG TO CER_CPU
/
GRANT EXECUTE ON GE_TIPIDENT_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_TIPIDENT_PG TO SISCEL_CPU
/
GRANT EXECUTE ON GE_TIPIDENT_PG TO SISCEL_GE
/
GRANT EXECUTE ON GE_TIPIDENT_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON GE_TIPIDENT_PG TO SISCEL_VE
/
