GRANT SELECT                                                           ON GE_USUARIO_APLIC_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE      ON GE_USUARIO_APLIC_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE      ON GE_USUARIO_APLIC_TD TO SISCEL_GA
/

