GRANT EXECUTE ON GE_VALIDACIONES_PG TO FAC_SISCEL
/
GRANT EXECUTE ON GE_VALIDACIONES_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GE_VALIDACIONES_PG TO SISCEL_GE
/
GRANT EXECUTE ON GE_VALIDACIONES_PG TO SISCEL_SELECT
/
