GRANT DELETE ON GED_PARAMETROS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON GED_PARAMETROS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GED_PARAMETROS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON GED_PARAMETROS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON GED_PARAMETROS_TD TO SISCEL_SELECT
/
GRANT SELECT ON GED_PARAMETROS TO MAS_PRODUCT_DML
/