GRANT ALTER ON GES_ERR_EVENTOS TO EBZ_SISCEL
/
GRANT SELECT ON GES_ERR_EVENTOS TO EBZ_SISCEL
/
GRANT SELECT ON GES_ERR_EVENTOS TO SISCEL_ADMIN
/
GRANT SELECT ON GES_ERR_EVENTOS TO SISCEL_GE
/
GRANT SELECT ON GES_ERR_EVENTOS TO SISCEL_SELECT
/
