GRANT ALTER ON GES_ERR_GENERAL TO EBZ_SISCEL
/
GRANT SELECT ON GES_ERR_GENERAL TO EBZ_SISCEL
/
GRANT SELECT ON GES_ERR_GENERAL TO SISCEL_ADMIN
/
GRANT SELECT ON GES_ERR_GENERAL TO SISCEL_GE
/
GRANT SELECT ON GES_ERR_GENERAL TO SISCEL_SELECT
/
