GRANT EXECUTE ON GR_PAC_ARPU_CONTRATO TO EBZ_SISCEL
/
GRANT EXECUTE ON GR_PAC_ARPU_CONTRATO TO SISCEL_ADMIN
/
GRANT EXECUTE ON GR_PAC_ARPU_CONTRATO TO SISCEL_GR
/
GRANT EXECUTE ON GR_PAC_ARPU_CONTRATO TO SISCEL_SELECT
/
