GRANT SELECT ON GR_SEQ_AUDITORIA TO EBZ_SISCEL
/
GRANT SELECT ON GR_SEQ_AUDITORIA TO SISCEL_ADMIN
/
GRANT SELECT ON GR_SEQ_AUDITORIA TO SISCEL_GR
/
GRANT SELECT ON GR_SEQ_AUDITORIA TO SISCEL_SELECT
/
