GRANT DELETE ON GRT_ORDSERV TO SISCEL_ADMIN
/
GRANT INSERT ON GRT_ORDSERV TO SISCEL_ADMIN
/
GRANT SELECT ON GRT_ORDSERV TO SISCEL_ADMIN
/
GRANT UPDATE ON GRT_ORDSERV TO SISCEL_ADMIN
/
GRANT DELETE ON GRT_ORDSERV TO SISCEL_GR
/
GRANT INSERT ON GRT_ORDSERV TO SISCEL_GR
/
GRANT SELECT ON GRT_ORDSERV TO SISCEL_GR
/
GRANT UPDATE ON GRT_ORDSERV TO SISCEL_GR
/
GRANT SELECT ON GRT_ORDSERV TO SISCEL_SELECT
/
GRANT SELECT ON GRT_ORDSERV TO SOLO_CONSULTA_SISCEL
/
