GRANT SELECT ON GSM_SEQ_SECIONES_ARCHIVO_SQ TO EBZ_SISCEL
/
GRANT SELECT ON GSM_SEQ_SECIONES_ARCHIVO_SQ TO SISCEL_ADMIN
/
GRANT SELECT ON GSM_SEQ_SECIONES_ARCHIVO_SQ TO SISCEL_GSM
/
GRANT SELECT ON GSM_SEQ_SECIONES_ARCHIVO_SQ TO SISCEL_SELECT
/
