GRANT SELECT ON GSM_HLR_SIMCARD_VW TO EBZ_SISCEL
/
GRANT DELETE ON GSM_HLR_SIMCARD_VW TO SISCEL_ADMIN
/
GRANT INSERT ON GSM_HLR_SIMCARD_VW TO SISCEL_ADMIN
/
GRANT SELECT ON GSM_HLR_SIMCARD_VW TO SISCEL_ADMIN
/
GRANT UPDATE ON GSM_HLR_SIMCARD_VW TO SISCEL_ADMIN
/
GRANT SELECT ON GSM_HLR_SIMCARD_VW TO SISCEL_GSM
/
GRANT SELECT ON GSM_HLR_SIMCARD_VW TO SISCEL_SELECT
/
GRANT SELECT ON GSM_HLR_SIMCARD_VW TO SOLO_CONSULTA_SISCEL
/
