GRANT SELECT ON GSM_SEQ_RANGOS_SQ TO EBZ_SISCEL
/
GRANT SELECT ON GSM_SEQ_RANGOS_SQ TO SISCEL_ADMIN
/
GRANT SELECT ON GSM_SEQ_RANGOS_SQ TO SISCEL_GSM
/
GRANT SELECT ON GSM_SEQ_RANGOS_SQ TO SISCEL_SELECT
/
