GRANT EXECUTE ON GSM_RANGOS_PREFIJOS TO EBZ_SISCEL
/
GRANT EXECUTE ON GSM_RANGOS_PREFIJOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON GSM_RANGOS_PREFIJOS TO SISCEL_GSM
/
GRANT EXECUTE ON GSM_RANGOS_PREFIJOS TO SISCEL_SELECT
/
