GRANT DELETE ON HIST_COM_CDMA TO PUBLIC
/
GRANT INSERT ON HIST_COM_CDMA TO PUBLIC
/
GRANT SELECT ON HIST_COM_CDMA TO PUBLIC
/
GRANT UPDATE ON HIST_COM_CDMA TO PUBLIC
/
GRANT SELECT ON HIST_COM_CDMA TO SOLO_CONSULTA_SISCEL
/
