GRANT DELETE ON HIST_MOV_CDMA TO PUBLIC
/
GRANT INSERT ON HIST_MOV_CDMA TO PUBLIC
/
GRANT SELECT ON HIST_MOV_CDMA TO PUBLIC
/
GRANT UPDATE ON HIST_MOV_CDMA TO PUBLIC
/
GRANT SELECT ON HIST_MOV_CDMA TO SOLO_CONSULTA_SISCEL
/
