GRANT DELETE ON IC_INTERFAZSERSUPL_TO TO SISCEL_ADMIN
/
GRANT INSERT ON IC_INTERFAZSERSUPL_TO TO SISCEL_ADMIN
/
GRANT SELECT ON IC_INTERFAZSERSUPL_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON IC_INTERFAZSERSUPL_TO TO SISCEL_ADMIN
/
GRANT DELETE ON IC_INTERFAZSERSUPL_TO TO SISCEL_IC
/
GRANT INSERT ON IC_INTERFAZSERSUPL_TO TO SISCEL_IC
/
GRANT SELECT ON IC_INTERFAZSERSUPL_TO TO SISCEL_IC
/
GRANT UPDATE ON IC_INTERFAZSERSUPL_TO TO SISCEL_IC
/
GRANT SELECT ON IC_INTERFAZSERSUPL_TO TO SISCEL_SELECT
/
