GRANT EXECUTE ON IC_P_TRUNC_ICGPREPAGO TO EBZ_SISCEL
/
GRANT EXECUTE ON IC_P_TRUNC_ICGPREPAGO TO SISCEL_ADMIN
/
GRANT EXECUTE ON IC_P_TRUNC_ICGPREPAGO TO SISCEL_IC
/
GRANT EXECUTE ON IC_P_TRUNC_ICGPREPAGO TO SISCEL_SELECT
/
