GRANT EXECUTE ON IC_PR_PENALIZACION TO QUETOL
/
GRANT EXECUTE ON IC_PR_PENALIZACION TO SISCEL_ADMIN
/
GRANT EXECUTE ON IC_PR_PENALIZACION TO SISCEL_CO
/
GRANT EXECUTE ON IC_PR_PENALIZACION TO SISCEL_SELECT
/
