GRANT EXECUTE ON IC_PR_MULTIIDIOMA_MENSAJES TO EBZ_SISCEL
/
GRANT EXECUTE ON IC_PR_MULTIIDIOMA_MENSAJES TO SISCEL_ADMIN
/
GRANT EXECUTE ON IC_PR_MULTIIDIOMA_MENSAJES TO SISCEL_IC
/
GRANT EXECUTE ON IC_PR_MULTIIDIOMA_MENSAJES TO SISCEL_SELECT
/
