GRANT EXECUTE ON IC_PROVISION_VENTA_PG TO APP_ADM;

GRANT EXECUTE ON IC_PROVISION_VENTA_PG TO ICON;

GRANT EXECUTE ON IC_PROVISION_VENTA_PG TO MAS_ADMIN_RO;

GRANT EXECUTE ON IC_PROVISION_VENTA_PG TO MAS_APPLICATION_RO;

GRANT EXECUTE ON IC_PROVISION_VENTA_PG TO MAS_SELECT_RO;

GRANT EXECUTE ON IC_PROVISION_VENTA_PG TO SISCEL;

GRANT EXECUTE ON IC_PROVISION_VENTA_PG TO SISCEL_ADMIN;

GRANT EXECUTE ON IC_PROVISION_VENTA_PG TO SISCEL_PV;

GRANT EXECUTE ON IC_PROVISION_VENTA_PG TO SISCEL_SELECT;