GRANT EXECUTE ON IC_P_TRUNCHLR TO EBZ_SISCEL
/
GRANT EXECUTE ON IC_P_TRUNCHLR TO OPS$CENTRAL
/
GRANT EXECUTE ON IC_P_TRUNCHLR TO OPS$XPCENTRA
/
GRANT EXECUTE ON IC_P_TRUNCHLR TO SISCEL_ADMIN
/
GRANT EXECUTE ON IC_P_TRUNCHLR TO SISCEL_SELECT
/
