GRANT EXECUTE ON IC_PARAM_ATLANTIDA_PG TO CER_CPU
/
GRANT EXECUTE ON IC_PARAM_ATLANTIDA_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON IC_PARAM_ATLANTIDA_PG TO SISCEL_IC
/
GRANT EXECUTE ON IC_PARAM_ATLANTIDA_PG TO SISCEL_SELECT
/
