GRANT EXECUTE ON IC_PKG_PARAMETROS TO EBZ_SISCEL
/
GRANT EXECUTE ON IC_PKG_PARAMETROS TO SISCEL_ADMIN
/
GRANT EXECUTE ON IC_PKG_PARAMETROS TO SISCEL_IC
/
GRANT EXECUTE ON IC_PKG_PARAMETROS TO SISCEL_SELECT
/
