GRANT DELETE ON IC_SECTRANSACCION_TH TO SISCEL_ADMIN
/
GRANT INSERT ON IC_SECTRANSACCION_TH TO SISCEL_ADMIN
/
GRANT SELECT ON IC_SECTRANSACCION_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON IC_SECTRANSACCION_TH TO SISCEL_ADMIN
/
GRANT DELETE ON IC_SECTRANSACCION_TH TO SISCEL_IC
/
GRANT INSERT ON IC_SECTRANSACCION_TH TO SISCEL_IC
/
GRANT SELECT ON IC_SECTRANSACCION_TH TO SISCEL_IC
/
GRANT UPDATE ON IC_SECTRANSACCION_TH TO SISCEL_IC
/
GRANT SELECT ON IC_SECTRANSACCION_TH TO SISCEL_SELECT
/
