GRANT SELECT ON ICB_SEQ_NUMMOV TO EBZ_SISCEL
/
GRANT ALTER ON ICB_SEQ_NUMMOV TO SISCEL_ADMIN
/
GRANT SELECT ON ICB_SEQ_NUMMOV TO SISCEL_ADMIN
/
GRANT SELECT ON ICB_SEQ_NUMMOV TO SISCEL_IC
/
GRANT SELECT ON ICB_SEQ_NUMMOV TO SISCEL_SELECT
/
