GRANT SELECT ON ICC_SEQ_NUMMOVPIN TO EBZ_SISCEL
/
GRANT SELECT ON ICC_SEQ_NUMMOVPIN TO SISCEL_ADMIN
/
GRANT SELECT ON ICC_SEQ_NUMMOVPIN TO SISCEL_IC
/
GRANT SELECT ON ICC_SEQ_NUMMOVPIN TO SISCEL_SELECT
/
