GRANT DELETE ON ICC_RENOTIFICACION TO SISCEL_ADMIN
/
GRANT INSERT ON ICC_RENOTIFICACION TO SISCEL_ADMIN
/
GRANT SELECT ON ICC_RENOTIFICACION TO SISCEL_ADMIN
/
GRANT UPDATE ON ICC_RENOTIFICACION TO SISCEL_ADMIN
/
GRANT SELECT ON ICC_RENOTIFICACION TO SISCEL_SELECT
/
GRANT SELECT ON ICC_RENOTIFICACION TO SOLO_CONSULTA_SISCEL
/
