GRANT DELETE ON ICC_USUARIOIP_TD TO SISCEL_ADMIN
/
GRANT INSERT ON ICC_USUARIOIP_TD TO SISCEL_ADMIN
/
GRANT SELECT ON ICC_USUARIOIP_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON ICC_USUARIOIP_TD TO SISCEL_ADMIN
/
GRANT SELECT ON ICC_USUARIOIP_TD TO SISCEL_SELECT
/
GRANT SELECT ON ICC_USUARIOIP_TD TO SOLO_CONSULTA_SISCEL
/
