GRANT DELETE ON ICC_SWITCH_TO TO SISCEL_ADMIN
/
GRANT INSERT ON ICC_SWITCH_TO TO SISCEL_ADMIN
/
GRANT SELECT ON ICC_SWITCH_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON ICC_SWITCH_TO TO SISCEL_ADMIN
/
GRANT SELECT ON ICC_SWITCH_TO TO SISCEL_SELECT
/
GRANT SELECT ON ICC_SWITCH_TO TO SOLO_CONSULTA_SISCEL
/
