GRANT DELETE ON ICC_NOTIFICACION TO SISCEL_ADMIN
/
GRANT INSERT ON ICC_NOTIFICACION TO SISCEL_ADMIN
/
GRANT SELECT ON ICC_NOTIFICACION TO SISCEL_ADMIN
/
GRANT UPDATE ON ICC_NOTIFICACION TO SISCEL_ADMIN
/
GRANT SELECT ON ICC_NOTIFICACION TO SISCEL_SELECT
/
GRANT SELECT ON ICC_NOTIFICACION TO SOLO_CONSULTA_SISCEL
/
