GRANT ALTER ON ICC_SEQ_NUMOOSS TO EBZ_SISCEL
/
GRANT SELECT ON ICC_SEQ_NUMOOSS TO EBZ_SISCEL
/
GRANT SELECT ON ICC_SEQ_NUMOOSS TO SISCEL_ADMIN
/
GRANT SELECT ON ICC_SEQ_NUMOOSS TO SISCEL_IC
/
GRANT SELECT ON ICC_SEQ_NUMOOSS TO SISCEL_SELECT
/
