GRANT DELETE ON ICG_HLRS TO SISCEL_ADMIN
/
GRANT INSERT ON ICG_HLRS TO SISCEL_ADMIN
/
GRANT SELECT ON ICG_HLRS TO SISCEL_ADMIN
/
GRANT UPDATE ON ICG_HLRS TO SISCEL_ADMIN
/
GRANT DELETE ON ICG_HLRS TO SISCEL_IC
/
GRANT INSERT ON ICG_HLRS TO SISCEL_IC
/
GRANT SELECT ON ICG_HLRS TO SISCEL_IC
/
GRANT UPDATE ON ICG_HLRS TO SISCEL_IC
/
GRANT SELECT ON ICG_HLRS TO SISCEL_SELECT
/
GRANT SELECT ON ICG_HLRS TO SOLO_CONSULTA_SISCEL
/
