GRANT SELECT ON ICM_SEQ_NUMMOV TO EBZ_SISCEL
/
GRANT ALTER ON ICM_SEQ_NUMMOV TO SISCEL_ADMIN
/
GRANT SELECT ON ICM_SEQ_NUMMOV TO SISCEL_ADMIN
/
GRANT SELECT ON ICM_SEQ_NUMMOV TO SISCEL_IC
/
GRANT SELECT ON ICM_SEQ_NUMMOV TO SISCEL_SELECT
/
