GRANT SELECT ON ICR_SEQ_NUMMOV TO EBZ_SISCEL
/
GRANT ALTER ON ICR_SEQ_NUMMOV TO SISCEL_ADMIN
/
GRANT SELECT ON ICR_SEQ_NUMMOV TO SISCEL_ADMIN
/
GRANT SELECT ON ICR_SEQ_NUMMOV TO SISCEL_IC
/
GRANT SELECT ON ICR_SEQ_NUMMOV TO SISCEL_SELECT
/
