GRANT DELETE ON ICT_CAMPOS_MOTIVOS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON ICT_CAMPOS_MOTIVOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON ICT_CAMPOS_MOTIVOS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON ICT_CAMPOS_MOTIVOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON ICT_CAMPOS_MOTIVOS_TD TO SISCEL_SELECT
/
