GRANT DELETE ON ICT_REGISTRO_CONSULTAS_TO TO SISCEL_ADMIN
/
GRANT INSERT ON ICT_REGISTRO_CONSULTAS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON ICT_REGISTRO_CONSULTAS_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON ICT_REGISTRO_CONSULTAS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON ICT_REGISTRO_CONSULTAS_TO TO SISCEL_SELECT
/
