GRANT DELETE ON ICT_MOTIVOS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON ICT_MOTIVOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON ICT_MOTIVOS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON ICT_MOTIVOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON ICT_MOTIVOS_TD TO SISCEL_SELECT
/
