GRANT DELETE ON INGRESO_MERC_AUX TO PUBLIC
/
GRANT INSERT ON INGRESO_MERC_AUX TO PUBLIC
/
GRANT SELECT ON INGRESO_MERC_AUX TO PUBLIC
/
GRANT UPDATE ON INGRESO_MERC_AUX TO PUBLIC
/
GRANT SELECT ON INGRESO_MERC_AUX TO SOLO_CONSULTA_SISCEL
/
