GRANT EXECUTE ON NP_ESTADOFLUJOPEDIDO_FN TO EBZ_SISCEL
/
GRANT EXECUTE ON NP_ESTADOFLUJOPEDIDO_FN TO SISCEL_ADMIN
/
GRANT EXECUTE ON NP_ESTADOFLUJOPEDIDO_FN TO SISCEL_IC
/
GRANT EXECUTE ON NP_ESTADOFLUJOPEDIDO_FN TO SISCEL_SELECT
/
