GRANT EXECUTE ON P_ACTUALIZA_CLASERV TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ACTUALIZA_CLASERV TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ACTUALIZA_CLASERV TO SISCEL_GA
/
GRANT EXECUTE ON P_ACTUALIZA_CLASERV TO SISCEL_SELECT
/
