GRANT EXECUTE ON P_ACTUALIZA_CARGO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ACTUALIZA_CARGO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ACTUALIZA_CARGO TO SISCEL_GA
/
GRANT EXECUTE ON P_ACTUALIZA_CARGO TO SISCEL_SELECT
/
