GRANT EXECUTE ON P_ACTUALIZA_NOCICLOCLI TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ACTUALIZA_NOCICLOCLI TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ACTUALIZA_NOCICLOCLI TO SISCEL_GA
/
GRANT EXECUTE ON P_ACTUALIZA_NOCICLOCLI TO SISCEL_SELECT
/
