GRANT EXECUTE ON P_ACTUALIZA_CANTIDAD TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ACTUALIZA_CANTIDAD TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ACTUALIZA_CANTIDAD TO SISCEL_GA
/
GRANT EXECUTE ON P_ACTUALIZA_CANTIDAD TO SISCEL_SELECT
/
