GRANT EXECUTE ON P_ACTUALIZA_ESTADO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ACTUALIZA_ESTADO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ACTUALIZA_ESTADO TO SISCEL_GE
/
GRANT EXECUTE ON P_ACTUALIZA_ESTADO TO SISCEL_SELECT
/
