GRANT EXECUTE ON P_AL_COMPSERIES TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_COMPSERIES TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_COMPSERIES TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_COMPSERIES TO SISCEL_SELECT
/
