GRANT EXECUTE ON P_AL_ANULA_GUIA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_ANULA_GUIA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_ANULA_GUIA TO SISCEL_GA
/
GRANT EXECUTE ON P_AL_ANULA_GUIA TO SISCEL_SELECT
/
