GRANT EXECUTE ON P_AL_DESASIGNA_NUMEROS_ALMACEN TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_DESASIGNA_NUMEROS_ALMACEN TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_DESASIGNA_NUMEROS_ALMACEN TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_DESASIGNA_NUMEROS_ALMACEN TO SISCEL_SELECT
/
