GRANT EXECUTE ON P_ALTA_CELULAR_PREPAGO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ALTA_CELULAR_PREPAGO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ALTA_CELULAR_PREPAGO TO SISCEL_PV
/
GRANT EXECUTE ON P_ALTA_CELULAR_PREPAGO TO SISCEL_SELECT
/
