GRANT EXECUTE ON P_AL_INTERFAZ_CLUB TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_INTERFAZ_CLUB TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_INTERFAZ_CLUB TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_INTERFAZ_CLUB TO SISCEL_SELECT
/
