GRANT EXECUTE ON P_AL_HIST_TRASPASOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_HIST_TRASPASOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_HIST_TRASPASOS TO SISCEL_GE
/
GRANT EXECUTE ON P_AL_HIST_TRASPASOS TO SISCEL_SELECT
/
