GRANT EXECUTE ON P_AL_TARJETAS_CRON TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_TARJETAS_CRON TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_TARJETAS_CRON TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_TARJETAS_CRON TO SISCEL_SELECT
/
