GRANT EXECUTE ON P_AL_CONS_STOCK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_CONS_STOCK TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_AL_CONS_STOCK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_CONS_STOCK TO SISCEL_SELECT
/
