GRANT EXECUTE ON P_AL_LIBERA_NUMERO_ALM TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_LIBERA_NUMERO_ALM TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_LIBERA_NUMERO_ALM TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_LIBERA_NUMERO_ALM TO SISCEL_SELECT
/
