GRANT EXECUTE ON P_AL_TRATAMIENTO_MASIVO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_TRATAMIENTO_MASIVO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_TRATAMIENTO_MASIVO TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_TRATAMIENTO_MASIVO TO SISCEL_SELECT
/
