GRANT EXECUTE ON P_AL_MANUAL_NRO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_MANUAL_NRO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_MANUAL_NRO TO SISCEL_GA
/
GRANT EXECUTE ON P_AL_MANUAL_NRO TO SISCEL_SELECT
/
