GRANT EXECUTE ON P_AL_DESACTIVA_CENTRAL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_DESACTIVA_CENTRAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_DESACTIVA_CENTRAL TO SISCEL_GA
/
GRANT EXECUTE ON P_AL_DESACTIVA_CENTRAL TO SISCEL_SELECT
/
