GRANT EXECUTE ON P_AL_MANUAL_ALM TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_MANUAL_ALM TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_MANUAL_ALM TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_MANUAL_ALM TO SISCEL_SELECT
/
