GRANT EXECUTE ON P_ALTA_INFACRENT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ALTA_INFACRENT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ALTA_INFACRENT TO SISCEL_GA
/
GRANT EXECUTE ON P_ALTA_INFACRENT TO SISCEL_SELECT
/
