GRANT EXECUTE ON P_ALTA_INTARBEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ALTA_INTARBEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ALTA_INTARBEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_ALTA_INTARBEEP TO SISCEL_SELECT
/
