GRANT EXECUTE ON P_AL_ASIGNA_NUMERO_AL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_ASIGNA_NUMERO_AL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_ASIGNA_NUMERO_AL TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_ASIGNA_NUMERO_AL TO SISCEL_SELECT
/
