GRANT EXECUTE ON P_ALTA_INTARTREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ALTA_INTARTREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ALTA_INTARTREK TO SISCEL_GA
/
GRANT EXECUTE ON P_ALTA_INTARTREK TO SISCEL_SELECT
/
