GRANT EXECUTE ON P_AL_ACTIVA_CENTRAL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_ACTIVA_CENTRAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_ACTIVA_CENTRAL TO SISCEL_GA
/
GRANT EXECUTE ON P_AL_ACTIVA_CENTRAL TO SISCEL_SELECT
/
