GRANT EXECUTE ON P_ALTA_INFACTREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ALTA_INFACTREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ALTA_INFACTREK TO SISCEL_GA
/
GRANT EXECUTE ON P_ALTA_INFACTREK TO SISCEL_SELECT
/
