GRANT EXECUTE ON P_AL_AFUP_CABNUME TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_AFUP_CABNUME TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_AFUP_CABNUME TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_AFUP_CABNUME TO SISCEL_SELECT
/
