GRANT EXECUTE ON P_ALTA_CICLOCLI TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ALTA_CICLOCLI TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ALTA_CICLOCLI TO SISCEL_GA
/
GRANT EXECUTE ON P_ALTA_CICLOCLI TO SISCEL_SELECT
/
