GRANT EXECUTE ON P_ALTA_INFACBEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ALTA_INFACBEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ALTA_INFACBEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_ALTA_INFACBEEP TO SISCEL_SELECT
/
