GRANT EXECUTE ON P_AL_VEN_DIS_WEB_NEW TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_VEN_DIS_WEB_NEW TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_VEN_DIS_WEB_NEW TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_VEN_DIS_WEB_NEW TO SISCEL_SELECT
/
