GRANT EXECUTE ON P_ALTA_INFACROAVIS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ALTA_INFACROAVIS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ALTA_INFACROAVIS TO SISCEL_GA
/
GRANT EXECUTE ON P_ALTA_INFACROAVIS TO SISCEL_SELECT
/
