GRANT EXECUTE ON P_AL_INTERFAZ_RECEPCION TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_INTERFAZ_RECEPCION TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_INTERFAZ_RECEPCION TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_INTERFAZ_RECEPCION TO SISCEL_SELECT
/
