GRANT EXECUTE ON P_ALTA_CELULAR_SAV TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ALTA_CELULAR_SAV TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ALTA_CELULAR_SAV TO SISCEL_GA
/
GRANT EXECUTE ON P_ALTA_CELULAR_SAV TO SISCEL_SELECT
/
