GRANT EXECUTE ON P_ALTA_CELULAR_OFI TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ALTA_CELULAR_OFI TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ALTA_CELULAR_OFI TO SISCEL_GA
/
GRANT EXECUTE ON P_ALTA_CELULAR_OFI TO SISCEL_SELECT
/
