GRANT EXECUTE ON P_ALTA_INTAROACOM TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ALTA_INTAROACOM TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ALTA_INTAROACOM TO SISCEL_GA
/
GRANT EXECUTE ON P_ALTA_INTAROACOM TO SISCEL_SELECT
/
