GRANT EXECUTE ON P_AL_ASIGNA_NUMERO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_ASIGNA_NUMERO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_ASIGNA_NUMERO TO SISCEL_GA
/
GRANT EXECUTE ON P_AL_ASIGNA_NUMERO TO SISCEL_SELECT
/
