GRANT EXECUTE ON P_AL_NUMERA_CEL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_AL_NUMERA_CEL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_AL_NUMERA_CEL TO SISCEL_AL
/
GRANT EXECUTE ON P_AL_NUMERA_CEL TO SISCEL_GA
/
GRANT EXECUTE ON P_AL_NUMERA_CEL TO SISCEL_SELECT
/
