GRANT EXECUTE ON P_ANULA_BAJAABO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ANULA_BAJAABO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ANULA_BAJAABO TO SISCEL_GA
/
GRANT EXECUTE ON P_ANULA_BAJAABO TO SISCEL_SELECT
/
