GRANT EXECUTE ON P_ASIGNA_UN_NUMERO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ASIGNA_UN_NUMERO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ASIGNA_UN_NUMERO TO SISCEL_GA
/
GRANT EXECUTE ON P_ASIGNA_UN_NUMERO TO SISCEL_SELECT
/
