GRANT EXECUTE ON P_BAJA_ABOROACOM TO EBZ_SISCEL
/
GRANT EXECUTE ON P_BAJA_ABOROACOM TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_BAJA_ABOROACOM TO SISCEL_GA
/
GRANT EXECUTE ON P_BAJA_ABOROACOM TO SISCEL_SELECT
/
