GRANT EXECUTE ON P_BAJA_ABOROAVIS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_BAJA_ABOROAVIS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_BAJA_ABOROAVIS TO SISCEL_GA
/
GRANT EXECUTE ON P_BAJA_ABOROAVIS TO SISCEL_SELECT
/
