GRANT EXECUTE ON P_BAJA_ABONADORENT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_BAJA_ABONADORENT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_BAJA_ABONADORENT TO SISCEL_GA
/
GRANT EXECUTE ON P_BAJA_ABONADORENT TO SISCEL_SELECT
/
