GRANT EXECUTE ON P_BAJA_ABONADOCEN TO EBZ_SISCEL
/
GRANT EXECUTE ON P_BAJA_ABONADOCEN TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_BAJA_ABONADOCEN TO SISCEL_GA
/
GRANT EXECUTE ON P_BAJA_ABONADOCEN TO SISCEL_SELECT
/
