GRANT EXECUTE ON P_BAJAMOROSIDAD_COMODATO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_BAJAMOROSIDAD_COMODATO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_BAJAMOROSIDAD_COMODATO TO SISCEL_CO
/
GRANT EXECUTE ON P_BAJAMOROSIDAD_COMODATO TO SISCEL_GA
/
GRANT EXECUTE ON P_BAJAMOROSIDAD_COMODATO TO SISCEL_SELECT
/
