GRANT EXECUTE ON P_BORRA_INFARENT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_BORRA_INFARENT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_BORRA_INFARENT TO SISCEL_GA
/
GRANT EXECUTE ON P_BORRA_INFARENT TO SISCEL_SELECT
/
