GRANT EXECUTE ON P_BORRA_NOCICLOCLI TO EBZ_SISCEL
/
GRANT EXECUTE ON P_BORRA_NOCICLOCLI TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_BORRA_NOCICLOCLI TO SISCEL_GA
/
GRANT EXECUTE ON P_BORRA_NOCICLOCLI TO SISCEL_SELECT
/
