GRANT EXECUTE ON P_BORRA_ESTADIAS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_BORRA_ESTADIAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_BORRA_ESTADIAS TO SISCEL_GA
/
GRANT EXECUTE ON P_BORRA_ESTADIAS TO SISCEL_SELECT
/
