GRANT EXECUTE ON P_BORRA_FACONCEPTOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_BORRA_FACONCEPTOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_BORRA_FACONCEPTOS TO SISCEL_GA
/
GRANT EXECUTE ON P_BORRA_FACONCEPTOS TO SISCEL_SELECT
/
