GRANT EXECUTE ON P_BUSCA_CELULAR TO EBZ_SISCEL
/
GRANT EXECUTE ON P_BUSCA_CELULAR TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_BUSCA_CELULAR TO SISCEL_GA
/
GRANT EXECUTE ON P_BUSCA_CELULAR TO SISCEL_SELECT
/
