GRANT EXECUTE ON P_CAMBIO_PLANSERV TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CAMBIO_PLANSERV TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CAMBIO_PLANSERV TO SISCEL_GA
/
GRANT EXECUTE ON P_CAMBIO_PLANSERV TO SISCEL_SELECT
/
