GRANT EXECUTE ON P_CAMBIO_PLANCOM TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CAMBIO_PLANCOM TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CAMBIO_PLANCOM TO SISCEL_GA
/
GRANT EXECUTE ON P_CAMBIO_PLANCOM TO SISCEL_SELECT
/
