GRANT EXECUTE ON P_CARGA_SERVSUPLABO_PERFIL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CARGA_SERVSUPLABO_PERFIL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CARGA_SERVSUPLABO_PERFIL TO SISCEL_GA
/
GRANT EXECUTE ON P_CARGA_SERVSUPLABO_PERFIL TO SISCEL_SELECT
/
