GRANT EXECUTE ON P_CAMBIO_PORTADOR TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CAMBIO_PORTADOR TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CAMBIO_PORTADOR TO SISCEL_GA
/
GRANT EXECUTE ON P_CAMBIO_PORTADOR TO SISCEL_SELECT
/
