GRANT EXECUTE ON P_CAMBIO_GRUPOTAR TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CAMBIO_GRUPOTAR TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CAMBIO_GRUPOTAR TO SISCEL_GA
/
GRANT EXECUTE ON P_CAMBIO_GRUPOTAR TO SISCEL_SELECT
/
