GRANT EXECUTE ON P_CAMBIO_CONCEPTO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CAMBIO_CONCEPTO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CAMBIO_CONCEPTO TO SISCEL_GA
/
GRANT EXECUTE ON P_CAMBIO_CONCEPTO TO SISCEL_SELECT
/
