GRANT EXECUTE ON P_CAMBIO_GRPSERV TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CAMBIO_GRPSERV TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CAMBIO_GRPSERV TO SISCEL_GA
/
GRANT EXECUTE ON P_CAMBIO_GRPSERV TO SISCEL_SELECT
/
