GRANT EXECUTE ON P_CAMBIO_PLANCOMRENT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CAMBIO_PLANCOMRENT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CAMBIO_PLANCOMRENT TO SISCEL_GA
/
GRANT EXECUTE ON P_CAMBIO_PLANCOMRENT TO SISCEL_SELECT
/
