GRANT EXECUTE ON P_CERRAR_SUSPENSION TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CERRAR_SUSPENSION TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CERRAR_SUSPENSION TO SISCEL_GA
/
GRANT EXECUTE ON P_CERRAR_SUSPENSION TO SISCEL_SELECT
/
