GRANT EXECUTE ON P_CIERRA_SERVICIOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CIERRA_SERVICIOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CIERRA_SERVICIOS TO SISCEL_GA
/
GRANT EXECUTE ON P_CIERRA_SERVICIOS TO SISCEL_SELECT
/
