GRANT EXECUTE ON P_CLOSERV_TERMINAL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CLOSERV_TERMINAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CLOSERV_TERMINAL TO SISCEL_GA
/
GRANT EXECUTE ON P_CLOSERV_TERMINAL TO SISCEL_SELECT
/
