GRANT EXECUTE ON P_CONFIRMAR_VENTA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CONFIRMAR_VENTA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CONFIRMAR_VENTA TO SISCEL_GA
/
GRANT EXECUTE ON P_CONFIRMAR_VENTA TO SISCEL_SELECT
/
