GRANT EXECUTE ON P_CONCEPTO_DESCUENTO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CONCEPTO_DESCUENTO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CONCEPTO_DESCUENTO TO SISCEL_GA
/
GRANT EXECUTE ON P_CONCEPTO_DESCUENTO TO SISCEL_SELECT
/
