GRANT EXECUTE ON P_CO_SUPERSUSPEN TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CO_SUPERSUSPEN TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CO_SUPERSUSPEN TO SISCEL_GA
/
GRANT EXECUTE ON P_CO_SUPERSUSPEN TO SISCEL_SELECT
/
