GRANT EXECUTE ON P_CONVERTIR_PRECIO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CONVERTIR_PRECIO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CONVERTIR_PRECIO TO SISCEL_GA
/
GRANT EXECUTE ON P_CONVERTIR_PRECIO TO SISCEL_SELECT
/
