GRANT EXECUTE ON P_CREDITO_MOROSIDAD TO EBZ_SISCEL
/
GRANT EXECUTE ON P_CREDITO_MOROSIDAD TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_CREDITO_MOROSIDAD TO SISCEL_GA
/
GRANT EXECUTE ON P_CREDITO_MOROSIDAD TO SISCEL_SELECT
/
