GRANT EXECUTE ON P_DATOS_USUARIO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_DATOS_USUARIO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_DATOS_USUARIO TO SISCEL_GA
/
GRANT EXECUTE ON P_DATOS_USUARIO TO SISCEL_SELECT
/
