GRANT EXECUTE ON P_DATOS_ABOTREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_DATOS_ABOTREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_DATOS_ABOTREK TO SISCEL_GA
/
GRANT EXECUTE ON P_DATOS_ABOTREK TO SISCEL_SELECT
/
