GRANT EXECUTE ON P_DATOS_ABOBEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_DATOS_ABOBEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_DATOS_ABOBEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_DATOS_ABOBEEP TO SISCEL_SELECT
/
