GRANT EXECUTE ON P_DEL_EQUIPABONOSER TO EBZ_SISCEL
/
GRANT EXECUTE ON P_DEL_EQUIPABONOSER TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_DEL_EQUIPABONOSER TO SISCEL_GA
/
GRANT EXECUTE ON P_DEL_EQUIPABONOSER TO SISCEL_SELECT
/
