GRANT EXECUTE ON P_DELETE_ABORENT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_DELETE_ABORENT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_DELETE_ABORENT TO SISCEL_GA
/
GRANT EXECUTE ON P_DELETE_ABORENT TO SISCEL_SELECT
/
