GRANT EXECUTE ON P_DEL_NUMESPABO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_DEL_NUMESPABO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_DEL_NUMESPABO TO SISCEL_GA
/
GRANT EXECUTE ON P_DEL_NUMESPABO TO SISCEL_SELECT
/
