GRANT EXECUTE ON P_DESCUENTOS_PLAN TO EBZ_SISCEL
/
GRANT EXECUTE ON P_DESCUENTOS_PLAN TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_DESCUENTOS_PLAN TO SISCEL_GA
/
GRANT EXECUTE ON P_DESCUENTOS_PLAN TO SISCEL_SELECT
/
