GRANT EXECUTE ON P_DELETE_CONCEPTOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_DELETE_CONCEPTOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_DELETE_CONCEPTOS TO SISCEL_GA
/
GRANT EXECUTE ON P_DELETE_CONCEPTOS TO SISCEL_SELECT
/
