GRANT EXECUTE ON P_DEL_SERVSUPLABO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_DEL_SERVSUPLABO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_DEL_SERVSUPLABO TO SISCEL_GA
/
GRANT EXECUTE ON P_DEL_SERVSUPLABO TO SISCEL_SELECT
/
