GRANT EXECUTE ON P_ESTADO_ABOROA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_ESTADO_ABOROA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_ESTADO_ABOROA TO SISCEL_GA
/
GRANT EXECUTE ON P_ESTADO_ABOROA TO SISCEL_SELECT
/
