GRANT EXECUTE ON P_EXISTE_USO_STOCK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_EXISTE_USO_STOCK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_EXISTE_USO_STOCK TO SISCEL_GA
/
GRANT EXECUTE ON P_EXISTE_USO_STOCK TO SISCEL_SELECT
/
