GRANT EXECUTE ON P_FACTURA_ROABAJA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_FACTURA_ROABAJA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_FACTURA_ROABAJA TO SISCEL_GA
/
GRANT EXECUTE ON P_FACTURA_ROABAJA TO SISCEL_SELECT
/
