GRANT EXECUTE ON P_GA_RESPUESTA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GA_RESPUESTA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GA_RESPUESTA TO SISCEL_CO
/
GRANT EXECUTE ON P_GA_RESPUESTA TO SISCEL_GA
/
GRANT EXECUTE ON P_GA_RESPUESTA TO SISCEL_PV
/
GRANT EXECUTE ON P_GA_RESPUESTA TO SISCEL_SELECT
/
