GRANT EXECUTE ON P_GA_DATOS_BAJA_DIARIOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GA_DATOS_BAJA_DIARIOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GA_DATOS_BAJA_DIARIOS TO SISCEL_GA
/
GRANT EXECUTE ON P_GA_DATOS_BAJA_DIARIOS TO SISCEL_SELECT
/
