GRANT EXECUTE ON P_GA_SUSPABOBEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GA_SUSPABOBEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GA_SUSPABOBEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_GA_SUSPABOBEEP TO SISCEL_SELECT
/
