GRANT EXECUTE ON P_GA_SUSPABOCEL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GA_SUSPABOCEL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GA_SUSPABOCEL TO SISCEL_GA
/
GRANT EXECUTE ON P_GA_SUSPABOCEL TO SISCEL_SELECT
/
