GRANT EXECUTE ON P_GA_REHABOBEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GA_REHABOBEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GA_REHABOBEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_GA_REHABOBEEP TO SISCEL_SELECT
/
