GRANT EXECUTE ON P_GA_DESRESERVA_PUNTUAL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GA_DESRESERVA_PUNTUAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GA_DESRESERVA_PUNTUAL TO SISCEL_GA
/
GRANT EXECUTE ON P_GA_DESRESERVA_PUNTUAL TO SISCEL_SELECT
/
