GRANT EXECUTE ON P_GA_USOSMIGRACION TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GA_USOSMIGRACION TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GA_USOSMIGRACION TO SISCEL_GA
/
GRANT EXECUTE ON P_GA_USOSMIGRACION TO SISCEL_SELECT
/
