GRANT EXECUTE ON P_GA_SUSPABOTREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GA_SUSPABOTREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GA_SUSPABOTREK TO SISCEL_GA
/
GRANT EXECUTE ON P_GA_SUSPABOTREK TO SISCEL_SELECT
/
