GRANT EXECUTE ON P_GA_INS_GLOSAFACT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GA_INS_GLOSAFACT TO PUBLIC
/
GRANT EXECUTE ON P_GA_INS_GLOSAFACT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GA_INS_GLOSAFACT TO SISCEL_GA
/
GRANT EXECUTE ON P_GA_INS_GLOSAFACT TO SISCEL_SELECT
/
