GRANT EXECUTE ON P_GA_REHABOTREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GA_REHABOTREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GA_REHABOTREK TO SISCEL_GA
/
GRANT EXECUTE ON P_GA_REHABOTREK TO SISCEL_SELECT
/
