GRANT EXECUTE ON P_GA_DESRESERVA_AUTOMATICA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GA_DESRESERVA_AUTOMATICA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GA_DESRESERVA_AUTOMATICA TO SISCEL_GA
/
GRANT EXECUTE ON P_GA_DESRESERVA_AUTOMATICA TO SISCEL_SELECT
/
