GRANT EXECUTE ON P_GENERA_CABECERA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GENERA_CABECERA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GENERA_CABECERA TO SISCEL_GA
/
GRANT EXECUTE ON P_GENERA_CABECERA TO SISCEL_SELECT
/
