GRANT EXECUTE ON P_GENERA_DOCVENTA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GENERA_DOCVENTA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GENERA_DOCVENTA TO SISCEL_GA
/
GRANT EXECUTE ON P_GENERA_DOCVENTA TO SISCEL_SELECT
/
