GRANT EXECUTE ON P_GR_MIN_GCLIENTES TO EBZ_SISCEL
/
GRANT EXECUTE ON P_GR_MIN_GCLIENTES TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_GR_MIN_GCLIENTES TO SISCEL_GR
/
GRANT EXECUTE ON P_GR_MIN_GCLIENTES TO SISCEL_SELECT
/
