GRANT EXECUTE ON P_HISTORICO_GRUPOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_HISTORICO_GRUPOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_HISTORICO_GRUPOS TO SISCEL_GA
/
GRANT EXECUTE ON P_HISTORICO_GRUPOS TO SISCEL_SELECT
/
