GRANT EXECUTE ON P_HISTORICO_SUSPENSIONES TO EBZ_SISCEL
/
GRANT EXECUTE ON P_HISTORICO_SUSPENSIONES TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_HISTORICO_SUSPENSIONES TO SISCEL_GA
/
GRANT EXECUTE ON P_HISTORICO_SUSPENSIONES TO SISCEL_GE
/
GRANT EXECUTE ON P_HISTORICO_SUSPENSIONES TO SISCEL_SELECT
/
