GRANT EXECUTE ON P_INTERFASES_CELULAR TO CER_CPU
/
GRANT EXECUTE ON P_INTERFASES_CELULAR TO EBZ_SISCEL
/
GRANT EXECUTE ON P_INTERFASES_CELULAR TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INTERFASES_CELULAR TO SISCEL_GA
/
GRANT EXECUTE ON P_INTERFASES_CELULAR TO SISCEL_SELECT
/
