GRANT EXECUTE ON P_INDICADOR_FACTURABLE TO EBZ_SISCEL
/
GRANT EXECUTE ON P_INDICADOR_FACTURABLE TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INDICADOR_FACTURABLE TO SISCEL_GA
/
GRANT EXECUTE ON P_INDICADOR_FACTURABLE TO SISCEL_SELECT
/
