GRANT EXECUTE ON P_INSERTAR_ACTUASERV TO EBZ_SISCEL
/
GRANT EXECUTE ON P_INSERTAR_ACTUASERV TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERTAR_ACTUASERV TO SISCEL_GA
/
GRANT EXECUTE ON P_INSERTAR_ACTUASERV TO SISCEL_SELECT
/
GRANT EXECUTE ON P_INSERTAR_ACTUASERV TO SISCEL_VE
/
