GRANT EXECUTE ON P_INDICADOR_FACTURENT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_INDICADOR_FACTURENT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INDICADOR_FACTURENT TO SISCEL_GA
/
GRANT EXECUTE ON P_INDICADOR_FACTURENT TO SISCEL_SELECT
/
