GRANT EXECUTE ON P_INTERFASES_GENERAL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_INTERFASES_GENERAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INTERFASES_GENERAL TO SISCEL_GA
/
GRANT EXECUTE ON P_INTERFASES_GENERAL TO SISCEL_SELECT
/
