GRANT EXECUTE ON P_INTERFASES_ABONADOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_INTERFASES_ABONADOS TO PUBLIC
/
GRANT EXECUTE ON P_INTERFASES_ABONADOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INTERFASES_ABONADOS TO SISCEL_GA
/
GRANT EXECUTE ON P_INTERFASES_ABONADOS TO SISCEL_SELECT
/
