GRANT EXECUTE ON P_INSERT_INTERGUIAS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_INSERT_INTERGUIAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERT_INTERGUIAS TO SISCEL_GA
/
GRANT EXECUTE ON P_INSERT_INTERGUIAS TO SISCEL_SELECT
/
