GRANT EXECUTE ON P_INSERTA_MOVIM TO EBZ_SISCEL
/
GRANT EXECUTE ON P_INSERTA_MOVIM TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERTA_MOVIM TO SISCEL_GA
/
GRANT EXECUTE ON P_INSERTA_MOVIM TO SISCEL_SELECT
/
