GRANT EXECUTE ON P_INSERTAR_CONCEPTOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_INSERTAR_CONCEPTOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERTAR_CONCEPTOS TO SISCEL_GA
/
GRANT EXECUTE ON P_INSERTAR_CONCEPTOS TO SISCEL_SELECT
/
GRANT EXECUTE ON P_INSERTAR_CONCEPTOS TO SISCEL_VE
/
