GRANT EXECUTE ON P_LIQUIDA_ROAMING TO EBZ_SISCEL
/
GRANT EXECUTE ON P_LIQUIDA_ROAMING TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_LIQUIDA_ROAMING TO SISCEL_GA
/
GRANT EXECUTE ON P_LIQUIDA_ROAMING TO SISCEL_SELECT
/
