GRANT EXECUTE ON P_LIMPIAR_PERFIL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_LIMPIAR_PERFIL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_LIMPIAR_PERFIL TO SISCEL_GA
/
GRANT EXECUTE ON P_LIMPIAR_PERFIL TO SISCEL_SELECT
/
