GRANT EXECUTE ON P_LIMITE_CONSUMO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_LIMITE_CONSUMO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_LIMITE_CONSUMO TO SISCEL_GA
/
GRANT EXECUTE ON P_LIMITE_CONSUMO TO SISCEL_SELECT
/
