GRANT EXECUTE ON P_LIQUIDA_ABONADO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_LIQUIDA_ABONADO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_LIQUIDA_ABONADO TO SISCEL_GA
/
GRANT EXECUTE ON P_LIQUIDA_ABONADO TO SISCEL_SELECT
/
