GRANT EXECUTE ON P_LIMITE_CONSUMO_CICLO TO CER_CPU
/
GRANT EXECUTE ON P_LIMITE_CONSUMO_CICLO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_LIMITE_CONSUMO_CICLO TO SISCEL_PV
/
GRANT EXECUTE ON P_LIMITE_CONSUMO_CICLO TO SISCEL_SELECT
/
