GRANT EXECUTE ON P_LIMPIAR_PERFILABO_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_LIMPIAR_PERFILABO_PR TO SISCEL_CO
/
GRANT EXECUTE ON P_LIMPIAR_PERFILABO_PR TO SISCEL_GA
/
GRANT EXECUTE ON P_LIMPIAR_PERFILABO_PR TO SISCEL_PV
/
GRANT EXECUTE ON P_LIMPIAR_PERFILABO_PR TO SISCEL_SELECT
/
