GRANT EXECUTE ON P_LIQUIDA_ABORENT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_LIQUIDA_ABORENT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_LIQUIDA_ABORENT TO SISCEL_GA
/
GRANT EXECUTE ON P_LIQUIDA_ABORENT TO SISCEL_SELECT
/
