GRANT EXECUTE ON P_LIMPIAR_CLASEABO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_LIMPIAR_CLASEABO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_LIMPIAR_CLASEABO TO SISCEL_GA
/
GRANT EXECUTE ON P_LIMPIAR_CLASEABO TO SISCEL_SELECT
/
