GRANT EXECUTE ON P_MANUAL_REUTIL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_MANUAL_REUTIL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_MANUAL_REUTIL TO SISCEL_GA
/
GRANT EXECUTE ON P_MANUAL_REUTIL TO SISCEL_SELECT
/
