GRANT EXECUTE ON P_MODIFICA_INTARENT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_MODIFICA_INTARENT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_MODIFICA_INTARENT TO SISCEL_GA
/
GRANT EXECUTE ON P_MODIFICA_INTARENT TO SISCEL_SELECT
/
