GRANT EXECUTE ON P_MODIFICA_ESTADOABO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_MODIFICA_ESTADOABO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_MODIFICA_ESTADOABO TO SISCEL_GA
/
GRANT EXECUTE ON P_MODIFICA_ESTADOABO TO SISCEL_PV
/
GRANT EXECUTE ON P_MODIFICA_ESTADOABO TO SISCEL_SELECT
/
