GRANT EXECUTE ON P_MODIFICA_CONCEPTOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_MODIFICA_CONCEPTOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_MODIFICA_CONCEPTOS TO SISCEL_GA
/
GRANT EXECUTE ON P_MODIFICA_CONCEPTOS TO SISCEL_SELECT
/
