GRANT EXECUTE ON P_MODIFICA_SEGNUM TO EBZ_SISCEL
/
GRANT EXECUTE ON P_MODIFICA_SEGNUM TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_MODIFICA_SEGNUM TO SISCEL_GA
/
GRANT EXECUTE ON P_MODIFICA_SEGNUM TO SISCEL_SELECT
/
