GRANT EXECUTE ON P_MODIFICA_CUOTAS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_MODIFICA_CUOTAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_MODIFICA_CUOTAS TO SISCEL_GA
/
GRANT EXECUTE ON P_MODIFICA_CUOTAS TO SISCEL_SELECT
/
