GRANT EXECUTE ON P_MODIF_DETALLE TO EBZ_SISCEL
/
GRANT EXECUTE ON P_MODIF_DETALLE TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_MODIF_DETALLE TO SISCEL_GA
/
GRANT EXECUTE ON P_MODIF_DETALLE TO SISCEL_SELECT
/
