GRANT EXECUTE ON P_MOVIMIENTO_BAJA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_MOVIMIENTO_BAJA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_MOVIMIENTO_BAJA TO SISCEL_GA
/
GRANT EXECUTE ON P_MOVIMIENTO_BAJA TO SISCEL_SELECT
/
