GRANT EXECUTE ON P_MODIFICA_NUMPROCESO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_MODIFICA_NUMPROCESO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_MODIFICA_NUMPROCESO TO SISCEL_GA
/
GRANT EXECUTE ON P_MODIFICA_NUMPROCESO TO SISCEL_SELECT
/
