GRANT EXECUTE ON P_MODIF_DIASESP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_MODIF_DIASESP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_MODIF_DIASESP TO SISCEL_GA
/
GRANT EXECUTE ON P_MODIF_DIASESP TO SISCEL_SELECT
/
