GRANT EXECUTE ON P_NUMERACION_BEEPER TO EBZ_SISCEL
/
GRANT EXECUTE ON P_NUMERACION_BEEPER TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_NUMERACION_BEEPER TO SISCEL_GA
/
GRANT EXECUTE ON P_NUMERACION_BEEPER TO SISCEL_SELECT
/
