GRANT EXECUTE ON P_NUMERACION_AUTOMATICAROA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_NUMERACION_AUTOMATICAROA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_NUMERACION_AUTOMATICAROA TO SISCEL_GA
/
GRANT EXECUTE ON P_NUMERACION_AUTOMATICAROA TO SISCEL_SELECT
/
