GRANT EXECUTE ON P_NUMERACION_TREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_NUMERACION_TREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_NUMERACION_TREK TO SISCEL_GA
/
GRANT EXECUTE ON P_NUMERACION_TREK TO SISCEL_SELECT
/
