GRANT EXECUTE ON P_NUMERACION_MANUAL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_NUMERACION_MANUAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_NUMERACION_MANUAL TO SISCEL_GA
/
GRANT EXECUTE ON P_NUMERACION_MANUAL TO SISCEL_SELECT
/
