GRANT EXECUTE ON P_NUMERACION_CELULAR TO EBZ_SISCEL
/
GRANT EXECUTE ON P_NUMERACION_CELULAR TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_NUMERACION_CELULAR TO SISCEL_GA
/
GRANT EXECUTE ON P_NUMERACION_CELULAR TO SISCEL_SELECT
/
