GRANT EXECUTE ON P_NUMERACION_MANUALROA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_NUMERACION_MANUALROA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_NUMERACION_MANUALROA TO SISCEL_GA
/
GRANT EXECUTE ON P_NUMERACION_MANUALROA TO SISCEL_SELECT
/
