GRANT EXECUTE ON P_NUMERACION_AUTOMATICABEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_NUMERACION_AUTOMATICABEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_NUMERACION_AUTOMATICABEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_NUMERACION_AUTOMATICABEEP TO SISCEL_SELECT
/
