GRANT EXECUTE ON P_NUMERACION_MANUALBEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_NUMERACION_MANUALBEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_NUMERACION_MANUALBEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_NUMERACION_MANUALBEEP TO SISCEL_SELECT
/
