GRANT EXECUTE ON P_OBTIENE_TIPOART TO EBZ_SISCEL
/
GRANT EXECUTE ON P_OBTIENE_TIPOART TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_OBTIENE_TIPOART TO SISCEL_GA
/
GRANT EXECUTE ON P_OBTIENE_TIPOART TO SISCEL_SELECT
/
