GRANT EXECUTE ON P_OBTIENE_ZONAIMPO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_OBTIENE_ZONAIMPO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_OBTIENE_ZONAIMPO TO SISCEL_GA
/
GRANT EXECUTE ON P_OBTIENE_ZONAIMPO TO SISCEL_SELECT
/
