GRANT EXECUTE ON P_OBTIENE_VALORACION TO EBZ_SISCEL
/
GRANT EXECUTE ON P_OBTIENE_VALORACION TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_OBTIENE_VALORACION TO SISCEL_GA
/
GRANT EXECUTE ON P_OBTIENE_VALORACION TO SISCEL_SELECT
/
