GRANT EXECUTE ON P_OBTIENE_TIPORUT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_OBTIENE_TIPORUT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_OBTIENE_TIPORUT TO SISCEL_GA
/
GRANT EXECUTE ON P_OBTIENE_TIPORUT TO SISCEL_SELECT
/
