GRANT EXECUTE ON P_OBTIENE_TIPMOVIM TO EBZ_SISCEL
/
GRANT EXECUTE ON P_OBTIENE_TIPMOVIM TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_OBTIENE_TIPMOVIM TO SISCEL_GA
/
GRANT EXECUTE ON P_OBTIENE_TIPMOVIM TO SISCEL_SELECT
/
