GRANT EXECUTE ON P_OBTIENE_DIRECCION TO EBZ_SISCEL
/
GRANT EXECUTE ON P_OBTIENE_DIRECCION TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_OBTIENE_DIRECCION TO SISCEL_GA
/
GRANT EXECUTE ON P_OBTIENE_DIRECCION TO SISCEL_SELECT
/
