GRANT EXECUTE ON P_OBTIENE_CICLO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_OBTIENE_CICLO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_OBTIENE_CICLO TO SISCEL_GA
/
GRANT EXECUTE ON P_OBTIENE_CICLO TO SISCEL_SELECT
/
