GRANT EXECUTE ON P_OBTIENE_CAMBIO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_OBTIENE_CAMBIO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_OBTIENE_CAMBIO TO SISCEL_GA
/
GRANT EXECUTE ON P_OBTIENE_CAMBIO TO SISCEL_SELECT
/
