GRANT EXECUTE ON P_OBTIENE_CATIMPOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_OBTIENE_CATIMPOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_OBTIENE_CATIMPOS TO SISCEL_GA
/
GRANT EXECUTE ON P_OBTIENE_CATIMPOS TO SISCEL_SELECT
/
