GRANT EXECUTE ON P_PLAN_TARIFARIO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_PLAN_TARIFARIO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_PLAN_TARIFARIO TO SISCEL_GA
/
GRANT EXECUTE ON P_PLAN_TARIFARIO TO SISCEL_SELECT
/
