GRANT EXECUTE ON P_PLAN_COMERCIAL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_PLAN_COMERCIAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_PLAN_COMERCIAL TO SISCEL_GA
/
GRANT EXECUTE ON P_PLAN_COMERCIAL TO SISCEL_SELECT
/
