GRANT EXECUTE ON P_PROCESO_REHABILITACIONP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_PROCESO_REHABILITACIONP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_PROCESO_REHABILITACIONP TO SISCEL_GA
/
GRANT EXECUTE ON P_PROCESO_REHABILITACIONP TO SISCEL_SELECT
/
