GRANT EXECUTE ON P_PROCESO_SUSPENSIONES TO EBZ_SISCEL
/
GRANT EXECUTE ON P_PROCESO_SUSPENSIONES TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_PROCESO_SUSPENSIONES TO SISCEL_GA
/
GRANT EXECUTE ON P_PROCESO_SUSPENSIONES TO SISCEL_SELECT
/
