GRANT EXECUTE ON P_PROCESO_REHABILITACIONT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_PROCESO_REHABILITACIONT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_PROCESO_REHABILITACIONT TO SISCEL_GA
/
GRANT EXECUTE ON P_PROCESO_REHABILITACIONT TO SISCEL_SELECT
/
