GRANT EXECUTE ON P_REPONER_INFORMACION TO EBZ_SISCEL
/
GRANT EXECUTE ON P_REPONER_INFORMACION TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_REPONER_INFORMACION TO SISCEL_GA
/
GRANT EXECUTE ON P_REPONER_INFORMACION TO SISCEL_SELECT
/
