GRANT EXECUTE ON P_RECUPERA_ARTICULOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_RECUPERA_ARTICULOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_RECUPERA_ARTICULOS TO SISCEL_GA
/
GRANT EXECUTE ON P_RECUPERA_ARTICULOS TO SISCEL_SELECT
/
