GRANT EXECUTE ON P_REPONER_NUMERACIONBEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_REPONER_NUMERACIONBEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_REPONER_NUMERACIONBEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_REPONER_NUMERACIONBEEP TO SISCEL_SELECT
/
