GRANT EXECUTE ON P_REPONER_VENTAS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_REPONER_VENTAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_REPONER_VENTAS TO SISCEL_GA
/
GRANT EXECUTE ON P_REPONER_VENTAS TO SISCEL_SELECT
/
