GRANT EXECUTE ON P_RECUPERA_CICLOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_RECUPERA_CICLOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_RECUPERA_CICLOS TO SISCEL_GA
/
GRANT EXECUTE ON P_RECUPERA_CICLOS TO SISCEL_SELECT
/
