GRANT EXECUTE ON P_RECUPERA_NUMERACION TO EBZ_SISCEL
/
GRANT EXECUTE ON P_RECUPERA_NUMERACION TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_RECUPERA_NUMERACION TO SISCEL_GA
/
GRANT EXECUTE ON P_RECUPERA_NUMERACION TO SISCEL_SELECT
/
