GRANT EXECUTE ON P_RECUPERA_CONCEPTO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_RECUPERA_CONCEPTO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_RECUPERA_CONCEPTO TO SISCEL_GA
/
GRANT EXECUTE ON P_RECUPERA_CONCEPTO TO SISCEL_SELECT
/
