GRANT EXECUTE ON P_RECUPERA_SERVNIVEL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_RECUPERA_SERVNIVEL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_RECUPERA_SERVNIVEL TO SISCEL_GA
/
GRANT EXECUTE ON P_RECUPERA_SERVNIVEL TO SISCEL_SELECT
/
