GRANT EXECUTE ON P_REPONER_NUMERACIONROA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_REPONER_NUMERACIONROA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_REPONER_NUMERACIONROA TO SISCEL_GA
/
GRANT EXECUTE ON P_REPONER_NUMERACIONROA TO SISCEL_SELECT
/
