GRANT EXECUTE ON P_REPONER_NUMERACIONTREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_REPONER_NUMERACIONTREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_REPONER_NUMERACIONTREK TO SISCEL_GA
/
GRANT EXECUTE ON P_REPONER_NUMERACIONTREK TO SISCEL_SELECT
/
