GRANT EXECUTE ON P_SELECT_ARTICULO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_ARTICULO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_ARTICULO TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_ARTICULO TO SISCEL_SELECT
/
