GRANT EXECUTE ON P_SEGUNDO_NUMERO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SEGUNDO_NUMERO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SEGUNDO_NUMERO TO SISCEL_GA
/
GRANT EXECUTE ON P_SEGUNDO_NUMERO TO SISCEL_SELECT
/
