GRANT EXECUTE ON P_SELECT_RANGOSROA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_RANGOSROA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_RANGOSROA TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_RANGOSROA TO SISCEL_SELECT
/
