GRANT EXECUTE ON P_SERIE_INTARCEL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SERIE_INTARCEL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SERIE_INTARCEL TO SISCEL_GA
/
GRANT EXECUTE ON P_SERIE_INTARCEL TO SISCEL_SELECT
/
