GRANT EXECUTE ON P_SELECT_SERHEX TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_SERHEX TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_SERHEX TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_SERHEX TO SISCEL_SELECT
/
