GRANT EXECUTE ON P_SELECT_CIUDAD TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_CIUDAD TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_CIUDAD TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_CIUDAD TO SISCEL_SELECT
/
