GRANT EXECUTE ON P_SERIE_INTARENT TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SERIE_INTARENT TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SERIE_INTARENT TO SISCEL_GA
/
GRANT EXECUTE ON P_SERIE_INTARENT TO SISCEL_SELECT
/
