GRANT EXECUTE ON P_SELECT_NUMGUIA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_NUMGUIA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_NUMGUIA TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_NUMGUIA TO SISCEL_SELECT
/
