GRANT EXECUTE ON P_SELECT_REUTILIZABLESTREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_REUTILIZABLESTREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_REUTILIZABLESTREK TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_REUTILIZABLESTREK TO SISCEL_SELECT
/
