GRANT EXECUTE ON P_SELECT_CLIENTE TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_CLIENTE TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_CLIENTE TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_CLIENTE TO SISCEL_SELECT
/
