GRANT EXECUTE ON P_SELECT_REUTILIZABLESROA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_REUTILIZABLESROA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_REUTILIZABLESROA TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_REUTILIZABLESROA TO SISCEL_SELECT
/
