GRANT EXECUTE ON P_SERIE_SEGURABO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SERIE_SEGURABO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SERIE_SEGURABO TO SISCEL_GA
/
GRANT EXECUTE ON P_SERIE_SEGURABO TO SISCEL_SELECT
/
