GRANT EXECUTE ON P_SELECT_REUTILIZABLES TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_REUTILIZABLES TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_REUTILIZABLES TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_REUTILIZABLES TO SISCEL_SELECT
/
