GRANT EXECUTE ON P_SELECT_RANGOS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_RANGOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_RANGOS TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_RANGOS TO SISCEL_SELECT
/
