GRANT EXECUTE ON P_SELECT_DES_BODEGA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_DES_BODEGA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_DES_BODEGA TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_DES_BODEGA TO SISCEL_SELECT
/
