GRANT EXECUTE ON P_SERIE_EQUIPABOSER TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SERIE_EQUIPABOSER TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SERIE_EQUIPABOSER TO SISCEL_GA
/
GRANT EXECUTE ON P_SERIE_EQUIPABOSER TO SISCEL_SELECT
/
