GRANT EXECUTE ON P_SELECT_RANGOSBEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_RANGOSBEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_RANGOSBEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_RANGOSBEEP TO SISCEL_SELECT
/
