GRANT EXECUTE ON P_SELECT_ACTUACION TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_ACTUACION TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_ACTUACION TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_ACTUACION TO SISCEL_SELECT
/
