GRANT EXECUTE ON P_SERIE_INTAROAVIS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SERIE_INTAROAVIS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SERIE_INTAROAVIS TO SISCEL_GA
/
GRANT EXECUTE ON P_SERIE_INTAROAVIS TO SISCEL_SELECT
/
