GRANT EXECUTE ON P_SELECT_RANGOSTREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_SELECT_RANGOSTREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_SELECT_RANGOSTREK TO SISCEL_GA
/
GRANT EXECUTE ON P_SELECT_RANGOSTREK TO SISCEL_SELECT
/
