GRANT EXECUTE ON P_TRASPASO_INTARXXX TO EBZ_SISCEL
/
GRANT EXECUTE ON P_TRASPASO_INTARXXX TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_TRASPASO_INTARXXX TO SISCEL_GA
/
GRANT EXECUTE ON P_TRASPASO_INTARXXX TO SISCEL_SELECT
/
