GRANT EXECUTE ON P_TRASPASO_INFACXXX TO EBZ_SISCEL
/
GRANT EXECUTE ON P_TRASPASO_INFACXXX TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_TRASPASO_INFACXXX TO SISCEL_GA
/
GRANT EXECUTE ON P_TRASPASO_INFACXXX TO SISCEL_SELECT
/
