GRANT EXECUTE ON P_UPD_INTERVBPL TO EBZ_SISCEL
/
GRANT EXECUTE ON P_UPD_INTERVBPL TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_UPD_INTERVBPL TO SISCEL_GA
/
GRANT EXECUTE ON P_UPD_INTERVBPL TO SISCEL_SELECT
/
