GRANT EXECUTE ON P_UPDTE_EMPRESA TO EBZ_SISCEL
/
GRANT EXECUTE ON P_UPDTE_EMPRESA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_UPDTE_EMPRESA TO SISCEL_GA
/
GRANT EXECUTE ON P_UPDTE_EMPRESA TO SISCEL_SELECT
/
