GRANT EXECUTE ON P_UPDTE_HOLDING TO EBZ_SISCEL
/
GRANT EXECUTE ON P_UPDTE_HOLDING TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_UPDTE_HOLDING TO SISCEL_GA
/
GRANT EXECUTE ON P_UPDTE_HOLDING TO SISCEL_SELECT
/
