GRANT EXECUTE ON P_UPDTE_MOVIMIENTO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_UPDTE_MOVIMIENTO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_UPDTE_MOVIMIENTO TO SISCEL_GA
/
GRANT EXECUTE ON P_UPDTE_MOVIMIENTO TO SISCEL_SELECT
/
