GRANT EXECUTE ON P_VALIDA_ROBADAS TO EBZ_SISCEL
/
GRANT EXECUTE ON P_VALIDA_ROBADAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_VALIDA_ROBADAS TO SISCEL_GA
/
GRANT EXECUTE ON P_VALIDA_ROBADAS TO SISCEL_SELECT
/
