GRANT EXECUTE ON P_VALIDA_ROAMING TO EBZ_SISCEL
/
GRANT EXECUTE ON P_VALIDA_ROAMING TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_VALIDA_ROAMING TO SISCEL_GA
/
GRANT EXECUTE ON P_VALIDA_ROAMING TO SISCEL_SELECT
/
