GRANT EXECUTE ON P_VALIDA_SUSPENSIONES TO EBZ_SISCEL
/
GRANT EXECUTE ON P_VALIDA_SUSPENSIONES TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_VALIDA_SUSPENSIONES TO SISCEL_GA
/
GRANT EXECUTE ON P_VALIDA_SUSPENSIONES TO SISCEL_SELECT
/
