GRANT EXECUTE ON P_VALIDA_ROBADASTREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_VALIDA_ROBADASTREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_VALIDA_ROBADASTREK TO SISCEL_GA
/
GRANT EXECUTE ON P_VALIDA_ROBADASTREK TO SISCEL_SELECT
/
