GRANT EXECUTE ON P_VALIDA_REPETICIONBEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_VALIDA_REPETICIONBEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_VALIDA_REPETICIONBEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_VALIDA_REPETICIONBEEP TO SISCEL_SELECT
/
