GRANT EXECUTE ON P_VALIDA_SERIETREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_VALIDA_SERIETREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_VALIDA_SERIETREK TO SISCEL_GA
/
GRANT EXECUTE ON P_VALIDA_SERIETREK TO SISCEL_SELECT
/
