GRANT EXECUTE ON P_VALIDA_REPETICIONTREK TO EBZ_SISCEL
/
GRANT EXECUTE ON P_VALIDA_REPETICIONTREK TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_VALIDA_REPETICIONTREK TO SISCEL_GA
/
GRANT EXECUTE ON P_VALIDA_REPETICIONTREK TO SISCEL_SELECT
/
