GRANT EXECUTE ON P_VALIDA_FORMATO TO EBZ_SISCEL
/
GRANT EXECUTE ON P_VALIDA_FORMATO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_VALIDA_FORMATO TO SISCEL_GA
/
GRANT EXECUTE ON P_VALIDA_FORMATO TO SISCEL_SELECT
/
