GRANT EXECUTE ON P_VALIDA_ROBADASBEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_VALIDA_ROBADASBEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_VALIDA_ROBADASBEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_VALIDA_ROBADASBEEP TO SISCEL_SELECT
/
