GRANT EXECUTE ON P_VALIDA_SERIEBEEP TO EBZ_SISCEL
/
GRANT EXECUTE ON P_VALIDA_SERIEBEEP TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_VALIDA_SERIEBEEP TO SISCEL_GA
/
GRANT EXECUTE ON P_VALIDA_SERIEBEEP TO SISCEL_SELECT
/
