GRANT DELETE ON PAGOS_PAC_CONTAB TO PUBLIC
/
GRANT INSERT ON PAGOS_PAC_CONTAB TO PUBLIC
/
GRANT SELECT ON PAGOS_PAC_CONTAB TO PUBLIC
/
GRANT UPDATE ON PAGOS_PAC_CONTAB TO PUBLIC
/
GRANT SELECT ON PAGOS_PAC_CONTAB TO SOLO_CONSULTA_SISCEL
/
