GRANT DELETE ON PF_TOLTARIFICA_10209 TO SISCEL_ADMIN
/
GRANT INSERT ON PF_TOLTARIFICA_10209 TO SISCEL_ADMIN
/
GRANT SELECT ON PF_TOLTARIFICA_10209 TO SISCEL_ADMIN
/
GRANT UPDATE ON PF_TOLTARIFICA_10209 TO SISCEL_ADMIN
/
GRANT SELECT ON PF_TOLTARIFICA_10209 TO SISCEL_SELECT
/
