GRANT EXECUTE ON PKG_ICC_SERVSUPLABO TO EBZ_SISCEL
/
GRANT EXECUTE ON PKG_ICC_SERVSUPLABO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PKG_ICC_SERVSUPLABO TO SISCEL_IC
/
GRANT EXECUTE ON PKG_ICC_SERVSUPLABO TO SISCEL_SELECT
/
