GRANT EXECUTE ON PNUMEROS_DISPONIBLES TO EBZ_SISCEL
/
GRANT EXECUTE ON PNUMEROS_DISPONIBLES TO SISCEL_ADMIN
/
GRANT EXECUTE ON PNUMEROS_DISPONIBLES TO SISCEL_GE
/
GRANT EXECUTE ON PNUMEROS_DISPONIBLES TO SISCEL_SELECT
/
