GRANT EXECUTE ON PP_RESRECVTA_HABSUS_ABO TO EBZ_SISCEL
/
GRANT EXECUTE ON PP_RESRECVTA_HABSUS_ABO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PP_RESRECVTA_HABSUS_ABO TO SISCEL_GA
/
GRANT EXECUTE ON PP_RESRECVTA_HABSUS_ABO TO SISCEL_SELECT
/
