GRANT EXECUTE ON PRC_APLICA_PAGO_REG TO EBZ_SISCEL
/
GRANT EXECUTE ON PRC_APLICA_PAGO_REG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PRC_APLICA_PAGO_REG TO SISCEL_CO
/
GRANT EXECUTE ON PRC_APLICA_PAGO_REG TO SISCEL_SELECT
/
