GRANT SELECT                            ON PS_PLANTARIF_PLANADIC_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PS_PLANTARIF_PLANADIC_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PS_PLANTARIF_PLANADIC_TD TO SISCEL_VE
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PS_PLANTARIF_PLANADIC_TD TO SISCEL_PV
/
GRANT SELECT                            ON PS_PLANTARIF_PLANADIC_TD TO MAS_PRODUCT_DML
/