GRANT EXECUTE  ON    PV_AUTORIZA_RENOVA_PG      TO   SISCEL_SELECT
/
GRANT EXECUTE  ON    PV_AUTORIZA_RENOVA_PG      TO   SISCEL_ADMIN
/
GRANT EXECUTE  ON    PV_AUTORIZA_RENOVA_PG      TO   SISCEL_PV
/
