GRANT EXECUTE ON PV_ACTUALIZA_CAMB_COMERC_PR TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_ACTUALIZA_CAMB_COMERC_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_ACTUALIZA_CAMB_COMERC_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_ACTUALIZA_CAMB_COMERC_PR TO SISCEL_SELECT
/
