GRANT   SELECT                             ON PV_AUDIDETLLAM_TH TO SISCEL_SELECT
/
GRANT   SELECT, INSERT, UPDATE, DELETE     ON PV_AUDIDETLLAM_TH TO SISCEL_ADMIN
/
GRANT   SELECT, INSERT, UPDATE, DELETE     ON PV_AUDIDETLLAM_TH TO SISCEL_PV
/

