GRANT EXECUTE ON PV_ACT_RECARGAPREPAGO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_ACT_RECARGAPREPAGO TO SISCEL_GA
/
GRANT EXECUTE ON PV_ACT_RECARGAPREPAGO TO SISCEL_PV
/
GRANT EXECUTE ON PV_ACT_RECARGAPREPAGO TO SISCEL_SELECT
/
