GRANT EXECUTE ON PV_ANULA_CAMSERIE TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_ANULA_CAMSERIE TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_ANULA_CAMSERIE TO SISCEL_PV
/
GRANT EXECUTE ON PV_ANULA_CAMSERIE TO SISCEL_SELECT
/
