GRANT EXECUTE ON PV_BAJA_ABONADO_PG TO SISCEL_GA
/
GRANT EXECUTE ON PV_BAJA_ABONADO_PG TO SISCEL_GE
/
GRANT EXECUTE ON PV_BAJA_ABONADO_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_BAJA_ABONADO_PG TO SISCEL_SELECT
/
