GRANT EXECUTE ON PV_BAJA_MASIVA_POSTPAGO_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_BAJA_MASIVA_POSTPAGO_PG TO SISCEL_GA
/
GRANT EXECUTE ON PV_BAJA_MASIVA_POSTPAGO_PG TO SISCEL_GE
/
GRANT EXECUTE ON PV_BAJA_MASIVA_POSTPAGO_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_BAJA_MASIVA_POSTPAGO_PG TO SISCEL_SELECT
/
