GRANT EXECUTE ON PV_CAMBIOPLANSERV_PREPAGO TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_CAMBIOPLANSERV_PREPAGO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_CAMBIOPLANSERV_PREPAGO TO SISCEL_PV
/
GRANT EXECUTE ON PV_CAMBIOPLANSERV_PREPAGO TO SISCEL_SELECT
/
