GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICA_CELULAR_TH TO SISCEL_PV
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICA_CELULAR_TH TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICA_CELULAR_TH TO SISCEL_VE
/

