GRANT     SELECT                                         ON PV_CAUSA_PLAN_OOSS_TO TO SISCEL_SELECT
/
GRANT     SELECT, INSERT, UPDATE, DELETE                 ON PV_CAUSA_PLAN_OOSS_TO TO SISCEL_ADMIN
/
GRANT     SELECT, INSERT, UPDATE, DELETE                 ON PV_CAUSA_PLAN_OOSS_TO TO SISCEL_PV
/

