GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICA_CELULAR_TO TO SISCEL_PV
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICA_CELULAR_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICA_CELULAR_TO TO SISCEL_VE
/

