GRANT EXECUTE  ON    PV_CONFIG_RENOVACION_PG      TO   SISCEL_SELECT
/
GRANT EXECUTE  ON    PV_CONFIG_RENOVACION_PG      TO   SISCEL_ADMIN
/
GRANT EXECUTE  ON    PV_CONFIG_RENOVACION_PG      TO   SISCEL_PV
/
