GRANT EXECUTE ON PV_CARGO_EQUIPO_QT TO SISCEL_SELECT
/
GRANT EXECUTE ON PV_CARGO_EQUIPO_QT TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_CARGO_EQUIPO_QT TO SISCEL_GA
/
GRANT EXECUTE ON PV_CARGO_EQUIPO_QT TO SISCEL_IC
/