GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CARGA_CALICELU_TO TO SISCEL_PV
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CARGA_CALICELU_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CARGA_CALICELU_TO TO SISCEL_VE
/

