GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICACION_TH TO SISCEL_PV
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICACION_TH TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICACION_TH TO SISCEL_VE
/

