GRANT SELECT                            ON PV_CONTACTO_ABONADO_TT TO SISCEL_SELECT
/
GRANT SELECT, INSERT, DELETE, UPDATE    ON PV_CONTACTO_ABONADO_TT TO SISCEL_ADMIN
/
GRANT SELECT, INSERT, DELETE, UPDATE    ON PV_CONTACTO_ABONADO_TT TO SISCEL_PV
/

