GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICACION_TD TO SISCEL_PV
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICACION_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_CALIFICACION_TD TO SISCEL_VE
/

