GRANT  SELECT                                  ON PV_CONTACTO_ABONADO_TO TO SISCEL_SELECT
/
GRANT  INSERT,UPDATE,DELETE,SELECT             ON PV_CONTACTO_ABONADO_TO TO SISCEL_ADMIN
/
GRANT  INSERT,UPDATE,DELETE,SELECT             ON PV_CONTACTO_ABONADO_TO TO SISCEL_PV
/

