GRANT DELETE ON PV_COMIS_OOSS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON PV_COMIS_OOSS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON PV_COMIS_OOSS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON PV_COMIS_OOSS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON PV_COMIS_OOSS_TD TO SISCEL_SELECT
/
