GRANT DELETE ON PV_DET_SUSPVOLPROG_TO TO SISCEL_ADMIN
/
GRANT INSERT ON PV_DET_SUSPVOLPROG_TO TO SISCEL_ADMIN
/
GRANT SELECT ON PV_DET_SUSPVOLPROG_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON PV_DET_SUSPVOLPROG_TO TO SISCEL_ADMIN
/
GRANT DELETE ON PV_DET_SUSPVOLPROG_TO TO SISCEL_PV
/
GRANT INSERT ON PV_DET_SUSPVOLPROG_TO TO SISCEL_PV
/
GRANT SELECT ON PV_DET_SUSPVOLPROG_TO TO SISCEL_PV
/
GRANT UPDATE ON PV_DET_SUSPVOLPROG_TO TO SISCEL_PV
/
GRANT SELECT ON PV_DET_SUSPVOLPROG_TO TO SISCEL_SELECT
/
