GRANT SELECT ON PV_ERRORES_SQ TO SISCEL_ADMIN
/
GRANT SELECT ON PV_ERRORES_SQ TO SISCEL_GA
/
GRANT SELECT ON PV_ERRORES_SQ TO SISCEL_GE
/
GRANT SELECT ON PV_ERRORES_SQ TO SISCEL_RE
/
GRANT SELECT ON PV_ERRORES_SQ TO SISCEL_SELECT
/
