GRANT EXECUTE ON PV_EVALDEUDA_WEB_PR TO CER_CPU
/
GRANT EXECUTE ON PV_EVALDEUDA_WEB_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_EVALDEUDA_WEB_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_EVALDEUDA_WEB_PR TO SISCEL_SELECT
/
