GRANT EXECUTE  ON PV_EXCLUSION_PLANES_SS_PG   TO   SISCEL_SELECT
/
GRANT EXECUTE  ON PV_EXCLUSION_PLANES_SS_PG   TO   SISCEL_ADMIN
/
GRANT EXECUTE  ON PV_EXCLUSION_PLANES_SS_PG   TO   SISCEL_PV
/
GRANT EXECUTE  ON PV_EXCLUSION_PLANES_SS_PG   TO   MAS_SELECT_RO
/
GRANT EXECUTE  ON PV_EXCLUSION_PLANES_SS_PG   TO   MAS_ADMIN_RO
/