GRANT DELETE ON PV_ENRUTA_LLAMADA TO SISCEL_ADMIN
/
GRANT INSERT ON PV_ENRUTA_LLAMADA TO SISCEL_ADMIN
/
GRANT SELECT ON PV_ENRUTA_LLAMADA TO SISCEL_ADMIN
/
GRANT UPDATE ON PV_ENRUTA_LLAMADA TO SISCEL_ADMIN
/
GRANT SELECT ON PV_ENRUTA_LLAMADA TO SISCEL_SELECT
/
