GRANT EXECUTE ON PV_FN_VER_INCOMP_SSPLAN_GRUPO TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_FN_VER_INCOMP_SSPLAN_GRUPO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_FN_VER_INCOMP_SSPLAN_GRUPO TO SISCEL_PV
/
GRANT EXECUTE ON PV_FN_VER_INCOMP_SSPLAN_GRUPO TO SISCEL_SELECT
/
