GRANT EXECUTE ON PV_FECHAFINCONTRATO_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_FECHAFINCONTRATO_PR TO SISCEL_CO
/
GRANT EXECUTE ON PV_FECHAFINCONTRATO_PR TO SISCEL_GA
/
GRANT EXECUTE ON PV_FECHAFINCONTRATO_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_FECHAFINCONTRATO_PR TO SISCEL_SELECT
/
