GRANT EXECUTE ON PV_FN_VER_INCOMP_SSPLAN TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_FN_VER_INCOMP_SSPLAN TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_FN_VER_INCOMP_SSPLAN TO SISCEL_PV
/
GRANT EXECUTE ON PV_FN_VER_INCOMP_SSPLAN TO SISCEL_SELECT
/
