GRANT EXECUTE ON PV_GEST_LIM_CON_CONSULTAS_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON PV_GEST_LIM_CON_CONSULTAS_PG TO  SISCEL_ADMIN
/
GRANT EXECUTE ON PV_GEST_LIM_CON_CONSULTAS_PG TO  SISCEL_GA
/
GRANT EXECUTE ON PV_GEST_LIM_CON_CONSULTAS_PG TO SISCEL_VE
/