GRANT EXECUTE ON PV_GENERALES_PG TO CER_CPU
/
GRANT EXECUTE ON PV_GENERALES_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_GENERALES_PG TO SISCEL_CPU
/
GRANT EXECUTE ON PV_GENERALES_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_GENERALES_PG TO SISCEL_SELECT
/
