GRANT EXECUTE   ON  PV_GRABAR_SIMCARD_SB_PG   TO SISCEL_PV
/
GRANT EXECUTE   ON  PV_GRABAR_SIMCARD_SB_PG   TO SISCEL_SELECT
/
GRANT EXECUTE   ON  PV_GRABAR_SIMCARD_SB_PG   TO SISCEL_ADMIN
/
GRANT EXECUTE   ON  PV_GRABAR_SIMCARD_SB_PG   TO SISCEL_FA
/
