GRANT EXECUTE ON PV_INFORMA_LIMSCORING_ATL_PG TO FAC_SISCEL
/
GRANT EXECUTE ON PV_INFORMA_LIMSCORING_ATL_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_INFORMA_LIMSCORING_ATL_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_INFORMA_LIMSCORING_ATL_PG TO SISCEL_SELECT
/
