GRANT EXECUTE ON PV_INS_RECARGAPREPAGO_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_INS_RECARGAPREPAGO_PR TO SISCEL_GA
/
GRANT EXECUTE ON PV_INS_RECARGAPREPAGO_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_INS_RECARGAPREPAGO_PR TO SISCEL_SELECT
/
