GRANT DELETE ON PV_ICGENERICA_TO TO SISCEL_ADMIN
/
GRANT INSERT ON PV_ICGENERICA_TO TO SISCEL_ADMIN
/
GRANT SELECT ON PV_ICGENERICA_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON PV_ICGENERICA_TO TO SISCEL_ADMIN
/
GRANT SELECT ON PV_ICGENERICA_TO TO SISCEL_SELECT
/
