GRANT     SELECT, INSERT, UPDATE, DELETE   ON PV_IPSERVSUPLABO_TO TO SISCEL_ADMIN
/
GRANT     SELECT, INSERT, UPDATE, DELETE   ON PV_IPSERVSUPLABO_TO TO SISCEL_PV
/
GRANT     SELECT, INSERT, UPDATE, DELETE   ON PV_IPSERVSUPLABO_TO TO SISCEL_GA
/
GRANT     SELECT                           ON PV_IPSERVSUPLABO_TO TO SISCEL_SELECT
/

