CREATE OR REPLACE TYPE PV_CI_ORSERV_QT AS OBJECT
(
  NUM_OS NUMBER(10),
  COD_OS VARCHAR2(5),
  PRODUCTO NUMBER(1),
  TIP_INTER NUMBER(2),
  COD_INTER NUMBER(10),
  USUARIO VARCHAR2(30),
  FECHA DATE,
  COMENTARIO VARCHAR2(500),
  NUM_CARGO NUMBER(8),
  COD_MODULO VARCHAR2(2),
  ID_GESTOR NUMBER(10),
  NUM_MOVIMIENTO NUMBER(9),
  COD_ESTADO NUMBER(1)
) 
/
SHOW ERRORS