GRANT EXECUTE ON PV_INS_RECARPREPAGO_QUIOSCO_PR TO SISCEL_SELECT
/
GRANT EXECUTE ON PV_INS_RECARPREPAGO_QUIOSCO_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_INS_RECARPREPAGO_QUIOSCO_PR TO SISCEL_GA
/
GRANT EXECUTE ON PV_INS_RECARPREPAGO_QUIOSCO_PR TO SISCEL_PV
/
