GRANT EXECUTE ON PV_INS_INTERFACT TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_INS_INTERFACT TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_INS_INTERFACT TO SISCEL_PV
/
GRANT EXECUTE ON PV_INS_INTERFACT TO SISCEL_SELECT
/
