GRANT  EXECUTE  ON PV_IPFIJA_PG  TO   SISCEL_SELECT
/
GRANT  EXECUTE  ON PV_IPFIJA_PG  TO   SISCEL_ADMIN
/
GRANT  EXECUTE  ON PV_IPFIJA_PG  TO   SISCEL_PV
/
GRANT EXECUTE ON PV_IPFIJA_PG TO MAS_PRODUCT
/
