GRANT EXECUTE ON PV_INCREMENTO_LC_PR TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_INCREMENTO_LC_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_INCREMENTO_LC_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_INCREMENTO_LC_PR TO SISCEL_SELECT
/
