GRANT EXECUTE ON PV_INICIA_ESTRUCTURAS_PG TO CER_CPU
/
GRANT EXECUTE ON PV_INICIA_ESTRUCTURAS_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_INICIA_ESTRUCTURAS_PG TO SISCEL_CPU
/
GRANT EXECUTE ON PV_INICIA_ESTRUCTURAS_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_INICIA_ESTRUCTURAS_PG TO SISCEL_SELECT
/
