GRANT EXECUTE ON PV_LIQUIDACION_DEUDA TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_LIQUIDACION_DEUDA TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_LIQUIDACION_DEUDA TO SISCEL_PV
/
GRANT EXECUTE ON PV_LIQUIDACION_DEUDA TO SISCEL_SELECT
/
