GRANT EXECUTE ON PV_LIMITE_CONSUMO_PG TO CER_CPU
/
GRANT EXECUTE ON PV_LIMITE_CONSUMO_PG TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_LIMITE_CONSUMO_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_LIMITE_CONSUMO_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_LIMITE_CONSUMO_PG TO SISCEL_SELECT
/
