GRANT EXECUTE ON PV_MTONBPORC_FN TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_MTONBPORC_FN TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_MTONBPORC_FN TO SISCEL_GA
/
GRANT EXECUTE ON PV_MTONBPORC_FN TO SISCEL_SELECT
/
