GRANT EXECUTE ON PV_MASCARA_NUM_PERSONAL_PG TO CER_CPU
/
GRANT EXECUTE ON PV_MASCARA_NUM_PERSONAL_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_MASCARA_NUM_PERSONAL_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_MASCARA_NUM_PERSONAL_PG TO SISCEL_SELECT
/
