GRANT EXECUTE ON PV_MODIFUSO_INTARCEL TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_MODIFUSO_INTARCEL TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_MODIFUSO_INTARCEL TO SISCEL_PV
/
GRANT EXECUTE ON PV_MODIFUSO_INTARCEL TO SISCEL_SELECT
/
