GRANT EXECUTE ON PV_MASCARA_CARGOS_PG TO CER_CPU
/
GRANT EXECUTE ON PV_MASCARA_CARGOS_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_MASCARA_CARGOS_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_MASCARA_CARGOS_PG TO SISCEL_SELECT
/
