GRANT SELECT                            ON PV_NUMRESTRIC_DETLLAM_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_NUMRESTRIC_DETLLAM_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON PV_NUMRESTRIC_DETLLAM_TO TO SISCEL_PV
/

