GRANT EXECUTE ON PV_NRO_PILOTO_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON PV_NRO_PILOTO_PG TO  SISCEL_ADMIN
/
GRANT EXECUTE ON PV_NRO_PILOTO_PG TO SISCEL_GA
/
GRANT EXECUTE ON PV_NRO_PILOTO_PG TO  SISCEL_PV
/
GRANT EXECUTE ON PV_NRO_PILOTO_PG TO SISCEL_VE
/

