GRANT EXECUTE ON PV_ORDEN_SERVICIO_PG TO CER_CPU
/
GRANT EXECUTE ON PV_ORDEN_SERVICIO_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_ORDEN_SERVICIO_PG TO SISCEL_CPU
/
GRANT EXECUTE ON PV_ORDEN_SERVICIO_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_ORDEN_SERVICIO_PG TO SISCEL_SELECT
/
