GRANT EXECUTE ON PV_PR_DEVVALPARAM TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_DEVVALPARAM TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_DEVVALPARAM TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_DEVVALPARAM TO SISCEL_SELECT
/
