GRANT EXECUTE ON PV_PR_AD_SERV_SUPLEM TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_AD_SERV_SUPLEM TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_AD_SERV_SUPLEM TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_AD_SERV_SUPLEM TO SISCEL_SELECT
/
