GRANT EXECUTE ON PV_PRC_CLIENTE_VAL_SITUACION TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_CLIENTE_VAL_SITUACION TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_CLIENTE_VAL_SITUACION TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_CLIENTE_VAL_SITUACION TO SISCEL_SELECT
/
