GRANT EXECUTE ON PV_PRC_CHEQUEOVENTAS TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_CHEQUEOVENTAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_CHEQUEOVENTAS TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_CHEQUEOVENTAS TO SISCEL_SELECT
/
