GRANT EXECUTE ON PV_PRC_INS_ICCMOVIMIENTO_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_INS_ICCMOVIMIENTO_PR TO SISCEL_GA
/
GRANT EXECUTE ON PV_PRC_INS_ICCMOVIMIENTO_PR TO SISCEL_GE
/
GRANT EXECUTE ON PV_PRC_INS_ICCMOVIMIENTO_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_INS_ICCMOVIMIENTO_PR TO SISCEL_SELECT
/
GRANT EXECUTE ON PV_PRC_INS_ICCMOVIMIENTO_PR TO SISCEL_VE
/
