GRANT EXECUTE ON PV_PRC_VAL_NUMMAXABO TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_VAL_NUMMAXABO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_VAL_NUMMAXABO TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_VAL_NUMMAXABO TO SISCEL_SELECT
/
