GRANT EXECUTE ON PV_PRC_UPDATE_RECARGAPREPAGO TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_UPDATE_RECARGAPREPAGO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_UPDATE_RECARGAPREPAGO TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_UPDATE_RECARGAPREPAGO TO SISCEL_SELECT
/
