GRANT EXECUTE ON PV_PRC_VAL_SUSPSERVICIO TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_VAL_SUSPSERVICIO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_VAL_SUSPSERVICIO TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_VAL_SUSPSERVICIO TO SISCEL_SELECT
/
