GRANT EXECUTE ON PV_PRC_VAL_AVISOSINIESTRO TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_VAL_AVISOSINIESTRO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_VAL_AVISOSINIESTRO TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_VAL_AVISOSINIESTRO TO SISCEL_SELECT
/
