GRANT EXECUTE ON PV_PRC_DELFRECUENTE TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_DELFRECUENTE TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_DELFRECUENTE TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_DELFRECUENTE TO SISCEL_SELECT
/
