GRANT EXECUTE ON PV_PR_EJECUTA_RESTRICCION TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_EJECUTA_RESTRICCION TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_EJECUTA_RESTRICCION TO SISCEL_GA
/
GRANT EXECUTE ON PV_PR_EJECUTA_RESTRICCION TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_EJECUTA_RESTRICCION TO SISCEL_SELECT
/
