GRANT EXECUTE ON PV_PRC_NOT_SERVTECNICO_CLIENTE TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_NOT_SERVTECNICO_CLIENTE TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_NOT_SERVTECNICO_CLIENTE TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_NOT_SERVTECNICO_CLIENTE TO SISCEL_SELECT
/
