GRANT EXECUTE ON PV_PRC_VAL_SUSPENSION TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_VAL_SUSPENSION TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_VAL_SUSPENSION TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_VAL_SUSPENSION TO SISCEL_SELECT
/
