GRANT EXECUTE ON PV_PR_ABOMINUTOS TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_ABOMINUTOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_ABOMINUTOS TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_ABOMINUTOS TO SISCEL_SELECT
/
