GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF TO SISCEL_SELECT
/
