GRANT     SELECT, INSERT, UPDATE, DELETE    ON PV_PENALIZACION_TMP TO SISCEL_ADMIN
/
GRANT     SELECT, INSERT, UPDATE, DELETE    ON PV_PENALIZACION_TMP TO SISCEL_PV
/
GRANT     SELECT, INSERT, UPDATE, DELETE    ON PV_PENALIZACION_TMP TO SISCEL_GA
/
GRANT     SELECT                            ON PV_PENALIZACION_TMP TO SISCEL_SELECT
/

