GRANT EXECUTE ON PV_PR_AD_SERV_SUPLEM_PK TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_AD_SERV_SUPLEM_PK TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_AD_SERV_SUPLEM_PK TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_AD_SERV_SUPLEM_PK TO SISCEL_SELECT
/
