GRANT EXECUTE ON PV_PLAN_FREEDOM_PK TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PLAN_FREEDOM_PK TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PLAN_FREEDOM_PK TO SISCEL_PV
/
GRANT EXECUTE ON PV_PLAN_FREEDOM_PK TO SISCEL_SELECT
/
