GRANT EXECUTE ON PV_PR_VALMIN_MDN TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_VALMIN_MDN TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_VALMIN_MDN TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_VALMIN_MDN TO SISCEL_SELECT
/
