GRANT EXECUTE ON PV_PR_SUSPENSION TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_SUSPENSION TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_SUSPENSION TO SISCEL_GA
/
GRANT EXECUTE ON PV_PR_SUSPENSION TO SISCEL_SELECT
/
