GRANT EXECUTE ON PV_PR_DEVALMACEN TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_DEVALMACEN TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_DEVALMACEN TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_DEVALMACEN TO SISCEL_SELECT
/
