GRANT      SELECT                                      ON PV_PRESTACION_OOSS_TO TO SISCEL_SELECT
/
GRANT      SELECT, INSERT, UPDATE, DELETE              ON PV_PRESTACION_OOSS_TO TO SISCEL_ADMIN
/
GRANT      SELECT, INSERT, UPDATE, DELETE              ON PV_PRESTACION_OOSS_TO TO SISCEL_PV
/


