GRANT EXECUTE ON PV_PR_REGULARIZACUENTA TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_REGULARIZACUENTA TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_REGULARIZACUENTA TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_REGULARIZACUENTA TO SISCEL_SELECT
/
