GRANT EXECUTE ON PV_PRC_VALFECCUMPLA_ABONADO TO CER_CPU
/
GRANT EXECUTE ON PV_PRC_VALFECCUMPLA_ABONADO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_VALFECCUMPLA_ABONADO TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_VALFECCUMPLA_ABONADO TO SISCEL_SELECT
/
