GRANT EXECUTE ON PV_PRC_FEC_CUMPLAN TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_FEC_CUMPLAN TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_FEC_CUMPLAN TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_FEC_CUMPLAN TO SISCEL_SELECT
/
