GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF_POS TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF_POS TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF_POS TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF_POS TO SISCEL_SELECT
/
