GRANT EXECUTE ON PV_PR_REHASUSPENSION TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_REHASUSPENSION TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_REHASUSPENSION TO SISCEL_GA
/
GRANT EXECUTE ON PV_PR_REHASUSPENSION TO SISCEL_SELECT
/
