GRANT EXECUTE ON PV_PR_BAJA_PREPAGO_PP_PR TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_BAJA_PREPAGO_PP_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_BAJA_PREPAGO_PP_PR TO SISCEL_GA
/
GRANT EXECUTE ON PV_PR_BAJA_PREPAGO_PP_PR TO SISCEL_SELECT
/
