GRANT EXECUTE ON PV_PRC_VAL_SUSPMORA TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_VAL_SUSPMORA TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_VAL_SUSPMORA TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_VAL_SUSPMORA TO SISCEL_SELECT
/
