GRANT EXECUTE ON PV_PRC_PORTABILIDAD_BA TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_PORTABILIDAD_BA TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_PORTABILIDAD_BA TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_PORTABILIDAD_BA TO SISCEL_SELECT
/
