GRANT EXECUTE ON PV_PRC_VAL_PLANTARIFIND TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_VAL_PLANTARIFIND TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_VAL_PLANTARIFIND TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_VAL_PLANTARIFIND TO SISCEL_SELECT
/
