GRANT EXECUTE ON PV_PRC_VALSITUABO_CLIENTE TO CER_CPU
/
GRANT EXECUTE ON PV_PRC_VALSITUABO_CLIENTE TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_VALSITUABO_CLIENTE TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_VALSITUABO_CLIENTE TO SISCEL_SELECT
/
