GRANT EXECUTE ON PV_PRC_BAJAMASIVA_PP_PR TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_BAJAMASIVA_PP_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_BAJAMASIVA_PP_PR TO SISCEL_GA
/
GRANT EXECUTE ON PV_PRC_BAJAMASIVA_PP_PR TO SISCEL_SELECT
/
