GRANT EXECUTE ON PV_PR_BAJAABONADO TO CER_CPU
/
GRANT EXECUTE ON PV_PR_BAJAABONADO TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_BAJAABONADO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_BAJAABONADO TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_BAJAABONADO TO SISCEL_SELECT
/
