GRANT EXECUTE ON PV_PR_SUSPVOLUNT TO CER_CPU
/
GRANT EXECUTE ON PV_PR_SUSPVOLUNT TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_SUSPVOLUNT TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_SUSPVOLUNT TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_SUSPVOLUNT TO SISCEL_SELECT
/
