GRANT EXECUTE ON PV_PRC_VAL_PERMISOS TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_VAL_PERMISOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_VAL_PERMISOS TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_VAL_PERMISOS TO SISCEL_SELECT
/
