GRANT EXECUTE ON PV_PRE_NOTACREDPARCIAL TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRE_NOTACREDPARCIAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRE_NOTACREDPARCIAL TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRE_NOTACREDPARCIAL TO SISCEL_SELECT
/
