GRANT EXECUTE ON PV_PRC_NOT_CAUSABAJAAMIS TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_NOT_CAUSABAJAAMIS TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_NOT_CAUSABAJAAMIS TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_NOT_CAUSABAJAAMIS TO SISCEL_SELECT
/
