GRANT EXECUTE ON PV_PR_BAJAAMISTAR TO CER_CPU
/
GRANT EXECUTE ON PV_PR_BAJAAMISTAR TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_BAJAAMISTAR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_BAJAAMISTAR TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_BAJAAMISTAR TO SISCEL_SELECT
/
