GRANT EXECUTE ON PV_PRC_VAL_SITUACIONCLIENTE TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_VAL_SITUACIONCLIENTE TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_VAL_SITUACIONCLIENTE TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_VAL_SITUACIONCLIENTE TO SISCEL_SELECT
/
