GRANT EXECUTE ON PV_PRC_PORTABILIDAD TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_PORTABILIDAD TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_PORTABILIDAD TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_PORTABILIDAD TO SISCEL_SELECT
/
