GRANT EXECUTE ON PV_PRC_PORTABILIDAD_CNT TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_PORTABILIDAD_CNT TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_PORTABILIDAD_CNT TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_PORTABILIDAD_CNT TO SISCEL_SELECT
/
