GRANT EXECUTE ON PV_PR_INSMOVIMIENTOS TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_INSMOVIMIENTOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_INSMOVIMIENTOS TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_INSMOVIMIENTOS TO SISCEL_SELECT
/
