GRANT EXECUTE ON PV_PRC_NOT_CAUSABAJATRAS TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_NOT_CAUSABAJATRAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_NOT_CAUSABAJATRAS TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_NOT_CAUSABAJATRAS TO SISCEL_SELECT
/
