GRANT EXECUTE ON PV_PLAN_INDEMNIZACION_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PLAN_INDEMNIZACION_PG TO SISCEL_CO
/
GRANT EXECUTE ON PV_PLAN_INDEMNIZACION_PG TO SISCEL_GA
/
GRANT EXECUTE ON PV_PLAN_INDEMNIZACION_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_PLAN_INDEMNIZACION_PG TO SISCEL_SELECT
/
