GRANT EXECUTE ON PV_PR_NUMDUPLICADO TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_NUMDUPLICADO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_NUMDUPLICADO TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_NUMDUPLICADO TO SISCEL_SELECT
/
