GRANT EXECUTE ON PV_PRC_PERFILDCTO_USUARIO TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_PERFILDCTO_USUARIO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_PERFILDCTO_USUARIO TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_PERFILDCTO_USUARIO TO SISCEL_SELECT
/
