GRANT EXECUTE ON PV_PRC_EJECUTA_OSPENDIENTES TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_EJECUTA_OSPENDIENTES TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_EJECUTA_OSPENDIENTES TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_EJECUTA_OSPENDIENTES TO SISCEL_SELECT
/
