GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF_PRE TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF_PRE TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF_PRE TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_NO_ES_SS_PLAN_DEF_PRE TO SISCEL_SELECT
/
