GRANT EXECUTE ON PV_PRC_VAL_FECHAANULBAJA TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_VAL_FECHAANULBAJA TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_VAL_FECHAANULBAJA TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_VAL_FECHAANULBAJA TO SISCEL_SELECT
/
