GRANT EXECUTE ON PV_PR_RESP_CENTRAL TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_RESP_CENTRAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_RESP_CENTRAL TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_RESP_CENTRAL TO SISCEL_SELECT
/
