GRANT EXECUTE ON PV_PCK_PROC_FACTUR TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PCK_PROC_FACTUR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PCK_PROC_FACTUR TO SISCEL_PV
/
GRANT EXECUTE ON PV_PCK_PROC_FACTUR TO SISCEL_SELECT
/
