GRANT EXECUTE ON PV_PR_CAMBIO_MIN TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PR_CAMBIO_MIN TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PR_CAMBIO_MIN TO SISCEL_PV
/
GRANT EXECUTE ON PV_PR_CAMBIO_MIN TO SISCEL_SELECT
/
