GRANT EXECUTE ON PV_PRC_NOT_SERVTECNICO TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_PRC_NOT_SERVTECNICO TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_PRC_NOT_SERVTECNICO TO SISCEL_PV
/
GRANT EXECUTE ON PV_PRC_NOT_SERVTECNICO TO SISCEL_SELECT
/
