GRANT SELECT                            ON PV_REG_SUSTOT_JOB_TO TO SISCEL_SELECT
/
GRANT SELECT, INSERT,DELETE,UPDATE      ON PV_REG_SUSTOT_JOB_TO TO SISCEL_ADMIN
/
GRANT SELECT, INSERT,DELETE,UPDATE      ON PV_REG_SUSTOT_JOB_TO TO SISCEL_PV
/

