GRANT   SELECT                           ON PV_REGISTRA_RENOVACION_OS_TO TO SISCEL_SELECT
/
GRANT   SELECT, INSERT, UPDATE, DELETE   ON PV_REGISTRA_RENOVACION_OS_TO TO SISCEL_ADMIN
/
GRANT   SELECT, INSERT, UPDATE, DELETE   ON PV_REGISTRA_RENOVACION_OS_TO TO SISCEL_PV
/

