GRANT DELETE ON PV_RELACION_ART_PLAN_TO TO PV_ADMIN_RO
/
GRANT INSERT ON PV_RELACION_ART_PLAN_TO TO PV_ADMIN_RO
/
GRANT SELECT ON PV_RELACION_ART_PLAN_TO TO PV_ADMIN_RO
/
GRANT UPDATE ON PV_RELACION_ART_PLAN_TO TO PV_ADMIN_RO
/
