GRANT EXECUTE ON PV_REORDENAMIENTO_PG TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_REORDENAMIENTO_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_REORDENAMIENTO_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_REORDENAMIENTO_PG TO SISCEL_SELECT
/
