GRANT EXECUTE ON PV_REORDENAMIENTOINFAC_PR TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_REORDENAMIENTOINFAC_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_REORDENAMIENTOINFAC_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_REORDENAMIENTOINFAC_PR TO SISCEL_SELECT
/
