GRANT  SELECT                            ON PV_RENOVACIONES_TD TO SISCEL_SELECT
/
GRANT  SELECT, INSERT, UPDATE, DELETE    ON PV_RENOVACIONES_TD TO SISCEL_ADMIN
/
GRANT  SELECT, INSERT, UPDATE, DELETE    ON PV_RENOVACIONES_TD TO SISCEL_PV
/

