GRANT DELETE ON PV_SERVSUPL_HOMTEC_TD TO SISCEL_ADMIN
/
GRANT INSERT ON PV_SERVSUPL_HOMTEC_TD TO SISCEL_ADMIN
/
GRANT SELECT ON PV_SERVSUPL_HOMTEC_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON PV_SERVSUPL_HOMTEC_TD TO SISCEL_ADMIN
/
GRANT SELECT ON PV_SERVSUPL_HOMTEC_TD TO SISCEL_SELECT
/
