GRANT DELETE ON PV_SERIELN_ERROR_TO TO SISCEL_ADMIN
/
GRANT INSERT ON PV_SERIELN_ERROR_TO TO SISCEL_ADMIN
/
GRANT SELECT ON PV_SERIELN_ERROR_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON PV_SERIELN_ERROR_TO TO SISCEL_ADMIN
/
GRANT SELECT ON PV_SERIELN_ERROR_TO TO SISCEL_SELECT
/
GRANT SELECT ON PV_SERIELN_ERROR_TO TO SOLO_CONSULTA_SISCEL
/
