GRANT EXECUTE ON PV_SERV_SUPLE_II_PG TO FAC_SISCEL
/
GRANT EXECUTE ON PV_SERV_SUPLE_II_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_SERV_SUPLE_II_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_SERV_SUPLE_II_PG TO SISCEL_SELECT
/
