GRANT EXECUTE ON PV_TRATAMIENTO_SS_PG TO CER_CPU
/
GRANT EXECUTE ON PV_TRATAMIENTO_SS_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_TRATAMIENTO_SS_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_TRATAMIENTO_SS_PG TO SISCEL_SELECT
/
