GRANT EXECUTE ON PV_TRASPASO_INDACTUAC_PG TO CER_CPU
/
GRANT EXECUTE ON PV_TRASPASO_INDACTUAC_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_TRASPASO_INDACTUAC_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_TRASPASO_INDACTUAC_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON PV_TRASPASO_INDACTUAC_PG TO SISCEL_VE
/
