GRANT DELETE ON PV_TECNO_ACTABO_TD TO SISCEL_ADMIN
/
GRANT INSERT ON PV_TECNO_ACTABO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON PV_TECNO_ACTABO_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON PV_TECNO_ACTABO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON PV_TECNO_ACTABO_TD TO SISCEL_SELECT
/
