GRANT DELETE ON PV_UMBRAL_TO TO SISCEL_ADMIN
/
GRANT INSERT ON PV_UMBRAL_TO TO SISCEL_ADMIN
/
GRANT SELECT ON PV_UMBRAL_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON PV_UMBRAL_TO TO SISCEL_ADMIN
/
GRANT SELECT ON PV_UMBRAL_TO TO SISCEL_SELECT
/
