GRANT EXECUTE ON PV_VER_VIGENCIA_FN TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_VER_VIGENCIA_FN TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_VER_VIGENCIA_FN TO SISCEL_PV
/
GRANT EXECUTE ON PV_VER_VIGENCIA_FN TO SISCEL_SELECT
/
