GRANT EXECUTE ON PV_VALPLANTIPPLAN_PR TO CER_CPU
/
GRANT EXECUTE ON PV_VALPLANTIPPLAN_PR TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_VALPLANTIPPLAN_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_VALPLANTIPPLAN_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_VALPLANTIPPLAN_PR TO SISCEL_SELECT
/
