GRANT EXECUTE ON PV_VAL_FECFINPLAN_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_VAL_FECFINPLAN_PR TO SISCEL_GA
/
GRANT EXECUTE ON PV_VAL_FECFINPLAN_PR TO SISCEL_GE
/
GRANT EXECUTE ON PV_VAL_FECFINPLAN_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_VAL_FECFINPLAN_PR TO SISCEL_RE
/
GRANT EXECUTE ON PV_VAL_FECFINPLAN_PR TO SISCEL_SELECT
/
