GRANT EXECUTE ON PV_VALCANSUSABO_CLIENTE_PR TO CER_CPU
/
GRANT EXECUTE ON PV_VALCANSUSABO_CLIENTE_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_VALCANSUSABO_CLIENTE_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_VALCANSUSABO_CLIENTE_PR TO SISCEL_SELECT
/
