GRANT EXECUTE ON PV_VAL_COMODATO_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_VAL_COMODATO_PR TO SISCEL_CO
/
GRANT EXECUTE ON PV_VAL_COMODATO_PR TO SISCEL_GA
/
GRANT EXECUTE ON PV_VAL_COMODATO_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_VAL_COMODATO_PR TO SISCEL_SELECT
/
