GRANT EXECUTE ON PV_VALABOTIPPLAN_PR TO EBZ_SISCEL
/
GRANT EXECUTE ON PV_VALABOTIPPLAN_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_VALABOTIPPLAN_PR TO SISCEL_PV
/
GRANT EXECUTE ON PV_VALABOTIPPLAN_PR TO SISCEL_SELECT
/
