GRANT EXECUTE ON PV_VIGENCIA_DIRECCION_PG TO GE_ADMIN_RO
/
GRANT EXECUTE ON PV_VIGENCIA_DIRECCION_PG TO GE_CONSULTA_RO
/
GRANT EXECUTE ON PV_VIGENCIA_DIRECCION_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON PV_VIGENCIA_DIRECCION_PG TO SISCEL_PV
/
GRANT EXECUTE ON PV_VIGENCIA_DIRECCION_PG TO SISCEL_SELECT
/
