GRANT EXECUTE ON PVERIFICA_RANGOS TO EBZ_SISCEL
/
GRANT EXECUTE ON PVERIFICA_RANGOS TO SISCEL_ADMIN
/
GRANT EXECUTE ON PVERIFICA_RANGOS TO SISCEL_GE
/
GRANT EXECUTE ON PVERIFICA_RANGOS TO SISCEL_SELECT
/
