GRANT SELECT ON RE_SEQ_SUBTEL TO EBZ_SISCEL
/
GRANT ALTER ON RE_SEQ_SUBTEL TO SISCEL_ADMIN
/
GRANT SELECT ON RE_SEQ_SUBTEL TO SISCEL_ADMIN
/
GRANT SELECT ON RE_SEQ_SUBTEL TO SISCEL_RE
/
GRANT SELECT ON RE_SEQ_SUBTEL TO SISCEL_SELECT
/
