GRANT SELECT ON RE_SEQ_NUM_INCIDENCIA TO EBZ_SISCEL
/
GRANT ALTER ON RE_SEQ_NUM_INCIDENCIA TO SISCEL_ADMIN
/
GRANT SELECT ON RE_SEQ_NUM_INCIDENCIA TO SISCEL_ADMIN
/
GRANT SELECT ON RE_SEQ_NUM_INCIDENCIA TO SISCEL_RE
/
GRANT SELECT ON RE_SEQ_NUM_INCIDENCIA TO SISCEL_SELECT
/
