GRANT SELECT ON RE_SEQ_STARTEL TO EBZ_SISCEL
/
GRANT ALTER ON RE_SEQ_STARTEL TO SISCEL_ADMIN
/
GRANT SELECT ON RE_SEQ_STARTEL TO SISCEL_ADMIN
/
GRANT SELECT ON RE_SEQ_STARTEL TO SISCEL_RE
/
GRANT SELECT ON RE_SEQ_STARTEL TO SISCEL_SELECT
/
