GRANT DELETE ON REC_EXTERNA_CONT TO PUBLIC
/
GRANT INSERT ON REC_EXTERNA_CONT TO PUBLIC
/
GRANT SELECT ON REC_EXTERNA_CONT TO PUBLIC
/
GRANT UPDATE ON REC_EXTERNA_CONT TO PUBLIC
/
GRANT SELECT ON REC_EXTERNA_CONT TO SOLO_CONSULTA_SISCEL
/
