GRANT DELETE ON RECAUDA_DEPOSITO_CTA TO PUBLIC
/
GRANT INSERT ON RECAUDA_DEPOSITO_CTA TO PUBLIC
/
GRANT SELECT ON RECAUDA_DEPOSITO_CTA TO PUBLIC
/
GRANT UPDATE ON RECAUDA_DEPOSITO_CTA TO PUBLIC
/
GRANT SELECT ON RECAUDA_DEPOSITO_CTA TO SOLO_CONSULTA_SISCEL
/
