GRANT ALTER ON RED_ORIGEN_CATEGORIA TO EBZ_SISCEL
/
GRANT DELETE ON RED_ORIGEN_CATEGORIA TO EBZ_SISCEL
/
GRANT INDEX ON RED_ORIGEN_CATEGORIA TO EBZ_SISCEL
/
GRANT INSERT ON RED_ORIGEN_CATEGORIA TO EBZ_SISCEL
/
GRANT REFERENCES ON RED_ORIGEN_CATEGORIA TO EBZ_SISCEL
/
GRANT SELECT ON RED_ORIGEN_CATEGORIA TO EBZ_SISCEL
/
GRANT UPDATE ON RED_ORIGEN_CATEGORIA TO EBZ_SISCEL
/
GRANT DELETE ON RED_ORIGEN_CATEGORIA TO SISCEL_ADMIN
/
GRANT INSERT ON RED_ORIGEN_CATEGORIA TO SISCEL_ADMIN
/
GRANT SELECT ON RED_ORIGEN_CATEGORIA TO SISCEL_ADMIN
/
GRANT UPDATE ON RED_ORIGEN_CATEGORIA TO SISCEL_ADMIN
/
GRANT DELETE ON RED_ORIGEN_CATEGORIA TO SISCEL_RE
/
GRANT INSERT ON RED_ORIGEN_CATEGORIA TO SISCEL_RE
/
GRANT SELECT ON RED_ORIGEN_CATEGORIA TO SISCEL_RE
/
GRANT UPDATE ON RED_ORIGEN_CATEGORIA TO SISCEL_RE
/
GRANT SELECT ON RED_ORIGEN_CATEGORIA TO SISCEL_SELECT
/
GRANT SELECT ON RED_ORIGEN_CATEGORIA TO SOLO_CONSULTA_SISCEL
/
