GRANT DELETE ON REVERSA_CICLO TO OPS$XPFACTUR
/
GRANT INSERT ON REVERSA_CICLO TO OPS$XPFACTUR
/
GRANT SELECT ON REVERSA_CICLO TO OPS$XPFACTUR
/
GRANT UPDATE ON REVERSA_CICLO TO OPS$XPFACTUR
/
GRANT SELECT ON REVERSA_CICLO TO SISCEL_SELECT
/
GRANT SELECT ON REVERSA_CICLO TO SOLO_CONSULTA_SISCEL
/
