GRANT DELETE ON SC_COBROS_LOTE_TD TO SISCEL_ADMIN
/
GRANT INSERT ON SC_COBROS_LOTE_TD TO SISCEL_ADMIN
/
GRANT SELECT ON SC_COBROS_LOTE_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON SC_COBROS_LOTE_TD TO SISCEL_ADMIN
/
GRANT SELECT ON SC_COBROS_LOTE_TD TO SISCEL_SELECT
/
GRANT SELECT ON SC_COBROS_LOTE_TD TO SOLO_CONSULTA_SISCEL
/
