GRANT DELETE ON SC_GRPCONCEPTO_TD TO SISCEL_ADMIN
/
GRANT INSERT ON SC_GRPCONCEPTO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON SC_GRPCONCEPTO_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON SC_GRPCONCEPTO_TD TO SISCEL_ADMIN
/
GRANT DELETE ON SC_GRPCONCEPTO_TD TO SISCEL_FA
/
GRANT INSERT ON SC_GRPCONCEPTO_TD TO SISCEL_FA
/
GRANT UPDATE ON SC_GRPCONCEPTO_TD TO SISCEL_FA
/
GRANT SELECT ON SC_GRPCONCEPTO_TD TO SISCEL_SELECT
/
GRANT SELECT ON SC_GRPCONCEPTO_TD TO SOLO_CONSULTA_SISCEL
/
