GRANT DELETE ON SC_INDAPERTURA_TD TO SISCEL_ADMIN
/
GRANT INSERT ON SC_INDAPERTURA_TD TO SISCEL_ADMIN
/
GRANT SELECT ON SC_INDAPERTURA_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON SC_INDAPERTURA_TD TO SISCEL_ADMIN
/
GRANT SELECT ON SC_INDAPERTURA_TD TO SISCEL_SELECT
/
GRANT SELECT ON SC_INDAPERTURA_TD TO SOLO_CONSULTA_SISCEL
/
