GRANT EXECUTE ON SC_P_GENERA_ASIENTO TO EBZ_SISCEL
/
GRANT EXECUTE ON SC_P_GENERA_ASIENTO TO SISCEL_ADMIN
/
GRANT EXECUTE ON SC_P_GENERA_ASIENTO TO SISCEL_SC
/
GRANT EXECUTE ON SC_P_GENERA_ASIENTO TO SISCEL_SELECT
/
