GRANT EXECUTE ON SC_P_INGRESA_LOTE TO EBZ_SISCEL
/
GRANT EXECUTE ON SC_P_INGRESA_LOTE TO SISCEL_ADMIN
/
GRANT EXECUTE ON SC_P_INGRESA_LOTE TO SISCEL_SC
/
GRANT EXECUTE ON SC_P_INGRESA_LOTE TO SISCEL_SELECT
/
