GRANT DELETE ON SP_CAUSALES_CIERRE_TD TO SISCEL_ADMIN
/
GRANT INSERT ON SP_CAUSALES_CIERRE_TD TO SISCEL_ADMIN
/
GRANT SELECT ON SP_CAUSALES_CIERRE_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON SP_CAUSALES_CIERRE_TD TO SISCEL_ADMIN
/
GRANT SELECT ON SP_CAUSALES_CIERRE_TD TO SISCEL_SELECT
/
