GRANT EXECUTE ON SP_FN_GETDECIMAL TO EBZ_SISCEL
/
GRANT EXECUTE ON SP_FN_GETDECIMAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON SP_FN_GETDECIMAL TO SISCEL_SELECT
/
GRANT EXECUTE ON SP_FN_GETDECIMAL TO SISCEL_ST
/
