GRANT EXECUTE ON SP_FN_RETORNA_QRY TO EBZ_SISCEL
/
GRANT EXECUTE ON SP_FN_RETORNA_QRY TO SISCEL_ADMIN
/
GRANT EXECUTE ON SP_FN_RETORNA_QRY TO SISCEL_SELECT
/
GRANT EXECUTE ON SP_FN_RETORNA_QRY TO SISCEL_ST
/
