GRANT EXECUTE ON SP_FN_FORMATO_NUMERO TO EBZ_SISCEL
/
GRANT EXECUTE ON SP_FN_FORMATO_NUMERO TO SISCEL_ADMIN
/
GRANT EXECUTE ON SP_FN_FORMATO_NUMERO TO SISCEL_SELECT
/
GRANT EXECUTE ON SP_FN_FORMATO_NUMERO TO SISCEL_ST
/
