GRANT   SELECT                                                            ON SP_FALLAS_INICIALES_TD TO SISCEL_SELECT
/
GRANT   SELECT, INSERT, UPDATE, DELETE           ON SP_FALLAS_INICIALES_TD TO SISCEL_ST
/
