GRANT DELETE ON SP_FORMA_PAGO TO SISCEL_ADMIN
/
GRANT INSERT ON SP_FORMA_PAGO TO SISCEL_ADMIN
/
GRANT SELECT ON SP_FORMA_PAGO TO SISCEL_ADMIN
/
GRANT UPDATE ON SP_FORMA_PAGO TO SISCEL_ADMIN
/
GRANT DELETE ON SP_FORMA_PAGO TO SISCEL_GA
/
GRANT INSERT ON SP_FORMA_PAGO TO SISCEL_GA
/
GRANT SELECT ON SP_FORMA_PAGO TO SISCEL_GA
/
GRANT UPDATE ON SP_FORMA_PAGO TO SISCEL_GA
/
GRANT SELECT ON SP_FORMA_PAGO TO SISCEL_SELECT
/
GRANT SELECT ON SP_FORMA_PAGO TO SOLO_CONSULTA_SISCEL
/
