GRANT EXECUTE ON SP_FN_FORMATOFECHA TO EBZ_SISCEL
/
GRANT EXECUTE ON SP_FN_FORMATOFECHA TO SISCEL_ADMIN
/
GRANT EXECUTE ON SP_FN_FORMATOFECHA TO SISCEL_SELECT
/
GRANT EXECUTE ON SP_FN_FORMATOFECHA TO SISCEL_ST
/
