GRANT DELETE ON SP_HREPUESTOS TO SISCEL_ADMIN
/
GRANT INSERT ON SP_HREPUESTOS TO SISCEL_ADMIN
/
GRANT SELECT ON SP_HREPUESTOS TO SISCEL_ADMIN
/
GRANT UPDATE ON SP_HREPUESTOS TO SISCEL_ADMIN
/
GRANT SELECT ON SP_HREPUESTOS TO SISCEL_SELECT
/
GRANT DELETE ON SP_HREPUESTOS TO SISCEL_ST
/
GRANT INSERT ON SP_HREPUESTOS TO SISCEL_ST
/
GRANT SELECT ON SP_HREPUESTOS TO SISCEL_ST
/
GRANT UPDATE ON SP_HREPUESTOS TO SISCEL_ST
/
GRANT SELECT ON SP_HREPUESTOS TO SOLO_CONSULTA_SISCEL
/
