GRANT   SELECT                                                            ON SP_OBSERVACIONES_ORDEN_TO TO SISCEL_SELECT
/
GRANT   SELECT, INSERT, UPDATE, DELETE           ON SP_OBSERVACIONES_ORDEN_TO TO SISCEL_ST
/

