GRANT DELETE ON SP_REPUESTOS TO SISCEL_ADMIN
/
GRANT INSERT ON SP_REPUESTOS TO SISCEL_ADMIN
/
GRANT SELECT ON SP_REPUESTOS TO SISCEL_ADMIN
/
GRANT UPDATE ON SP_REPUESTOS TO SISCEL_ADMIN
/
GRANT SELECT ON SP_REPUESTOS TO SISCEL_SELECT
/
GRANT DELETE ON SP_REPUESTOS TO SISCEL_ST
/
GRANT INSERT ON SP_REPUESTOS TO SISCEL_ST
/
GRANT SELECT ON SP_REPUESTOS TO SISCEL_ST
/
GRANT UPDATE ON SP_REPUESTOS TO SISCEL_ST
/
GRANT SELECT ON SP_REPUESTOS TO SOLO_CONSULTA_SISCEL
/
