GRANT SELECT ON SP_SEQ_ORDEN TO EBZ_SISCEL
/
GRANT ALTER ON SP_SEQ_ORDEN TO SISCEL_ADMIN
/
GRANT SELECT ON SP_SEQ_ORDEN TO SISCEL_ADMIN
/
GRANT SELECT ON SP_SEQ_ORDEN TO SISCEL_SELECT
/
GRANT SELECT ON SP_SEQ_ORDEN TO SISCEL_ST
/
