GRANT SELECT ON SP_SEQ_PETIGUIAS TO EBZ_SISCEL
/
GRANT ALTER ON SP_SEQ_PETIGUIAS TO SISCEL_ADMIN
/
GRANT SELECT ON SP_SEQ_PETIGUIAS TO SISCEL_ADMIN
/
GRANT SELECT ON SP_SEQ_PETIGUIAS TO SISCEL_SELECT
/
GRANT SELECT ON SP_SEQ_PETIGUIAS TO SISCEL_ST
/
