GRANT SELECT ON SP_SEQ_SOLICITUD TO EBZ_SISCEL
/
GRANT ALTER ON SP_SEQ_SOLICITUD TO SISCEL_ADMIN
/
GRANT SELECT ON SP_SEQ_SOLICITUD TO SISCEL_ADMIN
/
GRANT SELECT ON SP_SEQ_SOLICITUD TO SISCEL_SELECT
/
GRANT SELECT ON SP_SEQ_SOLICITUD TO SISCEL_ST
/
