GRANT SELECT ON SP_VCOMPROBANTE_ORDEN TO SISCEL_SELECT
/
GRANT SELECT ON SP_VCOMPROBANTE_ORDEN TO SISCEL_ST
/
GRANT SELECT ON SP_VCOMPROBANTE_ORDEN TO SISCEL_ADMIN
/
GRANT SELECT ON SP_VCOMPROBANTE_ORDEN TO EBZ_SISCEL
/
