GRANT DELETE ON SUCUR_PRIN_WMD TO PUBLIC
/
GRANT INSERT ON SUCUR_PRIN_WMD TO PUBLIC
/
GRANT SELECT ON SUCUR_PRIN_WMD TO PUBLIC
/
GRANT UPDATE ON SUCUR_PRIN_WMD TO PUBLIC
/
GRANT SELECT ON SUCUR_PRIN_WMD TO SOLO_CONSULTA_SISCEL
/
