GRANT DELETE ON TA_LRNOPERADOR TO SISCEL_ADMIN
/
GRANT INSERT ON TA_LRNOPERADOR TO SISCEL_ADMIN
/
GRANT SELECT ON TA_LRNOPERADOR TO SISCEL_ADMIN
/
GRANT UPDATE ON TA_LRNOPERADOR TO SISCEL_ADMIN
/
GRANT SELECT ON TA_LRNOPERADOR TO SISCEL_SELECT
/
GRANT SELECT ON TA_LRNOPERADOR TO SOLO_CONSULTA_SISCEL
/
