GRANT DELETE ON TA_PREPAGO_PASO TO SISCEL_ADMIN
/
GRANT INSERT ON TA_PREPAGO_PASO TO SISCEL_ADMIN
/
GRANT SELECT ON TA_PREPAGO_PASO TO SISCEL_ADMIN
/
GRANT UPDATE ON TA_PREPAGO_PASO TO SISCEL_ADMIN
/
GRANT SELECT ON TA_PREPAGO_PASO TO SISCEL_SELECT
/
GRANT DELETE ON TA_PREPAGO_PASO TO SISCEL_TA
/
GRANT INSERT ON TA_PREPAGO_PASO TO SISCEL_TA
/
GRANT SELECT ON TA_PREPAGO_PASO TO SISCEL_TA
/
GRANT UPDATE ON TA_PREPAGO_PASO TO SISCEL_TA
/
GRANT SELECT ON TA_PREPAGO_PASO TO SOLO_CONSULTA_SISCEL
/
