GRANT DELETE ON TA_PREPAGO TO SISCEL_ADMIN
/
GRANT INSERT ON TA_PREPAGO TO SISCEL_ADMIN
/
GRANT SELECT ON TA_PREPAGO TO SISCEL_ADMIN
/
GRANT UPDATE ON TA_PREPAGO TO SISCEL_ADMIN
/
GRANT SELECT ON TA_PREPAGO TO SISCEL_SELECT
/
GRANT DELETE ON TA_PREPAGO TO SISCEL_TA
/
GRANT INSERT ON TA_PREPAGO TO SISCEL_TA
/
GRANT SELECT ON TA_PREPAGO TO SISCEL_TA
/
GRANT UPDATE ON TA_PREPAGO TO SISCEL_TA
/
GRANT SELECT ON TA_PREPAGO TO SOLO_CONSULTA_SISCEL
/
