GRANT SELECT ON TA_SEC_HTOTREK TO EBZ_SISCEL
/
GRANT ALTER ON TA_SEC_HTOTREK TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_HTOTREK TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_HTOTREK TO SISCEL_SELECT
/
GRANT SELECT ON TA_SEC_HTOTREK TO SISCEL_TA
/
