GRANT SELECT ON TA_SEC_HTOMOT TO EBZ_SISCEL
/
GRANT ALTER ON TA_SEC_HTOMOT TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_HTOMOT TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_HTOMOT TO SISCEL_SELECT
/
GRANT SELECT ON TA_SEC_HTOMOT TO SISCEL_TA
/
