GRANT SELECT ON TA_SEC_HTOERI TO EBZ_SISCEL
/
GRANT ALTER ON TA_SEC_HTOERI TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_HTOERI TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_HTOERI TO SISCEL_SELECT
/
GRANT SELECT ON TA_SEC_HTOERI TO SISCEL_TA
/
