GRANT SELECT ON TA_SEC_FRAUDE TO EBZ_SISCEL
/
GRANT ALTER ON TA_SEC_FRAUDE TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_FRAUDE TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_FRAUDE TO SISCEL_SELECT
/
GRANT SELECT ON TA_SEC_FRAUDE TO SISCEL_TA
/
