GRANT SELECT ON TA_SEC_DETTREK TO EBZ_SISCEL
/
GRANT ALTER ON TA_SEC_DETTREK TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_DETTREK TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_DETTREK TO SISCEL_SELECT
/
GRANT SELECT ON TA_SEC_DETTREK TO SISCEL_TA
/
