GRANT SELECT ON TA_SEC_DETFRAUDE TO EBZ_SISCEL
/
GRANT ALTER ON TA_SEC_DETFRAUDE TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_DETFRAUDE TO SISCEL_ADMIN
/
GRANT SELECT ON TA_SEC_DETFRAUDE TO SISCEL_SELECT
/
GRANT SELECT ON TA_SEC_DETFRAUDE TO SISCEL_TA
/
