GRANT DELETE ON TAH_PREPAGO TO SISCEL_ADMIN
/
GRANT INSERT ON TAH_PREPAGO TO SISCEL_ADMIN
/
GRANT SELECT ON TAH_PREPAGO TO SISCEL_ADMIN
/
GRANT UPDATE ON TAH_PREPAGO TO SISCEL_ADMIN
/
GRANT SELECT ON TAH_PREPAGO TO SISCEL_SELECT
/
GRANT DELETE ON TAH_PREPAGO TO SISCEL_TA
/
GRANT INSERT ON TAH_PREPAGO TO SISCEL_TA
/
GRANT SELECT ON TAH_PREPAGO TO SISCEL_TA
/
GRANT UPDATE ON TAH_PREPAGO TO SISCEL_TA
/
GRANT SELECT ON TAH_PREPAGO TO SOLO_CONSULTA_SISCEL
/
