GRANT DELETE ON TECNO_WMD_SUC TO PUBLIC
/
GRANT INSERT ON TECNO_WMD_SUC TO PUBLIC
/
GRANT SELECT ON TECNO_WMD_SUC TO PUBLIC
/
GRANT UPDATE ON TECNO_WMD_SUC TO PUBLIC
/
GRANT SELECT ON TECNO_WMD_SUC TO SOLO_CONSULTA_SISCEL
/
