GRANT DELETE ON TMM_INTRARED TO OPS$XPFACTUR
/
GRANT INSERT ON TMM_INTRARED TO OPS$XPFACTUR
/
GRANT SELECT ON TMM_INTRARED TO OPS$XPFACTUR
/
GRANT UPDATE ON TMM_INTRARED TO OPS$XPFACTUR
/
GRANT SELECT ON TMM_INTRARED TO SOLO_CONSULTA_SISCEL
/
