GRANT EXECUTE ON TO_SERVICIOS_TOL_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON TO_SERVICIOS_TOL_PG TO SISCEL_GA
/
GRANT EXECUTE ON TO_SERVICIOS_TOL_PG TO SISCEL_PV
/
GRANT EXECUTE ON TO_SERVICIOS_TOL_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON TO_SERVICIOS_TOL_PG TO SISCEL_VE
/
