GRANT DELETE ON TOL_HISTACUMOPER TO SISCEL_ADMIN
/
GRANT INSERT ON TOL_HISTACUMOPER TO SISCEL_ADMIN
/
GRANT SELECT ON TOL_HISTACUMOPER TO SISCEL_ADMIN
/
GRANT UPDATE ON TOL_HISTACUMOPER TO SISCEL_ADMIN
/
GRANT SELECT ON TOL_HISTACUMOPER TO SISCEL_SELECT
/
GRANT SELECT ON TOL_HISTACUMOPER TO SOLO_CONSULTA_SISCEL
/
