GRANT DELETE ON TOL_AGRZONAIMP_TO TO SISCEL_ADMIN
/
GRANT INSERT ON TOL_AGRZONAIMP_TO TO SISCEL_ADMIN
/
GRANT SELECT ON TOL_AGRZONAIMP_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON TOL_AGRZONAIMP_TO TO SISCEL_ADMIN
/
GRANT SELECT ON TOL_AGRZONAIMP_TO TO SISCEL_SELECT
/
