GRANT SELECT ON TR_SEQ_NUMMOV TO EBZ_SISCEL
/
GRANT SELECT ON TR_SEQ_NUMMOV TO SISCEL_ADMIN
/
GRANT ALTER ON TR_SEQ_NUMMOV TO SISCEL_SELECT
/
GRANT SELECT ON TR_SEQ_NUMMOV TO SISCEL_SELECT
/
GRANT SELECT ON TR_SEQ_NUMMOV TO SISCEL_TR
/
