GRANT EXECUTE ON VE_CREA_LINEA_VENTA_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_CREA_LINEA_VENTA_PG TO SISCEL_GA
/
GRANT EXECUTE ON VE_CREA_LINEA_VENTA_PG TO SISCEL_PV
/
GRANT EXECUTE ON VE_CREA_LINEA_VENTA_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON VE_CREA_LINEA_VENTA_PG TO SISCEL_VE
/
