GRANT DELETE ON VE_CODIGOSPROCESOS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON VE_CODIGOSPROCESOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_CODIGOSPROCESOS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON VE_CODIGOSPROCESOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_CODIGOSPROCESOS_TD TO SISCEL_SELECT
/
