GRANT DELETE ON VE_CASOS_MIGRACION_TD TO SISCEL_ADMIN
/
GRANT INSERT ON VE_CASOS_MIGRACION_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_CASOS_MIGRACION_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON VE_CASOS_MIGRACION_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_CASOS_MIGRACION_TD TO SISCEL_SELECT
/
GRANT SELECT ON VE_CASOS_MIGRACION_TD TO SOLO_CONSULTA_SISCEL
/
