GRANT EXECUTE ON VE_DESBLOQUEAPREPAGO_SMS_PG TO FAC_SISCEL
/
GRANT EXECUTE ON VE_DESBLOQUEAPREPAGO_SMS_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_DESBLOQUEAPREPAGO_SMS_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON VE_DESBLOQUEAPREPAGO_SMS_PG TO SISCEL_VE
/
