GRANT SELECT                            ON VE_ELEMENTOS_ACTIVOS_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_ELEMENTOS_ACTIVOS_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_ELEMENTOS_ACTIVOS_TD TO SISCEL_GE
/

