GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON SISCEL.VE_EXCEPCION_CALIFICACION_TD TO SISCEL_ADMIN;

GRANT DELETE, INSERT, SELECT, UPDATE ON SISCEL.VE_EXCEPCION_CALIFICACION_TD TO SISCEL_GA;

GRANT SELECT ON SISCEL.VE_EXCEPCION_CALIFICACION_TD TO SISCEL_SELECT;

GRANT ALTER, DELETE, INSERT, SELECT ON SISCEL.VE_EXCEPCION_CALIFICACION_TD TO SISCEL_VE;