GRANT SELECT                            ON VE_ESTADOSOLIC_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_ESTADOSOLIC_TD TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_ESTADOSOLIC_TD TO SISCEL_VE
/

