GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON SISCEL.VE_HISTORICO_LABORAL_BURO_TO TO SISCEL_ADMIN;

GRANT DELETE, INSERT, SELECT, UPDATE ON SISCEL.VE_HISTORICO_LABORAL_BURO_TO TO SISCEL_GA;

GRANT SELECT ON SISCEL.VE_HISTORICO_LABORAL_BURO_TO TO SISCEL_SELECT;

GRANT ALTER, DELETE, INSERT, SELECT ON SISCEL.VE_HISTORICO_LABORAL_BURO_TO TO SISCEL_VE;