GRANT DELETE ON VE_LIMITE_PREPAGO_TD TO SISCEL_ADMIN
/
GRANT INSERT ON VE_LIMITE_PREPAGO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_LIMITE_PREPAGO_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON VE_LIMITE_PREPAGO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_LIMITE_PREPAGO_TD TO SISCEL_SELECT
/
GRANT DELETE ON VE_LIMITE_PREPAGO_TD TO SISCEL_VE
/
GRANT INSERT ON VE_LIMITE_PREPAGO_TD TO SISCEL_VE
/
GRANT SELECT ON VE_LIMITE_PREPAGO_TD TO SISCEL_VE
/
GRANT UPDATE ON VE_LIMITE_PREPAGO_TD TO SISCEL_VE
/
