GRANT DELETE ON VE_MATRIZESTADOS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON VE_MATRIZESTADOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_MATRIZESTADOS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON VE_MATRIZESTADOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_MATRIZESTADOS_TD TO SISCEL_SELECT
/
