GRANT DELETE ON VE_ORDENESTADOS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON VE_ORDENESTADOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_ORDENESTADOS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON VE_ORDENESTADOS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_ORDENESTADOS_TD TO SISCEL_SELECT
/
