GRANT EXECUTE ON VE_P_CAMBPLANCOM TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_CAMBPLANCOM TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_CAMBPLANCOM TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_CAMBPLANCOM TO SISCEL_SELECT
/
