GRANT DELETE ON VE_PROCESOSOMITIDOS_TO TO SISCEL_ADMIN
/
GRANT INSERT ON VE_PROCESOSOMITIDOS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON VE_PROCESOSOMITIDOS_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON VE_PROCESOSOMITIDOS_TO TO SISCEL_ADMIN
/
GRANT SELECT ON VE_PROCESOSOMITIDOS_TO TO SISCEL_SELECT
/
