GRANT EXECUTE ON VE_P_VENTASREAL TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_VENTASREAL TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_VENTASREAL TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_VENTASREAL TO SISCEL_SELECT
/
