GRANT EXECUTE ON VE_P_CAMBIOEQUIPO TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_CAMBIOEQUIPO TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_CAMBIOEQUIPO TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_CAMBIOEQUIPO TO SISCEL_SELECT
/
