GRANT EXECUTE ON VE_P_LIQEJECREPR TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_LIQEJECREPR TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_LIQEJECREPR TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_LIQEJECREPR TO SISCEL_SELECT
/
