GRANT EXECUTE ON VE_P_GETARTCTODTO TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_GETARTCTODTO TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_GETARTCTODTO TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_GETARTCTODTO TO SISCEL_SELECT
/
