GRANT EXECUTE ON VE_P_INSVENTASERV TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_INSVENTASERV TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_INSVENTASERV TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_INSVENTASERV TO SISCEL_SELECT
/
