GRANT EXECUTE ON VE_P_BMOVILIZACION TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_BMOVILIZACION TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_BMOVILIZACION TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_BMOVILIZACION TO SISCEL_SELECT
/
