GRANT EXECUTE ON VE_P_INSANOMLIQ TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_INSANOMLIQ TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_INSANOMLIQ TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_INSANOMLIQ TO SISCEL_SELECT
/
