GRANT EXECUTE ON VE_P_VENTASHIST TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_VENTASHIST TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_VENTASHIST TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_VENTASHIST TO SISCEL_SELECT
/
