GRANT EXECUTE ON VE_P_GETINFOABO TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_GETINFOABO TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_GETINFOABO TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_GETINFOABO TO SISCEL_SELECT
/
