GRANT EXECUTE ON VE_P_VENTARRIENDO TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_VENTARRIENDO TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_VENTARRIENDO TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_VENTARRIENDO TO SISCEL_SELECT
/
