GRANT EXECUTE ON VE_PARAMETROS_COMERCIALES_PG TO CER_CPU
/
GRANT EXECUTE ON VE_PARAMETROS_COMERCIALES_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_PARAMETROS_COMERCIALES_PG TO SISCEL_CPU
/
GRANT EXECUTE ON VE_PARAMETROS_COMERCIALES_PG TO SISCEL_GA
/
GRANT EXECUTE ON VE_PARAMETROS_COMERCIALES_PG TO SISCEL_PV
/
GRANT EXECUTE ON VE_PARAMETROS_COMERCIALES_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON VE_PARAMETROS_COMERCIALES_PG TO SISCEL_VE
/
