GRANT EXECUTE ON VE_P_LIQHABEJECREPR TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_LIQHABEJECREPR TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_LIQHABEJECREPR TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_LIQHABEJECREPR TO SISCEL_SELECT
/
