GRANT DELETE ON VE_PLANTILLA_TIPCOMIS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON VE_PLANTILLA_TIPCOMIS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_PLANTILLA_TIPCOMIS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON VE_PLANTILLA_TIPCOMIS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_PLANTILLA_TIPCOMIS_TD TO SISCEL_SELECT
/
GRANT SELECT ON VE_PLANTILLA_TIPCOMIS_TD TO SOLO_CONSULTA_SISCEL
/
