GRANT EXECUTE ON VE_P_INSRENUNCIAS TO EBZ_SISCEL
/
GRANT EXECUTE ON VE_P_INSRENUNCIAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_P_INSRENUNCIAS TO SISCEL_GA
/
GRANT EXECUTE ON VE_P_INSRENUNCIAS TO SISCEL_SELECT
/
