GRANT DELETE ON VE_REDVENTAS_TD TO SISCEL_ADMIN
/
GRANT INSERT ON VE_REDVENTAS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_REDVENTAS_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON VE_REDVENTAS_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_REDVENTAS_TD TO SISCEL_SELECT
/
GRANT DELETE ON VE_REDVENTAS_TD TO SISCEL_VE
/
GRANT INSERT ON VE_REDVENTAS_TD TO SISCEL_VE
/
GRANT SELECT ON VE_REDVENTAS_TD TO SISCEL_VE
/
GRANT UPDATE ON VE_REDVENTAS_TD TO SISCEL_VE
/
GRANT SELECT ON VE_REDVENTAS_TD TO SOLO_CONSULTA_SISCEL
/
