GRANT SELECT ON VE_SEQ_CTOPLAN TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_CTOPLAN TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_CTOPLAN TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_CTOPLAN TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_CTOPLAN TO SISCEL_VE
/
