GRANT SELECT ON VE_SEQ_PLANCOM TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_PLANCOM TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_PLANCOM TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_PLANCOM TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_PLANCOM TO SISCEL_VE
/
