GRANT SELECT ON VE_SEQ_RESULTPRO TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_RESULTPRO TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_RESULTPRO TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_RESULTPRO TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_RESULTPRO TO SISCEL_VE
/
