GRANT SELECT ON VE_SEQ_RENUNCIAS TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_RENUNCIAS TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_RENUNCIAS TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_RENUNCIAS TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_RENUNCIAS TO SISCEL_VE
/
