GRANT SELECT ON VE_SEQ_ANOMLIQ TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_ANOMLIQ TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_ANOMLIQ TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_ANOMLIQ TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_ANOMLIQ TO SISCEL_VE
/
