GRANT SELECT ON VE_SEQ_CUADRANTESLIQ TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_CUADRANTESLIQ TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_CUADRANTESLIQ TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_CUADRANTESLIQ TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_CUADRANTESLIQ TO SISCEL_VE
/
