GRANT SELECT ON VE_SEQ_ANOMLIQTRA TO EBZ_SISCEL
/
GRANT SELECT ON VE_SEQ_ANOMLIQTRA TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_ANOMLIQTRA TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_ANOMLIQTRA TO SISCEL_VE
/
