GRANT SELECT ON VE_SEQ_FRANDTOLLAM TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_FRANDTOLLAM TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_FRANDTOLLAM TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_FRANDTOLLAM TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_FRANDTOLLAM TO SISCEL_VE
/
