GRANT SELECT ON VE_SEQ_LIQTRAFICO TO EBZ_SISCEL
/
GRANT SELECT ON VE_SEQ_LIQTRAFICO TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_LIQTRAFICO TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_LIQTRAFICO TO SISCEL_VE
/
