GRANT SELECT ON VE_SEQ_VENTA TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_VENTA TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_VENTA TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_VENTA TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_VENTA TO SISCEL_VE
/
