GRANT SELECT ON VE_SEQ_VENTART TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_VENTART TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_VENTART TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_VENTART TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_VENTART TO SISCEL_VE
/
