GRANT EXECUTE ON VE_SELECCIONAR_TABLAS_PG TO MAS_PRODUCT_DML
/
GRANT EXECUTE ON VE_SELECCIONAR_TABLAS_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_SELECCIONAR_TABLAS_PG TO SISCEL_FA
/
GRANT EXECUTE ON VE_SELECCIONAR_TABLAS_PG TO SISCEL_PV
/
GRANT EXECUTE ON VE_SELECCIONAR_TABLAS_PG TO SISCEL_SELECT
/
