GRANT SELECT ON VE_SEQ_PROSPECTO TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_PROSPECTO TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_PROSPECTO TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_PROSPECTO TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_PROSPECTO TO SISCEL_VE
/
