GRANT SELECT ON VE_SEQ_DTOLLAM TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_DTOLLAM TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_DTOLLAM TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_DTOLLAM TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_DTOLLAM TO SISCEL_VE
/
