GRANT SELECT ON VE_SEQ_LIQUIDACION TO EBZ_SISCEL
/
GRANT ALTER ON VE_SEQ_LIQUIDACION TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_LIQUIDACION TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_LIQUIDACION TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_LIQUIDACION TO SISCEL_VE
/
