GRANT SELECT ON VE_SEQ_SSTEMP TO SISCEL_ADMIN
/
GRANT SELECT ON VE_SEQ_SSTEMP TO SISCEL_ER
/
GRANT SELECT ON VE_SEQ_SSTEMP TO SISCEL_GA
/
GRANT SELECT ON VE_SEQ_SSTEMP TO SISCEL_SELECT
/
GRANT SELECT ON VE_SEQ_SSTEMP TO SISCEL_VE
/
