GRANT SELECT                            ON VE_TIPO_SOLICITUD_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_TIPO_SOLICITUD_TD TO SISCEL_GA
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_TIPO_SOLICITUD_TD TO SISCEL_VE
/

