GRANT EXECUTE ON VE_TIPIFICACION_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON VE_TIPIFICACION_PG TO  SISCEL_ADMIN
/
GRANT EXECUTE ON VE_TIPIFICACION_PG TO SISCEL_VE
/
GRANT EXECUTE ON VE_TIPIFICACION_PG TO SISCEL_AL
/

