GRANT SELECT                            ON VE_TIENDA_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_TIENDA_TD TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_TIENDA_TD TO SISCEL_VE
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_TIENDA_TD TO SISCEL_AL
/

