GRANT EXECUTE ON VE_UPD_INFO_CLIENTES_PG TO SISCEL_VE ;
GRANT EXECUTE ON VE_UPD_INFO_CLIENTES_PG TO SISCEL_GA ;
GRANT EXECUTE ON VE_UPD_INFO_CLIENTES_PG TO SISCEL_FA ;
GRANT EXECUTE ON VE_UPD_INFO_CLIENTES_PG TO SISCEL_CO ;
GRANT EXECUTE ON VE_UPD_INFO_CLIENTES_PG TO SISCEL_ADMIN ;
GRANT EXECUTE ON VE_UPD_INFO_CLIENTES_PG TO SISCEL_SELECT ;
