GRANT SELECT , INSERT , UPDATE , DELETE ON VE_USUPERFIL_TD TO SISCEL_VE
/
GRANT SELECT                            ON VE_USUPERFIL_TD TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_USUPERFIL_TD TO SISCEL_ADMIN
/

