GRANT SELECT                            ON VE_VENTAS_QUIOSCO_TO TO SISCEL_SELECT
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_VENTAS_QUIOSCO_TO TO SISCEL_ADMIN
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_VENTAS_QUIOSCO_TO TO SISCEL_VE
/
GRANT SELECT , INSERT , UPDATE , DELETE ON VE_VENTAS_QUIOSCO_TO TO SISCEL_AL
/

