GRANT DELETE ON VE_VENTA_MOVIMIENTO_TD TO SISCEL_ADMIN
/
GRANT INSERT ON VE_VENTA_MOVIMIENTO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_VENTA_MOVIMIENTO_TD TO SISCEL_ADMIN
/
GRANT UPDATE ON VE_VENTA_MOVIMIENTO_TD TO SISCEL_ADMIN
/
GRANT SELECT ON VE_VENTA_MOVIMIENTO_TD TO SISCEL_SELECT
/
GRANT SELECT ON VE_VENTA_MOVIMIENTO_TD TO SOLO_CONSULTA_SISCEL
/
