GRANT EXECUTE ON VE_VALIDACIONES_CLIENTES_PG TO FAC_SISCEL
/
GRANT EXECUTE ON VE_VALIDACIONES_CLIENTES_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_VALIDACIONES_CLIENTES_PG TO SISCEL_GA
/
GRANT EXECUTE ON VE_VALIDACIONES_CLIENTES_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON VE_VALIDACIONES_CLIENTES_PG TO SISCEL_VE
/
