GRANT EXECUTE ON VE_VALIDACION_LINEA_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON VE_VALIDACION_LINEA_PG TO SISCEL_GA
/
GRANT EXECUTE ON VE_VALIDACION_LINEA_PG TO SISCEL_PV
/
GRANT EXECUTE ON VE_VALIDACION_LINEA_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON VE_VALIDACION_LINEA_PG TO SISCEL_VE
/
