GRANT SELECT ON VES_PUNTOS_VENTA TO EBZ_SISCEL
/
GRANT SELECT ON VES_PUNTOS_VENTA TO SISCEL_ADMIN
/
GRANT SELECT ON VES_PUNTOS_VENTA TO SISCEL_SELECT
/
GRANT SELECT ON VES_PUNTOS_VENTA TO SISCEL_VE
/
