GRANT EXECUTE ON VT_VALIDA_AUTENTICACION_PR TO EBZ_SISCEL
/
GRANT EXECUTE ON VT_VALIDA_AUTENTICACION_PR TO SISCEL_ADMIN
/
GRANT EXECUTE ON VT_VALIDA_AUTENTICACION_PR TO SISCEL_SELECT
/
GRANT EXECUTE ON VT_VALIDA_AUTENTICACION_PR TO SISCEL_VE
/
