/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.inventarioportabilidad.ejb.session;

/**
 * Home interface for InventarioPortabilidad.
 * @generated 
 * @wtp generated
 */
public interface InventarioPortabilidadHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/InventarioPortabilidad";
   public static final String JNDI_NAME="InventarioPortabilidad";

   public com.tmmas.cl.scl.inventarioportabilidad.ejb.session.InventarioPortabilidad create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
