CREATE OR REPLACE TYPE IC_DETALLEMOV_TO_QT AS OBJECT (
        NUM_MOVIMIENTO NUMBER(9),
        NOM_SUBPARAMETRO VARCHAR2(20),
        VAL_SUBPARAMETRO VARCHAR2(25),
        -- Constructor por defecto
        CONSTRUCTOR FUNCTION IC_DETALLEMOV_TO_QT RETURN SELF AS RESULT
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY IC_DETALLEMOV_TO_QT IS
        -- Constructor por defecto
        CONSTRUCTOR FUNCTION IC_DETALLEMOV_TO_QT RETURN SELF AS RESULT AS
        BEGIN
                SELF.NUM_MOVIMIENTO := NULL;
                SELF.NOM_SUBPARAMETRO := NULL;
                SELF.VAL_SUBPARAMETRO := NULL;
                RETURN;
        END;
END;
/
SHOW ERRORS
