CREATE OR REPLACE TYPE IC_PROVISION_QT AS OBJECT
(
  COD_CLIENTE VARCHAR2(25),
  COD_PROV_SERV VARCHAR2(25),
  TIP_ACCION VARCHAR2(25),
  TIP_SER VARCHAR2(25),
  COD_PROD_CONTRAT NUMBER(10),
  FECHA_EJECUCION DATE,
  NUM_CELULAR NUMBER(15),
  NUM_ABONADO NUMBER(8),
  TIP_TERMINAL VARCHAR2(1),
  COD_CENTRAL NUMBER(3),
  NUM_SERIE VARCHAR2(25),
  COD_TECNOLOGIA VARCHAR2(7),
  ID_PLAN VARCHAR2(15),
  IMPORTE VARCHAR2(25),
  COD_MONEDA VARCHAR2(25),
  USUARIO VARCHAR2(25),
  COD_CAUSA VARCHAR2(25),
  MONTO_BONIF VARCHAR2(25),
  TIPO_BONO VARCHAR2(25),
  COD_PERIODIF VARCHAR2(25),
  FECHA_EJEC_BONO DATE,
  NUM_MOVANT   NUMBER(9),
  NOM_USUARORA VARCHAR2(30),
  CONSTRUCTOR FUNCTION IC_PROVISION_QT RETURN SELF AS RESULT
);
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY                 IC_PROVISION_QT IS
        -- Constructor por defecto
        CONSTRUCTOR FUNCTION IC_PROVISION_QT RETURN SELF AS RESULT AS
        BEGIN
   SELF.COD_CLIENTE:=NULL;
   SELF.COD_PROV_SERV :=NULL;
   SELF.TIP_ACCION :=NULL;
   SELF.TIP_SER :=NULL;
   SELF.COD_PROD_CONTRAT  :=NULL;
   SELF.FECHA_EJECUCION  :=NULL;
   SELF.NUM_CELULAR :=NULL;
   SELF.NUM_ABONADO :=NULL;
   SELF.TIP_TERMINAL :=NULL;
   SELF.COD_CENTRAL :=NULL;
   SELF.NUM_SERIE :=NULL;
   SELF.COD_TECNOLOGIA :=NULL;
   SELF.ID_PLAN :=NULL;
   SELF.IMPORTE :=NULL;
   SELF.COD_MONEDA :=NULL;
   SELF.USUARIO :=NULL;
   SELF.COD_CAUSA :=NULL;
   SELF.MONTO_BONIF :=NULL;
   SELF.TIPO_BONO :=NULL;
   SELF.COD_PERIODIF :=NULL;
   SELF.FECHA_EJEC_BONO :=NULL;
   SELF.NUM_MOVANT :=NULL;
   SELF.NOM_USUARORA :=NULL;
   RETURN;
        END;
END;
/
SHOW ERRORS
