CREATE OR REPLACE
TYPE SE_DETALLE_ESPEC_TO_QT AS OBJECT
(
  COD_ESPEC_PROD NUMBER(8),
  COD_SERVICIO_BASE VARCHAR2(10),
  IND_TIPO_SERVICIO VARCHAR2(10),
  COD_PROV_SERV NUMBER(8),
  COD_PERFIL_LISTA NUMBER(8),
  CONSTRUCTOR FUNCTION SE_DETALLE_ESPEC_TO_QT RETURN SELF AS RESULT
);
/


CREATE OR REPLACE
TYPE BODY               SE_DETALLE_ESPEC_TO_QT AS
  CONSTRUCTOR FUNCTION SE_DETALLE_ESPEC_TO_QT RETURN self AS result AS
  BEGIN
  COD_ESPEC_PROD := NULL;
  COD_SERVICIO_BASE := NULL;
  IND_TIPO_SERVICIO := NULL;
  COD_PROV_SERV := NULL;
  COD_PERFIL_LISTA := NULL;
    RETURN;
  END;
END;
/