CREATE OR REPLACE
TYPE SE_LIMITE_CONSUMO_QT AS OBJECT
(
  COD_LIMCONS     VARCHAR2(5),
  IND_UNIDADES    VARCHAR2(5),
  IMP_LIMITE      NUMBER(14,4),
  DESCRIPCION     VARCHAR2(50),
  COD_PLANTARIF  VARCHAR2(5),
  IND_DEFAULT    VARCHAR2(1),
  COD_CLIENTE     NUMBER(8),
  NUM_ABONADO     NUMBER(8),
  FEC_DESDE       DATE,
  FEC_HASTA       DATE,
  NOM_USUARORA    VARCHAR2(30),
  FEC_ASIGNACION  DATE,
  MTO_LIMCONSUMO  NUMBER(14,4),
  CONSTRUCTOR FUNCTION SE_LIMITE_CONSUMO_QT RETURN self AS result
); 
/
CREATE OR REPLACE
TYPE BODY SE_LIMITE_CONSUMO_QT IS
  CONSTRUCTOR FUNCTION SE_LIMITE_CONSUMO_QT RETURN self AS result AS
  BEGIN
    SELF.COD_LIMCONS    :=NULL;
    SELF.IND_UNIDADES   :=NULL;
    SELF.IMP_LIMITE     :=NULL;
    SELF.DESCRIPCION    :=NULL;
    SELF.COD_PLANTARIF  :=NULL;
    SELF.IND_DEFAULT    :=NULL;
    SELF.COD_CLIENTE    :=NULL;
    SELF.NUM_ABONADO    :=NULL;
    SELF.FEC_DESDE      :=NULL;
    SELF.FEC_HASTA      :=NULL;
    SELF.NOM_USUARORA   :=NULL;
    SELF.FEC_ASIGNACION :=NULL;
    SELF.MTO_LIMCONSUMO :=NULL;
    RETURN;
  END;
END; 
/