CREATE OR REPLACE TYPE SE_PERFIL_LISTA_TD_QT AS OBJECT
(
  COD_PERFIL_LISTA NUMBER(8),
  NOM_PERFIL VARCHAR2(10),
  DES_PERFIL VARCHAR2(30),
  IND_TIP_PLATAFORMA VARCHAR2(10),
  FEC_INI_VIG VARCHAR2(255),
  FEC_TER_VIG VARCHAR2(255),
  NUM_MAXIMO_LISTA INTEGER,
  IND_TIP_COMPORTA VARCHAR2(1),
  FLG_AUTO_AFIN VARCHAR2(1)
)
/
SHOW ERRORS
