CREATE OR REPLACE TYPE SE_PLANES_ALTAMIRA_TD_QT AS OBJECT
(
  COD_PLAN_AA VARCHAR2(10),
  TIPO_PLAN_AA VARCHAR2(10),
  DES_PLAN_AA VARCHAR2(30),
  IND_TIP_PLATAFORMA VARCHAR2(10),
  FEC_INI_VIG DATE,
  FEC_TER_VIG DATE,
  COD_LISTA_AA VARCHAR2(10),
  CAN_BONIFICAR VARCHAR2(10),
  TIP_UNIDAD_BONIFICAR VARCHAR2(10)
)
/
SHOW ERRORS
