DROP TYPE SV_LISTA_CONTRA_TO_LST_QT;

DROP TYPE SV_LISTA_CONTRA_TO_QT;

CREATE OR REPLACE TYPE SV_LISTA_CONTRA_TO_QT AS OBJECT
(
  COD_PROD_CONTRATADO NUMBER(38),
  VALOR_ELEMENTO VARCHAR2(18),
  FEC_INICIO_VIGENCIA DATE,
  FEC_TERMINO_VIGENCIA DATE,
  COD_CATEGORIA_DESTINO VARCHAR2(20),
  NUM_PROCESO VARCHAR2(10),
  ORIGEN_PROCESO VARCHAR2(5),
  FEC_PROCESO DATE,
  ORIGEN_PROC_DESCONTRATA VARCHAR2(5),
  NUM_PROC_DESCONTRATA VARCHAR2(10)
)
/
SHOW ERRORS
