CREATE OR REPLACE TYPE SV_PROD_CONTRA_QT AS OBJECT
(
  COD_PROD_CONTRATADO NUMBER(38),
  NUM_PROC_DESCONTRATA VARCHAR2(10),
  ORIGEN_PROC_DESCONTRATA VARCHAR2(5),
  CANT_PROD_CONTRATADO NUMBER(20),
  COD_CLIENTE NUMBER(8),
  NUM_ABONADO NUMBER(8)
)
/
SHOW ERRORS
