#!/usr/bin/sh

HOME=/produccion/cergte/central
#---------------->>> Includ de las librerias JAR necesarias para la ejecucion  <<<------------------#
#CLASSPATH=$CLASSPATH:$ORACLE_HOME/jdbc/lib/classes12.zip
CLASSPATH=$CLASSPATH:$HOME/ICC/jar/ojdbc14.jar
CLASSPATH=$CLASSPATH:$HOME/ICC/jar/Scheduler.jar
CLASSPATH=$CLASSPATH:$HOME/ICC/jar/log4j-1.2.8.jar
CLASSPATH=$CLASSPATH:$HOME/ICC/bin/:.

#--------------------------------->>> Configuracion de parametros <<<-------------------------------#
numMovimiento=$1
archCfgIC=$HOME/ICC/cfg/ICConfiguracion.cfg
archCfgLog=$HOME/ICC/cfg/libcentral.cfg

#--------------------------------->>> Ejecucion de la Clase Main  <<<-------------------------------#
/usr/j2se/bin/java -cp $CLASSPATH -d64 -Djava.library.path=$HOME/ICC/lib com.tmmas.IC.GeneraMovMasivos.ProcesaMovimientos  $archCfgIC $numMovimiento $tipoEstado $archCfgLog

