/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.oh.isscusord.soa.bean.ejb.jms;

/**
 * Message Driven layer for OrdenServicioMDB.
 * @generated 
 * @wtp generated
 */
public class OrdenServicioMDBMdb
   extends com.tmmas.scl.operations.crm.f.oh.isscusord.soa.bean.ejb.jms.OrdenServicioMDBBean
   implements javax.ejb.MessageDrivenBean, 
              javax.jms.MessageListener
{
   public void setMessageDrivenContext(javax.ejb.MessageDrivenContext ctx) throws javax.ejb.EJBException
   {
      super.setMessageDrivenContext(ctx);
   }

   public void ejbRemove() 
   {
      super.ejbRemove();
   }

}
