CREATE OR REPLACE PACKAGE AUD_AUDITORIA_PG
IS

FUNCTION AUD_REGISTRA_AUDITORIA_FN (
										EV_owner		IN VARCHAR2
 									,	EV_tabla		IN VARCHAR2
									,	EV_operacion	IN VARCHAR2
									,	EV_pk			IN VARCHAR2
									,	EV_detalle  	IN VARCHAR2 ) RETURN NUMBER;

END AUD_AUDITORIA_PG;
/
SHOW ERRORS
