GRANT SELECT, INSERT, UPDATE, DELETE     ON SE_PROVISIONAMIENTO_SERV_TD TO SISCEL_ADMIN
/
GRANT SELECT, INSERT, UPDATE, DELETE     ON SE_PROVISIONAMIENTO_SERV_TD TO SISCEL_IC
/
GRANT SELECT                             ON SE_PROVISIONAMIENTO_SERV_TD TO MAS_SERVICE_DML
/
