//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : P-TMM-08004
//  @ File Name : CuotaBO.java
//  @ Date : 09/09/2008
//  @ Author : hsegura
//
//

package com.tmmas.scl.framework.customerdomainfacturacion.CustomerBillABE.bo;

import com.tmmas.scl.framework.CustomerDomain.exception.RateUsageRecordsException;
import com.tmmas.scl.framework.customerdomainfacturacion.CustomerABE.dao.ClienteDAO;
import com.tmmas.scl.framework.customerdomainfacturacion.CustomerABE.dao.Interface.ClienteDAOIT;
import com.tmmas.scl.framework.customerdomainfacturacion.CustomerBillABE.bo.Interface.CuotaBOIT;
import com.tmmas.scl.framework.customerdomainfacturacion.CustomerBillABE.dao.CuotaDAO;
import com.tmmas.scl.framework.customerdomainfacturacion.CustomerBillABE.dao.Interface.CuotaDAOIT;

public class CuotaBO implements CuotaBOIT {
	public boolean validarCantidadCuotas(long cantCuotas)
			throws RateUsageRecordsException {
		CuotaDAOIT cuotaDAO = new CuotaDAO();

		return cuotaDAO.validarCantidadCuotas(cantCuotas);

	}
}
