CREATE OR REPLACE FORCE VIEW CO_VIEWREPT(
   PRODUCTO
 , COD_TIPDOCUM
 , IMPORTE_DEBE
 , IMPORTE_HABER
 , NUM_DIAS
 ) AS 
SELECT
       COD_PRODUCTO
     , COD_TIPDOCUM
     , IMPORTE_DEBE
     , IMPORTE_HABER
     , ROUND(SYSDATE - FEC_EFECTIVIDAD)
 FROM CO_CARTERA
         GROUP BY COD_PRODUCTO, COD_TIPDOCUM, FEC_EFECTIVIDAD,
  IMPORTE_DEBE, IMPORTE_HABER
/
SHOW ERRORS
