CREATE OR REPLACE FORCE VIEW ICG_VENTSERVICIO(
   COD_PRODUCTO
 , COD_SERVICIO
 , DES_SERVICIO
 , NUM_NIVELES
 , IND_ESTADO
 , IND_ABONADOS
 ) AS 
SELECT
       "COD_PRODUCTO"
     , "COD_SERVICIO"
     , "DES_SERVICIO"
     , "NUM_NIVELES"
     , "IND_ESTADO"
     , "IND_ABONADOS"
 FROM ICG_SERVICIO
/
SHOW ERRORS
