CREATE OR REPLACE FORCE VIEW ICG_VCENTACTU(
   COD_PRODUCTO
 , COD_CENTRAL
 , COD_ACTUACION
 , COD_ACCION
 , NUM_MAXINTENTOS
 ) AS 
SELECT
       T1.COD_PRODUCTO
     , T1.COD_CENTRAL
     , T2.COD_ACTUACION
     , T2.COD_ACCION
     , T1.NUM_MAXINTENTOS
 FROM ICG_CENTRAL T1,ICG_ACTUACION T2
  WHERE T1.COD_PRODUCTO = T2.COD_PRODUCTO
/
SHOW ERRORS
