CREATE OR REPLACE FORCE VIEW VE_MODIFICACIONES_VW(
   COD_CUENTA
 , COD_CLIENTE
 , COD_TIPMODI
 , FEC_MODIFICA
 , CANTIDAD
 ) AS 
select
c.COD_CUENTA, c.COD_CLIENTE, a.COD_TIPMODI, to_char(a.FEC_MODIFICA, 'YYYYMM') FEC_MODIFICA, count(1) cantidad
FROM  GA_MODABOCEL_MVW a, ga_abocel c
where a.NUM_ABONADO=c.NUM_ABONADO
and a.FEC_MODIFICA >= add_months(SYSDATE,-12)
group by c.COD_CUENTA, c.COD_CLIENTE, a.COD_TIPMODI, to_char(a.FEC_MODIFICA, 'YYYYMM')
/
SHOW ERRORS
