/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.b.bcm.apppridisreb.bean.ejb.session;

/**
 * Local home interface for AppPriDisRebFacade.
 * @generated 
 * @wtp generated
 */
public interface AppPriDisRebFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AppPriDisRebFacadeLocal";
   public static final String JNDI_NAME="AppPriDisRebFacadeLocal";

   public com.tmmas.scl.operations.crm.b.bcm.apppridisreb.bean.ejb.session.AppPriDisRebFacadeLocal create()
      throws javax.ejb.CreateException;

}
