/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.wsventaenlace.negocio.ejb.session;

/**
 * Remote interface for AsociaRangoFacade.
 * @generated 
 * @wtp generated
 */
public interface AsociaRangoFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ServicioVentasEnlaceException
    * @generated     */
   public com.tmmas.scl.wsventaenlace.transport.dto.OOSSDTO cargaGenericaDatos( com.tmmas.scl.wsventaenlace.transport.dto.OOSSDTO oOSSDTO )
      throws com.tmmas.scl.wsventaenlace.common.exception.ServicioVentasEnlaceException, java.rmi.RemoteException;

}
