/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.wsventaenlace.negocio.ejb.session;

/**
 * Local interface for AsociaRangoFacade.
 * @generated 
 * @wtp generated
 */
public interface AsociaRangoFacadeLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ServicioVentasEnlaceException
    * @generated     */
   public com.tmmas.scl.wsventaenlace.transport.dto.OOSSDTO cargaGenericaDatos( com.tmmas.scl.wsventaenlace.transport.dto.OOSSDTO oOSSDTO ) throws com.tmmas.scl.wsventaenlace.common.exception.ServicioVentasEnlaceException;

}
