/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.wsventaenlace.negocio.ejb.session;

/**
 * Local home interface for AsociaRangoFacade.
 * @generated 
 * @wtp generated
 */
public interface AsociaRangoFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AsociaRangoFacadeLocal";
   public static final String JNDI_NAME="AsociaRangoFacadeLocal";

   public com.tmmas.scl.wsventaenlace.negocio.ejb.session.AsociaRangoFacadeLocal create()
      throws javax.ejb.CreateException;

}
