/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.gestionlc.ejb.session;

/**
 * Home interface for AbonoLimiteConsumo.
 * @generated 
 * @wtp generated
 */
public interface AbonoLimiteConsumoHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AbonoLimiteConsumo";
   public static final String JNDI_NAME="AbonoLimiteConsumo";

   public com.tmmas.scl.gestionlc.ejb.session.AbonoLimiteConsumo create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
