/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.gestionlc.ejb.session;

/**
 * Local interface for AbonoLimiteConsumo.
 * @generated 
 * @wtp generated
 */
public interface AbonoLimiteConsumoLocal
   extends javax.ejb.EJBLocalObject
{

}
