/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.gestionlc.ejb.session;

/**
 * Remote interface for AbonoLimiteConsumo.
 * @generated 
 * @wtp generated
 */
public interface AbonoLimiteConsumo
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.CargaAbonoLimiteConsumoOutDTO cargaAbonoLimiteConsumo( com.tmmas.scl.gestionlc.common.dto.ws.CargaAbonoLimiteConsumoInDTO pIn )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.WSCargaAbonoLimiteConsumoOutDTO cargaAbonoLimiteConsumoWS( com.tmmas.scl.gestionlc.common.dto.ws.WSCargaAbonoLimiteConsumoInDTO pIn )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.EjecucionAbonoLimiteConsumoOutDTO ejecutarAbonoLimiteConsumo( com.tmmas.scl.gestionlc.common.dto.ws.EjecucionAbonoLimiteConsumoInDTO pIn )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.WSEjecutaAbonoLimiteConsumoOutDTO ejecutaAbonoLimiteConsumoWS( com.tmmas.scl.gestionlc.common.dto.ws.WSEjecutaAbonoLimiteConsumoInDTO pIn )
      throws java.rmi.RemoteException;

}
