/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.gestionlc.ejb.session;

/**
 * Home interface for GestLimCon.
 * @generated 
 * @wtp generated
 */
public interface GestLimConHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GestLimCon";
   public static final String JNDI_NAME="GestLimCon";

   public com.tmmas.scl.gestionlc.ejb.session.GestLimCon create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
