/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.gestionlc.ejb.session;

/**
 * Remote interface for ModificacionLimiteConsumo.
 * @generated 
 * @wtp generated
 */
public interface ModificacionLimiteConsumo
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.CargaModificacionLimiteConsumoOutDTO cargarModificacionLimiteConsumo( com.tmmas.scl.gestionlc.common.dto.ws.CargaModificacionLimiteConsumoInDTO pIn )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.WSCargaModificacionLimiteConsumoOutDTO cargarModificacionLimiteConsumoWS( com.tmmas.scl.gestionlc.common.dto.ws.WSCargaModificacionLimiteConsumoInDTO pIn )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.EjecutaModificacionLimiteConsumoOutDTO ejecutaModificacionLimiteConsumo( com.tmmas.scl.gestionlc.common.dto.ws.EjecutaModificacionLimiteConsumoInDTO pIn )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.WSEjecutaModificacionLimiteConsumoOutDTO ejecutaModificacionLimiteConsumoWS( com.tmmas.scl.gestionlc.common.dto.ws.WSEjecutaModificacionLimiteConsumoInDTO pIn )
      throws java.rmi.RemoteException;

}
