/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.gestionlc.ejb.session;

/**
 * Local interface for RestitucionEquipo.
 * @generated 
 * @wtp generated
 */
public interface RestitucionEquipoLocal
   extends javax.ejb.EJBLocalObject
{

}
