/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.gestionlc.ejb.session;

/**
 * Remote interface for RestitucionEquipo.
 * @generated 
 * @wtp generated
 */
public interface RestitucionEquipo
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.CargaSeguimientoSiniestroOutDTO cargarSeguimientoSiniestro( com.tmmas.scl.gestionlc.common.dto.ws.CargaSeguimientoSiniestroInDTO cargaInDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.CargaRestitucionEquipoOutDTO cargarRestitucionEquipo( com.tmmas.scl.gestionlc.common.dto.ws.CargaRestitucionEquipoInDTO inDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.RecargaCboModalidadOutDTO recargarCboModalidad( com.tmmas.scl.gestionlc.common.dto.ws.RecargaCboModalidadInDTO inDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.RecargaCboCuotasOutDTO recargarCboCuotas( com.tmmas.scl.gestionlc.common.dto.ws.RecargaCboCuotasInDTO inDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.CargaSeleccionEquipoOutDTO cargarSeleccionEquipo( com.tmmas.scl.gestionlc.common.dto.ws.CargaSeleccionEquipoInDTO cargaInDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.RecargaListSeriesOutDTO recargaListSeries( com.tmmas.scl.gestionlc.common.dto.ws.RecargaListSeriesInDTO inDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.EjecutaRestitucionEquipoOutDTO ejecutarRestitucionEquipo( com.tmmas.scl.gestionlc.common.dto.ws.EjecutaRestitucionEquipoInDTO inDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.gestionlc.common.dto.ws.EjecutaCierreRestitucionOutDTO ejecutarCierreRestitucion( com.tmmas.scl.gestionlc.common.dto.ws.EjecutaCierreRestitucionInDTO inDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws GestionLimiteConsumoException, Exception
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void rollbackReservaSerie( java.lang.Long lonNumTransaccion )
      throws com.tmmas.scl.gestionlc.common.exception.GestionLimiteConsumoException, java.lang.Exception, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void desbloquearVendedor( com.tmmas.scl.gestionlc.common.dto.UsuarioDTO inDTO )
      throws java.rmi.RemoteException;

}
