/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.gestionlc.ejb.session;

/**
 * Home interface for RestitucionEquipo.
 * @generated 
 * @wtp generated
 */
public interface RestitucionEquipoHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/RestitucionEquipo";
   public static final String JNDI_NAME="RestitucionEquipo";

   public com.tmmas.scl.gestionlc.ejb.session.RestitucionEquipo create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
