/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.gestiondedirecciones.negocio.ejb.session;

/**
 * Home interface for GestionDeDirecciones.
 * @generated 
 * @wtp generated
 */
public interface GestionDeDireccionesHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GestionDeDirecciones";
   public static final String JNDI_NAME="GestionDeDirecciones";

   public com.tmmas.cl.scl.gestiondedirecciones.negocio.ejb.session.GestionDeDirecciones create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
