//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : P-TMM-08004
//  @ File Name : OficinaBOIT.java
//  @ Date : 09/09/2008
//  @ Author : hsegura
//
//

package com.tmmas.scl.framework.customerdomainfacturacion.CustomerABE.bo.Interface;

import com.tmmas.scl.framework.CustomerDomain.CustomerABE.dto.OficinaDTO;
import com.tmmas.scl.framework.CustomerDomain.exception.RateUsageRecordsException;

public interface OficinaBOIT {
	public OficinaDTO obtenerOficina(String codUsuario)
			throws RateUsageRecordsException;

}
