/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.RateUsageRecordsWS.soa.ejb.session;

/**
 * Remote interface for RateUsageRecordsWS.
 * @generated 
 * @wtp generated
 */
public interface RateUsageRecordsWS
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.CustomerDomain.CustomerBillABE.dto.FacturaMiscelaneaSalidaDTO generarFacturaMiscelanea( com.tmmas.scl.framework.CustomerDomain.CustomerBillABE.dto.FacturaMiscelaneaEntradaDTO facturaMiscelaneaEntradaDTO )
      throws com.tmmas.scl.framework.CustomerDomain.exception.RateUsageRecordsException, java.rmi.RemoteException;

}
