/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.RateUsageRecordsWS.soa.ejb.session;

/**
 * Home interface for RateUsageRecordsWS.
 * @generated 
 * @wtp generated
 */
public interface RateUsageRecordsWSHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/RateUsageRecordsWS";
   public static final String JNDI_NAME="RateUsageRecordsWS";

   public com.tmmas.scl.RateUsageRecordsWS.soa.ejb.session.RateUsageRecordsWS create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
