CREATE OR REPLACE TRIGGER AL_AFIN_SERORD
AFTER INSERT
ON AL_SERIES_ORDENES
DECLARE
CN_NNUMERO_0  CONSTANT NUMBER(2):=0;
CN_NNUMERO_9  CONSTANT NUMBER(2):=9;
CN_NNUMERO_99 CONSTANT NUMBER(2):=99;
BEGIN
DELETE AL_SERIES_ORDENES WHERE NUM_ORDEN = CN_NNUMERO_99 AND TIP_ORDEN= CN_NNUMERO_9;
END;
/
SHOW ERRORS
