CREATE OR REPLACE TRIGGER SISCEL.AL_AFMO_CABMOVI
AFTER UPDATE ON SISCEL.AL_CAB_MOVI_LOCA
FOR EACH ROW

DECLARE
    v_cod AL_CAB_MOVI_LOCA%ROWTYPE;
BEGIN
  IF :NEW.cod_estado = 'CE' THEN
   v_cod.num_movi := :NEW.num_movi;
  AL_PAC_LOCALIZA.P_CIERR_LOCALIZACION(v_cod.num_movi);
  END IF;
END;
/
SHOW ERRORS
