CREATE OR REPLACE TRIGGER CA_TRG_AFDEL_TIPINCIDENCIA
AFTER DELETE ON CA_TIPINCIDENCIAS
FOR EACH ROW
--
--   FECHA:30/05/2002
--

DECLARE
BEGIN
        DELETE FROM GE_MULTIIDIOMA
        WHERE nom_tabla = 'CA_TIPINCIDENCIAS'
          AND nom_campo = 'TIP_INCIDENCIA'
          AND cod_producto = 0
          AND cod_concepto = :OLD.tip_incidencia;
   EXCEPTION
     WHEN OTHERS THEN
     NULL;
END CA_TRG_AFDEL_TIPINCIDENCIA;
/
SHOW ERRORS
