CREATE OR REPLACE TRIGGER CE_TRG_AFIN_CED_EMPRESAS
AFTER INSERT
ON CED_EMPRESAS
FOR EACH ROW

DECLARE
MAX_CAJA CO_EMPRESAS_REX.COD_CAJA%TYPE;

BEGIN
	select NVL(MAX(COD_CAJA),0) INTO MAX_CAJA from CO_EMPRESAS_REX
	where COD_OFICINA = 'NT';

	insert into CO_EMPRESAS_REX  ( EMP_RECAUDADORA,
	COD_OFICINA,   COD_CAJA,   COD_ESTADO,   IND_ABIERTA)
	VALUES (:NEW.COD_EMPRESA, 'NT', (MAX_CAJA + 1), NULL, NULL);
END;
/
SHOW ERRORS
