CREATE OR REPLACE TRIGGER CO_FILCOBTO_AFUP_TG
AFTER UPDATE OF COD_ESTADO ON CO_FILTROS_COBEXT_TO

DECLARE
BEGIN
	DELETE CO_FILTROS_COBEXT_TO WHERE COD_ESTADO = 'EJE' OR COD_ESTADO = 'ERR';
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		NULL;
	WHEN OTHERS THEN
		RAISE_APPLICATION_ERROR( -20002, 'ERROR INESPERADO EN TRIGGER : ORA-' || TO_CHAR( SQLCODE ) || '.', TRUE );
END;
/
SHOW ERRORS
