CREATE OR REPLACE TRIGGER ER_TRG_AFUP_SOLICITUD
AFTER UPDATE OF COD_ESTADO
ON ERT_SOLICITUD

DECLARE
V_SOLICITUD  ERT_SOLICITUD%ROWTYPE;
Begin
	 DELETE ERT_SOLICITUD
	 WHERE COD_ESTADO=9 OR COD_ESTADO=4;
     EXCEPTION WHEN OTHERS THEN
     RAISE_APPLICATION_ERROR
   (-20002,'ERROR TRIGGER ER_TRG_AFUP_SOLICITUD: '||
    'ERROR'||' ORA'||TO_CHAR(SQLCODE),TRUE);
END;
/
SHOW ERRORS
