CREATE OR REPLACE TRIGGER FA_TRG_AFUPDELTIPOORDSERV
BEFORE UPDATE  OR DELETE
ON PPT_TIPOORDSERV
FOR EACH ROW

BEGIN
  INSERT into PPH_HISTIPOORDSERV values
  (:OLD.COD_TIPOORDSERV
  ,:OLD.FEC_DESDE
  ,:OLD.FEC_HASTA
  ,:OLD.DES_TIPOORDSERV
  ,:OLD.VAL_TIPOORDSERV
  ,:OLD.COD_ACTABO
  ,:OLD.NOM_USUARIO
  ,:OLD.FEC_ULTMOD)
	 ;
	 EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20003,'ERROR TRIGGER FA_TRG_AFUPDELTIPOORDSERV: '|| 'ERROR'||' ORA'||TO_CHAR(SQLCODE),TRUE);
END;
/
SHOW ERRORS
