CREATE OR REPLACE TRIGGER FA_TRG_AFDEL_FADIMPGRUPOS
AFTER DELETE ON FAD_IMPGRUPOS
FOR EACH ROW

DECLARE

BEGIN
	DELETE FROM GE_MULTIIDIOMA
	WHERE    NOM_TABLA    = 'FAD_IMPGRUPOS'
	and      NOM_CAMPO    = 'COD_GRUPOS'
	and      COD_PRODUCTO = 1
	and      COD_CONCEPTO = :old.COD_GRUPO;
	EXCEPTION
		WHEN OTHERS THEN
			Null;

END FA_TRG_AFDEL_FADIMPGRUPOS;
/
SHOW ERRORS
