CREATE OR REPLACE TRIGGER FA_TRG_AFDEL_FACONCEPTOS
AFTER DELETE ON FA_CONCEPTOS
FOR EACH ROW

DECLARE

BEGIN
	DELETE FROM GE_MULTIIDIOMA
	WHERE    NOM_TABLA    = 'FA_CONCEPTOS'
	and      NOM_CAMPO    = 'COD_CONCEPTO'
	and      COD_PRODUCTO = :old.COD_PRODUCTO
	and      COD_CONCEPTO = :old.COD_CONCEPTO;
	EXCEPTION
		WHEN OTHERS THEN
			Null;

END FA_TRG_AFDEL_FACONCEPTOS;
/
SHOW ERRORS
