CREATE OR REPLACE TRIGGER FA_TRG_AFDEL_FADIMPSUBGRUPOS
AFTER DELETE ON FAD_IMPSUBGRUPOS
FOR EACH ROW

DECLARE

BEGIN
	DELETE FROM GE_MULTIIDIOMA
	WHERE    NOM_TABLA    = 'FAD_IMPSUBGRUPOS'
	and      NOM_CAMPO    = 'COD_SUBGRUPO'
	and      COD_PRODUCTO = 1
	and      COD_CONCEPTO = :old.COD_SUBGRUPO;
	EXCEPTION
		WHEN OTHERS THEN
			Null;

END FA_TRG_AFDEL_FADIMPSUBGRUPOS;
/
SHOW ERRORS
