CREATE OR REPLACE TRIGGER GE_BEDE_GE_PERFIL_TG
BEFORE DELETE
ON GE_PERFIL_TO
FOR EACH ROW

DECLARE
   vNOM_PERFIL GE_PERFIL_TO.NOM_PERFIL%Type;
BEGIN

    -- Este Trigger Borra la relacion Perfil Grupo.
    vNOM_PERFIL := :old.NOM_PERFIL;
    DELETE GE_PERFIL_GRUPO_TO
    WHERE NOM_PERFIL  =vNOM_PERFIL;
END;
/
SHOW ERRORS
