CREATE OR REPLACE TRIGGER GE_TRG_AFDEL_RECATEGRECL
 AFTER DELETE ON RE_CATEGRECL
FOR EACH ROW

DECLARE
-- Creacion : 02 de mayo de 2002
-- Autor : Alejandra Montealegre
BEGIN
DELETE FROM GE_MULTIIDIOMA
WHERE NOM_TABLA = 'GA_SERVSUPL'
AND NOM_CAMPO_DES = 'COD_SERVICIO'
AND COD_PRODUCTO = 0
AND COD_CONCEPTO = :old.COD_CATEGRECL;
   EXCEPTION
     WHEN OTHERS THEN
       Null;
END GE_TRG_AFDEL_RECATEGRECL;
/
SHOW ERRORS
