CREATE OR REPLACE TRIGGER GSM_BEDE_SECIONES_ARCHIVOS_TG
BEFORE  DELETE
ON GSM_SECIONES_ARCHIVOS_TO
FOR EACH ROW

DECLARE
   v_SEC_ARCHIVO_SECCION GSM_SECIONES_ARCHIVOS_TO.SEC_ARCHIVO_SECCION%type;
begin
     v_SEC_ARCHIVO_SECCION := :old.SEC_ARCHIVO_SECCION;
     DELETE GSM_SECARCH_CAMPOS_TO
     WHERE SEC_ARCHIVO_SECCION = v_SEC_ARCHIVO_SECCION;
end;
/
SHOW ERRORS
