CREATE OR REPLACE TRIGGER GSM_AFUP_SOL_AUC_TG
AFTER UPDATE
ON GSM_SOLICITUD_AUC_TO
FOR EACH ROW
	     
WHEN ( NEW.NUM_CANTIDAD = NEW.NUM_CANTIDAD_AUC  AND   NEW.NUM_CANTIDAD_AUC <> OLD.NUM_CANTIDAD_AUC )
begin
	  UPDATE  GSM_CABSOL_SIMCARD_TO
	  SET     IND_AUC = 1,
	  		  COD_ESTADO ='DD'
	  WHERE   NUM_SEQ_SOLICITUD = :NEW.NUM_SEQ_SOLICITUD;
END;
/
SHOW ERRORS
