CREATE OR REPLACE TRIGGER GSM_DSOL_AFDE_TG
AFTER  DELETE
ON GSM_DET_SOLICITUD_AUC_TO
FOR EACH ROW
DECLARE
  v_simcard GSM_DET_SOLICITUD_AUC_TO.NUM_SIMCARD%TYPE;
begin

    v_simcard  := :OLD.NUM_SIMCARD;
    -- Borro Historico del detalle de la simcard
    DELETE FROM GSM_DET_SOLICITUD_AUC_TH
    WHERE NUM_SIMCARD = v_simcard;
end;
/
SHOW ERRORS
