CREATE OR REPLACE TRIGGER icb_afup_movimiento
AFTER UPDATE
OF COD_ESTADO
ON ICB_MOVIMIENTO

DECLARE
BEGIN
   DELETE ICB_MOVIMIENTO WHERE COD_ESTADO=0
                            OR COD_ESTADO=10;
END;
/
SHOW ERRORS
