CREATE OR REPLACE TRIGGER icb_afin_histmov
AFTER INSERT
ON ICB_HISTMOVIMIENTO

DECLARE
  V_TABLA VARCHAR2(35):= NULL;
BEGIN
  V_TABLA:= 'ICB_HISTMOVIMIENTO';
  DELETE FROM ICB_HISTMOVIMIENTO WHERE COD_ACT = 'BO';
  EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR
   (-20006,'ERROR TRIGGER ICB_AFIN_HISTMOV: '||
    V_TABLA ||' ORA'||TO_CHAR(SQLCODE),TRUE);
END;
/
SHOW ERRORS
