CREATE OR REPLACE TRIGGER ICB_AFIN_HISTCOM
AFTER INSERT
ON ICB_HISTCOMPROC

DECLARE
  V_TABLA VARCHAR2(35):= NULL;
BEGIN
  V_TABLA:= 'ICB_HISTCOMPROC';
  DELETE FROM ICB_HISTCOMPROC WHERE COD_ACT = 'BO';
  EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR
   (-20006,'ERROR TRIGGER ICB_AFIN_HISTCOM: '||
    V_TABLA ||' ORA'||TO_CHAR(SQLCODE),TRUE);
END;
/
SHOW ERRORS
