CREATE OR REPLACE TRIGGER icc_afin_histcom
AFTER INSERT
ON ICC_HISTCOMPROC

DECLARE
  V_TABLA VARCHAR2(35):= NULL;
BEGIN
  V_TABLA:= 'ICC_HISTCOMPROC';
  DELETE FROM ICC_HISTCOMPROC WHERE COD_ACT = 'BO';
  EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR
   (-20006,'ERROR TRIGGER ICC_AFIN_HISTCOM: '||
    V_TABLA ||' ORA'||TO_CHAR(SQLCODE),TRUE);
END;
/
SHOW ERRORS
