CREATE OR REPLACE TRIGGER icc_afup_movimiento
AFTER UPDATE
OF COD_ESTADO
ON ICC_MOVIMIENTO
DECLARE
BEGIN
   DELETE ICC_MOVIMIENTO WHERE COD_ESTADO=0
                            OR COD_ESTADO=10;
END;
/
SHOW ERRORS
