CREATE OR REPLACE TRIGGER icm_afin_histmov
AFTER INSERT
ON ICM_HISTMOVIMIENTO

DECLARE
  V_TABLA VARCHAR2(35):= NULL;
BEGIN
  V_TABLA:= 'ICM_HISTMOVIMIENTO';
  DELETE FROM ICM_HISTMOVIMIENTO WHERE COD_ACT = 'BO';
  EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR
   (-20006,'ERROR TRIGGER ICM_AFIN_HISTMOV: '||
    V_TABLA ||' ORA'||TO_CHAR(SQLCODE),TRUE);
END;
/
SHOW ERRORS
