CREATE OR REPLACE TRIGGER ICM_AFIN_HISTCOM
AFTER INSERT
ON ICM_HISTCOMPROC

DECLARE
  V_TABLA VARCHAR2(35):= NULL;
BEGIN
  V_TABLA:= 'ICM_HISTCOMPROC';
  DELETE FROM ICM_HISTCOMPROC WHERE COD_ACT = 'BO';
  EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR
   (-20006,'ERROR TRIGGER ICM_AFIN_HISTCOM: '|| V_TABLA ||' '||SQLERRM);
END;
/
SHOW ERRORS
