CREATE OR REPLACE TRIGGER icm_afup_movimiento
AFTER UPDATE
OF COD_ESTADO
ON ICM_MOVIMIENTO

DECLARE
BEGIN
   DELETE ICM_MOVIMIENTO WHERE COD_ESTADO=0
                            OR COD_ESTADO=10;
END;
/
SHOW ERRORS
