CREATE OR REPLACE TRIGGER icr_afup_movimiento
AFTER UPDATE
OF COD_ESTADO
ON ICR_MOVIMIENTO

DECLARE
BEGIN
   DELETE ICR_MOVIMIENTO WHERE COD_ESTADO=0
                            OR COD_ESTADO=10;
END;
/
SHOW ERRORS
