CREATE OR REPLACE TRIGGER icr_afin_histmov
AFTER INSERT
ON ICR_HISTMOVIMIENTO

DECLARE
  V_TABLA VARCHAR2(35):= NULL;
BEGIN
  V_TABLA:= 'ICR_HISTMOVIMIENTO';
  DELETE FROM ICR_HISTMOVIMIENTO WHERE COD_ACT = 'BO';
  EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR
   (-20006,'ERROR TRIGGER ICR_AFIN_HISTMOV: '||
    V_TABLA ||' ORA'||TO_CHAR(SQLCODE),TRUE);
END;
/
SHOW ERRORS
