CREATE OR REPLACE TRIGGER ICR_AFIN_HISTCOM
AFTER INSERT
ON ICR_HISTCOMPROC

DECLARE
  V_TABLA VARCHAR2(35):= NULL;
BEGIN
  V_TABLA:= 'ICR_HISTCOMPROC';
  DELETE FROM ICR_HISTCOMPROC WHERE COD_ACT = 'BO';
  EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR
   (-20006,'ERROR TRIGGER ICR_AFIN_HISTCOM: '||
    V_TABLA ||' ORA'||TO_CHAR(SQLCODE),TRUE);
END;
/
SHOW ERRORS
