CREATE OR REPLACE TRIGGER PV_INTAR_BEIN_TG
BEFORE INSERT ON GA_INTARCEL
FOR EACH ROW

DECLARE

	V_NUMMINMDN	 GA_INTARCEL.NUM_MIN_MDN%TYPE;

BEGIN

	IF :NEW.NUM_CELULAR = 0 THEN
		:NEW.NUM_MIN_MDN := 0;
	ELSE
		V_NUMMINMDN:= GE_FN_MIN_DE_MDN(TO_CHAR(:NEW.NUM_CELULAR));
		:NEW.NUM_MIN_MDN := V_NUMMINMDN;
	END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR  (-20002,'ERROR INESPERADO EN TRIGGER : ORA-'||TO_CHAR(SQLCODE)||'.',TRUE);
        NULL;
END;
/
SHOW ERRORS
