CREATE OR REPLACE TRIGGER PV_TRG_UPD_GA_LNCELU
BEFORE UPDATE ON GA_SINIESTROS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

BEGIN

	 IF :NEW.COD_ESTADO = 'FO' THEN

    	UPDATE GA_LNCELU
		SET FEC_CONSTPOL = :NEW.FEC_FORMALIZA,
		    NUM_CONSTPOL = :NEW.NUM_CONSTPOL
		WHERE NUM_SERIE = :NEW.NUM_SERIE
		AND NUM_ABONADO = :NEW.NUM_ABONADO;


	 END IF;


END	PV_TRG_UPD_GA_LNCELU;
/
SHOW ERRORS
