CREATE OR REPLACE TRIGGER TA_TRG_AFIN_ALMS AFTER INSERT ON GE_ALMS FOR EACH ROW

BEGIN
   TA_PR_INSERT_GEMULTIIDIOMA
   ( 'GE_ALMS', 'COD_ALM', :new.cod_alm,'DES_ALM', :new.des_alm );
END TA_TRG_AFIN_ALMS;
/
SHOW ERRORS
