CREATE OR REPLACE TRIGGER TA_TRG_AFIN_SERVESPE AFTER INSERT ON TA_SERVESPECIALES FOR EACH ROW

BEGIN
   TA_PR_INSERT_GEMULTIIDIOMA
   ( 'TA_SERVESPECIALES', 'NUM_SERVESPECIAL', :new.num_servespecial,'DES_SERVESPECIAL', :new.des_servespecial);
END TA_TRG_AFIN_SERVESPE;
/
SHOW ERRORS
