CREATE OR REPLACE TRIGGER TA_TRG_AFIN_PAISES AFTER INSERT ON GE_PAISES FOR EACH ROW

BEGIN
   TA_PR_INSERT_GEMULTIIDIOMA
   ( 'GE_PAISES', 'COD_PAIS', :new.cod_pais,'DES_PAIS', :new.des_pais );
END TA_TRG_AFIN_PAISES;
/
SHOW ERRORS
