CREATE OR REPLACE TRIGGER TA_TRG_AFUP_PAISES AFTER UPDATE ON GE_PAISES FOR EACH ROW

BEGIN
   UPDATE GE_MULTIIDIOMA
      SET DES_CONCEPTO  = :new.des_pais,
          FEC_ULTMOD    = SYSDATE,
          NOM_USUARIO   = USER
    WHERE NOM_TABLA     = 'GE_PAISES'
      AND NOM_CAMPO     = 'COD_PAIS'
      AND COD_PRODUCTO  = 0
      AND COD_CONCEPTO  = :new.cod_pais
      AND COD_IDIOMA    = ge_fn_idioma_local()
      AND NOM_CAMPO_DES = 'DES_PAIS' ;
END TA_TRG_AFUP_PAISES;
/
SHOW ERRORS
