CREATE OR REPLACE TRIGGER TA_TRG_AFUP_ALMS AFTER UPDATE ON GE_ALMS FOR EACH ROW

BEGIN
   UPDATE GE_MULTIIDIOMA
      SET DES_CONCEPTO  = :new.des_alm,
          FEC_ULTMOD    = SYSDATE,
          NOM_USUARIO   = USER
    WHERE NOM_TABLA     = 'GE_ALMS'
      AND NOM_CAMPO     = 'COD_ALM'
      AND COD_PRODUCTO  = 0
      AND COD_CONCEPTO  = :new.cod_alm
      AND COD_IDIOMA    = ge_fn_idioma_local()
      AND NOM_CAMPO_DES = 'DES_ALM' ;
END TA_TRG_AFUP_ALMS;
/
SHOW ERRORS
