CREATE OR REPLACE TRIGGER TOL_TRG_BEFDE_NUMNACIONAL
BEFORE  DELETE ON TA_NUMNACIONAL
FOR EACH ROW
DECLARE

begin

  DELETE FROM TOL_RANNUME_TD
     WHERE to_number(cod_oper) = :OLD.cod_operador
     AND num_lini = :OLD.num_tdesde
     AND num_linf = :OLD.num_thasta;

 EXCEPTION
   WHEN OTHERS THEN
   RAISE_APPLICATION_ERROR(-20999,'ERROR EN EL TOL_TRG_BEFDE_NUMNACIONAL '||SQLERRM);
   NULL;
END;
/
SHOW ERRORS
