CREATE OR REPLACE TRIGGER TR_VALIDA_GA_ABOAMIST_NUM_MIN
BEFORE INSERT OR UPDATE ON GA_ABOAMIST
FOR EACH ROW
 
WHEN (
NEW.NUM_MIN IS NULL
      )
BEGIN
	:NEW.NUM_MIN := AL_FN_PREFIJO_NUMERO(:NEW.NUM_CELULAR);
	DBMS_OUTPUT.PUT_LINE('NEW NUM_MIN '||:NEW.NUM_MIN);
END TR_VALIDA_GA_ABOAMIST_NUM_MIN;
/
SHOW ERRORS
