CREATE OR REPLACE TRIGGER TRG_AFUP_FAFACTDNOCIC AFTER UPDATE OF COD_OPERADORA ON FA_FACTDOCU_NOCICLO

DECLARE
BEGIN
RAISE_APPLICATION_ERROR   (-20001,'NO SE PERMITE MODIFICAR OPERADORA' ,TRUE);
END;
/
SHOW ERRORS
