CREATE OR REPLACE TRIGGER ve_afup_tipcomis
AFTER UPDATE
ON VE_VENDEDORES
FOR EACH ROW
 
WHEN (
new.cod_tipcomis <> old.cod_tipcomis
      )
DECLARE
BEGIN
   UPDATE GE_SEG_USUARIO
   SET
      COD_TIPCOMIS = :NEW.COD_TIPCOMIS
   WHERE
      COD_VENDEDOR = :OLD.COD_VENDEDOR;
END;
/
SHOW ERRORS
