//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : P-TMM-08004
//  @ File Name : CentroEmisorDAOIT.java
//  @ Date : 09/09/2008
//  @ Author : hsegura
//
//



package com.tmmas.scl.framework.customerdomainfacturacion.CustomerBillABE.dao.Interface;

import com.tmmas.scl.framework.CustomerDomain.exception.RateUsageRecordsException;


public interface CentroEmisorDAOIT {
	public String obtenerCentroEmisor(String codOficina, String codTipoDocto)throws RateUsageRecordsException;
}
