/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.sel.negsal.bean.ejb.session;

/**
 * Local interface for NegSalFacade.
 * @generated 
 * @wtp generated
 */
public interface NegSalFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
