/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.sel.negsal.bean.ejb.session;

/**
 * Home interface for NegSalFacade.
 * @generated 
 * @wtp generated
 */
public interface NegSalFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/NegSalFacade";
   public static final String JNDI_NAME="NegSalFacade";

   public com.tmmas.scl.operations.crm.f.sel.negsal.bean.ejb.session.NegSalFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
