/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.sel.negsal.bean.ejb.session;

/**
 * Local home interface for NegSalFacade.
 * @generated 
 * @wtp generated
 */
public interface NegSalFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/NegSalFacadeLocal";
   public static final String JNDI_NAME="NegSalFacadeLocal";

   public com.tmmas.scl.operations.crm.f.sel.negsal.bean.ejb.session.NegSalFacadeLocal create()
      throws javax.ejb.CreateException;

}
