GRANT SELECT ON PF_CARGOS_PRODUCTOS_SQ TO MAS_APPLICATION_RO;
GRANT SELECT ON PF_CARGOS_PRODUCTOS_SQ TO MAS_SELECT_RO;
GRANT SELECT ON PF_CARGOS_PRODUCTOS_SQ TO MAS_ADMIN_RO;
GRANT SELECT ON PF_CARGOS_PRODUCTOS_SQ TO SISCEL_SELECT;
