GRANT SELECT ON PF_PRODUCTOS_OFERTADOS_SQ TO MAS_ADMIN_RO
/
GRANT SELECT ON PF_PRODUCTOS_OFERTADOS_SQ TO MAS_APPLICATION_RO
/
GRANT SELECT ON PF_PRODUCTOS_OFERTADOS_SQ TO MAS_SELECT_RO
/
GRANT SELECT ON PF_PRODUCTOS_OFERTADOS_SQ TO SISCEL_SELECT
/
