GRANT SELECT ON PF_PRODUCTOS_CONTRATADOS_SQ TO MAS_ADMIN_RO
/
GRANT SELECT ON PF_PRODUCTOS_CONTRATADOS_SQ TO MAS_APPLICATION_RO
/
GRANT SELECT ON PF_PRODUCTOS_CONTRATADOS_SQ TO MAS_PRODUCT_DML
/
GRANT SELECT ON PF_PRODUCTOS_CONTRATADOS_SQ TO MAS_SELECT_RO
/
GRANT SELECT ON PF_PRODUCTOS_CONTRATADOS_SQ TO SISCEL
/
GRANT SELECT ON PF_PRODUCTOS_CONTRATADOS_SQ TO SISCEL_ADMIN
/
GRANT SELECT ON PF_PRODUCTOS_CONTRATADOS_SQ TO SISCEL_PV
/
GRANT SELECT ON PF_PRODUCTOS_CONTRATADOS_SQ TO SISCEL_SELECT
/
