GRANT DELETE ON PF_RESTRICCIONES_PROD_TD TO MAS_ADMIN_RO
/
GRANT INSERT ON PF_RESTRICCIONES_PROD_TD TO MAS_ADMIN_RO
/
GRANT SELECT ON PF_RESTRICCIONES_PROD_TD TO MAS_ADMIN_RO
/
GRANT UPDATE ON PF_RESTRICCIONES_PROD_TD TO MAS_ADMIN_RO
/
GRANT SELECT ON PF_RESTRICCIONES_PROD_TD TO MAS_APPLICATION_RO
/
GRANT SELECT ON PF_RESTRICCIONES_PROD_TD TO MAS_PRODUCT_DML
/
GRANT SELECT ON PF_RESTRICCIONES_PROD_TD TO MAS_SELECT_RO
/
