GRANT SELECT ON PR_PROCESOS_PROD_SQ TO MAS_ADMIN_RO
/
GRANT SELECT ON PR_PROCESOS_PROD_SQ TO MAS_APPLICATION_RO
/
GRANT SELECT ON PR_PROCESOS_PROD_SQ TO MAS_PRODUCT_DML
/
GRANT SELECT ON PR_PROCESOS_PROD_SQ TO MAS_SELECT_RO
/
GRANT SELECT ON PR_PROCESOS_PROD_SQ TO SISCEL_VE
/
