GRANT DELETE, INSERT, SELECT, UPDATE ON PR_PRODUCTOS_CONTRATADOS_TH TO MAS_ADMIN_RO
/

GRANT SELECT ON PR_PRODUCTOS_CONTRATADOS_TH TO MAS_APPLICATION_RO
/

GRANT DELETE, INSERT, SELECT, UPDATE ON PR_PRODUCTOS_CONTRATADOS_TH TO MAS_PRODUCT_DML
/

GRANT SELECT ON PR_PRODUCTOS_CONTRATADOS_TH TO MAS_SELECT_RO
/

GRANT SELECT ON PR_PRODUCTOS_CONTRATADOS_TH TO MAS_SERVICE_DML
/

GRANT SELECT ON PR_PRODUCTOS_CONTRATADOS_TH TO SISCEL
/