/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.fab.cim.mancon.bean.ejb.session;

/**
 * Local home interface for ManConFacade.
 * @generated 
 * @wtp generated
 */
public interface ManConFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ManConFacadeLocal";
   public static final String JNDI_NAME="ManConFacadeLocal";

   public com.tmmas.scl.operations.crm.fab.cim.mancon.bean.ejb.session.ManConFacadeLocal create()
      throws javax.ejb.CreateException;

}
