/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.fab.cim.mancon.bean.ejb.session;

/**
 * Remote interface for ManConFacade.
 * @generated 
 * @wtp generated
 */
public interface ManConFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO obtenerDatosCliente( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO obtenerDatosCliente( com.tmmas.scl.framework.marketSalesDomain.contactLeadProspectABE.dataTransferObject.VentaDTO venta )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO obtenerDatosAbonado( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO obtenerDatosAbonado2( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoListDTO obtenerListaAbonados( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * Obtiene lista de clientes por cuenta <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteTipoPlanListDTO obtenerDatosClienteCuenta( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * Obtiene lista de subcuentas de la cuenta <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.SubCuentaListDTO obtenerSubCuentas( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteListDTO buscarCliente( com.tmmas.scl.framework.serviceDomain.serviceABE.businessObject.dataTransferObject.NumeroDTO numero )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteListDTO buscarCliente( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoBeneficiarioListDTO obtieneAbonadosBeneficiarios( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO abonadoDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoBeneficiarioListDTO obtieneAbonadosBeneficiariosPorNumCelular( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO abonadoDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * Consulta hibrido <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO consultaHibrido( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.ConsultaHibridoDTO consulta )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * Consulta hibrido <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO agregaAbonadosBeneficiarios( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoBeneficiarioListDTO abonadoBeneficiarioListDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * Consulta hibrido <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO eliminaAbonadoBeneficiario( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoBeneficiarioListDTO abonadoBeneficiarioListDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO caducaEliminaAbonadoBeneficiario( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoBeneficiarioListDTO abonadoBeneficiarioList )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO obtenerNumeroMovimientoAlta( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO obtenerDatosAbonadoByNumCelular( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoVetadoListDTO obtieneAbonadosVetados( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO abonadoDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public int validaAbonadoBajaProgramada( long numAbonado )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO actualizarAbonadoVetadoTerminoVigencia( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoVetadoListDTO abonadoVetadoDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO agregarAbonadosVetados( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoVetadoListDTO abonadoVetadoListDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO crearSubCuenta( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.SubCuentaDTO cuenta )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.CuentaPersonalDTO obtenerNumeroPersonal( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.CuentaPersonalDTO cuentaPersonalDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public int obtenerInfoPer( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.CuentaPersonalDTO cuentaPersonalDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public int validaPersonal( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.CuentaPersonalDTO cuentaPersonalDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public int validaAtlantida( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public int validaAtlantidaCliente( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO obtenerCliente( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.CuentaPersonalDTO cuentaPersonalDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoListDTO obtenerListaAbonadosFiltrados( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.FiltroAbonadosDTO filtro )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO validaFiltroAbonados( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.ValidaFiltroAbonadosDTO filtro )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO obtenerNumAbonadosCliente( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO obtenerAbonadoEmpresa( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoListDTO obtieneBloqueAbonados( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.FiltroAbonadosDTO bloque )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO actualizarLineasPorPlan( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.PlanEvaluacionRiesgoDTO planEval )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.Long obtenerNumClientesCuenta( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteListDTO listarClientesCuenta( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.DatosClienteDTO obtenerDatosAdicCliente( java.lang.Long codCliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.IntegracionInClasificacionDTO consultaClasificacionCliente( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.IntegracionInClasificacionDTO integracionInClasificacionDTO )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO getCliente( com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.CalificacionAbonadoDTO obtieneCalificacionAbonado( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.CalificacionAbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.fab.cim.mancon.common.exception.ManConException, java.rmi.RemoteException;

}
