/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.osr.supbillandcol.bean.ejb.session;

/**
 * Local interface for SupBillAndColFacade.
 * @generated 
 * @wtp generated
 */
public interface SupBillAndColFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
