/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.o.csr.supordhan.bean.ejb.session;

/**
 * Local home interface for SupOrdHanFacade.
 * @generated 
 * @wtp generated
 */
public interface SupOrdHanFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SupOrdHanFacadeLocal";
   public static final String JNDI_NAME="SupOrdHanFacadeLocal";

   public com.tmmas.scl.operations.crm.o.csr.supordhan.bean.ejb.session.SupOrdHanFacadeLocal create()
      throws javax.ejb.CreateException;

}
