/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.o.csr.supordhan.bean.ejb.session;

/**
 * Home interface for SupOrdHanFacade.
 * @generated 
 * @wtp generated
 */
public interface SupOrdHanFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SupOrdHanFacade";
   public static final String JNDI_NAME="SupOrdHanFacade";

   public com.tmmas.scl.operations.crm.o.csr.supordhan.bean.ejb.session.SupOrdHanFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
