//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : P-TMM-08004
//  @ File Name : CuotaDTO.java
//  @ Date : 09/09/2008
//  @ Author : hsegura
//
//



package com.tmmas.scl.framework.CustomerDomain.CustomerBillABE.dto;

import java.io.Serializable;


public class CuotaDTO implements Serializable {
	private String codCuota;
	private String numCuota;
	private String desCuota;
	public String getCodCuota() {
		return codCuota;
	}
	public void setCodCuota(String codCuota) {
		this.codCuota = codCuota;
	}
	public String getDesCuota() {
		return desCuota;
	}
	public void setDesCuota(String desCuota) {
		this.desCuota = desCuota;
	}
	public String getNumCuota() {
		return numCuota;
	}
	public void setNumCuota(String numCuota) {
		this.numCuota = numCuota;
	}
}
