//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : P-TMM-08004
//  @ File Name : FacturaMicelaneaSalidaDTO.java
//  @ Date : 28/08/2008
//  @ Author : 
//
//



package com.tmmas.scl.framework.CustomerDomain.CustomerBillABE.dto;

import java.io.Serializable;


public class FacturaMiscelaneaSalidaDTO implements Serializable {
	private static final long serialVersionUID = 1L;
	private String numeroProceso;
	private String montoFacturaNeto;
	private String  snError;
	private String svMensaje;	
	private String  snEvento;	
	public static long getSerialVersionUID() {
		return serialVersionUID;
	}
	public String getMontoFacturaNeto() {
		return montoFacturaNeto;
	}
	public void setMontoFacturaNeto(String montoFacturaNeto) {
		this.montoFacturaNeto = montoFacturaNeto;
	}
	public String getNumeroProceso() {
		return numeroProceso;
	}
	public void setNumeroProceso(String numeroProceso) {
		this.numeroProceso = numeroProceso;
	}
	public String getSnError() {
		return snError;
	}
	public void setSnError(String snError) {
		this.snError = snError;
	}
	public String getSnEvento() {
		return snEvento;
	}
	public void setSnEvento(String snEvento) {
		this.snEvento = snEvento;
	}
	public String getSvMensaje() {
		return svMensaje;
	}
	public void setSvMensaje(String svMensaje) {
		this.svMensaje = svMensaje;
	}
	
}
