CREATE OR REPLACE FORCE VIEW AL_GAMA_VW
(
   COD_DOMINIO,
   VALOR,
   DESCRIPCION_VALOR,
   IND_ESTADO,
   FEC_CREACION,
   USU_CREACION,
   FEC_MODIFICACION,
   USU_MODIFICACION
)
AS
   SELECT   COD_DOMINIO,
            VALOR,
            DESCRIPCION_VALOR,
            IND_ESTADO,
            FEC_CREACION,
            USU_CREACION,
            FEC_MODIFICACION,
            USU_MODIFICACION
     FROM   GE_VALORES_DOMINIOS_KNL_VW
    WHERE   COD_DOMINIO = 'GAMA'
   WITH READ ONLY
/   


