CREATE OR REPLACE FORCE VIEW CO_DOCTOS_PAGO_VALI_VW(
   COD_DOMINIO
 , VALOR
 , DESCRIPCION_VALOR
 , IND_ESTADO
 , FEC_CREACION
 , USU_CREACION
 , FEC_MODIFICACION
 , USU_MODIFICACION
 ) AS 
SELECT
  COD_DOMINIO,
  VALOR,
  DESCRIPCION_VALOR,
  IND_ESTADO,
  FEC_CREACION,
  USU_CREACION,
  FEC_MODIFICACION,
  USU_MODIFICACION
FROM
  GE_VALORES_DOMINIOS_KNL_VW
WHERE
  COD_DOMINIO ='COD_DOCTOS_PAGO_VALI'
WITH READ ONLY
/
SHOW ERRORS
