/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.ss911correofax.negocio.ejb;

/**
 * Home interface for ServSupl911CorreoFaxFacade.
 * @generated 
 * @wtp generated
 */
public interface ServSupl911CorreoFaxFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServSupl911CorreoFaxFacade";
   public static final String JNDI_NAME="ServSupl911CorreoFaxFacade";

   public com.tmmas.cl.scl.ss911correofax.negocio.ejb.ServSupl911CorreoFaxFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
