/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.ss911correofax.negocio.ejb;

/**
 * Remote interface for ServSupl911CorreoFaxFacade.
 * @generated 
 * @wtp generated
 */
public interface ServSupl911CorreoFaxFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void insertGaContactoAbonadoTO( com.tmmas.cl.scl.ss911correofax.dto.GaContactoAbonadoToDTO gaContactoAbonadoTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.ss911correofax.dto.CodigosDTO[] getListCodigos( com.tmmas.cl.scl.ss911correofax.dto.CodigosDTO entrada )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.ss911correofax.dto.ContactoAbonadoTT[] obtenerListaContactos( com.tmmas.cl.scl.ss911correofax.dto.ContactoAbonadoTT contactoAbonadoTT )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void deleteInsertPvContactoAbonadoTT( com.tmmas.cl.scl.ss911correofax.dto.ContactoAbonadoTT[] contactoAbonadoTTs )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.ss911correofax.dto.ParametrosGeneralesDTO getParametroGeneral( com.tmmas.cl.scl.ss911correofax.dto.ParametrosGeneralesDTO entrada )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void setDireccion( com.tmmas.cl.scl.ss911correofax.dto.DireccionNegocioWebDTO entrada )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void setGaContTHDelGaContTO_DelDireccion( com.tmmas.cl.scl.ss911correofax.dto.GaContactoAbonadoTO gaContactoAbonadoTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

}
