/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.ss911correofax.negocio.ejb;

/**
 * Local interface for ServSupl911CorreoFaxFacade.
 * @generated 
 * @wtp generated
 */
public interface ServSupl911CorreoFaxFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
