/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.spnsclcatalogo.soa.ejb.session;

/**
 * Home interface for SpnSclCatalogo.
 * @generated 
 * @wtp generated
 */
public interface SpnSclCatalogoHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SpnSclCatalogo";
   public static final String JNDI_NAME="SpnSclCatalogo";

   public com.tmmas.cl.scl.spnsclcatalogo.soa.ejb.session.SpnSclCatalogo create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
