/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.spnsclcatalogo.soa.ejb.session;

/**
 * Remote interface for SpnSclCatalogo.
 * @generated 
 * @wtp generated
 */
public interface SpnSclCatalogo
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListClienteIdentOutDTO getListadoClientesXIdentificacion( com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsClienteIdentInDTO cliente )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.BodegaDTO[] getBodegasPorVendedor( java.lang.String codigoVendedor )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WsOutSSuplementariosDTO getSSincluidosEnPlan( java.lang.String codigoPlanTarifario )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.WsOutSSuplementariosDTO getSSOpcionalesAlPlan( java.lang.String codigoPlanTarifario,java.lang.String codigoArticulo,java.lang.String codigCentral )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListPlanTarifarioOutDTO getListadoPlanesTarifarios( com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsPlanTarifarioInDTO inWSLstPlanTarifDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListModalidadPagoOutDTO getListadoModalidadPago(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.RegionDTO[] getListadoRegiones(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.ProvinciaDTO[] getListadoProvincias( com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.RegionDTO region )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.CiudadDTO[] getListadoCiudades( com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.ProvinciaDTO provincia )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.ComunaSPNDTO[] getListadoComunas( com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.CiudadDTO ciudad )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListCicloFactOutDTO getListadoCiclosPostPago(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.VendedorDTO[] getTipoComisionista(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListBancoOutDTO getListadoBancosPAC(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListTarjetaOutDTO getListadoTarjetas(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.CantidadStockSerieDTO getCantidadStockSerie( com.tmmas.cl.scl.gestiondeabonados.businessobject.dto.CantidadSerieDTO cantidadSerieDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.SumaPrecioPlanesDTO getSumaPrecioPlanesXAntiguedad( com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.SumaPlanesDTO sumaPlanesDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonapp.dto.WsReglaSSOutDTO getReglasCompatibilidadSS(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonapp.dto.WsCategoriaImpostivaOutDTO getListCategImpositivas(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonapp.dto.WsActividadesOutDTO getListActividades(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonapp.dto.WsOcupacionesOutDTO getListaOcupaciones(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonapp.dto.WsSucursalesBancoOutDTO getSucursalesBanco( com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.SucursalBancoDTO sucursalBancoDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonapp.dto.WsClasificacionCuentaOutDTO getClasificacionCuenta(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsHomeLineaOutDTO getHomeLinea( com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.DireccionCentralDTO direccionCentralDTO )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonapp.dto.WSEstadoCivilOutDTO getListaEstadoCivil(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonapp.dto.WsEstadoOutDTO getListaEstados(  )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondedirecciones.businessobject.dto.PuebloDTO[] getListadoPueblos( com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.EstadoDTO estado )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsListConsultaPlanTarifarioOutDTO getConsultaPlanesTarifarios( com.tmmas.cl.scl.gestiondeclientescommon.commonapp.dto.WsConsultaPlanTarifarioInDTO consultaPlanTarifarioIn )
      throws java.rmi.RemoteException;

}
