/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.sel.negsal.soa.bean.ejb.session;

/**
 * Local home interface for NegSalORC.
 * @generated 
 * @wtp generated
 */
public interface NegSalORCLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/NegSalORCLocal";
   public static final String JNDI_NAME="NegSalORCLocal";

   public com.tmmas.scl.operations.crm.f.sel.negsal.soa.bean.ejb.session.NegSalORCLocal create()
      throws javax.ejb.CreateException;

}
