/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.sel.negsal.soa.bean.ejb.session;

/**
 * Home interface for NegSalORC.
 * @generated 
 * @wtp generated
 */
public interface NegSalORCHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/NegSalORC";
   public static final String JNDI_NAME="NegSalORC";

   public com.tmmas.scl.operations.crm.f.sel.negsal.soa.bean.ejb.session.NegSalORC create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
