CREATE OR REPLACE PROCEDURE            P_NP_SACAR_USUARIO
(
VP_COD_USUARIO     IN  PSD_USUARIO.COD_USUARIO%TYPE,
VP_LOGIN_USUARIO   OUT PSD_USUARIO.UID_USUARIO%TYPE,
VP_ERR             OUT NUMBER
)
is
BEGIN
    VP_ERR := 0;
    SELECT uid_usuario
	INTO vp_login_usuario
	FROM PSD_USUARIO
	WHERE COD_USUARIO = VP_COD_USUARIO;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
              VP_ERR:= SQLCODE;
	WHEN OTHERS then
	      VP_ERR:= SQLCODE;
END;
/
SHOW ERRORS
