/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.smo.fulfillment.scaa.issserord.bean.ejb.session;

/**
 * Local interface for IssSerOrdFacade.
 * @generated 
 * @wtp generated
 */
public interface IssSerOrdFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
