/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.oh.clocusord.bean.ejb.session;

/**
 * Local home interface for CloCusOrdFacade.
 * @generated 
 * @wtp generated
 */
public interface CloCusOrdFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CloCusOrdFacadeLocal";
   public static final String JNDI_NAME="CloCusOrdFacadeLocal";

   public com.tmmas.scl.operations.crm.f.oh.clocusord.bean.ejb.session.CloCusOrdFacadeLocal create()
      throws javax.ejb.CreateException;

}
