/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.oh.clocusord.bean.ejb.session;

/**
 * Local interface for CloCusOrdFacade.
 * @generated 
 * @wtp generated
 */
public interface CloCusOrdFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
