/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.gestionlc.ejb.session;

/**
 * Session layer for Foo.
 * @generated 
 * @wtp generated
 */
public class FooSession
   extends com.tmmas.scl.gestionlc.ejb.session.FooBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {

      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbRemove();
   }

}
