CREATE OR REPLACE TYPE AL_SERIE_QT AS OBJECT
(
  NUM_SERIE     VARCHAR2(25),
  COD_BODEGA    NUMBER(6),
  TIP_STOCK     NUMBER(2),
  COD_ARTICULO  NUMBER(6),
  COD_USO       NUMBER(2),
  COD_ESTADO    NUMBER(2),
  NUM_DESDE     NUMBER(9),
  FEC_ENTRADA   DATE,
  IND_TELEFONO  NUMBER(1),
  CAP_CODE      NUMBER(7),
  NUM_TELEFONO  NUMBER(15),
  NUM_SERIEMEC  VARCHAR2(20),
  PRC_COMPRA    NUMBER(14,4),
  COD_PRODUCTO  NUMBER(1),
  COD_CENTRAL   NUMBER(3),
  COD_SUBALM    VARCHAR2(5),
  COD_CAT       NUMBER(2),
  PLAN          VARCHAR2(3),
  CARGA         NUMBER(14,4),
  NUM_SEC_LOCA  NUMBER(10),
  COD_HLR       VARCHAR2(10),
  COD_PLAZA     VARCHAR2(5),
  CONSTRUCTOR FUNCTION AL_SERIE_QT RETURN self AS result

)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY AL_SERIE_QT IS
  CONSTRUCTOR FUNCTION AL_SERIE_QT RETURN self AS result AS

  BEGIN
    NUM_SERIE     := NULL;
    COD_BODEGA    := NULL;
    TIP_STOCK     := NULL;
    COD_ARTICULO  := NULL;
    COD_USO       := NULL;
    COD_ESTADO    := NULL;
    NUM_DESDE     := NULL;
    FEC_ENTRADA   := NULL;
    IND_TELEFONO  := NULL;
    CAP_CODE      := NULL;
    NUM_TELEFONO  := NULL;
    NUM_SERIEMEC  := NULL;
    PRC_COMPRA    := NULL;
    COD_PRODUCTO  := NULL;
    COD_CENTRAL   := NULL;
    COD_SUBALM    := NULL;
    COD_CAT       := NULL;
    PLAN          := NULL;
    CARGA         := NULL;
    NUM_SEC_LOCA  := NULL;
    COD_HLR       := NULL;
    COD_PLAZA     := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
