CREATE OR REPLACE TYPE AL_TIPOS_TERMINALES_QT AS OBJECT
(
  COD_PRODUCTO  NUMBER(1),
  TIP_TERMINAL  VARCHAR2(1),
  DES_TERMINAL  VARCHAR2(15),
  CONSTRUCTOR FUNCTION AL_TIPOS_TERMINALES_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY AL_TIPOS_TERMINALES_QT IS

  CONSTRUCTOR FUNCTION AL_TIPOS_TERMINALES_QT RETURN self AS result AS
  BEGIN
    COD_PRODUCTO  := NULL;
    TIP_TERMINAL  := NULL;
    DES_TERMINAL  := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
