CREATE OR REPLACE TYPE AL_USO_QT AS OBJECT
(
  COD_USO               NUMBER(2),
  DES_USO               VARCHAR2(20),
  IND_RESTPLAN          NUMBER(1),
  IND_CARGOPRO          NUMBER(1),
  IND_USOVENTA          NUMBER(1),
  NUM_DIAS_HIBERNACION  NUMBER(3),
  CONSTRUCTOR FUNCTION AL_USO_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY AL_USO_QT IS

  CONSTRUCTOR FUNCTION AL_USO_QT RETURN self AS result AS
  BEGIN
    COD_USO               :=NULL;
    DES_USO               :=NULL;
    IND_RESTPLAN          :=NULL;
    IND_CARGOPRO          :=NULL;
    IND_USOVENTA          :=NULL;
    NUM_DIAS_HIBERNACION  :=NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
