CREATE OR REPLACE TYPE ER_DATOSBURO_OT AS OBJECT
(
  REGISTRO00CIU ER_REG00CIU_OT,
  REGISTRO00EXT ER_REG00EXT_OT,
  REGISTRO03 ER_REG03_CT,
  REGISTRO08 ER_REG08_CT,
  REGISTRO01 ER_REG01_CT,
  REGISTRO20 ER_REG20_OT,
  REGISTRO99 ER_REG99_OT,
  DEUDA_TOTAL NUMBER,
  CONSTRUCTOR FUNCTION ER_DATOSBURO_OT(self IN OUT NOCOPY ER_DATOSBURO_OT) RETURN self AS result
)  NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY ER_DATOSBURO_OT IS
  CONSTRUCTOR FUNCTION ER_DATOSBURO_OT(self IN OUT NOCOPY ER_DATOSBURO_OT) RETURN self AS result AS
  BEGIN
    REGISTRO20:=NEW ER_REG20_OT();
    REGISTRO00CIU:= NEW ER_REG00CIU_OT();
    REGISTRO00EXT:= NEW ER_REG00EXT_OT();
    REGISTRO99:=    NEW ER_REG99_OT();
    SELF.REGISTRO03:= NEW ER_REG03_CT();
    SELF.REGISTRO08:= NEW ER_REG08_CT();
  RETURN;
  END;
END;
/
SHOW ERRORS
