CREATE OR REPLACE TYPE               ER_REG08_OT AS OBJECT
(
  TIPO_REGISTRO VARCHAR2(2),
  VECTOR_COMPORTAMIENTO VARCHAR2(24),
  GARANTE VARCHAR2(2),
  DESC_GARANTE VARCHAR2(9),
  INDICADOR_VALORES VARCHAR2(1),
  VALOR_INICIAL VARCHAR2(7),
  SALDO_ACTUAL VARCHAR2(7),
  SALDO_MORA VARCHAR2(7),
  CUOTA VARCHAR2(7),
  CUOTAS_CANCELADAS VARCHAR2(3),
  TOTAL_CUOTAS VARCHAR2(3),
  PERIODO_PAGO VARCHAR2(1),
  TIPO_OBLIGACION VARCHAR2(1),
  FORMA_PAGO_TOTAL VARCHAR2(1),
  SENAL_ALIVIO VARCHAR2(1),
  NOVEDAD_ALIVIADA VARCHAR2(2),
  POSISCION_ALIVIO VARCHAR2(2),
  CONSTRUCTOR FUNCTION ER_REG08_OT(self IN OUT NOCOPY ER_REG08_OT) RETURN self AS result
) NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY ER_REG08_OT IS
  CONSTRUCTOR FUNCTION ER_REG08_OT(self IN OUT NOCOPY ER_REG08_OT) RETURN self AS result AS
  BEGIN
    RETURN;
  END;
END;
/
SHOW ERRORS
