CREATE OR REPLACE TYPE               ER_REG00EXT_OT AS OBJECT
(
  TIPO_REGISTRO VARCHAR2(2),
  COD_SUSCRIPTOR VARCHAR2(6),
  FECHA_CONSULTA VARCHAR2(8),
  TIPO_IDENTIFICACION VARCHAR2(1),
  NOMBRE VARCHAR2(45),
  NUM_IDENT VARCHAR2(11),
  ESPACIO_FUTURO1 VARCHAR2(8),
  ESPACIO_FUTURO2 VARCHAR2(64),
  NACIONALIDAD VARCHAR2(15),
CONSTRUCTOR FUNCTION ER_REG00EXT_OT(self IN OUT NOCOPY ER_REG00EXT_OT) RETURN self AS result
) NOT FINAL;
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY ER_REG00EXT_OT IS
  CONSTRUCTOR FUNCTION ER_REG00EXT_OT(self IN OUT NOCOPY ER_REG00EXT_OT) RETURN self AS result AS
  BEGIN
      self.TIPO_REGISTRO:=NULL;
      RETURN;
  END;
END;
/
SHOW ERRORS
