CREATE OR REPLACE TYPE               ER_REG99_OT AS OBJECT
(
  TIPO_REGISTRO VARCHAR2(2),
  COD_RESPUESTA VARCHAR2(2),
  MENSAJE VARCHAR2(76),
CONSTRUCTOR FUNCTION ER_REG99_OT(self IN OUT NOCOPY ER_REG99_OT) RETURN self AS result
)NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY ER_REG99_OT IS
CONSTRUCTOR FUNCTION ER_REG99_OT(self IN OUT NOCOPY ER_REG99_OT) RETURN self AS result AS
  BEGIN
    RETURN;
  END;
END;
/
SHOW ERRORS
