CREATE OR REPLACE TYPE               ER_REG00CIU_OT AS OBJECT
(
  TIPO_REGISTRO VARCHAR2(2),
  COD_SUSCRIPTOR VARCHAR2(6),
  FECHA_CONSULTA VARCHAR2(8),
  COD_TIPIDENT VARCHAR2(1),
  NOMBRE_COMPLETO VARCHAR2(45),
  NUM_IDENT VARCHAR2(11),
  VIGENCIA VARCHAR2(2),
  FECHA_EXPEDICION VARCHAR2(6),
  CIUDAD VARCHAR2(15),
  DEPARTAMENTO VARCHAR2(10),
  PRIMER_APELLIDO VARCHAR2(16),
  SEGUNDO_APELLIDO VARCHAR2(16),
  NOMBRE VARCHAR2(20),
  GENERO VARCHAR2(1),
  RANGO_EDAD VARCHAR2(1),
CONSTRUCTOR FUNCTION ER_REG00CIU_OT(self IN OUT NOCOPY ER_REG00CIU_OT) RETURN self AS result
)NOT FINAL;
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY ER_REG00CIU_OT IS
  CONSTRUCTOR FUNCTION ER_REG00CIU_OT(self IN OUT NOCOPY ER_REG00CIU_OT) RETURN self AS result AS
  BEGIN
    RETURN;
  END;
END;
/
SHOW ERRORS
