CREATE OR REPLACE TYPE               ER_REG01_OT AS OBJECT
(
  TIPO_REGISTRO VARCHAR2(2),
  COD_SUSCRIPTOR VARCHAR2(6),
  FECHA_CONSULTA VARCHAR2(8),
  COD_TIPIDENT VARCHAR2(1),
  NOMBRE VARCHAR2(45),
  NUM_IDENT VARCHAR2(11),
  ESPACIO_FUTURO VARCHAR2(7),
  CONSTRUCTOR FUNCTION ER_REG01_OT(self IN OUT NOCOPY ER_REG01_OT) RETURN self AS result
)NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY ER_REG01_OT IS
  CONSTRUCTOR FUNCTION ER_REG01_OT(self IN OUT NOCOPY ER_REG01_OT) RETURN self AS result AS
  BEGIN
    RETURN;
  END;
END;
/
SHOW ERRORS
