CREATE OR REPLACE TYPE               ER_REG03_OT AS OBJECT
(
  TIPO_REGISTRO VARCHAR2(2),
  COD_ESTADO VARCHAR2(2),
  ESPACIO_FUTURO VARCHAR2(2),
  DESCRIPCION_ESTADO VARCHAR2(15),
  IND_VALORES VARCHAR2(8),
  TIP_CUENTA VARCHAR2(3),
  COD_SUSCRIPTOR VARCHAR2(6),
  NOM_SUSCRIPTOR VARCHAR2(14),
  FECHA_ACTUALIZACION VARCHAR2(6),
  NUM_OBLIGACION VARCHAR2(9),
  FECHA_APERTURA VARCHAR2(6),
  FECHA_VENCIMIENTO VARCHAR2(6),
  ESPACIO_FUTURO2 VARCHAR2(1),
  CONSTRUCTOR FUNCTION ER_REG03_OT(self IN OUT NOCOPY ER_REG03_OT) RETURN self AS result
)NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY ER_REG03_OT IS
  CONSTRUCTOR FUNCTION ER_REG03_OT(self IN OUT NOCOPY ER_REG03_OT) RETURN self AS result AS
  BEGIN
    RETURN;
  END;
END;
/
SHOW ERRORS
