CREATE OR REPLACE TYPE               ER_REG20_OT AS OBJECT
(
  TIPO_REGISTRO VARCHAR2(2),
  TIPO_SCORE VARCHAR2(2),
  CALIFICACION VARCHAR2(7),
  CLASIFICACION VARCHAR2(1),
  RAZON1 VARCHAR2(5),
  RAZON2 VARCHAR2(5),
  RAZON3 VARCHAR2(5),
  RAZON4 VARCHAR2(5),
  RAZON5 VARCHAR2(5),
  RAZON6 VARCHAR2(5),
  RAZON7 VARCHAR2(5),
  RAZON8 VARCHAR2(5),
  GCC    VARCHAR2(5),
  GAMA   VARCHAR2(5),
  ESPACIO_FUTURO VARCHAR2(18),
CONSTRUCTOR FUNCTION ER_REG20_OT(self IN OUT NOCOPY ER_REG20_OT) RETURN self AS result
)NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY ER_REG20_OT IS
  CONSTRUCTOR FUNCTION ER_REG20_OT(self IN OUT NOCOPY ER_REG20_OT) RETURN self AS result AS
  BEGIN
    RETURN;
  END;
END;
/
SHOW ERRORS
