CREATE OR REPLACE TYPE ERD_PARAMETROS_OT AS OBJECT
(
  COD_CODIGO          NUMBER(6),
  COD_SUBCODIGO       NUMBER(6),
  DES_CODIGO          VARCHAR2(50),
  COD_PARAMETRO       NUMBER(6),
  IND_TIPO_PARAMETRO  NUMBER(2),
  DES_PARAMETRO1      VARCHAR2(55),
  DES_PARAMETRO2      VARCHAR2(30),
  VAL_OPERADOR1       CHAR(1),
  VAL_OPERADOR2       CHAR(1),
  VAL_PARAMETRO1      VARCHAR2(20),
  VAL_PARAMETRO2      VARCHAR2(20),
  NOM_USUARIO_MODI    VARCHAR2(30),
  FEC_MODI_H          DATE,
  CONSTRUCTOR FUNCTION ERD_PARAMETROS_OT (self IN OUT NOCOPY ERD_PARAMETROS_OT) RETURN self AS result
)  NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY ERD_PARAMETROS_OT  IS
  CONSTRUCTOR FUNCTION ERD_PARAMETROS_OT (self IN OUT NOCOPY ERD_PARAMETROS_OT) RETURN self AS result AS
    BEGIN
        RETURN;
    END;
END;
/
SHOW ERRORS
