CREATE OR REPLACE TYPE FA_CARGOS_REC_QT AS OBJECT
(
  COD_CLIENTESERV NUMBER(10),
  NUM_ABONADOSERV NUMBER(10),
  COD_PROD_CONTRATADO NUMBER(38),
  COD_CARGO_CONTRATADO NUMBER(9),
  COD_CLIENTEPAGO NUMBER(10),
  NUM_ABONADOPAGO NUMBER(10),
  COD_TIPSERV VARCHAR2(2),
  COD_SERVICIO VARCHAR2(5),
  COD_PLANSERV VARCHAR2(5),
  IND_CARGOPRO NUMBER(1),
  COD_CONCEPTO NUMBER(9),
  FEC_ALTA DATE,
  FEC_BAJA DATE,
  FEC_DESDECOBR DATE,
  FEC_HASTACOBR DATE,
  IND_BLOQUEO VARCHAR2(5),
  EST_BLOQUEO VARCHAR2(5),
  FEC_DESDEBLOC DATE,
  FEC_HASTABLOC DATE,
  FEC_ULTFACTURA DATE,
  COD_ULTCICLFACT NUMBER(10),
  NUM_ULTPROCESO NUMBER(10),
  FEC_ULTMOD DATE,
  NOM_USUARIO VARCHAR2(30)
)
/
SHOW ERRORS
