CREATE OR REPLACE TYPE FA_CLIENTE_DTO_OT AS OBJECT
(COD_CLIENTE NUMBER(8) ,
FEC_DESDE DATE,
FEC_HASTA DATE,
TIP_DISTRIBUCION NUMBER(1),
COD_DESPACHO VARCHAR2(5),
NOM_EMAIL  VARCHAR2(70),
NOM_USUARIO VARCHAR2(30),
FEC_ULTMOD DATE ,
CONSTRUCTOR FUNCTION FA_CLIENTE_DTO_OT RETURN SELF AS RESULT
)
/
SHOW ERRORS
CREATE OR REPLACE type body FA_CLIENTE_DTO_OT IS
    -- Constructor por defecto
    CONSTRUCTOR FUNCTION FA_CLIENTE_DTO_OT RETURN SELF AS RESULT AS
    BEGIN
        self.COD_CLIENTE := null;
        self.FEC_DESDE := null;
        self.FEC_HASTA := null;
		self.TIP_DISTRIBUCION := null;
        self.COD_DESPACHO := null;
        self.NOM_EMAIL := null;
        self.NOM_USUARIO := null;
        self.FEC_ULTMOD := null;

        RETURN;
    END;
END;
/
SHOW ERRORS
