CREATE OR REPLACE TYPE GA_APROVISIONAR_QT AS OBJECT
(
NUM_ABONADO	  		 		   NUMBER(08),
COD_ACTABO	  		 		   VARCHAR2(02),
NOM_USUARORA  			 	   VARCHAR2(30),
TIP_TERMINAL  			 	   VARCHAR2(01),
COD_CENTRAL	  			 	   NUMBER(03),
NUM_CELULAR	  	   		 	   NUMBER(15),
NUM_SERIE	  	   		 	   VARCHAR(25),
TIP_TECNOLOGIA				   VARCHAR2(07),
IMEI	   				   	   VARCHAR2(20),
VAL_OOSS  	   				   NUMBER(14,4),
COD_PLANTARIF_NUEVO			   VARCHAR2(3),
NUN_OOSS					   NUMBER(10),
COD_OOSS					   VARCHAR2(05),
SEQ_NUMMOV  				   NUMBER(9),
COD_TIPLAN					   VARCHAR2(5),
COD_SERVICIOS				   VARCHAR2(255),
COD_PLANTARIF				   VARCHAR2(3),
VALOR_PLAN					   NUMBER(14,4),
NUM_MOVANT  				   NUMBER(9)
)
/
SHOW ERRORS
