CREATE OR REPLACE TYPE GA_CAUCASER_QT AS OBJECT
(
  COD_PRODUCTO     NUMBER(1),
  COD_CAUCASER     VARCHAR2(2),
  DES_CAUCASER     VARCHAR2(30),
  IND_ANTIGUEDAD   NUMBER(1),
  IND_CARGO        NUMBER(1),
  IND_DEV_ALMACEN  NUMBER(1),
  COD_ESTADO_DEV   NUMBER(2),
  CONSTRUCTOR FUNCTION GA_CAUCASER_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY GA_CAUCASER_QT IS

  CONSTRUCTOR FUNCTION GA_CAUCASER_QT RETURN self AS result AS
  BEGIN
    COD_PRODUCTO := NULL;
    COD_CAUCASER := NULL;
    DES_CAUCASER := NULL;
    IND_ANTIGUEDAD := NULL;
    IND_CARGO := NULL;
    IND_DEV_ALMACEN := NULL;
    COD_ESTADO_DEV := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
