CREATE OR REPLACE TYPE GA_EQUIPABOSER_QT AS OBJECT
(
  NUM_ABONADO     NUMBER(8),
  NUM_SERIE       VARCHAR2(25),
  COD_PRODUCTO    NUMBER(1),
  IND_PROCEQUI    VARCHAR2(1),
  FEC_ALTA        DATE,
  IND_PROPIEDAD   VARCHAR2(1),
  COD_BODEGA      NUMBER(6),
  TIP_STOCK       NUMBER(2),
  COD_ARTICULO    NUMBER(6),
  IND_EQUIACC     VARCHAR2(1),
  COD_MODVENTA    NUMBER(2),
  TIP_TERMINAL    VARCHAR2(1),
  COD_USO         NUMBER(2),
  COD_CUOTA       VARCHAR2(2),
  COD_ESTADO      NUMBER(2),
  CAP_CODE        NUMBER(7),
  COD_PROTOCOLO   VARCHAR2(2),
  NUM_VELOCIDAD   NUMBER(4),
  COD_FRECUENCIA  NUMBER(1),
  COD_VERSION     NUMBER(2),
  NUM_SERIEMEC    VARCHAR2(20),
  DES_EQUIPO      VARCHAR2(40),
  COD_PAQUETE     NUMBER(6),
  NUM_MOVIMIENTO  NUMBER(10),
  COD_CAUSA       VARCHAR2(2),
  IND_EQPRESTADO  VARCHAR2(1),
  NUM_IMEI        VARCHAR2(25),
  COD_TECNOLOGIA  VARCHAR2(7),
  IMP_CARGO       NUMBER(14,4),
  TIP_DTO         NUMBER(1),
  VAL_DTO         NUMBER(14,4),
  CONSTRUCTOR FUNCTION GA_EQUIPABOSER_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY GA_EQUIPABOSER_QT IS

  CONSTRUCTOR FUNCTION GA_EQUIPABOSER_QT RETURN self AS result AS
  BEGIN
    NUM_ABONADO      := NULL;
    NUM_SERIE        := NULL;
    COD_PRODUCTO     := NULL;
    IND_PROCEQUI     := NULL;
    FEC_ALTA         := NULL;
    IND_PROPIEDAD    := NULL;
    COD_BODEGA       := NULL;
    TIP_STOCK        := NULL;
    COD_ARTICULO     := NULL;
    IND_EQUIACC      := NULL;
    COD_MODVENTA     := NULL;
    TIP_TERMINAL     := NULL;
    COD_USO          := NULL;
    COD_CUOTA        := NULL;
    COD_ESTADO       := NULL;
    CAP_CODE         := NULL;
    COD_PROTOCOLO    := NULL;
    NUM_VELOCIDAD    := NULL;
    COD_FRECUENCIA   := NULL;
    COD_VERSION      := NULL;
    NUM_SERIEMEC     := NULL;
    DES_EQUIPO       := NULL;
    COD_PAQUETE      := NULL;
    NUM_MOVIMIENTO   := NULL;
    COD_CAUSA        := NULL;
    IND_EQPRESTADO   := NULL;
    NUM_IMEI         := NULL;
    COD_TECNOLOGIA   := NULL;
    IMP_CARGO        := NULL;
    TIP_DTO          := NULL;
    VAL_DTO          := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
