CREATE OR REPLACE TYPE GA_PRESUPUESTO_QT AS OBJECT
(
  NUM_PROCESO NUMBER(8),
  NUM_VENTA NUMBER(8),
  FECHA_VCTO DATE,
  TIP_FOLIACION VARCHAR2(1),
  IMP_BASE NUMBER,
  IMP_DTO NUMBER,
  IMP_IMPUESTO NUMBER
)
/
SHOW ERRORS
