CREATE OR REPLACE TYPE GA_SINIESTROS_QT AS OBJECT
(
  NUM_SINIESTRO    NUMBER(8),
  NUM_ABONADO      NUMBER(8),
  COD_PRODUCTO     NUMBER(1),
  COD_CAUSA        VARCHAR2(2),
  COD_ESTADO       VARCHAR2(2),
  NUM_TERMINAL     VARCHAR2(15),
  NUM_SERIE        VARCHAR2(25),
  FEC_SINIESTRO    DATE,
  COD_SERVICIO     VARCHAR2(3),
  COD_CARGOBASICO  VARCHAR2(3),
  FEC_FORMALIZA    DATE,
  FEC_ANULA        DATE,
  FEC_RESTITUC     DATE,
  NUM_CONSTPOL     VARCHAR2(20),
  NUM_SOLLIQ       VARCHAR2(15),
  NUM_SERIEREP     VARCHAR2(25),
  IND_SUSP         NUMBER(1),
  TIP_TERMINAL     VARCHAR2(1),
  CONSTRUCTOR FUNCTION GA_SINIESTROS_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY GA_SINIESTROS_QT IS

  CONSTRUCTOR FUNCTION GA_SINIESTROS_QT RETURN self AS result AS
  BEGIN
    NUM_SINIESTRO    := NULL;
    NUM_ABONADO      := NULL;
    COD_PRODUCTO     := NULL;
    COD_CAUSA        := NULL;
    COD_ESTADO       := NULL;
    NUM_TERMINAL     := NULL;
    NUM_SERIE        := NULL;
    FEC_SINIESTRO    := NULL;
    COD_SERVICIO     := NULL;
    COD_CARGOBASICO  := NULL;
    FEC_FORMALIZA    := NULL;
    FEC_ANULA        := NULL;
    FEC_RESTITUC     := NULL;
    NUM_CONSTPOL     := NULL;
    NUM_SOLLIQ       := NULL;
    NUM_SERIEREP     := NULL;
    IND_SUSP         := NULL;
    TIP_TERMINAL     := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
