CREATE OR REPLACE TYPE GE_CARTA_10034_QT AS OBJECT
( COD_OS VARCHAR2(5),
  TEX_CARTA VARCHAR2(2000),
  COD_PLAN_TARIF VARCHAR2(3),
  DES_PLAN_TARIF VARCHAR2(30),
  FEC_CICLO DATE,
  NUM_UNIDADES VARCHAR2(19),
  CONSTRUCTOR FUNCTION GE_CARTA_10034_QT RETURN self AS result
);
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY GE_CARTA_10034_QT IS
  CONSTRUCTOR FUNCTION GE_CARTA_10034_QT RETURN self AS result AS
  BEGIN
    COD_OS      := NULL;
    TEX_CARTA   := NULL;
    COD_PLAN_TARIF   := NULL;
    DES_PLAN_TARIF := NULL;
    FEC_CICLO := NULL;
    NUM_UNIDADES := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
