CREATE OR REPLACE TYPE GE_CLIENTES_OT AS OBJECT
(
  COD_CLIENTE             NUMBER  ( 8),
  NOM_CLIENTE             VARCHAR2(50),
  COD_TIPIDENT            VARCHAR2( 2),
  NUM_IDENT               VARCHAR2(20),
  COD_CALCLIEN            VARCHAR2( 2),
  IND_SITUACION           VARCHAR2( 2),
  FEC_ALTA                DATE        ,
  IND_FACTUR              NUMBER  ( 1),
  IND_TRASPASO            VARCHAR2( 1),
  IND_AGENTE              VARCHAR2( 1),
  FEC_ULTMOD              DATE        ,
  NUM_FAX                 VARCHAR2(15),
  IND_MANDATO             NUMBER  ( 1),
  NOM_USUARORA            VARCHAR2(30),
  IND_ALTA                VARCHAR2( 1),
  COD_CUENTA              NUMBER  ( 8),
  IND_ACEPVENT            VARCHAR2( 1),
  COD_ABC                 VARCHAR2( 1),
  COD_123                 NUMBER  ( 1),
  COD_ACTIVIDAD           NUMBER  ( 3),
  COD_PAIS                VARCHAR2( 3),
  TEF_CLIENTE1            VARCHAR2(15),
  NUM_ABOCEL              NUMBER  ( 7),
  TEF_CLIENTE2            VARCHAR2(15),
  NUM_ABOBEEP             NUMBER  ( 4),
  IND_DEBITO              VARCHAR2( 1),
  NUM_ABOTRUNK            NUMBER  ( 4),
  COD_PROSPECTO           NUMBER  ( 8),
  NUM_ABOTREK             NUMBER  ( 4),
  COD_SISPAGO             NUMBER  ( 2),
  NOM_APECLIEN1           VARCHAR2(20),
  NOM_EMAIL               VARCHAR2(255),
  NUM_ABORENT             NUMBER  ( 4),
  NOM_APECLIEN2           VARCHAR2(20),
  NUM_ABOROAMING          NUMBER  ( 4),
  FEC_ACEPVENT            DATE,
  IMP_STOPDEBIT           NUMBER(12,4),
  COD_BANCO               VARCHAR2(15),
  COD_SUCURSAL            VARCHAR2( 4),
  IND_TIPCUENTA           VARCHAR2( 1),
  COD_TIPTARJETA          VARCHAR2( 3),
  NUM_CTACORR             VARCHAR2(18),
  NUM_TARJETA             VARCHAR2(18),
  FEC_VENCITARJ           DATE,
  COD_BANCOTARJ           VARCHAR2(15),
  COD_TIPIDTRIB           VARCHAR2( 2),
  NUM_IDENTTRIB           VARCHAR2(20),
  COD_TIPIDENTAPOR        VARCHAR2( 2),
  NUM_IDENTAPOR           VARCHAR2(20),
  NOM_APODERADO           VARCHAR2(40),
  COD_OFICINA             VARCHAR2( 2),
  FEC_BAJA                DATE,
  COD_COBRADOR            NUMBER  ( 6),
  COD_PINCLI              VARCHAR2( 4),
  COD_CICLO               NUMBER  ( 2),
  NUM_CELULAR             NUMBER  (15),
  IND_TIPPERSONA          VARCHAR2( 1),
  COD_CICLONUE            NUMBER  ( 2),
  COD_CATEGORIA           NUMBER  ( 4),
  COD_SECTOR              NUMBER  ( 4),
  COD_SUPERVISOR          NUMBER  ( 6),
  IND_ESTCIVIL            CHAR    ( 1),
  FEC_NACIMIEN            DATE,
  IND_SEXO                CHAR    ( 1),
  NUM_INT_GRUP_FAM        NUMBER  ( 2),
  COD_NPI                 NUMBER  ( 2),
  COD_SUBCATEGORIA        VARCHAR2( 5),
  COD_USO                 VARCHAR2( 5),
  COD_IDIOMA              VARCHAR2( 5),
  COD_TIPIDENT2           VARCHAR2( 2),
  NUM_IDENT2              VARCHAR2(20),
  NOM_USUARIO_ASESOR      VARCHAR2(30),
  COD_OPERADORA           VARCHAR2( 5),
  IND_FACTURAELECTRONICA  NUMBER  ( 1),
  CONSTRUCTOR FUNCTION GE_CLIENTES_OT (self IN OUT NOCOPY GE_CLIENTES_OT) RETURN self AS result
)  NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY GE_CLIENTES_OT  IS
  CONSTRUCTOR FUNCTION GE_CLIENTES_OT (self IN OUT NOCOPY GE_CLIENTES_OT) RETURN self AS result AS
    BEGIN
        RETURN;
    END;
END;
/
SHOW ERRORS
