CREATE OR REPLACE TYPE GE_CARTA_10060_QT AS OBJECT
(
  COD_OS      VARCHAR2(5),
  TEX_CARTA   VARCHAR2(2000),
  NUM_CELULAR NUMBER(15),
  NUM_ABOANDO NUMBER(8),
  REFERENCIA  VARCHAR2(300),
  CONSTRUCTOR FUNCTION GE_CARTA_10060_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY GE_CARTA_10060_QT IS
  CONSTRUCTOR FUNCTION GE_CARTA_10060_QT RETURN self AS result AS
  BEGIN
    COD_OS      := NULL;
    TEX_CARTA   := NULL;
    REFERENCIA  := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
