CREATE OR REPLACE TYPE        GE_CARTA_40009_QT AS OBJECT
(
  COD_OS      VARCHAR2(5),
  TEX_CARTA   VARCHAR2(2000),
  NUM_OS_ANT  VARCHAR2(2000),
  CONSTRUCTOR FUNCTION GE_CARTA_40009_QT RETURN self AS result
);
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY        GE_CARTA_40009_QT IS

  CONSTRUCTOR FUNCTION GE_CARTA_40009_QT RETURN self AS result AS
  BEGIN
    COD_OS      := NULL;
    TEX_CARTA   := NULL;
    NUM_OS_ANT  := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
