CREATE OR REPLACE TYPE GE_DIRECCION_QT AS OBJECT
(
  COD_OFICINA 	  VARCHAR2(2),
  COD_REGION  	  VARCHAR2(3),
  COD_PROVINCIA   VARCHAR2(5),
  COD_CIUDAD	  VARCHAR2(5),
  COD_PLAZA		  VARCHAR2(5)
)
/
SHOW ERRORS
