CREATE OR REPLACE TYPE GE_MODVENTA_QT AS OBJECT
(
  COD_MODVENTA  NUMBER(2),
  DES_MODVENTA  VARCHAR2(40),
  IND_CUOTAS    NUMBER(1),
  IND_PAGADO    NUMBER(1),
  COD_CAUPAGO   NUMBER(2),
  IND_ABONO     NUMBER(1),
  CONSTRUCTOR FUNCTION GE_MODVENTA_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY GE_MODVENTA_QT IS

  CONSTRUCTOR FUNCTION GE_MODVENTA_QT RETURN self AS result AS
  BEGIN
    COD_MODVENTA := NULL;
    DES_MODVENTA := NULL;
    IND_CUOTAS   := NULL;
    IND_PAGADO   := NULL;
    COD_CAUPAGO  := NULL;
    IND_ABONO    := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
