CREATE OR REPLACE TYPE GE_OOSS_EN_LINEA_QT AS OBJECT
(
  COD_OS VARCHAR2(5),
  COD_PRODUCTO NUMBER(1),
  TIP_INTER NUMBER(2),
  COD_INTER NUMBER(10),
  USUARIO VARCHAR2(30),
  FECHA   VARCHAR2(30),
  COMENTARIO VARCHAR2(500),
  NUM_MOVIMIENTO NUMBER(9),
  COD_ESTADO NUMBER(1),
  COD_MODULO VARCHAR2(2),
  ID_GESTOR NUMBER(10),
  NUM_OS NUMBER(10)
)
/
SHOW ERRORS
