CREATE OR REPLACE TYPE GE_ORDEN_SERVICIO_QT AS OBJECT
(
  COD_OS VARCHAR2(5),
  DESCRIPCION VARCHAR2(50),
  COD_TIPMODI VARCHAR2(2),
  GRUPO VARCHAR2(1),
  NOM_EXE VARCHAR2(30),
  CARTA VARCHAR2(255),
  IND_PRORROGA NUMBER(1),
  MENU VARCHAR2(14),
  TIP_EXTENCION VARCHAR2(3),
  TIP_PROCESA NUMBER(2),
  COD_APLIC VARCHAR2(3),
  COD_MODGENER VARCHAR2(3),
  IND_CRON NUMBER(1),
  IND_ARCHIVO NUMBER(2),
  IND_ALGUNOS NUMBER(2),
  FEC_MIGRACION DATE,
  PRG VARCHAR2(60),
  IND_CSERVICIO VARCHAR2(60),
  IND_LOCK NUMBER(2),
  TIP_PROCESA_FAC NUMBER(8),
  COD_MENSAJE NUMBER(3),
  PRG_RUTA VARCHAR2(60),
  TIP_OOSS NUMBER(1),
  IND_ORSERV VARCHAR2(3)
)
/
SHOW ERRORS
