CREATE OR REPLACE TYPE GE_SESION_QT AS OBJECT
(

  COD_CLIENTE        NUMBER(8),
  NUM_ABONADO        NUMBER(8),
  COD_ORDENSERVICIO  NUMBER(10),
  NUM_ORDENSERVICIO  NUMBER(10),
  NOM_USUARIO        VARCHAR2(50),
  CLAVE              VARCHAR2(50),
  FORWARD            VARCHAR2(50),
  COD_PROGRAMA       VARCHAR2(10),
  NUM_VERSION        NUMBER(10),
  ORIGEN_SERIE	     VARCHAR2(1),	 --- RRG 08-03-2009 COL 78629
  CONSTRUCTOR FUNCTION GE_SESION_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY GE_SESION_QT IS

  CONSTRUCTOR FUNCTION GE_SESION_QT RETURN self AS result AS
  BEGIN
    COD_CLIENTE        := NULL;
    NUM_ABONADO        := NULL;
    COD_ORDENSERVICIO  := NULL;
    NUM_ORDENSERVICIO  := NULL;
    NOM_USUARIO        := NULL;
    CLAVE              := NULL;
    FORWARD            := NULL;
    COD_PROGRAMA       := NULL;
    NUM_VERSION        := NULL;
    ORIGEN_SERIE       := NULL;		--- RRG 08-03-2009 COL 78629
    RETURN;
  END;
END;
/
SHOW ERRORS
