CREATE OR REPLACE TYPE GE_SEG_USUARIO_QT AS OBJECT
(
  NOM_USUARIO        VARCHAR2(30),
  NOM_OPERADOR       VARCHAR2(40),
  IND_ADM            VARCHAR2(1),
  COD_OFICINA        VARCHAR2(2),
  COD_TIPCOMIS       VARCHAR2(2),
  COD_VENDEDOR       NUMBER(6),
  IND_EXCEP_ERIESGO  VARCHAR2(1),
  DES_OFICINA        VARCHAR2(40),
  COD_COMUNA         VARCHAR2(5),
  DES_COMUNA         VARCHAR2(30),
  GRUP_CALLCENTER    VARCHAR2(1),
  CONSTRUCTOR FUNCTION GE_SEG_USUARIO_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY GE_SEG_USUARIO_QT AS
  CONSTRUCTOR FUNCTION GE_SEG_USUARIO_QT RETURN self AS result AS
  BEGIN
    NOM_USUARIO       := NULL;
    NOM_OPERADOR      := NULL;
    IND_ADM           := NULL;
    COD_OFICINA       := NULL;
    COD_TIPCOMIS      := NULL;
    COD_VENDEDOR      := NULL;
    IND_EXCEP_ERIESGO := NULL;
    DES_OFICINA       := NULL;
    COD_COMUNA        := NULL;
    DES_COMUNA        := NULL;
    GRUP_CALLCENTER   := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
