CREATE OR REPLACE TYPE ICG_CENTRAL_QT AS OBJECT
(
  COD_CENTRAL      NUMBER(3),
  COD_PRODUCTO     NUMBER(1),
  NOM_CENTRAL      VARCHAR2(15),
  COD_NEMOTEC      VARCHAR2(15),
  COD_ALM          VARCHAR2(3),
  NUM_MAXINTENTOS  NUMBER(2),
  COD_SISTEMA      NUMBER(2),
  COD_COBERTURA    NUMBER(1),
  TIE_RESPUESTA    NUMBER(12,4),
  NODOCOM          VARCHAR2(20),
  COD_TECNOLOGIA   VARCHAR2(7),
  COD_HLR          VARCHAR2(10),
  CONSTRUCTOR FUNCTION ICG_CENTRAL_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY ICG_CENTRAL_QT IS

  CONSTRUCTOR FUNCTION ICG_CENTRAL_QT RETURN self AS result AS
  BEGIN
    COD_CENTRAL      := NULL;
    COD_PRODUCTO     := NULL;
    NOM_CENTRAL      := NULL;
    COD_NEMOTEC      := NULL;
    COD_ALM          := NULL;
    NUM_MAXINTENTOS  := NULL;
    COD_SISTEMA      := NULL;
    COD_COBERTURA    := NULL;
    TIE_RESPUESTA    := NULL;
    NODOCOM          := NULL;
    COD_TECNOLOGIA   := NULL;
    COD_HLR          := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
