CREATE OR REPLACE TYPE PV_ACT_PARAM_COMERCIAL_QT AS OBJECT
(
  NUM_ABONADO          NUMBER(8),
  COD_CLIENTE          NUMBER(8),
  COD_PLANTARIF        VARCHAR2(3),
  TIP_PLANTARIF        VARCHAR2(1),
  FEC_VENCIMIENTO      DATE,
  PERIODOFACT          NUMBER(7),
  COD_PLANTARIF_NUE    VARCHAR2(3),
  TIP_PLANTARIF_NUE    VARCHAR2(1),
  COD_LIMCONSUMO        VARCHAR2(5),
  COD_CARGOBASICO        VARCHAR2(3),
  IMP_CARGOBASICO        NUMBER(14,4),
  IND_EJECUCION        VARCHAR2(1),
  COD_ACTABO           VARCHAR2(2)
)
/
SHOW ERRORS