CREATE OR REPLACE TYPE PV_BUSQ_TIPO_DOC_QT AS OBJECT
(
  COD_CLIENTE   NUMBER(8),
  IND_AGENTE    VARCHAR(1),
  IND_SITUACION VARCHAR(2),
  COD_PRODUCTO  NUMBER(1),
  COD_AMICICLO  VARCHAR(20),
  COD_MODULO    VARCHAR(2)
)
/
SHOW ERRORS
