CREATE OR REPLACE TYPE PV_BOLSAS_DINAMICAS_QT AS OBJECT
(
SECUENCIA 		  NUMBER(9),
COD_CLIENTE 	  NUMBER(8),
COD_CICLO 		  NUMBER(2),
COD_PLANTARIF1 	  VARCHAR2(3),
COD_PLANTARIF2 	  VARCHAR2(3),
COD_PRODUCTO 	  NUMBER(1),
COD_CARGO 		  VARCHAR2(3),
IMP_CARGO 		  NUMBER(14,4),
IMP_MAXIMO 		  NUMBER(14,4),
FECHA 	   		  DATE
)
/
SHOW ERRORS
