CREATE OR REPLACE
TYPE PV_CAMCOM_OT AS OBJECT
(
  NUM_OS              NUMBER(10),
  NUM_ABONADO         NUMBER(8),
  NUM_CELULAR         NUMBER(15),
  COD_CLIENTE         NUMBER(8),
  COD_CUENTA          NUMBER(8),
  COD_PRODUCTO        NUMBER(1),
  BDATOS              VARCHAR2(15),
  NUM_VENTA           NUMBER(8),
  NUM_TRANSACCION     NUMBER(9),
  NUM_FOLIO           NUMBER(9),
  NUM_CUOTAS          NUMBER(2),
  NUM_PROCESO         NUMBER(8),
  COD_ACTABO          VARCHAR2(2),
  FH_ANULA            DATE,
  USER_ANULA          VARCHAR2(30),
  CAT_TRIBUT          VARCHAR2(1),
  COD_ESTADOC         NUMBER(3),
  COD_CAUSAELIM       VARCHAR2(5),
  FEC_VENCIMIENTO     DATE,
  ABONADOS            VARCHAR2(1024),
  TABLA               VARCHAR2(30),
  CLASE_SERVICIO_ACT  VARCHAR2(255),
  CLASE_SERVICIO_DES  VARCHAR2(255),
  IND_MSG             NUMBER(2),
  NUM_CARGO_OS        NUMBER(14,4),
  IMP_CARGO_SER       NUMBER(14,4),
  IND_CENTRAL_SS      NUMBER(1),
  IND_PORTABLE        NUMBER(1),
  TIP_TERMINAL        VARCHAR2(1),
  TIP_SUSP_AVSINIE    VARCHAR2(1),
  PREF_PLAZA          VARCHAR2(25),
  CONSTRUCTOR FUNCTION PV_CAMCOM_OT RETURN self AS result
)NOT FINAL
/
SHOW ERROR

CREATE OR REPLACE
TYPE BODY PV_CAMCOM_OT IS
  CONSTRUCTOR FUNCTION PV_CAMCOM_OT RETURN self AS result AS
  BEGIN
    RETURN;
  END;
END;
/
SHOW ERROR