CREATE OR REPLACE TYPE PV_CARGOS_QT AS OBJECT
(
  IDSECUENCIA NUMBER(9),
  CODCLIENTE NUMBER(8),
  CODCICLO NUMBER(2),
  CODPLANTARIF VARCHAR2(3),
  CODPLANTARIFDESTINO VARCHAR2(3),
  CODCARGOBASICO VARCHAR2(3),
  COD_CUOTA VARCHAR2(2),
  PERMISO VARCHAR2(255),
  DES_CUOTA VARCHAR2(30),
  VALOR_ORDENACION VARCHAR2(20),
  PROGRAMA VARCHAR2(180),
  CANAL_VENTA NUMBER,
  TIP_CONTRATO VARCHAR2(3),
  NUM_MESES NUMBER,
  COD_OPERACION VARCHAR2(5),
  IND_CAUSA NUMBER,
  COD_CAUSA VARCHAR2(2)
)
/
SHOW ERRORS
