CREATE OR REPLACE TYPE PV_CICLOS_FACTURACION_QT AS OBJECT
(
  IDSECUENCIA 	 NUMBER(9),
  IDOOSS      	 NUMBER(10),
  CODOOSS 	     VARCHAR2(5),
  FECHAEJECUCION VARCHAR2(100),
  CODCLIENTE 	 NUMBER(8),
  NUMABONADO 	 NUMBER(8)
)
/
SHOW ERRORS
