CREATE OR REPLACE TYPE PV_CARGO_EQUIPO_QT AS OBJECT
(
    IND_AUTO_MAN     VARCHAR(2),
    DES_ARTICULO     VARCHAR2(40),
    NUM_UNIDADES     VARCHAR(2),
    PRC_DEDUCIBLE    NUMBER(14,4),
    DES_MONEDA       VARCHAR2(20),
    COD_CONCEPTOART  NUMBER(4),
    COD_MONEDA       VARCHAR2(3),
    VAL_MINIMO       VARCHAR2(2),
    VAL_MAXIMO       VARCHAR2(2),
    IND_EQUIPO       NUMBER(2),
    IND_PAQUETE      NUMBER(2),
    MES_GARANTIA     NUMBER(2),
    IND_ACCESORIO    NUMBER(2),
    COD_ARTICULO     NUMBER(6),
    COD_STOCK        NUMBER(2),
    COD_ESTADO       NUMBER(2)      
);
/