CREATE OR REPLACE TYPE PV_CONS_PREPAGOS_QT AS OBJECT
(
NUM_CELULAR          NUMBER(15),
NUM_SERIE            VARCHAR2(25),
NUM_ABONADO   		 NUMBER(8),
COD_TECNOLOGIA       VARCHAR2(7),
COD_PLANTARIF_ACTUAL VARCHAR2(3),
COD_PLANTARIF 		 VARCHAR2(3),
COD_PLANSERV       	 VARCHAR2(3),
COD_ACTABO         	 VARCHAR2(2),
VN_SALDO			 NUMBER  (14,4),
IMP_TARIFA			 NUMBER  (14,4)
)
/
SHOW ERRORS
