CREATE OR REPLACE TYPE PV_COMBINATORIA_OS_QT AS OBJECT
(
  COD_OS VARCHAR2(5),
  NOM_COMBINATORIA VARCHAR2(50),
  FLG_ESTADO NUMBER(1),
  CONSTRUCTOR FUNCTION PV_COMBINATORIA_OS_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY PV_COMBINATORIA_OS_QT IS

  CONSTRUCTOR FUNCTION PV_COMBINATORIA_OS_QT RETURN self AS result AS
  BEGIN
  COD_OS := NULL;
  NOM_COMBINATORIA := NULL;
  FLG_ESTADO := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
