CREATE OR REPLACE TYPE PV_DETALLE_OS_QT AS OBJECT
 (NUM_PROCESO NUMBER(38),
  NUM_OS NUMBER(38),
  COD_ERROR NUMBER(6),
  DES_ERROR VARCHAR2(3000),
  ESTADO VARCHAR2(12),
  FEC_ESTADO DATE,
  NUM_EVENTO NUMBER(9),
  NUM_ABONADO NUMBER(38),
  COD_CLIENTE NUMBER(38),
  CONSTRUCTOR FUNCTION PV_DETALLE_OS_QT RETURN SELF AS RESULT
);
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY PV_DETALLE_OS_QT IS

  CONSTRUCTOR FUNCTION PV_DETALLE_OS_QT RETURN SELF AS RESULT AS
  BEGIN
 NUM_PROCESO  := NULL;
 NUM_OS   := NULL;
 COD_ERROR  := NULL;
 DES_ERROR  := NULL;
 ESTADO   := NULL;
 FEC_ESTADO  := NULL;
 NUM_EVENTO  := NULL;
 NUM_ABONADO  := NULL;
 COD_CLIENTE := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
