CREATE OR REPLACE TYPE PV_DET_SUSPVOLPROG_QT AS OBJECT
(
  NUM_DET_SUS_VOL_PRG  NUMBER(16),
  NUM_ABONADO          NUMBER(8),
  NUM_PERIODOSUSP_1    NUMBER(16),
  NUM_PERIODOSUSP_2    NUMBER(16),
  FEC_SOLICITUD        DATE,
  FEC_SUSPENSION       DATE,
  FEC_REHABILITACION   DATE,
  FEC_ACTUALIZACION    DATE,
  DIAS_PERIODOSUSP_1   NUMBER(4),
  DIAS_PERIODOSUSP_2   NUMBER(4),
  ESTADO               VARCHAR2(5 BYTE),
  COD_CAUSAL           VARCHAR2(200 BYTE),
  USUARIO              VARCHAR2(200 BYTE),
  NUM_OS_SUS           NUMBER(10),
  NUM_OS_REH           NUMBER(10),
  CONSTRUCTOR FUNCTION PV_DET_SUSPVOLPROG_QT RETURN self AS result
)NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY PV_DET_SUSPVOLPROG_QT IS
  CONSTRUCTOR FUNCTION PV_DET_SUSPVOLPROG_QT RETURN self AS result AS
  BEGIN
    RETURN;
  END;
END;
/
SHOW ERRORS
