CREATE OR REPLACE TYPE PV_FA_CICLFACT_QT AS OBJECT
(
COD_CICLO  	  		   		 	NUMBER   (02),
FECHA_CICLO_FEC_DESDELLAM	 	VARCHAR2 (20),
PERIODO_CICLO_COD_CICLFACT      NUMBER   (6),
NUM_ABONADO						NUMBER   (8)
)
/
SHOW ERRORS
