CREATE OR REPLACE TYPE PV_GESTOR_BCORP_QT AS OBJECT
(N_NUM_ABONADO    				NUMBER(8),
V_COD_ACTABO_GESTOR				VARCHAR2(30),
V_NOM_USUARORA  				VARCHAR2(30),
V_COD_PLANTARIF_ACTUA  			VARCHAR2(3),
V_COD_PLANTARIF_NUEVO			VARCHAR2(3),
V_TIP_MOVIMIENTO				VARCHAR2(2),
V_COD_ACTABO_OOSS		    	VARCHAR2(30),
V_ABONADO_GESTOR				VARCHAR2(09),
V_ABONADO_GESTOR_DEF			VARCHAR2(09),
N_SEQ_TRANS_ACABO				NUMBER(9)
)
/
SHOW ERRORS
