CREATE OR REPLACE TYPE PV_GA_INTARCEL_QT AS OBJECT
(
  NUM_ABONADO 	         NUMBER(8),
  COD_CLIENTE 			 NUMBER,
  FORMATO2 	  		     VARCHAR2(20),
  FORMATO4 				 VARCHAR2(20),
  FEC_DESDE 			 DATE,
  FEC_HASTA 	 		 DATE,
  COD_PRODUCTO           NUMBER(1),
  IND_NUMERO   			 NUMBER(1),
  CNT_GA_INTARCEL_ACC    NUMBER(12),
  NUM_CELULAR            NUMBER(15),
  COD_ACTABO			 VARCHAR2(2)
)
/
SHOW ERRORS
