CREATE OR REPLACE TYPE PV_GA_PARAMBAJAINDEMNIZ_QT AS OBJECT
(

	   COD_PRODUCTO 	NUMBER(1),
	   NUM_ABONADO		NUMBER(8),
	   FEC_ALTA	   		DATE,
	   FEC_PRORROGA	   	DATE,
	   COD_TIPCONTRATO	VARCHAR2(3),
	   NUM_MESES	   	NUMBER(2)


)
/
SHOW ERRORS
