CREATE OR REPLACE TYPE PV_GED_PARAMETROS_QT AS OBJECT
(NOM_PARAMETRO	VARCHAR2(20),
COD_MODULO		VARCHAR2(2),
COD_PRODUCTO	NUMBER(22),
VAL_PARAMETRO	VARCHAR2(20),
DES_PARAMETRO	VARCHAR2(50),
NOM_USUARIO		VARCHAR2(30),
FEC_ALTA		DATE,
VALOR_NUMERICO  NUMBER(20,6),
VALOR_TEXTO     VARCHAR2(250),
VALOR_FECHA		DATE,
VALOR_DOMINIO   VARCHAR2(50)
)
/
SHOW ERRORS
