CREATE OR REPLACE TYPE PV_GA_CARGOSBINDEMNIZ_QT AS OBJECT
(

	   COD_ACTABO 	   VARCHAR2(2),
	   COD_CONCEPTO	   NUMBER(4),
	   COD_MONEDA	   VARCHAR2(3),
	   COD_PRODUCTO	   NUMBER(1),
	   COD_TIPSERV	   VARCHAR2(1),
	   COD_SERVICIO	   VARCHAR2(3),
	   DES_MONEDA      VARCHAR2(20),
	   DES_SERVICIO	   VARCHAR2(40),
	   MESES_CONTRATO  NUMBER(2),
	   NUM_MESES	   NUMBER(2),
	   VALOR		   NUMBER(14,4)


)
/
SHOW ERRORS
