CREATE OR REPLACE TYPE PV_IORSERV_OT AS OBJECT
(
  NUM_OS         NUMBER(10),
  COD_OS         VARCHAR2(5),
  NUM_OSPADRE    NUMBER(10),
  DESCRIPCION    VARCHAR2(50),
  FECHA_ING      DATE,
  PRODUCTO       NUMBER(1),
  USUARIO        VARCHAR2(30),
  STATUS         VARCHAR2(30),
  TIP_PROCESA    NUMBER(1),
  FH_EJECUCION   DATE,
  COD_ESTADO     NUMBER(3),
  COD_MODGENER   VARCHAR2(3),
  NUM_OSF        NUMBER(7),
  TIP_SUBSUJETO  VARCHAR2(2),
  NFILE          VARCHAR2(30),
  PATH_FILE      VARCHAR2(30),
  TIP_SUJETO     VARCHAR2(2),
  IND_LOCK       NUMBER(2),
  PRIORIDAD      NUMBER(2),
  NUM_OSF_ERR    NUMBER(7),
  COMENTARIO     VARCHAR2(500),
  FH_RECOLECTOR  DATE,
  FH_RESPALDO    DATE,
  COD_MODULO     VARCHAR2(2),
  ID_GESTOR      NUMBER(10),
  NUM_INTENTOS   NUMBER(3),
  NUM_OSFTOTAL   NUMBER(10),
  CONSTRUCTOR FUNCTION PV_IORSERV_OT RETURN self AS result
)NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY PV_IORSERV_OT IS
  CONSTRUCTOR FUNCTION PV_IORSERV_OT RETURN self AS result AS
  BEGIN
    RETURN;
  END;
END;
/
SHOW ERRORS
