CREATE OR REPLACE TYPE PV_IORSERV_QT AS OBJECT
(
NUM_OS           NUMBER(10),
COD_OS           VARCHAR2(5),
MAX_INTENTOS	 NUMBER(3),
COMENTARIO  	 VARCHAR2(500),
NUM_OS_ORIGEN	 NUMBER(10),
COD_CLIENTE 	  	   		NUMBER(8),
NUM_ABONADO 	  			NUMBER(8),
COD_PLANTARIF 	  			VARCHAR2(3),
COD_PLANTARIF_NUEVO			VARCHAR2(3),
CODIGO			 VARCHAR2(1),
MENSAJE			 VARCHAR2(100)
)
/
SHOW ERRORS
