CREATE OR REPLACE TYPE PV_ORDEN_SERVICIO_QT AS OBJECT

--PV_ORDEN_SERVICIO_QT v1.0 //CREACION PROYECTO CPU
--PV_ORDEN_SERVICIO_QT v1.1 //COL-74626|17-12-2008|GEZ
(
  CODACT_AL VARCHAR2(255),
  CODACT_BA VARCHAR2(255),
  TIP_ESTADO NUMBER(1),
  IDSECUENCIA NUMBER(10),
  USUARIO VARCHAR2(30),
  COD_OS VARCHAR2(5),
  NUM_ABONADO NUMBER(8),
  PERIODOFACT NUMBER(7),
  COD_PLANTARIF VARCHAR2(3),
  FEC_VENCIMIENTO DATE,
  COD_ACTABO VARCHAR2(2),
  NUM_OSF NUMBER(10),
  DESCRIPCION VARCHAR2(50),
  TIP_PROCESA NUMBER(2),
  COD_MODGENER VARCHAR2(3),
  DES_ESTADOC VARCHAR2(30),
  NUM_CELULAR NUMBER(15),
  COD_CLIENTE NUMBER(8),
  COD_CUENTA NUMBER(8),
  COD_PRODUCTO NUMBER(1),
  TIP_TERMINAL VARCHAR2(1),
  TIP_PLANTARIF VARCHAR2(1),
  COD_SERVICIO VARCHAR2(255),
  COD_ESTADO NUMBER(3),
  COD_OSANT	 VARCHAR2(5),
  COMBINATORIA VARCHAR2(20),
  EVENTO VARCHAR2(10),
  COD_PLANTARIF_NUE VARCHAR2(3),--OCB
  TIP_PLANTARIF_NUE VARCHAR2(1),--OCB
  COD_CLIENTE_NUE NUMBER(8),    --OCB
  COD_CUENTA_NUE NUMBER(8),     --OCB
  --NUM_MOVIMIENTO NUMBER(8),	    --OCB	--COL-74626|17-12-2008|GEZ
  NUM_MOVIMIENTO NUMBER(9),	    		--COL-74626|17-12-2008|GEZ
  COD_CAUSA_EXC	 NUMBER(3),
  ABONADO_NUEVO NUMBER(8),
  TIP_SUJETO VARCHAR2(2),
  COD_CAUSA	 VARCHAR2(2),
  IND_PORTABLE NUMBER(1),
  NUM_DIA            NUMBER(3),
  COD_VENDEDOR       NUMBER(6),
  PARAM1_MENS        VARCHAR2(255),
  NUM_CELU_PERS      VARCHAR2(15), --OCB
  COD_GRPSERV		 VARCHAR2(2),   --EV
  COMENTARIO		 VARCHAR2(500)
)
/
SHOW ERRORS
