CREATE OR REPLACE TYPE PV_ORDEN_DE_SERVICIO_QT AS OBJECT
 (NUM_PROCESO       NUMBER(38),
  COD_OS      VARCHAR2(5),
  ESTADO      VARCHAR2(12),
  FEC_ACTUALIZACION DATE,
  CONSTRUCTOR FUNCTION PV_ORDEN_DE_SERVICIO_QT RETURN SELF AS RESULT
);
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY PV_ORDEN_DE_SERVICIO_QT IS

  CONSTRUCTOR FUNCTION PV_ORDEN_DE_SERVICIO_QT RETURN SELF AS RESULT AS
  BEGIN
    NUM_PROCESO       := NULL;
    COD_OS            := NULL;
    ESTADO            := NULL;
    FEC_ACTUALIZACION := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
