CREATE OR REPLACE TYPE PV_PLANTARIF_QT AS OBJECT
(
  COD_PLANTARIF   	   VARCHAR2(3),
  DES_PLANTARIF  	   VARCHAR2(30),
  COD_LIMCONSUMO 	   VARCHAR2(2),
  DES_LIMCONSUMO 	   VARCHAR2(30),
  COD_CARGOBASICO 	   VARCHAR2(3),
  DES_CARGOBASICO 	   VARCHAR2(30),
  IMP_CARGOBASICO 	   NUMBER(12,4),
  NUM_DIAS 		  	   NUMBER(3),
  TIP_PLANTARIF   	   VARCHAR2(1),
  IMP_LIMCONSUMO  	   NUMBER(14,4),
  COD_TIPLAN	  	   VARCHAR2(5),
  CANTIDAD_ABONADOS	   NUMBER(5),
  COD_CLIENTE 		   NUMBER(8),
  NUM_FRECFIJOS		   NUMBER(5),
  NUM_FRECMOVIL		   NUMBER(5),
  IND_FF			   NUMBER(2),
  NUM_FRECING		   NUMBER(6)

)
/
SHOW ERRORS
