CREATE OR REPLACE TYPE PV_PARAM_ABOCEL_QT AS OBJECT
(
  NUM_OS             NUMBER(10),
  NUM_ABONADO        NUMBER(8),
  COD_TIPMODI        VARCHAR2(2),
  FEC_MODIFICA       DATE,
  NUOM_USUARORA      VARCHAR2(30),
  NUM_CELULAR        NUMBER(15),
  COD_USO            VARCHAR2(2),
  TIP_PLANTARIF      VARCHAR2(1),
  TIP_TERMINAL       VARCHAR2(1),
  COD_PLANTARIF      VARCHAR2(3),
  COD_CARGOBASICO    VARCHAR2(3),
  COD_PLANSERV       VARCHAR2(3),
  COD_LIMCONSUMO     VARCHAR2(3),
  NUM_SERIE          VARCHAR2(25),
  NUM_SERIEHEX       VARCHAR2(8),
  COD_EMPRESA        NUMBER(8),
  COD_GRPSERV        VARCHAR2(2),
  COD_CARRIER        NUMBER(5),
  COD_CICLO          NUMBER(2),
  IND_FACTUR         NUMBER(1),
  COD_CAUSA          VARCHAR2(3),
  NUM_MIN            VARCHAR2(3),
  COD_TIPCONTRATO    VARCHAR2(3),
  NUM_MESES          NUMBER(2),
  IND_EQPRESTADO     VARCHAR2(1),
  FEC_PRORROGA       DATE,
  NUM_CICLOS         NUMBER(10),
  NUM_MINUTOS        NUMBER(10),
  FEC_FINCONTRATO    DATE,
  COD_SERVICIO       VARCHAR2(3),
  OBS_DETALLE        VARCHAR2(255),
  COD_TIPSEGU        NUMBER(2),
  NUM_CONTRATO       VARCHAR2(21),
  NUM_ANEXO          VARCHAR2(21),
  COD_PRODUCTO       NUMBER(1),
  COD_PLANTARIF_NUE  VARCHAR2(3),
  TIP_PLANTARIF_NUE  VARCHAR2(1),
  NUM_DIA            NUMBER(3),
  COD_VENDEDOR       NUMBER(6),
  PARAM1_MENS        VARCHAR2(255),
  CONSTRUCTOR FUNCTION PV_PARAM_ABOCEL_QT RETURN self AS result
)NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY PV_PARAM_ABOCEL_QT IS
  CONSTRUCTOR FUNCTION PV_PARAM_ABOCEL_QT RETURN self AS result AS
  BEGIN
    RETURN;
  END;
END;
/
SHOW ERRORS
