CREATE OR REPLACE TYPE        PV_REGIST_NIVEL_MODIF_QT AS OBJECT
(
  NUM_ABONADO NUMBER(8),
  TIP_SUBJETO VARCHAR2(1),
  COD_TIPMODI VARCHAR2(2),
  FEC_MODIFICA VARCHAR2(30),
  NOM_USUARORA VARCHAR2(30),
  COD_CLIENTE NUMBER(8),
  NOM_CLIENTE VARCHAR2(50),
  NOM_APECLIEN1 VARCHAR2(20),
  NOM_APECLIEN2 VARCHAR2(20),
  COD_PLANTARIF_ANTIGUO VARCHAR2(3),
  COD_PLANTARIF_DESTINO VARCHAR2(3),
  COD_LIMCONSUMO_ANTIGUO VARCHAR2(5),
  COD_LIMCONSUMO_DESTINO VARCHAR2(5),
  COD_CARGOBASICO_ANTIGUO VARCHAR2(3),
  COD_CARGOBASICO_DESTINO VARCHAR2(3),
  COD_CICLO_ANTIGUO NUMBER(2),
  COD_CICLO_DESTINO NUMBER(2),
  COD_PLANSERV_ANTIGUO VARCHAR2(3),
  COD_PLANSERV_DESTINO VARCHAR2(3)
)
/
SHOW ERRORS
