CREATE OR REPLACE TYPE PV_REG_REORD_PLAN_QT AS OBJECT
(
COD_CLIENTE_ORI				NUMBER   (08),
COD_CLIENTE_DES				NUMBER   (08),
COD_CUENTA_ORI				NUMBER   (08),
COD_CUENTA_DES				NUMBER   (08),
NUM_ABONADO					NUMBER   (08),
COD_SUBCUENTA_ORI			VARCHAR2 (15),
COD_SUBCUENTA_DES			VARCHAR2 (15),
COD_PLANTARIF_NUEVO			VARCHAR2 (03),
COD_PRODUCTO				NUMBER   (01),
ID_USER						VARCHAR2 (30),
COD_ACTABO					VARCHAR2 (02),
COD_TIPO_CONTRATO			VARCHAR2 (03),
TIPO_TRASPASO				VARCHAR2 (03),
NUM_CONTRATO				VARCHAR2 (21),
NUM_ANEXO					VARCHAR2 (21),
COD_USUARIO_DES				NUMBER   (08),
COD_USUARIO_ORI				NUMBER   (08),
TIP_MOVIMIENTO				VARCHAR2 (2),
NUM_CELULAR					VARCHAR  (15),
COD_EMPRESA_ORI 			NUMBER   (8),
COD_EMPRESA_DES 			NUMBER   (8)
)
/
SHOW ERRORS
