CREATE OR REPLACE TYPE PV_RESTRICCIONES_QT AS OBJECT
(
  COD_MODULO       VARCHAR2(2),
  COD_PRODUCTO     NUMBER(1),
  NUM_RESTRICCION  NUMBER(5),
  TIP_RUTINA       VARCHAR2(5),
  NOM_RUTINA       VARCHAR2(50),
  DES_RUTINA       VARCHAR2(100),
  PARAM_RESTRIC    VARCHAR2(100),
  FEC_ULTMOD       DATE,
  NOM_USUARIO      VARCHAR2(30),
  COD_ACTUACION    VARCHAR2(10),
  COD_EVENTO       VARCHAR2(10),
  PARAMETROS       VARCHAR2(4000),
  CONSTRUCTOR FUNCTION PV_RESTRICCIONES_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY PV_RESTRICCIONES_QT IS

  CONSTRUCTOR FUNCTION PV_RESTRICCIONES_QT RETURN self AS result AS
  BEGIN
    COD_MODULO       := NULL;
    COD_PRODUCTO     := NULL;
    NUM_RESTRICCION  := NULL;
    TIP_RUTINA       := NULL;
    NOM_RUTINA       := NULL;
    DES_RUTINA       := NULL;
    PARAM_RESTRIC    := NULL;
    FEC_ULTMOD       := NULL;
    NOM_USUARIO      := NULL;
	COD_ACTUACION    := NULL;
	COD_EVENTO       := NULL;
	PARAMETROS       := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
