CREATE OR REPLACE TYPE PV_SOLICITUD_QT AS OBJECT
(
  NUM_VENTA	  NUMBER(8),
  LIN_AUTORIZA	  NUMBER(4),
  COD_OFICINA  VARCHAR2(2),
  COD_ESTADO	  VARCHAR2(3),
  NUM_AUTORIZACION  NUMBER(8),
  COD_VENDEDOR	   NUMBER(6),
  NUM_UNIDADES	   NUMBER(6),
  PRECIO_ORIGEN		   NUMBER(14,4),
  IND_TIPO_VENTA NUMBER(1),
  COD_CLIENTE	   NUMBER(8),
  COD_MOD_VENTA NUMBER(2),
  NOM_USUARIO_VENTA	 VARCHAR2(30),
  COD_CONCEPTO	 NUMBER(4),
  IMP_CARGO		 NUMBER(14,4),
  COD_MONEDA	 VARCHAR2(3),
  NUM_ABONADO	 NUMBER(8),
  NUM_SERIE		 VARCHAR2(25),
  COD_CONCEPTO_DESC	 NUMBER(4),
  VAL_DESCUENTO		 NUMBER(12,4),
  TIP_DESCUENTO		 NUMBER(1),
  IND_MODIFICACION	 NUMBER(1),
  COD_ORIGEN		 VARCHAR2(2)
)
/
SHOW ERRORS
