CREATE OR REPLACE TYPE PV_SUSPVOLPROG_QT AS OBJECT
(
  NUM_PERIODOSUSP  NUMBER(16),
  NUM_ABONADO      NUMBER(8),
  COD_CLIENTE      NUMBER(8),
  FEC_INICIO       DATE,
  FEC_FIN          DATE,
  DIAS_ACUM        NUMBER(4),
  CONSTRUCTOR FUNCTION PV_SUSPVOLPROG_QT RETURN self AS result
)NOT FINAL
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY PV_SUSPVOLPROG_QT IS
  CONSTRUCTOR FUNCTION PV_SUSPVOLPROG_QT RETURN self AS result AS
  BEGIN
    RETURN;
  END;
END;
/
SHOW ERRORS
