CREATE OR REPLACE TYPE PV_SERVDEFAULT_PLAN_QT AS OBJECT
(
COD_CENTRAL	  		 NUMBER  (03),
COD_PRODUCTO		 NUMBER  (01),
TIP_TERMINAL		 VARCHAR2(01),
TIP_TECNOLOGIA		 VARCHAR2(07),
COD_PLANTARIF_ACTUA	 VARCHAR2(03),
COD_PLANTARIF_NUEVO	 VARCHAR2(03),
NUM_ABONADO	  		 NUMBER  (08),
COD_ACTABO   		 VARCHAR2(2)
)
/
SHOW ERRORS
