CREATE OR REPLACE TYPE PV_TRASPASO_PLAN_QT AS OBJECT
(
 	NUM_TRANSACCION	   	   NUMBER(9),
	NUM_ABONADO 		   NUMBER(8),
	COD_CLIENUE	 		   NUMBER(8),
	COD_CUENTANUE		   NUMBER(8),
	COD_SUBCTANUE		   VARCHAR2(15),
	COD_USUARNUE    	   NUMBER(8),
	COD_PRODUCTO		   NUMBER(1),
	NUM_TERMINAL		   VARCHAR2(15),
	NUM_ABONADOANT		   NUMBER(8),
	COD_CLIENANT		   NUMBER(8),
	COD_CUENTAANT		   NUMBER(8),
	COD_SUBCTAANT		   VARCHAR2(15),
	COD_USUARANT		   NUMBER(8),
	IND_TRASDEUDA		   VARCHAR2(3),
	NOM_USUARORA		   VARCHAR2(30),
	IND_TRASPASO		   VARCHAR2(3),
	COD_PLANTARIF_ORIG	   VARCHAR2(3),
	COD_PLANTARIF_DEST	   VARCHAR2(3),
	COD_VENDEDOR		   NUMBER(6)
)
/
SHOW ERRORS
