CREATE OR REPLACE TYPE PV_VALIDAOoSS_PENDPLAN_QT AS OBJECT
(
COD_ESTADO     	  		NUMBER(3),
NUM_INTENTOS   			NUMBER(3),
COD_MODULO     			VARCHAR2(2),
COD_OS         	   		VARCHAR2(5),
NUM_ABONADO    			NUMBER(8),
NUM_OS         			NUMBER(10),
FECHA_EJECUCION			VARCHAR2(25),
COD_CLIENTE 	  	   		NUMBER(8),
COD_PLANTARIF 	  			VARCHAR2(3),
COD_PLANTARIF_NUEVO			VARCHAR2(3),
CODIGO					VARCHAR2(1),
MENSAJE					VARCHAR2(100),
COD_CLIENTE_DEST   		NUMBER(8)
)
/
SHOW ERRORS
