CREATE OR REPLACE TYPE PV_VAL_FREEDOM_QT AS OBJECT
(
  PARAM_PROPOR_VTA VARCHAR2(5),
  NUM_VENTA NUMBER(8),
  PARAM_PROPOR1 NUMBER(1),
  PARAM_PROPOR2 NUMBER(1),
  RESULTADO VARCHAR(5)
)
/
SHOW ERRORS
