CREATE OR REPLACE TYPE PV_VALIDA_PERM_QT AS OBJECT
(
	NUM_ABONADO          NUMBER (8),
	TIEMPO_MIN      	 NUMBER (5),
	COD_CAUSA_BAJA  	 VARCHAR2(2),
	COD_CAUSA_BAJA_PARAM VARCHAR2(2)
)
/
SHOW ERRORS
