CREATE OR REPLACE TYPE TA_PLANTARIF_QT AS OBJECT
(
   COD_CARGOBASICO  VARCHAR2(3)
 , DES_CARGOBASICO  VARCHAR2(40)
 , FEC_DESDE        DATE
 , FEC_HASTA        DATE
 , IMP_CARGOBASICO  NUMBER(12,4)
 , COD_MONEDA       VARCHAR2(3)
 , DES_MONEDA       VARCHAR2(20)
 , COD_PLANTARIF    VARCHAR2(3)
 , COD_PRODUCTO     NUMBER(1)
 )
/
SHOW ERRORS
