CREATE OR REPLACE TYPE VE_CATPLANTARIF_QT AS OBJECT
(
  COD_CATEGORIA       VARCHAR2(3),
  COD_PRODUCTO        NUMBER(1),
  COD_PLANTARIF       VARCHAR2(3),
  NOM_USUARIO         VARCHAR2(30),
  FEC_EFECTIVIDAD     DATE,
  FEC_FINEFECTIVIDAD  DATE,
  CONSTRUCTOR FUNCTION VE_CATPLANTARIF_QT RETURN self AS result
)
/
SHOW ERRORS
CREATE OR REPLACE TYPE BODY VE_CATPLANTARIF_QT IS

  CONSTRUCTOR FUNCTION VE_CATPLANTARIF_QT RETURN self AS result AS
  BEGIN
  COD_CATEGORIA := NULL;
  COD_PRODUCTO := NULL;
  COD_PLANTARIF := NULL;
  NOM_USUARIO := NULL;
  FEC_EFECTIVIDAD := NULL;
  FEC_FINEFECTIVIDAD := NULL;
    RETURN;
  END;
END;
/
SHOW ERRORS
