/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.pv.customerorder.negocio.ejb.session;

/**
 * Remote interface for CustomerOrderFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface CustomerOrderFacadeSTL
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.pv.customerorder.commonapp.dto.ProductListDTO getInstalledCustomerAccountProductBundle( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.CustomerAccountDTO cust )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.CustomerOrderException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void setInstalledCustomerAccountProductBundle( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.ProductListDTO prodList )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.CustomerOrderException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.pv.customerorder.commonapp.dto.ProductListDTO getUnInstalledCustomerAccountProductBundle( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.CustomerAccountDTO cust )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.CustomerOrderException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.pv.customerorder.commonapp.dto.ReglasSSDTO[] getReglasdeValidacionSS(  )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.CustomerOrderException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.pv.customerorder.commonapp.dto.CustomerAccountDTO getCustomerAccountData( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.CustomerAccountDTO cust )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.CustomerOrderException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.pv.customerorder.commonapp.dto.SecurityDTO getSecurityData( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.SecurityDTO seg )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.CustomerOrderException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void setCustomerAccountProductBundle( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.ProductListDTO prodList )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.CustomerOrderException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void saveCustomerOrderProduct( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.OrdenServicioDTO oS )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.CustomerOrderException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.pv.customerorder.commonapp.dto.CustomerAccountDTO getInvolvementProductBundletData( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.AbonadoDTO abo )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.CustomerOrderException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.pv.customerorder.commonapp.dto.ProductListDTO getInstalledInvolvementProductBundle( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.AbonadoDTO abo )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.CustomerOrderException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void setInvolvementProductBundleAttributes( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.ProductListDTO prodList )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.CustomerOrderException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.pv.customerorder.commonapp.dto.BolsaAbonadoDTO[] getFreeUnitStock( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.CustomerAccountDTO dto )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.TOLException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.pv.customerorder.commonapp.dto.CustomerAccountDTO getFreeUnitBagId( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.CustomerAccountDTO dto )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.TOLException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void setFreeUnitStock( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.DistribucionBolsaDTO dto )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.TOLException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void setFreeUnitStockPlanTarifOOSS( com.tmmas.cl.scl.pv.customerorder.commonapp.dto.PlanTarifarioDistDTO[] planTarifarioArr,java.lang.String comentario )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.TOLException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.pv.customerorder.commonapp.dto.PlanTarifarioDTO[] obtenerPlanesDistribuidos( java.lang.Long codigoCliente )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.ProductDomainException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.pv.customerorder.commonapp.dto.DistribucionBolsaDTO obtenerDatosBolsa( java.lang.String codPlanTarif )
      throws com.tmmas.cl.scl.pv.customerorder.commonapp.exception.ProductDomainException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void setSessionContext( javax.ejb.SessionContext arg0 )
      throws java.rmi.RemoteException;

}
