/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.pv.customerorder.negocio.ejb.session;

/**
 * Local interface for CustomerOrderFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface CustomerOrderFacadeSTLLocal
   extends javax.ejb.EJBLocalObject
{

}
