/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.o.csr.manprooffinv.bean.ejb.session;

/**
 * Remote interface for ManProOffInvFacade.
 * @generated 
 * @wtp generated
 */
public interface ManProOffInvFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PlanTarifarioListDTO obtenerPlanesTarifarios( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.BusquedaPlanTarifarioDTO param )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PlanTarifarioDTO obtenerTipoCobroPlanTarifario( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PlanTarifarioDTO plan )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ProductoOfertadoListDTO obtenerDetalleProductos( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ProductoOfertadoListDTO param )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ProductoOfertadoListDTO obtenerProductosOfertables( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO param )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.serviceDomain.serviceSpecEntitiesABE.businessObject.dataTransferObject.ReglasListaNumerosListDTO obtenerRestriccionesLista( com.tmmas.scl.framework.serviceDomain.serviceSpecEntitiesABE.businessObject.dataTransferObject.EspecServicioListaDTO param )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ProductoOfertadoListDTO obtenerProductosPorDefecto( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ProductoOfertadoListDTO obtenerProductosOfertablesPorPaquete( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PaqueteDTO paquete )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ProductoOfertadoListDTO obtenerProductosOfertablesPaquetePorDefecto( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PaqueteDTO paquete )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PlanTarifarioDTO obtenerDetallePlanTarif( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PlanTarifarioDTO planTarif )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ProductoOfertadoListDTO obtenerProductosOfertablesporCanal( com.tmmas.scl.framework.productDomain.productABE.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ProductoOfertadoListDTO obtenerLCplanAdicional( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ProductoOfertadoListDTO productoOfertadoLista )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productSpecificationABE.dataTransferObject.LimiteConsumoProductoListDTO consultaAboLc( com.tmmas.scl.framework.productDomain.productSpecificationABE.dataTransferObject.LimiteConsumoProductoDTO limiteConsumoProducto )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productSpecificationABE.dataTransferObject.TipoComportamientoListDTO obtenerTiposComportamiento(  )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ProductoScoringListDTO obtenerProductosScoring( java.lang.Long numAbonado )
      throws com.tmmas.scl.operations.crm.o.csr.manprooffinv.common.exception.ManProOffInvException, java.rmi.RemoteException;

}
