/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.o.csr.manprooffinv.bean.ejb.session;

/**
 * Home interface for ManProOffInvFacade.
 * @generated 
 * @wtp generated
 */
public interface ManProOffInvFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ManProOffInvFacade";
   public static final String JNDI_NAME="ManProOffInvFacade";

   public com.tmmas.scl.operations.crm.o.csr.manprooffinv.bean.ejb.session.ManProOffInvFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
