/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.o.csr.manprooffinv.bean.ejb.session;

/**
 * Local interface for ManProOffInvFacade.
 * @generated 
 * @wtp generated
 */
public interface ManProOffInvFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
