/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.avisinie.bean.ejb.session;

/**
 * Home interface for AvisoDeSiniestroFacade.
 * @generated 
 * @wtp generated
 */
public interface AvisoDeSiniestroFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AvisoDeSiniestroFacade";
   public static final String JNDI_NAME="AvisoDeSiniestroFacade";

   public com.tmmas.scl.operation.crm.fab.cusintman.avisinie.bean.ejb.session.AvisoDeSiniestroFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
