/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.avisinie.bean.ejb.session;

/**
 * Local home interface for AvisoDeSiniestroFacade.
 * @generated 
 * @wtp generated
 */
public interface AvisoDeSiniestroFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AvisoDeSiniestroFacadeLocal";
   public static final String JNDI_NAME="AvisoDeSiniestroFacadeLocal";

   public com.tmmas.scl.operation.crm.fab.cusintman.avisinie.bean.ejb.session.AvisoDeSiniestroFacadeLocal create()
      throws javax.ejb.CreateException;

}
