/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.avisinie.bean.ejb.session;

/**
 * Remote interface for AvisoDeSiniestroFacade.
 * @generated 
 * @wtp generated
 */
public interface AvisoDeSiniestroFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO obtenerDatosCliente( com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.AbonadoDTO obtenerDatosAbonado( com.tmmas.scl.framework.productDomain.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO obtenerDatosUsuarioAbonado( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.BodegaDTO[] obtenerBodegas( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sesion )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.TipoDeContratoDTO[] obtenerTiposDeContrato( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sessionDTO )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.MesesProrrogasDTO[] obtenerMesesProrroga(  )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO[] obtenerModalidadPago( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO Sesion,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO CausaCamSerie )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO[] obtenerModalidadPagoSimcard( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO Sesion,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO CausaCamSerie )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.TipoTerminalDTO[] obtenerTipoTerminal( com.tmmas.scl.framework.ProductDomain.dto.TecnologiaDTO tecnologia )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.CuotaDTO[] obtenerCuotas( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sesion,com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO modalidadPago )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.CentralDTO[] obtenerCentralTecnologiaHlr( com.tmmas.scl.framework.ProductDomain.dto.SerieDTO serie,com.tmmas.scl.framework.ProductDomain.dto.TecnologiaDTO tecnologia )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void validaCausaCamSerie( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sesion,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO causaCamSerie )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.MensajeRetornoDTO ejecutaRestrccion( com.tmmas.scl.framework.ProductDomain.dto.RestriccionesDTO restricciones )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO obtenerInformacionUsuario( com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO usuarioSistema )
      throws com.tmmas.scl.framework.aplicationDomain.exception.AplicationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void reservaSimcard( java.lang.String accionProceso,com.tmmas.scl.framework.ProductDomain.dto.SerieDTO serie,com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO usuarioSistema,com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado,java.lang.String parametros,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO causa,com.tmmas.scl.framework.ProductDomain.dto.TipoTerminalDTO terminal,com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO modalidadPago )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, com.tmmas.scl.framework.customerDomain.exception.CustomerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.CausaSiniestroDTO[] obtenerCausasSiniestro( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado,java.lang.String actAbo )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.TipoSiniestroDTO[] obtenerTiposDeSiniestros( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.TipoSuspencionDTO[] obtenerTiposDeSuspencion(  )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SolicitudAvisoDeSiniestroDTO grabaAvisoDeSiniestro( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado,com.tmmas.scl.framework.ProductDomain.dto.TipoSiniestroDTO tipoSiniestro,com.tmmas.scl.framework.ProductDomain.dto.TipoSuspencionDTO tipoSuspencion,com.tmmas.scl.framework.ProductDomain.dto.CausaSiniestroDTO causaSiniestro,com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO usuarioSistema,java.lang.String actabo,java.lang.String num_os,java.lang.String comentario,java.lang.String numeroDesvio )
   throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void registrarOOSSAvisoSiniestro( com.tmmas.scl.operation.crm.fab.cusintman.avisinie.common.dataTransfertObject.RegistraAvisoDeSiniestroActionDTO regAviSinActDTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO aceptarPresupuesto( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PresupuestoDTO presup )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ResultadoRegCargosDTO parametrosRegistrarCargos( com.tmmas.scl.framework.productDomain.dataTransferObject.RegCargosDTO cargos )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.CambioPlanPendienteDTO validarCambioPlanPendiente( com.tmmas.scl.framework.ProductDomain.dto.CambioPlanPendienteDTO cambioPlan )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.OperadoraLocalDTO obtenerOperadoraLocal(  )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;
   
 //Inicio Inc. 174755/CSR-11002/06-09-2011/FDL
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public String verificaNumeroDesviado(String numeroDesviado)
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;
 //Fin Inc. 174755/CSR-11002/06-09-2011/FDL

}
