/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.avisinie.bean.ejb.session;

/**
 * Local interface for AvisoDeSiniestroFacade.
 * @generated 
 * @wtp generated
 */
public interface AvisoDeSiniestroFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
