CREATE OR REPLACE PACKAGE Ra_Extrae_Auditoria_Pg
AS


FUNCTION RA_CAMPOS_PK_FN (EV_pk IN VARCHAR2,EN_Campo NUMBER) RETURN VARCHAR2;

FUNCTION RA_CAMPOS_FN (EV_valor_ant IN VARCHAR2,EV_valor_nue IN VARCHAR2,EN_Campo NUMBER, EN_sep VARCHAR2 DEFAULT null) RETURN VARCHAR2;

PROCEDURE RA_EXTRAE_CO_INTERESES_PR;

PROCEDURE RA_EXTRAE_CO_CATEGORIAS_PR;

PROCEDURE RA_EXTRAE_GE_IMPUESTOS_PR;

PROCEDURE RA_EXTRAE_AUDITORIA_PR;

END RA_EXTRAE_AUDITORIA_PG;
/
SHOW ERRORS