/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.oh.comord.bean.ejb.session;

/**
 * Local home interface for ComOrdFacade.
 * @generated 
 * @wtp generated
 */
public interface ComOrdFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ComOrdFacadeLocal";
   public static final String JNDI_NAME="ComOrdFacadeLocal";

   public com.tmmas.scl.operations.crm.f.oh.comord.bean.ejb.session.ComOrdFacadeLocal create()
      throws javax.ejb.CreateException;

}
