//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : P-TMM-08004
//  @ File Name : UsuarioBOIT.java
//  @ Date : 09/09/2008
//  @ Author : hsegura
//
//



package com.tmmas.scl.framework.Sistema.bo.Interface;

import com.tmmas.scl.framework.CustomerDomain.exception.RateUsageRecordsException;
import com.tmmas.scl.framework.Sistema.dto.UsuarioDTO;
import com.tmmas.scl.framework.Sistema.dto.UsuarioQueryDTO;


public interface UsuarioBOIT {
	/**
	 * validar que el usuario tenga rol y permiso de ejecusion y que tenga codigo de vendedor
	 */	
	public boolean validarUsuario(UsuarioQueryDTO usuarioQueryDTO)throws RateUsageRecordsException;
	public String obtenerZonaImpositiva(String codOficina)throws RateUsageRecordsException;
}
