/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.rmo.rsar.manresinv.bean.ejb.session;

/**
 * Local interface for ManResInvFacade.
 * @generated 
 * @wtp generated
 */
public interface ManResInvFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
