/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.rmo.rsar.manresinv.bean.ejb.session;

/**
 * Remote interface for ManResInvFacade.
 * @generated 
 * @wtp generated
 */
public interface ManResInvFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO crearFrecuentesAltamira( com.tmmas.scl.framework.serviceDomain.serviceSpecEntitiesABE.businessObject.dataTransferObject.FreqAltamiraListDTO frecAltDTO )
      throws com.tmmas.scl.operations.rmo.rsar.manresinv.common.exception.ManResInvException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.customerABE.dataTransferObject.RetornoDTO eliminarFrecuentesAltamira( com.tmmas.scl.framework.serviceDomain.serviceSpecEntitiesABE.businessObject.dataTransferObject.FreqAltamiraListDTO frecAltDTO )
      throws com.tmmas.scl.operations.rmo.rsar.manresinv.common.exception.ManResInvException, java.rmi.RemoteException;

}
