
NOMBRE=His_ConvenioPAC

include $(COM_ENV_PRECOM)

EXE=$(XPCM_EXE)/
OBJ_EXTERNO=$(GE_LIB_PATH)/geora.o $(GE_LIB_PATH)/utils.o $(XPCM_LIB)/GEN_biblioteca.o

APLICACION=$(EXE)$(NOMBRE)
OBJETO_LOCAL=$(O)$(NOMBRE).o
INTERMEDIO_C=$(C)$(NOMBRE).c
FUENTE_PC=$(PC)$(NOMBRE).pc
CABECERA_H=$(H)$(NOMBRE).h

all: $(APLICACION)

$(APLICACION): $(OBJETO_LOCAL) $(OBJ_EXTERNO)
	$(CC) $(CFLAGS) $(COM_INCLUDE) $(OBJ_EXTERNO) $(PROLDLIBS) -o $(APLICACION) $(OBJETO_LOCAL)

$(OBJETO_LOCAL) : $(INTERMEDIO_C)
	$(CC) -o $(OBJETO_LOCAL) $(CFLAGS) $(COM_INCLUDE) -c $(INTERMEDIO_C)

$(INTERMEDIO_C) : $(FUENTE_PC)
	$(PROC) $(COM_PROCFLAGS) userid=$(ORAUSER)/$(ORAPASS) MODE=ANSI iname=$(FUENTE_PC) oname=$(INTERMEDIO_C)

clean:
	$(RMF) $(INTERMEDIO_C)
	$(RMF) $(OBJETO_LOCAL)
	
cleanall: clean
	$(RMF) $(APLICACION)
