/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.vendedor.negocio.ejb.session;

/**
 * Remote interface for VendedorFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface VendedorFacadeSTL
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.vendedor.dto.VendedorDTO recuperarInformacionVendedor( com.tmmas.scl.vendedor.dto.VendedorDTO vendedor )
      throws com.tmmas.scl.vendedor.exception.VendedorException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void registrarInformacionVendedor( com.tmmas.scl.vendedor.dto.VendedorDTO vendedor )
      throws com.tmmas.scl.vendedor.exception.VendedorException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.vendedor.dto.ConfiguracionVendedorCPUDTO recuperarConfiguracionVendedorCPU( com.tmmas.scl.vendedor.dto.ConfiguracionVendedorCPUDTO config )
      throws com.tmmas.scl.vendedor.exception.VendedorException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.vendedor.dto.UsuarioVendedorDTO obtenerInformacionUsuarioVendedor( com.tmmas.scl.vendedor.dto.UsuarioSistemaDTO usuarioSistema )
      throws com.tmmas.scl.vendedor.exception.VendedorException, java.rmi.RemoteException;

}
