/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.vendedor.negocio.ejb.session;

/**
 * Local home interface for VendedorFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface VendedorFacadeSTLLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/VendedorFacadeSTLLocal";
   public static final String JNDI_NAME="VendedorFacadeSTLLocal";

   public com.tmmas.scl.vendedor.negocio.ejb.session.VendedorFacadeSTLLocal create()
      throws javax.ejb.CreateException;

}
