/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.vendedor.negocio.ejb.session;

/**
 * Local interface for VendedorFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface VendedorFacadeSTLLocal
   extends javax.ejb.EJBLocalObject
{

}
