/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.vendedor.negocio.ejb.session;

/**
 * Home interface for VendedorFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface VendedorFacadeSTLHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/VendedorFacadeSTL";
   public static final String JNDI_NAME="VendedorFacadeSTL";

   public com.tmmas.scl.vendedor.negocio.ejb.session.VendedorFacadeSTL create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
