/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.pv.customerorder.service.servicios;

/**
 * Local home interface for BillingProductChargeFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface BillingProductChargeFacadeSTLLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/BillingProductChargeFacadeSTLLocal";
   public static final String JNDI_NAME="BillingProductChargeFacadeSTLLocal";

   public com.tmmas.cl.scl.pv.customerorder.service.servicios.BillingProductChargeFacadeSTLLocal create()
      throws javax.ejb.CreateException;

}
