/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.pv.customerorder.service.servicios;

/**
 * Home interface for BillingProductChargeFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface BillingProductChargeFacadeSTLHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/BillingProductChargeFacadeSTL";
   public static final String JNDI_NAME="BillingProductChargeFacadeSTL";

   public com.tmmas.cl.scl.pv.customerorder.service.servicios.BillingProductChargeFacadeSTL create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
