/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.pv.customerorder.service.servicios;

/**
 * Local interface for BillingProductChargeFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface BillingProductChargeFacadeSTLLocal
   extends javax.ejb.EJBLocalObject
{

}
