/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.integracionexterna.negocio.session;

/**
 * Local interface for IntegracionExterna.
 * @generated 
 * @wtp generated
 */
public interface IntegracionExternaLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void insertaTraspasoOP( java.lang.String numTraspaso,java.lang.String numSecuencia,java.lang.String codEstado ) throws com.tmmas.cl.scl.integracionexterna.common.exception.IntegracionExternaException, java.lang.Exception;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public boolean validaTraspOP( java.lang.String numSecuencia ) throws com.tmmas.cl.scl.integracionexterna.common.exception.IntegracionExternaException, java.lang.Exception;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void actualizaTraspasoOP( java.lang.String numTraspaso,java.lang.String numSecuencia,java.lang.String codEstado ) throws com.tmmas.cl.scl.integracionexterna.common.exception.IntegracionExternaException, java.lang.Exception;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.integracionexterna.common.dto.ws.SalidaConsultaTraspasoDTO consultaEstadoTraspOP( java.lang.String numSecuencia ) throws com.tmmas.cl.scl.integracionexterna.common.exception.IntegracionExternaException, java.lang.Exception;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public boolean validaBodegaDTS( java.lang.String codCliente,java.lang.String codBodega ) throws com.tmmas.cl.scl.integracionexterna.common.exception.IntegracionExternaException, java.lang.Exception;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String consultaParametros( java.lang.String nomParametro,java.lang.String codModulo,java.lang.String codProducto ) throws com.tmmas.cl.scl.integracionexterna.common.exception.IntegracionExternaException, java.lang.Exception;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void eliminaTraspasoMasivo( java.lang.String nomTraspasoMasivo ) throws com.tmmas.cl.scl.integracionexterna.common.exception.IntegracionExternaException;

}
