/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.cambserie.bean.ejb.session;

/**
 * Local home interface for CamSerFacade.
 * @generated 
 * @wtp generated
 */
public interface CamSerFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CamSerFacadeLocal";
   public static final String JNDI_NAME="CamSerFacadeLocal";

   public com.tmmas.scl.operation.crm.fab.cusintman.cambserie.bean.ejb.session.CamSerFacadeLocal create()
      throws javax.ejb.CreateException;

}
