/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.cambserie.bean.ejb.session;

/**
 * Local interface for CamSerFacade.
 * @generated 
 * @wtp generated
 */
public interface CamSerFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
