/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.smo.fulfillment.scaa.allspeserpar.bean.ejb.session;

/**
 * Local interface for AllSpeSerParFacade.
 * @generated 
 * @wtp generated
 */
public interface AllSpeSerParFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
