/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.smo.fulfillment.scaa.allspeserpar.bean.ejb.session;

/**
 * Local home interface for AllSpeSerParFacade.
 * @generated 
 * @wtp generated
 */
public interface AllSpeSerParFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AllSpeSerParFacadeLocal";
   public static final String JNDI_NAME="AllSpeSerParFacadeLocal";

   public com.tmmas.scl.operations.smo.fulfillment.scaa.allspeserpar.bean.ejb.session.AllSpeSerParFacadeLocal create()
      throws javax.ejb.CreateException;

}
