/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.frameworkcargos.bean.ejb.session;

/**
 * Remote interface for FrmkCargosFacade.
 * @generated 
 * @wtp generated
 */
public interface FrmkCargosFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ObtencionCargosDTO obtenerCargos( com.tmmas.scl.framework.customerDomain.dataTransferObject.ParametrosObtencionCargosDTO parametros )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkCargosException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ResultadoRegCargosDTO parametrosRegistrarCargos( com.tmmas.scl.framework.productDomain.dataTransferObject.RegCargosDTO cargos )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkCargosException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO registraCargosBatch( com.tmmas.scl.framework.customerDomain.dataTransferObject.RegistroCargosBatchDTO registro )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkCargosException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.RegCargosDTO construirRegistroCargos( com.tmmas.scl.framework.customerDomain.dataTransferObject.ObtencionCargosDTO resultadoObtenerCargos )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkCargosException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void cierreVenta( com.tmmas.scl.framework.customerDomain.dataTransferObject.GaVentasDTO gaVentasDTO )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkCargosException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.socketps.common.dto.ListasDTO consultaLista( com.tmmas.cl.scl.socketps.common.dto.ConsultaListaDTO consultaLista )
      throws com.tmmas.cl.scl.socketps.common.exception.SocketPSException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.socketps.common.dto.PlanDTO consultaPlan( com.tmmas.cl.scl.socketps.common.dto.ConsultaPlanDTO consultaPlan )
      throws com.tmmas.cl.scl.socketps.common.exception.SocketPSException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.socketps.common.dto.SaldoDTO consultaSaldo( com.tmmas.cl.scl.socketps.common.dto.ConsultaSaldoDTO consultaSaldo )
      throws com.tmmas.cl.scl.socketps.common.exception.SocketPSException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.PrecioTerminalDTO getRecPrecioEquipoActual( com.tmmas.scl.framework.productDomain.dataTransferObject.TerminalDTO terminalDTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.PrecioTerminalDTO getRecPrecioEquipoNuevo( com.tmmas.scl.framework.customerDomain.dataTransferObject.PrecioEquipoNuevoDTO precioEquipoNuevoDTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void actualizaFacturacion( com.tmmas.scl.framework.customerDomain.dataTransferObject.ParametrosEjecucionFacturacionDTO parametrosEjecucion )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkCargosException, java.rmi.RemoteException;

}
