/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.frameworkcargos.bean.ejb.session;

/**
 * Local home interface for FrmkCargosFacade.
 * @generated 
 * @wtp generated
 */
public interface FrmkCargosFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/FrmkCargosFacadeLocal";
   public static final String JNDI_NAME="FrmkCargosFacadeLocal";

   public com.tmmas.cl.scl.frameworkcargos.bean.ejb.session.FrmkCargosFacadeLocal create()
      throws javax.ejb.CreateException;

}
