/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.cambsimcard.bean.ejb.session;

/**
 * Local home interface for CamSimCarFacade.
 * @generated 
 * @wtp generated
 */
public interface CamSimCarFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CamSimCarFacadeLocal";
   public static final String JNDI_NAME="CamSimCarFacadeLocal";

   public com.tmmas.scl.operation.crm.fab.cusintman.cambsimcard.bean.ejb.session.CamSimCarFacadeLocal create()
      throws javax.ejb.CreateException;

}
