/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.cambsimcard.bean.ejb.session;

/**
 * Remote interface for CamSimCarFacade.
 * @generated 
 * @wtp generated
 */
public interface CamSimCarFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO obtenerDatosCliente( com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.AbonadoDTO obtenerDatosAbonado( com.tmmas.scl.framework.productDomain.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO obtenerDatosUsuarioAbonado( com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.BodegaDTO[] obtenerBodegas( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sesion )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO[] obtenerCausaCambioSerie(  )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.TipoDeContratoDTO[] obtenerTiposDeContrato( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sessionDTO )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.MesesProrrogasDTO[] obtenerMesesProrroga(  )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO[] obtenerModalidadPago( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO Sesion,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO CausaCamSerie )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO[] obtenerModalidadPagoSimcard( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO Sesion,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO CausaCamSerie )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.TipoTerminalDTO[] obtenerTipoTerminal( com.tmmas.scl.framework.ProductDomain.dto.TecnologiaDTO tecnologia )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.CuotaDTO[] obtenerCuotas( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sesion,com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO modalidadPago )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.UsosVentaDTO[] obtenerUsosVenta(  )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.CentralDTO[] obtenerCentralTecnologiaHlr( com.tmmas.scl.framework.ProductDomain.dto.SerieDTO serie,com.tmmas.scl.framework.ProductDomain.dto.TecnologiaDTO tecnologia )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void validaCausaCamSerie( com.tmmas.scl.framework.aplicationDomain.dto.SesionDTO sesion,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO causaCamSerie )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.MensajeRetornoDTO ejecutaRestrccion( com.tmmas.scl.framework.ProductDomain.dto.RestriccionesDTO restricciones )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO obtenerInformacionUsuario( com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO usuarioSistema )
      throws com.tmmas.scl.framework.aplicationDomain.exception.AplicationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SerieDTO reservaSimcard( java.lang.String accionProceso,com.tmmas.scl.framework.ProductDomain.dto.SerieDTO serie,com.tmmas.scl.framework.aplicationDomain.dto.UsuarioSistemaDTO usuarioSistema,com.tmmas.scl.framework.customerDomain.dto.UsuarioAbonadoDTO usuarioAbonado,java.lang.String parametros,com.tmmas.scl.framework.ProductDomain.dto.CausaCamSerieDTO causa,com.tmmas.scl.framework.ProductDomain.dto.TipoTerminalDTO terminal,com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO modalidadPago )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, com.tmmas.scl.framework.customerDomain.exception.CustomerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SerieDTO recInfoSerie( com.tmmas.scl.framework.ProductDomain.dto.SerieDTO serie )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.SecuenciaDTO obtenerSecuencia( com.tmmas.scl.framework.customerDomain.dataTransferObject.SecuenciaDTO parametro )
      throws com.tmmas.scl.operations.crm.fab.customerinterfacemanagement.common.exception.CusIntManException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.FormaPagoListDTO obtenerFormasPago( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.BusquedaFormasPagoDTO formaPago )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.DocumentoListDTO obtenerTiposDocumento( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.BusquedaTiposDocumentoDTO tipoDocumento )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO eliminarSolicitud( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RegistroSolicitudDTO registro )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO eliminarPresupuesto( com.tmmas.scl.framework.productDomain.dataTransferObject.RegistroFacturacionDTO registro )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.CuotasProductoDTO[] obtenerCuotasProducto(  )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ObtencionCargosDTO obtencionCargos( com.tmmas.scl.framework.customerDomain.dataTransferObject.ParametrosObtencionCargosDTO parametrosCargos )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.UsuarioDTO obtenerVendedor( com.tmmas.scl.framework.customerDomain.dataTransferObject.UsuarioDTO usuario )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.CartaGeneralDTO obtenerTextoCarta( com.tmmas.scl.framework.productDomain.dataTransferObject.CartaGeneralDTO cartaGeneral )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.DescuentoVendedorDTO obtenerDescuentoVendedor( com.tmmas.scl.framework.customerDomain.dataTransferObject.DescuentoVendedorDTO vendedor )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RespuestaSolicitudDTO solicitarAprobacionDescuento( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RegistroSolicitudListDTO registro )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RegistroSolicitudDTO consultarEstadoSolicitud( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RegistroSolicitudDTO registro )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.RegCargosDTO construirRegistroCargos( com.tmmas.scl.framework.customerDomain.dataTransferObject.ObtencionCargosDTO cargos )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.ResultadoRegCargosDTO parametrosRegistrarCargos( com.tmmas.scl.framework.productDomain.dataTransferObject.RegCargosDTO cargos )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO registrarVenta( com.tmmas.scl.framework.customerDomain.dataTransferObject.IngresoVentaDTO venta )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO aceptarPresupuesto( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PresupuestoDTO presup )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ContratoDTO obtenerTipoContrato( com.tmmas.scl.framework.customerDomain.dataTransferObject.ContratoDTO contrato )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PresupuestoDTO obtenerDetallePresupuesto( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PresupuestoDTO presup )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.VendedorDTO obtenerVendedor( com.tmmas.scl.framework.productDomain.dataTransferObject.VendedorDTO vendedor )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO insertarConceptoDescuento( com.tmmas.scl.framework.customerDomain.dataTransferObject.DescuentoDTO desc )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.DescuentoDTO obtenerCodConceptoDescuento( com.tmmas.scl.framework.productDomain.dataTransferObject.DatosGeneralesDTO param )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO eliminaCodConceptoDescuento( long numTransaccion )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO obtenerPlanComercial( com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO consultarEstadoFacturado( long numProceso )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.ArchivoFacturaDTO obtenerRutaFactura( com.tmmas.scl.framework.productDomain.dataTransferObject.ArchivoFacturaDTO factura )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ParametroDTO obtenerParametroGeneral( com.tmmas.scl.framework.customerDomain.dataTransferObject.ParametroDTO parametro )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void cierreVenta( com.tmmas.scl.framework.customerDomain.dataTransferObject.GaVentasDTO gaVentasDTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO registrarOOSSEnLinea( com.tmmas.scl.framework.customerDomain.dataTransferObject.RegistrarOossEnLineaDTO registro )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO actualizaRenova( com.tmmas.scl.framework.customerDomain.dataTransferObject.RegistrarRenovaDTO registrarRenova )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO obtenerModalidadPago( com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO modalidad )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void registrarOOSSCambioSimcard( com.tmmas.scl.operation.crm.fab.cusintman.cambsimcard.common.dataTransferObject.RegistraCambioDeSimcardActionDTO regCmbSimActDTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.SimcardDTO obtenerSimcard( com.tmmas.scl.framework.productDomain.dataTransferObject.SimcardDTO simcardDTO )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.PlanTarifarioDTO getCategoriaPlanTarifario( com.tmmas.scl.framework.productDomain.dataTransferObject.PlanTarifarioDTO planTarifarioDTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.aplicationDomain.dto.OperadoraLocalDTO obtenerOperadoraLocal(  )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.BodegaDTO[] getBodegasXVendedor( com.tmmas.scl.framework.ProductDomain.dto.BodegaDTO bodegaDTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.ArticuloInDTO[] getArticulos( com.tmmas.scl.framework.ProductDomain.dto.ArticuloInDTO entrada )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO validaSerieExterna( com.tmmas.scl.framework.ProductDomain.dto.SerieDTO serie )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SerieDTO[] buscarSeries( com.tmmas.scl.framework.ProductDomain.dto.SerieDTO serie )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.SerieDTO[] listarSerie( com.tmmas.scl.framework.ProductDomain.dto.SerieDTO entrada )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.DatosCentralDTO obtenerDatosCentral( int codCentral )
      throws com.tmmas.scl.framework.ProductDomain.exception.ProductException, java.rmi.RemoteException;

}
