//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : P-TMM-08004
//  @ File Name : UsuarioDAOIT.java
//  @ Date : 09/09/2008
//  @ Author : hsegura
//
//

package com.tmmas.scl.framework.Sistema.dao.Interface;

import com.tmmas.scl.framework.CustomerDomain.exception.RateUsageRecordsException;
import com.tmmas.scl.framework.Sistema.dto.UsuarioQueryDTO;

public interface UsuarioDAOIT {
	/**
	 * Recupera el rol del usuario
	 * 
	 * @throws RateUsageRecordsException
	 */
	public boolean recuperarRol(UsuarioQueryDTO usuarioQueryDTO)
			throws RateUsageRecordsException;
	public String obtenerZonaImpositiva(String codOficina)throws RateUsageRecordsException;
}
