/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.oh.isscusord.bean.ejb.session;

/**
 * Home interface for IssCusOrdFacade.
 * @generated 
 * @wtp generated
 */
public interface IssCusOrdFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/IssCusOrdFacade";
   public static final String JNDI_NAME="IssCusOrdFacade";

   public com.tmmas.scl.operations.crm.f.oh.isscusord.bean.ejb.session.IssCusOrdFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
