/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.oh.isscusord.bean.ejb.session;

/**
 * Local interface for IssCusOrdFacade.
 * @generated 
 * @wtp generated
 */
public interface IssCusOrdFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
