CREATE OR REPLACE TYPE PF_ESPEC_PRODUCTO_QT AS OBJECT
(
  COD_ESP_PROD NUMBER,
  ID_ESPEC_PROD VARCHAR2(10),
  DES_ESPEC_PROD VARCHAR2(30),
  FEC_INI_VIG DATE,
  FEC_TER_VIG DATE,
  TIPO_COMPORTAMIENTO VARCHAR2(5),
  IND_TIPO_PLATAFORMA VARCHAR2(5)
)
/
SHOW ERRORS
