CREATE OR REPLACE TYPE PF_PRODUCTO_OFERTADO_QT AS OBJECT
(
  COD_PROD NUMBER(8),
  IND_APLICA VARCHAR2(1),
  ID_PROD_OFERTADO VARCHAR2(10),
  COD_CATEGORIA_PLAN_BASICO VARCHAR2(10),
  DES_PROD_OFERTADO VARCHAR2(30),
  IND_TIPO_PLATAFORMA VARCHAR2(5),
  COD_ESPEC_PROD NUMBER,
  IND_PAQUETE VARCHAR2(1),
  FEC_INICIO_VIGENCIA DATE,
  FLG_ACTIVA VARCHAR2(10),
  COD_CATEGORIA VARCHAR2(10),
  FEC_TERMINO_VIGENCIA DATE,
  MAX_MODIFICACIONES NUMBER(5),
  MAX_CONTRATACIONES NUMBER(5)
)
/
SHOW ERRORS
