CREATE OR REPLACE TYPE PF_RESTR_CONTRATA_TD_QT AS OBJECT
(
  IND_TIPO_PLATAFORMA VARCHAR2(10),
  IND_NIVEL_APLICA VARCHAR2(10),
  TIPO_COMPORTAMIENTO VARCHAR2(10),
  FEC_INI_VIG DATE,
  CAN_MAX VARCHAR2(10),
  MTO_MAX VARCHAR2(10),
  MIN_CICLOS VARCHAR2(10),
  FEC_TER_VIG DATE
)
/
SHOW ERRORS
