CREATE OR REPLACE
TYPE PR_PROCESO_PRODUCTO_QT AS OBJECT
(
  COD_PROCESO NUMBER(30),
  NUM_PROCESO VARCHAR2(20),
  ORIGEN_PROCESO VARCHAR2(10),
  FEC_PROCESO DATE,
  ESTADO_PROCESO VARCHAR2(10),
  NUM_EVENTO  NUMBER(9),
  COD_OS VARCHAR2(5),
  COD_CLIENTE NUMBER(8),
  NUM_ABONADO NUMBER(8),
  CONSTRUCTOR FUNCTION PR_PROCESO_PRODUCTO_QT RETURN SELF AS RESULT
);
/
CREATE OR REPLACE
TYPE BODY PR_PROCESO_PRODUCTO_QT IS
CONSTRUCTOR FUNCTION PR_PROCESO_PRODUCTO_QT RETURN SELF AS RESULT AS
  BEGIN
  	COD_PROCESO    := NULL;
  	NUM_PROCESO    := NULL;
  	ORIGEN_PROCESO := NULL;
  	FEC_PROCESO    := NULL;
  	ESTADO_PROCESO := NULL;
  	NUM_EVENTO     := NULL;
  	COD_OS         := NULL;
  	COD_CLIENTE    := NULL;
  	NUM_ABONADO    := NULL;
  	RETURN;
  END;
END;
/
