CREATE OR REPLACE
TYPE PR_PRODUCTOS_CONTS_TO_QT AS OBJECT
(
  COD_PROD_CONTRATADO NUMBER(8),
  COD_CLIENTE_BENEFICIARIO NUMBER(10),
  NUM_ABONADO_BENEFICIARIO NUMBER(10),
  COD_PROD_OFERTADO NUMBER(8),
  FEC_INICIO_VIGENCIA DATE,
  COD_CANAL VARCHAR2(20),
  NUM_PROCESO VARCHAR2(10),
  ORIGEN_PROCESO VARCHAR2(2),
  FEC_PROCESO DATE,
  COD_ESTADO VARCHAR2(10),
  IND_CONDICION_CONTRATACION VARCHAR2(1),
  COD_CLIENTE_CONTRATANTE NUMBER(10),
  NUM_ABONADO_CONTRATANTE NUMBER(10),
  FEC_TERMINO_VIGENCIA DATE,
  IND_PRIORIDAD NUMBER(10),
  COD_PROD_CONTRAT_PADRE NUMBER(10),
  COD_PERFIL_LISTA VARCHAR2(10),
  TIPO_COMPORTAMIENTO VARCHAR2(10),
  COD_LIMCONS VARCHAR2(5),
  MTO_LIMCONS NUMBER(14,4),
  CONSTRUCTOR FUNCTION PR_PRODUCTOS_CONTS_TO_QT RETURN SELF AS RESULT
); 
/
CREATE OR REPLACE
TYPE BODY PR_PRODUCTOS_CONTS_TO_QT IS
        -- Constructor por defecto
        CONSTRUCTOR FUNCTION PR_PRODUCTOS_CONTS_TO_QT RETURN SELF AS RESULT AS
        BEGIN
   SELF.COD_PROD_CONTRATADO := NULL;
   SELF.COD_CLIENTE_BENEFICIARIO := NULL;
   SELF.NUM_ABONADO_BENEFICIARIO := NULL;
   SELF.COD_PROD_OFERTADO := NULL;
   SELF.FEC_INICIO_VIGENCIA := NULL;
   SELF.COD_CANAL := NULL;
   SELF.NUM_PROCESO := NULL;
   SELF.ORIGEN_PROCESO := NULL;
   SELF.FEC_PROCESO := NULL;
   SELF.COD_ESTADO := NULL;
   SELF.IND_CONDICION_CONTRATACION := NULL;
   SELF.COD_CLIENTE_CONTRATANTE := NULL;
   SELF.NUM_ABONADO_CONTRATANTE := NULL;
   SELF.FEC_TERMINO_VIGENCIA := NULL;
   SELF.IND_PRIORIDAD := NULL;
   SELF.COD_PROD_CONTRAT_PADRE := NULL;
   SELF.COD_PERFIL_LISTA := NULL;
   SELF.TIPO_COMPORTAMIENTO := NULL;
   SELF.COD_LIMCONS := NULL;
   SELF.MTO_LIMCONS:=NULL;
            RETURN;
        END;
END; 
/
