CREATE OR REPLACE
TYPE PR_PRODUCTO_DESCONTRATA_QT AS OBJECT
(
  ORIGEN_PROCESO_DESCONTRATA VARCHAR2(5),
  NUM_PROC_DESCONTRATA VARCHAR2(10),
  FEC_DESCONTRATA DATE,
  TIPO_COMPORTAMIENTO VARCHAR2(20),
  COD_PERFIL_LISTA NUMBER(38),
  COD_PROD_CONTRA_PADRE NUMBER(38),
  IND_PRIORIDAD NUMBER(5),
  FEC_TERMINO_VIGENCIA DATE,
  NUM_ABONADO_CONTRATANTE NUMBER(38),
  COD_CLIENTE_CONTRATANTE NUMBER(38),
  IND_CONDICION_CONTRATACION VARCHAR2(1),
  COD_ESTADO VARCHAR2(10),
  FEC_PROCESO DATE,
  ORIGEN_PROCESO VARCHAR2(5),
  NUM_PROCESO VARCHAR2(10),
  COD_CANAL VARCHAR2(20),
  FEC_INICIO_VIGENCIA DATE,
  COD_PROD_OFERTADO NUMBER(38),
  NUM_ABONADO_BENEFICIARIO NUMBER(38),
  COD_CLIENTE_BENEFICIARIO NUMBER(38),
  COD_PROD_CONTRATADO NUMBER(38),
  COD_LIMCONS VARCHAR2(5),
  NOM_USUARIO VARCHAR2(30),
  MTO_LIMCONS NUMBER(14,4),
  CONSTRUCTOR FUNCTION PR_PRODUCTO_DESCONTRATA_QT RETURN SELF AS RESULT
); 
/
CREATE OR REPLACE
TYPE BODY PR_PRODUCTO_DESCONTRATA_QT IS
CONSTRUCTOR FUNCTION PR_PRODUCTO_DESCONTRATA_QT RETURN SELF AS RESULT AS
  BEGIN
      SELF.ORIGEN_PROCESO_DESCONTRATA := NULL;
      SELF.NUM_PROC_DESCONTRATA       := NULL;
      SELF.FEC_DESCONTRATA            := NULL;
      SELF.TIPO_COMPORTAMIENTO        := NULL;
      SELF.COD_PERFIL_LISTA           := NULL;
      SELF.COD_PROD_CONTRA_PADRE      := NULL;
      SELF.IND_PRIORIDAD              := NULL;
      SELF.FEC_TERMINO_VIGENCIA       := NULL;
      SELF.NUM_ABONADO_CONTRATANTE    := NULL;
      SELF.COD_CLIENTE_CONTRATANTE    := NULL;
      SELF.IND_CONDICION_CONTRATACION := NULL;
      SELF.COD_ESTADO                 := NULL;
      SELF.FEC_PROCESO                := NULL;
      SELF.ORIGEN_PROCESO             := NULL;
      SELF.NUM_PROCESO                := NULL;
      SELF.COD_CANAL                  := NULL;
      SELF.FEC_INICIO_VIGENCIA        := NULL;
      SELF.COD_PROD_OFERTADO          := NULL;
      SELF.NUM_ABONADO_BENEFICIARIO   := NULL;
      SELF.COD_CLIENTE_BENEFICIARIO   := NULL;
      SELF.COD_PROD_CONTRATADO        := NULL;
      SELF.COD_LIMCONS                := NULL;
      SELF.NOM_USUARIO                := NULL;
      SELF.MTO_LIMCONS                := NULL;
      RETURN;
  END;
END; 
/