CREATE OR REPLACE TYPE PR_PROCESOS_PROD_TD_QT AS OBJECT
(
  COD_PROCESO NUMBER(30),
  NUM_PROCESO VARCHAR2(20),
  ORIGEN_PROCESO VARCHAR2(10),
  FEC_PROCESO DATE,
  ESTADO_PROCESO VARCHAR2(10)
)
/
SHOW ERRORS
