CREATE OR REPLACE
TYPE PR_VENTA_QT AS OBJECT
(
  NUM_VENTA NUMBER(8),
  CONSTRUCTOR FUNCTION PR_VENTA_QT RETURN SELF AS RESULT
);
/


CREATE OR REPLACE
TYPE BODY PR_VENTA_QT IS
CONSTRUCTOR FUNCTION PR_VENTA_QT RETURN SELF AS RESULT AS
  BEGIN
  	SELF.NUM_VENTA := NULL;
  	RETURN;
  END;
END;
/
