/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.integracionsicsa.negocio.session;

/**
 * Home interface for IntegracionSICSA.
 * @generated 
 * @wtp generated
 */
public interface IntegracionSICSAHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/IntegracionSICSA";
   public static final String JNDI_NAME="IntegracionSICSA";

   public com.tmmas.cl.scl.integracionsicsa.negocio.session.IntegracionSICSA create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
