/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.integracionsicsa.negocio.session;

/**
 * Local home interface for IntegracionSICSA.
 * @generated 
 * @wtp generated
 */
public interface IntegracionSICSALocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/IntegracionSICSALocal";
   public static final String JNDI_NAME="IntegracionSICSALocal";

   public com.tmmas.cl.scl.integracionsicsa.negocio.session.IntegracionSICSALocal create()
      throws javax.ejb.CreateException;

}
