//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : P-TMM-08004
//  @ File Name : ConfiguracionSistemaBO.java
//  @ Date : 09/09/2008
//  @ Author : hsegura
//
//

package com.tmmas.scl.framework.Sistema.bo;

import org.apache.commons.configuration.CompositeConfiguration;
import org.apache.log4j.Logger;

import com.tmmas.cl.framework20.util.UtilProperty;
import com.tmmas.scl.framework.CustomerDomain.exception.RateUsageRecordsException;
import com.tmmas.scl.framework.Sistema.bo.Interface.ConfiguracionSistemaBOIT;
import com.tmmas.scl.framework.Sistema.dao.ConfiguracionSistemaDAO;
import com.tmmas.scl.framework.Sistema.dao.Interface.ConfiguracionSistemaDAOIT;
import com.tmmas.scl.framework.Sistema.dto.FormatoFechaDTO;

public class ConfiguracionSistemaBO implements ConfiguracionSistemaBOIT {

	private static Logger logger = Logger
			.getLogger(ConfiguracionSistemaBO.class);

	private CompositeConfiguration config;

	public ConfiguracionSistemaBO() {
		super();
		config = UtilProperty
				.getConfiguration("ServicioFacturacionWS.properties",
						"com/tmmas/scl/framework/properties/archivorecursos.properties");
	}

	/**
	 * Comprueba si la version corresponde
	 */
	public boolean verificarVersion() throws RateUsageRecordsException {
		logger.debug("verificarVersion():start");
		boolean result = false;
		ConfiguracionSistemaDAOIT configuracionSistemaDAO = new ConfiguracionSistemaDAO();
		result = configuracionSistemaDAO.verificarVersion();
		logger.debug("verificarVersion():end");
		return result;

	}

	public void obtenerValorImpresion() {

	}

	public boolean obtenerConfiguracionInternacional()
			throws RateUsageRecordsException {
		logger.debug("verificarVersion():start");
		boolean result = false;
		ConfiguracionSistemaDAOIT configuracionSistemaDAO = new ConfiguracionSistemaDAO();
		result = configuracionSistemaDAO.obtenerConfiguracionInternacional();
		logger.debug("verificarVersion():end");

		return result;

	}


	public String obtenerFechaSistema() throws RateUsageRecordsException {
		logger.debug("obtenerFechaSistema():start");
		String result = null;
		ConfiguracionSistemaDAOIT configuracionSistemaDAO = new ConfiguracionSistemaDAO();

		result = configuracionSistemaDAO.obtenerFechaSistema();
		logger.debug("result : " + result);
		return result;
	}


	public boolean validarFechaVencimiento(String fechaVencimiento)
			throws RateUsageRecordsException {
		logger.debug("validarFechaVencimiento():start");
		boolean result = false;
		ConfiguracionSistemaDAOIT configuracionSistemaDAO = new ConfiguracionSistemaDAO();
		result = configuracionSistemaDAO
				.validarFechaVencimiento(fechaVencimiento);
		logger.debug("result : " + result);
		logger.debug("validarFechaVencimiento():end");
		return result;
	}

	public FormatoFechaDTO obtenerParametrosFechasSCL()
			throws RateUsageRecordsException {

		ConfiguracionSistemaDAOIT configuracionSistemaDAO = new ConfiguracionSistemaDAO();
		return configuracionSistemaDAO.obtenerParametrosFechasSCL();

	}

	public void obtenerParametrosFacturacion() throws RateUsageRecordsException {

	}


	public String obtenerLetra(String codDcto, String catImpositiva)
			throws RateUsageRecordsException {
		logger.debug("obtenerLetra():start");
		ConfiguracionSistemaDAOIT configuracionSistemaDAO = new ConfiguracionSistemaDAO();
		String result = null;
		result = configuracionSistemaDAO.obtenerLetra(codDcto, catImpositiva);
		logger.debug("result : " + result);
		logger.debug("obtenerLetra():end");
		return result;

	}

	public String obtenerSecuencia(String nombreSecuencia)
			throws RateUsageRecordsException {
		logger.debug("obtenerSecuencia():start");
		String result = null;
		ConfiguracionSistemaDAOIT configuracionSistemaDAO = new ConfiguracionSistemaDAO();
		result = configuracionSistemaDAO.obtenerSecuencia(nombreSecuencia);
		logger.debug("result : " + result);
		logger.debug("obtenerSecuencia():end");
		return result;
	}

	public String obtenerParamGral(String parametro)
			throws RateUsageRecordsException {
		logger.debug("obtenerParamGral():start");
		String result = null;
		ConfiguracionSistemaDAOIT configuracionSistemaDAO = new ConfiguracionSistemaDAO();
		result = configuracionSistemaDAO.obtenerParamGral(parametro);
		logger.debug("result : " + result);
		logger.debug("obtenerParamGral():end");
		return result;

	}

	public String obtenerDatosGener(String parametro)
			throws RateUsageRecordsException {
		logger.debug("obtenerDatosGener():start");
		String result = null;
		ConfiguracionSistemaDAOIT configuracionSistemaDAO = new ConfiguracionSistemaDAO();
		result = configuracionSistemaDAO.obtenerDatosGener(parametro);
		logger.debug("result : " + result);
		logger.debug("obtenerDatosGener():end");
		return result;

	}

	public String obtenerModGener(String catTributaria, String modCobro,
			String centroEmision, String codMiscelanea)
			throws RateUsageRecordsException {
		logger.debug("obtenerModGener():start");
		String result = null;
		ConfiguracionSistemaDAOIT configuracionSistemaDAO = new ConfiguracionSistemaDAO();

		result = configuracionSistemaDAO.obtenerModGener(catTributaria,
				modCobro, centroEmision, codMiscelanea);
		logger.debug("result : " + result);
		logger.debug("obtenerModGener():end");
		return result;

	}




}
