//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : P-TMM-08004
//  @ File Name : ConfiguracionFacturacionBO.java
//  @ Date : 09/09/2008
//  @ Author : hsegura
//
//



package com.tmmas.scl.framework.Sistema.bo;


public class ConfiguracionFacturacionBO extends ConfiguracionSistemaBO {
	public void obtenerParametrosFacturacion() {
	
	}
	
	public void obtenerDiasVencimiento() {
	
	}
}
