//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : P-TMM-08004
//  @ File Name : ClienteDAOIT.java
//  @ Date : 09/09/2008
//  @ Author : hsegura
//
//



package com.tmmas.scl.framework.customerdomainfacturacion.CustomerABE.dao.Interface;

import com.tmmas.scl.framework.CustomerDomain.CustomerABE.dto.ClienteDTO;
import com.tmmas.scl.framework.CustomerDomain.exception.RateUsageRecordsException;


public interface ClienteDAOIT {
	public void obtenerIdentificadorCliente()throws RateUsageRecordsException;
	public String  obtenerSubcategoriaCliente()throws RateUsageRecordsException;
	public String obtenerZonaImpositiva(String codOficina)throws RateUsageRecordsException;
	public String obtenerCategoriaTributaria()throws RateUsageRecordsException;	
	public void obtenerCategoriaImpositiva()throws RateUsageRecordsException;
	public ClienteDTO obtenerDatosCliente(String codCliente,String fechaActual)throws RateUsageRecordsException;
	
}
