/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.oh.detcusordfea.bean.ejb.session;

/**
 * Home interface for DetCusOrdFeaFacade.
 * @generated 
 * @wtp generated
 */
public interface DetCusOrdFeaFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/DetCusOrdFeaFacade";
   public static final String JNDI_NAME="DetCusOrdFeaFacade";

   public com.tmmas.scl.operations.crm.f.oh.detcusordfea.bean.ejb.session.DetCusOrdFeaFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
