/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.f.oh.detcusordfea.bean.ejb.session;

/**
 * Local interface for DetCusOrdFeaFacade.
 * @generated 
 * @wtp generated
 */
public interface DetCusOrdFeaFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
