GRANT DELETE ON AL_PRECIOS_RETAIL_TT TO SISCEL_ADMIN
/
GRANT INSERT ON AL_PRECIOS_RETAIL_TT TO SISCEL_ADMIN
/
GRANT SELECT ON AL_PRECIOS_RETAIL_TT TO SISCEL_ADMIN
/
GRANT UPDATE ON AL_PRECIOS_RETAIL_TT TO SISCEL_ADMIN
/
GRANT DELETE ON AL_PRECIOS_RETAIL_TT TO SISCEL_AL
/
GRANT INSERT ON AL_PRECIOS_RETAIL_TT TO SISCEL_AL
/
GRANT SELECT ON AL_PRECIOS_RETAIL_TT TO SISCEL_AL
/
GRANT UPDATE ON AL_PRECIOS_RETAIL_TT TO SISCEL_AL
/
GRANT SELECT ON AL_PRECIOS_RETAIL_TT TO SISCEL_SELECT
/
