GRANT EXECUTE ON EBZ_PAC_GA_CTES_CTAS TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON EBZ_PAC_GA_CTES_CTAS TO SISCEL
/
GRANT EXECUTE ON EBZ_PAC_GA_CTES_CTAS TO SISCEL_ADMIN
/
GRANT EXECUTE ON EBZ_PAC_GA_CTES_CTAS TO SISCEL_SELECT
/
