GRANT EXECUTE ON EBZ_PAC_GA_DTOS_GENERALES TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON EBZ_PAC_GA_DTOS_GENERALES TO SISCEL
/
GRANT EXECUTE ON EBZ_PAC_GA_DTOS_GENERALES TO SISCEL_ADMIN
/
GRANT EXECUTE ON EBZ_PAC_GA_DTOS_GENERALES TO SISCEL_SELECT
/
