GRANT EXECUTE ON EBZ_PAC_SEGURIDAD TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON EBZ_PAC_SEGURIDAD TO SISCEL
/
GRANT EXECUTE ON EBZ_PAC_SEGURIDAD TO SISCEL_ADMIN
/
GRANT EXECUTE ON EBZ_PAC_SEGURIDAD TO SISCEL_SELECT
/
