GRANT EXECUTE ON EBZ_PAC_FA_SISCEL TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON EBZ_PAC_FA_SISCEL TO SISCEL
/
GRANT EXECUTE ON EBZ_PAC_FA_SISCEL TO SISCEL_ADMIN
/
GRANT EXECUTE ON EBZ_PAC_FA_SISCEL TO SISCEL_SELECT
/
