GRANT EXECUTE ON MSG_ELIMINAR_MENSAJES TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON MSG_ELIMINAR_MENSAJES TO SISCEL
/
GRANT EXECUTE ON MSG_ELIMINAR_MENSAJES TO SISCEL_ADMIN
/
GRANT EXECUTE ON MSG_ELIMINAR_MENSAJES TO SISCEL_SELECT
/
