GRANT EXECUTE ON NP_ACTIVACION_TARJETAS_PG TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON NP_ACTIVACION_TARJETAS_PG TO SISCEL
/
GRANT EXECUTE ON NP_ACTIVACION_TARJETAS_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON NP_ACTIVACION_TARJETAS_PG TO SISCEL_SELECT
/
