GRANT DEBUG ON NP_ART_CANAL_PG TO EBZ_SISCEL_DML;

GRANT DEBUG ON NP_ART_CANAL_PG TO INTERNET;

GRANT DEBUG ON NP_ART_CANAL_PG TO SISCEL_ADMIN;

GRANT DEBUG ON NP_ART_CANAL_PG TO SISCEL_SELECT;

GRANT EXECUTE ON NP_ART_CANAL_PG TO INTERNET_SELECT;

GRANT EXECUTE ON NP_ART_CANAL_PG TO SISCEL_VE;
