GRANT DELETE ON NP_DET_VENTAS_OL_TO TO SISCEL_ADMIN
/
GRANT INSERT ON NP_DET_VENTAS_OL_TO TO SISCEL_ADMIN
/
GRANT SELECT ON NP_DET_VENTAS_OL_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON NP_DET_VENTAS_OL_TO TO SISCEL_ADMIN
/
GRANT SELECT ON NP_DET_VENTAS_OL_TO TO SISCEL_SELECT
/

