GRANT DELETE ON NP_ERRORES_DEVOLUCION_TO TO SISCEL_ADMIN
/
GRANT INSERT ON NP_ERRORES_DEVOLUCION_TO TO SISCEL_ADMIN
/
GRANT SELECT ON NP_ERRORES_DEVOLUCION_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON NP_ERRORES_DEVOLUCION_TO TO SISCEL_ADMIN
/
GRANT SELECT ON NP_ERRORES_DEVOLUCION_TO TO SISCEL_SELECT
/
