GRANT EXECUTE ON NP_GESTOR_MAYORISTAS_PG TO EBZ_SISCEL_DML
/
GRANT EXECUTE ON NP_GESTOR_MAYORISTAS_PG TO SISCEL
/
GRANT EXECUTE ON NP_GESTOR_MAYORISTAS_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON NP_GESTOR_MAYORISTAS_PG TO SISCEL_SELECT
/
