GRANT  EXECUTE  ON  NP_LIMITE_CREDITO_FN  TO SISCEL_ADMIN
/
GRANT  EXECUTE  ON  NP_LIMITE_CREDITO_FN  TO SISCEL_GE
/
GRANT  EXECUTE  ON  NP_LIMITE_CREDITO_FN  TO SISCEL_SELECT
/
GRANT  EXECUTE  ON  NP_LIMITE_CREDITO_FN  TO INTERNET_SELECT
/
