GRANT EXECUTE ON NP_LIMITE_ARTICULOS_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON NP_LIMITE_ARTICULOS_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON NP_LIMITE_ARTICULOS_PG TO SISCEL_VE
/
GRANT EXECUTE ON NP_LIMITE_ARTICULOS_PG TO INTERNET
/
GRANT EXECUTE ON NP_LIMITE_ARTICULOS_PG TO INTERNET_SELECT
/

