GRANT EXECUTE  ON NP_MANTENEDOR_PROMOCIONES_PG   TO  SISCEL_SELECT
/
GRANT EXECUTE  ON NP_MANTENEDOR_PROMOCIONES_PG   TO  SISCEL_ADMIN
/
GRANT EXECUTE  ON NP_MANTENEDOR_PROMOCIONES_PG   TO INTERNET
/
GRANT EXECUTE  ON NP_MANTENEDOR_PROMOCIONES_PG   TO EBZ_SISCEL_EXE
/
