GRANT DELETE ON NP_PEDIDO_TH TO EBZ_SISCEL_DML
/
GRANT INSERT ON NP_PEDIDO_TH TO EBZ_SISCEL_DML
/
GRANT SELECT ON NP_PEDIDO_TH TO EBZ_SISCEL_DML
/
GRANT UPDATE ON NP_PEDIDO_TH TO EBZ_SISCEL_DML
/
GRANT SELECT ON NP_PEDIDO_TH TO EBZ_SISCEL_DQL
/
GRANT DELETE ON NP_PEDIDO_TH TO SISCEL_ADMIN
/
GRANT INSERT ON NP_PEDIDO_TH TO SISCEL_ADMIN
/
GRANT SELECT ON NP_PEDIDO_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON NP_PEDIDO_TH TO SISCEL_ADMIN
/
GRANT SELECT ON NP_PEDIDO_TH TO SISCEL_SELECT
/
