GRANT DELETE ON NP_SER_VENTAS_OL_TO TO SISCEL_ADMIN
/
GRANT INSERT ON NP_SER_VENTAS_OL_TO TO SISCEL_ADMIN
/
GRANT SELECT ON NP_SER_VENTAS_OL_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON NP_SER_VENTAS_OL_TO TO SISCEL_ADMIN
/
GRANT SELECT ON NP_SER_VENTAS_OL_TO TO SISCEL_SELECT
/

