GRANT DELETE, INSERT, SELECT, UPDATE ON EBZ_SISCEL.NP_VAL_SERIES_TEMP_TO TO EBZ_SISCEL_DML
/
GRANT DELETE, INSERT, SELECT, UPDATE ON EBZ_SISCEL.NP_VAL_SERIES_TEMP_TO TO SISCEL_ADMIN
/
GRANT SELECT ON EBZ_SISCEL.NP_VAL_SERIES_TEMP_TO TO SISCEL_SELECT
/
GRANT SELECT ON EBZ_SISCEL.NP_VAL_SERIES_TEMP_TO TO SOLO_CONSULTA_EBZ_SISCEL
/