GRANT SELECT ON NPD_USUARIO TO EBZ_SISCEL_DQL
/
GRANT DELETE ON NPD_USUARIO TO SISCEL
/
GRANT INSERT ON NPD_USUARIO TO SISCEL
/
GRANT SELECT ON NPD_USUARIO TO SISCEL
/
GRANT UPDATE ON NPD_USUARIO TO SISCEL
/
GRANT SELECT ON NPD_USUARIO TO SISCEL_ADMIN
/
GRANT UPDATE ON NPD_USUARIO TO SISCEL_ADMIN
/
GRANT SELECT ON NPD_USUARIO TO SISCEL_SELECT
/
