GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON NPT_LIMITE_ARTICULO_TH TO EBZ_SISCEL_DML
/
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON NPT_LIMITE_ARTICULO_TH TO SISCEL
/
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON NPT_LIMITE_ARTICULO_TH TO SISCEL_ADMIN
/
GRANT ALTER, DELETE, INSERT, SELECT ON NPT_LIMITE_ARTICULO_TH TO SISCEL_SELECT
/