GRANT DELETE ON NPT_ERRORES_PROC_HISTORICO_TH TO SISCEL_ADMIN
/
GRANT INSERT ON NPT_ERRORES_PROC_HISTORICO_TH TO SISCEL_ADMIN
/
GRANT SELECT ON NPT_ERRORES_PROC_HISTORICO_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON NPT_ERRORES_PROC_HISTORICO_TH TO SISCEL_ADMIN
/
GRANT SELECT ON NPT_ERRORES_PROC_HISTORICO_TH TO SISCEL_SELECT
/
