GRANT SELECT ON NPT_PROMOCION_SQ TO SISCEL_SELECT
/
GRANT SELECT ON NPT_PROMOCION_SQ TO SISCEL_ADMIN
/
GRANT SELECT ON NPT_PROMOCION_SQ TO INTERNET
/
GRANT SELECT ON NPT_PROMOCION_SQ TO EBZ_SISCEL_EXE
/

