GRANT DELETE, INSERT, SELECT, UPDATE ON NPT_DETALLE_PEDIDO_SUG TO EBZ_SISCEL_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON NPT_DETALLE_PEDIDO_SUG TO SISCEL_ADMIN;

GRANT SELECT ON NPT_DETALLE_PEDIDO_SUG TO SISCEL_SELECT;

GRANT DELETE, INSERT, SELECT ON NPT_DETALLE_PEDIDO_SUG TO INTERNET;
