GRANT DELETE ON NPT_DETALLE_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT INSERT ON NPT_DETALLE_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT SELECT ON NPT_DETALLE_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON NPT_DETALLE_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT SELECT ON NPT_DETALLE_PEDIDO_HIST_TH TO SISCEL_SELECT
/
