GRANT DELETE ON NPT_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT INSERT ON NPT_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT SELECT ON NPT_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON NPT_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT SELECT ON NPT_PEDIDO_HIST_TH TO SISCEL_SELECT
/
