GRANT DELETE ON NPT_SERIE_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT INSERT ON NPT_SERIE_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT SELECT ON NPT_SERIE_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON NPT_SERIE_PEDIDO_HIST_TH TO SISCEL_ADMIN
/
GRANT SELECT ON NPT_SERIE_PEDIDO_HIST_TH TO SISCEL_SELECT
/
