GRANT DELETE, INSERT, SELECT, UPDATE ON NPT_URL_TD TO EBZ_SISCEL_DML
/
GRANT DELETE, INSERT, SELECT ON NPT_URL_TD TO INTERNET
/
GRANT DELETE, INSERT, SELECT, UPDATE ON NPT_URL_TD TO SISCEL_ADMIN
/
GRANT DELETE, INSERT, SELECT ON NPT_URL_TD TO SISCEL_SELECT
/