GRANT  SELECT                           ON NPT_PROM_CLIENTE_TD TO SISCEL_SELECT
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON NPT_PROM_CLIENTE_TD TO SISCEL_ADMIN
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON NPT_PROM_CLIENTE_TD TO EBZ_SISCEL_DML
/
GRANT  SELECT, INSERT, UPDATE, DELETE   ON NPT_PROM_CLIENTE_TD TO EBZ_SISCEL_DQL
/

