GRANT SELECT                            ON NPT_PROM_ARTICULO_TH TO SISCEL_SELECT
/
GRANT SELECT, INSERT, UPDATE, DELETE    ON NPT_PROM_ARTICULO_TH TO SISCEL_ADMIN
/
GRANT SELECT, INSERT, UPDATE, DELETE    ON NPT_PROM_ARTICULO_TH TO EBZ_SISCEL_DML
/
GRANT SELECT, INSERT, UPDATE, DELETE    ON NPT_PROM_ARTICULO_TH TO EBZ_SISCEL_DQL
/

