GRANT DELETE, INSERT, SELECT, UPDATE ON NPT_LIMITE_ARTICULO_TD TO EBZ_SISCEL_DML;

GRANT DELETE, INSERT, SELECT ON NPT_LIMITE_ARTICULO_TD TO INTERNET;

GRANT DELETE, INSERT, SELECT, UPDATE ON NPT_LIMITE_ARTICULO_TD TO SISCEL_ADMIN;

GRANT DELETE, INSERT, SELECT ON NPT_LIMITE_ARTICULO_TD TO SISCEL_SELECT;
