GRANT DELETE, INSERT, SELECT, UPDATE ON NPT_GRUPO_MAIL TO EBZ_SISCEL_DML
/
GRANT DELETE, INSERT, SELECT ON NPT_GRUPO_MAIL TO INTERNET
/
GRANT DELETE, INSERT, SELECT, UPDATE ON NPT_GRUPO_MAIL TO SISCEL_ADMIN
/
GRANT DELETE, INSERT, SELECT ON NPT_GRUPO_MAIL TO SISCEL_SELECT
/