GRANT SELECT ,INSERT,UPDATE,DELETE      ON NPT_AUDIT_CLIENTE_TH TO SISCEL_ADMIN
/
GRANT SELECT ,INSERT,UPDATE,DELETE      ON NPT_AUDIT_CLIENTE_TH TO SISCEL_AL
/
GRANT SELECT                            ON NPT_AUDIT_CLIENTE_TH TO SISCEL_SELECT
/
