GRANT DELETE, INSERT, SELECT, UPDATE ON NPT_PEDIDO_SUGERIDO TO EBZ_SISCEL_DML;

GRANT DELETE, INSERT, SELECT ON NPT_PEDIDO_SUGERIDO TO INTERNET;

GRANT DELETE, INSERT, SELECT, UPDATE ON NPT_PEDIDO_SUGERIDO TO SISCEL_ADMIN;

GRANT SELECT ON NPT_PEDIDO_SUGERIDO TO SISCEL_SELECT;
