GRANT EXECUTE ON P_INSERT_PEDIDO_DET TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_INSERT_PEDIDO_DET TO SISCEL
/
GRANT EXECUTE ON P_INSERT_PEDIDO_DET TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERT_PEDIDO_DET TO SISCEL_SELECT
/
