GRANT EXECUTE ON P_INSERT_RECLAMO TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_INSERT_RECLAMO TO SISCEL
/
GRANT EXECUTE ON P_INSERT_RECLAMO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERT_RECLAMO TO SISCEL_SELECT
/
