GRANT EXECUTE ON P_INSERT_DEVOLUCION_ENC TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_INSERT_DEVOLUCION_ENC TO SISCEL
/
GRANT EXECUTE ON P_INSERT_DEVOLUCION_ENC TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERT_DEVOLUCION_ENC TO SISCEL_SELECT
/
