GRANT EXECUTE ON P_INSERT_PEDIDO_SUG_ENC TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERT_PEDIDO_SUG_ENC TO SISCEL_SELECT
/
GRANT EXECUTE ON P_INSERT_PEDIDO_SUG_ENC TO SISCEL_VE
/
GRANT EXECUTE ON P_INSERT_PEDIDO_SUG_ENC TO INTERNET
/
GRANT EXECUTE ON P_INSERT_PEDIDO_SUG_ENC TO INTERNET_SELECT
/
