GRANT EXECUTE ON P_INSERT_ESTADO_DEVOLUCION TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_INSERT_ESTADO_DEVOLUCION TO SISCEL
/
GRANT EXECUTE ON P_INSERT_ESTADO_DEVOLUCION TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERT_ESTADO_DEVOLUCION TO SISCEL_SELECT
/
