GRANT EXECUTE ON P_INSERT_COURRIER_DEV TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_INSERT_COURRIER_DEV TO SISCEL
/
GRANT EXECUTE ON P_INSERT_COURRIER_DEV TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERT_COURRIER_DEV TO SISCEL_SELECT
/
