GRANT EXECUTE ON P_INSERT_PEDIDO_DET_SUG TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERT_PEDIDO_DET_SUG TO SISCEL_SELECT
/
GRANT EXECUTE ON P_INSERT_PEDIDO_DET_SUG TO SISCEL_VE
/
GRANT EXECUTE ON P_INSERT_PEDIDO_DET_SUG TO INTERNET
/
GRANT EXECUTE ON P_INSERT_PEDIDO_DET_SUG TO INTERNET_SELECT
/
