GRANT EXECUTE ON P_INSERT_DOCUMENTO_PED TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_INSERT_DOCUMENTO_PED TO SISCEL
/
GRANT EXECUTE ON P_INSERT_DOCUMENTO_PED TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERT_DOCUMENTO_PED TO SISCEL_SELECT
/
