GRANT EXECUTE ON P_INSERT_EVA_CLI_PEDIDO TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_INSERT_EVA_CLI_PEDIDO TO SISCEL
/
GRANT EXECUTE ON P_INSERT_EVA_CLI_PEDIDO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERT_EVA_CLI_PEDIDO TO SISCEL_SELECT
/
