GRANT EXECUTE ON P_INSERT_COURRIER_PED TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_INSERT_COURRIER_PED TO SISCEL
/
GRANT EXECUTE ON P_INSERT_COURRIER_PED TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_INSERT_COURRIER_PED TO SISCEL_SELECT
/
