GRANT EXECUTE ON P_NP_INSERT_ESTADO_FACTURA TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_NP_INSERT_ESTADO_FACTURA TO SISCEL
/
GRANT EXECUTE ON P_NP_INSERT_ESTADO_FACTURA TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_NP_INSERT_ESTADO_FACTURA TO SISCEL_SELECT
/
