GRANT EXECUTE ON P_NP_ESTADO_TRASPASO TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_NP_ESTADO_TRASPASO TO SISCEL
/
GRANT EXECUTE ON P_NP_ESTADO_TRASPASO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_NP_ESTADO_TRASPASO TO SISCEL_SELECT
/
