GRANT EXECUTE ON P_NP_SACAR_USUARIO TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_NP_SACAR_USUARIO TO SISCEL
/
GRANT EXECUTE ON P_NP_SACAR_USUARIO TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_NP_SACAR_USUARIO TO SISCEL_SELECT
/
