GRANT EXECUTE ON P_UPDATE_APROBACION_DEVOLUCION TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON P_UPDATE_APROBACION_DEVOLUCION TO SISCEL
/
GRANT EXECUTE ON P_UPDATE_APROBACION_DEVOLUCION TO SISCEL_ADMIN
/
GRANT EXECUTE ON P_UPDATE_APROBACION_DEVOLUCION TO SISCEL_SELECT
/
