GRANT EXECUTE ON WGC_INSERT_FORMULARIO TO EBZ_SISCEL_EXE
/
GRANT EXECUTE ON WGC_INSERT_FORMULARIO TO SISCEL
/
GRANT EXECUTE ON WGC_INSERT_FORMULARIO TO SISCEL_ADMIN
/
GRANT EXECUTE ON WGC_INSERT_FORMULARIO TO SISCEL_SELECT
/
