/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.direccion.negocio.ejb.session;

/**
 * Local interface for DireccionFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface DireccionFacadeSTLLocal
   extends javax.ejb.EJBLocalObject
{

}
