/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.direccion.negocio.ejb.session;

/**
 * Home interface for DireccionFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface DireccionFacadeSTLHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/DireccionFacadeSTL";
   public static final String JNDI_NAME="DireccionFacadeSTL";

   public com.tmmas.cl.scl.direccion.negocio.ejb.session.DireccionFacadeSTL create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
