GRANT EXECUTE ON GA_CONS_ATLANTIDA_FS_PG TO SISCEL_ADMIN
/
GRANT EXECUTE ON GA_CONS_ATLANTIDA_FS_PG TO SISCEL_GA
/
GRANT EXECUTE ON GA_CONS_ATLANTIDA_FS_PG TO SISCEL_SELECT
/
GRANT EXECUTE ON GA_CONS_ATLANTIDA_FS_PG TO SLI_EXPLOTACION
/
