GRANT DELETE ON GE_AUDITORIA_TO TO SISCEL
/
GRANT INSERT ON GE_AUDITORIA_TO TO SISCEL
/
GRANT SELECT ON GE_AUDITORIA_TO TO SISCEL
/
GRANT UPDATE ON GE_AUDITORIA_TO TO SISCEL
/
GRANT SELECT ON GE_AUDITORIA_TO TO SISCEL_SELECT
/
