GRANT DELETE ON GE_AUDITORIA_TH TO SISCEL_ADMIN
/
GRANT INSERT ON GE_AUDITORIA_TH TO SISCEL_ADMIN
/
GRANT SELECT ON GE_AUDITORIA_TH TO SISCEL_ADMIN
/
GRANT UPDATE ON GE_AUDITORIA_TH TO SISCEL_ADMIN
/
GRANT SELECT ON GE_AUDITORIA_TH TO SISCEL_SELECT
/
