GRANT DELETE ON GE_COLA_PETICIONES_TO TO SISCEL
/
GRANT INSERT ON GE_COLA_PETICIONES_TO TO SISCEL
/
GRANT SELECT ON GE_COLA_PETICIONES_TO TO SISCEL
/
GRANT UPDATE ON GE_COLA_PETICIONES_TO TO SISCEL
/
GRANT DELETE ON GE_COLA_PETICIONES_TO TO SISCEL_ADMIN
/
GRANT INSERT ON GE_COLA_PETICIONES_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GE_COLA_PETICIONES_TO TO SISCEL_ADMIN
/
GRANT UPDATE ON GE_COLA_PETICIONES_TO TO SISCEL_ADMIN
/
GRANT SELECT ON GE_COLA_PETICIONES_TO TO SISCEL_SELECT
/
