/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.b.bcm.mancol.bean.ejb.session;

/**
 * Local home interface for ManColFacade.
 * @generated 
 * @wtp generated
 */
public interface ManColFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ManColFacadeLocal";
   public static final String JNDI_NAME="ManColFacadeLocal";

   public com.tmmas.scl.operations.crm.b.bcm.mancol.bean.ejb.session.ManColFacadeLocal create()
      throws javax.ejb.CreateException;

}
