/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.smo.bean.ejb.session;

/**
 * Home interface for SerManOpeFacade.
 * @generated 
 * @wtp generated
 */
public interface SerManOpeFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SerManOpeFacade";
   public static final String JNDI_NAME="SerManOpeFacade";

   public com.tmmas.scl.operations.smo.bean.ejb.session.SerManOpeFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
