/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.smo.bean.ejb.session;

/**
 * Local home interface for SerManOpeFacade.
 * @generated 
 * @wtp generated
 */
public interface SerManOpeFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SerManOpeFacadeLocal";
   public static final String JNDI_NAME="SerManOpeFacadeLocal";

   public com.tmmas.scl.operations.smo.bean.ejb.session.SerManOpeFacadeLocal create()
      throws javax.ejb.CreateException;

}
