/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.frameworkooss.bean.ejb.session;

/**
 * Local home interface for FrmkOOSSFacade.
 * @generated 
 * @wtp generated
 */
public interface FrmkOOSSFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/FrmkOOSSFacadeLocal";
   public static final String JNDI_NAME="FrmkOOSSFacadeLocal";

   public com.tmmas.scl.frameworkooss.bean.ejb.session.FrmkOOSSFacadeLocal create()
      throws javax.ejb.CreateException;

}
