/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.frameworkooss.bean.ejb.session;

/**
 * Remote interface for FrmkOOSSFacade.
 * @generated 
 * @wtp generated
 */
public interface FrmkOOSSFacade
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * Obtiene numero de secuencia <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.SecuenciaDTO obtenerSecuencia( com.tmmas.scl.framework.customerDomain.dataTransferObject.SecuenciaDTO secuencia )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkOOSSException, java.rmi.RemoteException;

   /**
    * Obtiene las formas de pago <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.FormaPagoListDTO obtenerFormasPago( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.BusquedaFormasPagoDTO param )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkOOSSException, java.rmi.RemoteException;

   /**
    * Obtiene los tipos de documentos de pago <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.DocumentoListDTO obtenerTiposDocumentos( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.BusquedaTiposDocumentoDTO param )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Obtiene elimina la solicitud de descuento <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO eliminarSolicitud( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RegistroSolicitudDTO registro )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkOOSSException, java.rmi.RemoteException;

   /**
    * Elimina el presupuesto <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO eliminarPresupuesto( com.tmmas.scl.framework.productDomain.dataTransferObject.RegistroFacturacionDTO registro )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkOOSSException, java.rmi.RemoteException;

   /**
    * Obtiene el numero de cuotas en el que se puede parcelar el pago de un producto <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.CuotasProductoDTO[] obtenerCuotasProducto(  )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkOOSSException, java.rmi.RemoteException;

   /**
    * Obtiene el vendedor asociado al usuario <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.UsuarioDTO obtenerVendedor( com.tmmas.scl.framework.customerDomain.dataTransferObject.UsuarioDTO usuario )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkOOSSException, java.rmi.RemoteException;

   /**
    * Obtiene el texto de la carta <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.CartaGeneralDTO obtenerTextoCarta( com.tmmas.scl.framework.productDomain.dataTransferObject.CartaGeneralDTO cartaGeneral )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkOOSSException, java.rmi.RemoteException;

   /**
    * Obtiene el máximo, mínimo del descuento y el indicador de si tiene privilegios para hacer los descuentos. <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.DescuentoVendedorDTO obtenerDescuentoVendedor( com.tmmas.scl.framework.customerDomain.dataTransferObject.DescuentoVendedorDTO vendedor )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkOOSSException, java.rmi.RemoteException;

   /**
    * Obtiene el estado de la solicitud <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RegistroSolicitudDTO consultarEstadoSolicitud( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RegistroSolicitudDTO registro )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkOOSSException, java.rmi.RemoteException;

   /**
    * Registra una venta <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO registrarVenta( com.tmmas.scl.framework.customerDomain.dataTransferObject.IngresoVentaDTO venta )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkOOSSException, java.rmi.RemoteException;

   /**
    * Acepta el presupuesto <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO aceptarPresupuesto( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PresupuestoDTO presup )
      throws com.tmmas.scl.framework.commonDoman.exception.FrmkOOSSException, java.rmi.RemoteException;

   /**
    * Obtener tipo contrato <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ContratoDTO obtenerTipoContrato( com.tmmas.scl.framework.customerDomain.dataTransferObject.ContratoDTO contrato )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Obtiene las modalidades de pago <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO obtenerModalidadPago( com.tmmas.scl.framework.ProductDomain.dto.ModalidadPagoDTO modalidad )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Obtiene el detalle del presupuesto <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PresupuestoDTO obtenerDetallePresupuesto( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.PresupuestoDTO presup )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Obtiene datos del vendedor <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.VendedorDTO obtenerVendedor( com.tmmas.scl.framework.productDomain.dataTransferObject.VendedorDTO vendedor )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Inserta un concepto de descuento <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO insertarConceptoDescuento( com.tmmas.scl.framework.customerDomain.dataTransferObject.DescuentoDTO desc )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Obtiene el codigo de concepto de descuento <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.DescuentoDTO obtenerCodConceptoDescuento( com.tmmas.scl.framework.productDomain.dataTransferObject.DatosGeneralesDTO sec )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Elimina el codigo de concepto de descuento <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO eliminaCodConceptoDescuento( long numTransaccion )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Obtiene el plan comercial <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO obtenerPlanComercial( com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Registra una solicitud de aprobación de descuento en SCL <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RespuestaSolicitudDTO solicitarAprobacionDescuento( com.tmmas.scl.framework.productDomain.productOfferingABE.dataTransferObject.RegistroSolicitudListDTO registro )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Consulta el estado de una factura <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO consultarEstadoFacturado( long numProceso )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Obtiene la ruta de una factura <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.ArchivoFacturaDTO obtenerRutaFactura( com.tmmas.scl.framework.productDomain.dataTransferObject.ArchivoFacturaDTO factura )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Obtiene parámetros generales <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ParametroDTO obtenerParametroGeneral( com.tmmas.scl.framework.customerDomain.dataTransferObject.ParametroDTO registro )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * registrarOOSSEnLinea <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO registrarOOSSEnLinea( com.tmmas.scl.framework.customerDomain.dataTransferObject.RegistrarOossEnLineaDTO registro )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * Actualiza Renovación <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO actualizaRenova( com.tmmas.scl.framework.customerDomain.dataTransferObject.RegistrarRenovaDTO param )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.productDomain.dataTransferObject.AbonadoDTO obtenerDatosAbonado2( com.tmmas.scl.framework.productDomain.dataTransferObject.AbonadoDTO abonado )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO obtenerDatosCliente( com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteDTO cliente )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.scl.framework.customerDomain.dataTransferObject.RetornoDTO insertarCobroAdelantado( com.tmmas.scl.framework.customerDomain.dataTransferObject.ClienteCobroAdentadoDTO clienteCobroAdelantadoDTO )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * registrarCarta <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public boolean registrarCarta( com.tmmas.scl.framework.productDomain.dataTransferObject.CartaGeneralDTO dto,long numOS )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

}
