/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.anulsinie.bean.ejb.session;

/**
 * Local interface for AnuSinFacade.
 * @generated 
 * @wtp generated
 */
public interface AnuSinFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
