/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operation.crm.fab.cusintman.anulsinie.bean.ejb.session;

/**
 * Home interface for AnuSinFacade.
 * @generated 
 * @wtp generated
 */
public interface AnuSinFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AnuSinFacade";
   public static final String JNDI_NAME="AnuSinFacade";

   public com.tmmas.scl.operation.crm.fab.cusintman.anulsinie.bean.ejb.session.AnuSinFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
