/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.frameworkcargos.bean.ejb.session;

/**
 * Local interface for FrmkCargosFacade.
 * @generated 
 * @wtp generated
 */
public interface FrmkCargosFacadeLocal
   extends javax.ejb.EJBLocalObject
{

}
