GRANT SELECT ON GE_AUDREG_SQ TO SISCEL
/
GRANT SELECT ON GE_AUDREG_SQ TO SISCEL_GA
/
GRANT SELECT ON GE_AUDREG_SQ TO SISCEL_GE
/
GRANT SELECT ON GE_AUDREG_SQ TO SISCEL_RE
/
GRANT SELECT ON GE_AUDREG_SQ TO SISCEL_SELECT
/
