/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.altacliente.negocio.ejb.session;

/**
 * Local interface for AltaClienteFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface AltaClienteFacadeSTLLocal
   extends javax.ejb.EJBLocalObject
{

}
