GRANT DELETE ON GE_DOMINIOS_TD TO MAS_GENERAL_DML WITH GRANT OPTION
/
GRANT INSERT ON GE_DOMINIOS_TD TO MAS_GENERAL_DML WITH GRANT OPTION
/
GRANT SELECT ON GE_DOMINIOS_TD TO MAS_GENERAL_DML WITH GRANT OPTION
/
GRANT UPDATE ON GE_DOMINIOS_TD TO MAS_GENERAL_DML WITH GRANT OPTION
/
