GRANT DELETE ON GE_VALORES_DOMINIOS_TD TO MAS_GENERAL_DML WITH GRANT OPTION
/
GRANT INSERT ON GE_VALORES_DOMINIOS_TD TO MAS_GENERAL_DML WITH GRANT OPTION
/
GRANT SELECT ON GE_VALORES_DOMINIOS_TD TO MAS_GENERAL_DML WITH GRANT OPTION
/
GRANT UPDATE ON GE_VALORES_DOMINIOS_TD TO MAS_GENERAL_DML WITH GRANT OPTION
/
GRANT INSERT ON GE_VALORES_DOMINIOS_TD TO OPS$SQLPARAM
/
GRANT SELECT ON GE_VALORES_DOMINIOS_TD TO OPS$SQLPARAM
/
GRANT UPDATE ON GE_VALORES_DOMINIOS_TD TO OPS$SQLPARAM
/
