GRANT SELECT, INSERT, DELETE, UPDATE  ON GROUPS TO SISCEL_PV
/
GRANT SELECT, INSERT, DELETE, UPDATE  ON GROUPS TO SISCEL_SELECT
/
GRANT SELECT, INSERT, DELETE, UPDATE  ON GROUPS TO SISCEL_VE
/
GRANT SELECT, INSERT, DELETE, UPDATE  ON GROUPS TO SISCEL_AL
/