GRANT SELECT, INSERT, DELETE, UPDATE  ON USERS TO SISCEL_PV
/
GRANT SELECT, INSERT, DELETE, UPDATE  ON USERS TO SISCEL_SELECT
/
GRANT SELECT, INSERT, DELETE, UPDATE  ON USERS TO SISCEL_VE
/
GRANT SELECT, INSERT, DELETE, UPDATE  ON USERS TO SISCEL_AL
/