/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.socketps.negocio.ejb.session;

/**
 * Home interface for ConsultaFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface ConsultaFacadeSTLHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ConsultaFacadeSTL";
   public static final String JNDI_NAME="ConsultaFacadeSTL";

   public com.tmmas.cl.scl.socketps.negocio.ejb.session.ConsultaFacadeSTL create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
