/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.tasacion.negocio.ejb.session;

/**
 * Home interface for TasacionFacadeSTL.
 * @generated 
 * @wtp generated
 */
public interface TasacionFacadeSTLHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TasacionFacadeSTL";
   public static final String JNDI_NAME="TasacionFacadeSTL";

   public com.tmmas.cl.scl.tasacion.negocio.ejb.session.TasacionFacadeSTL create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
