/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.activacionmasiva.soa.ejb.session;

/**
 * Local interface for ActivacionMasivaORQ.
 * @generated 
 * @wtp generated
 */
public interface ActivacionMasivaORQLocal
   extends javax.ejb.EJBLocalObject
{

}
