/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.activacionmasiva.soa.ejb.session;

/**
 * Remote interface for ActivacionMasivaORQ.
 * @generated 
 * @wtp generated
 */
public interface ActivacionMasivaORQ
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String ejemplo( java.lang.String param )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void updUsuario( com.tmmas.cl.scl.customerdomain.businessobject.dto.UsuarioInDTO entrada )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws GeneralException
    * @throws 
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.ActivacionLineaOutDTO altaLinea( com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.ParametrosComercialesINDTO actLinea,com.tmmas.cl.scl.commonbusinessentities.dto.ws.UsuarioActInDTO usuario )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws 
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.ParametrosComercialesDTO getParametrosComerciales( com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.CabeceraArchivoCOLDTO objetoSesion )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws 
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.CabeceraArchivoDTO getParametrosGenerales( com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.CabeceraArchivoCOLDTO objetoSesion )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.CabeceraArchivoDTO getParametrosVenta( com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.CabeceraArchivoCOLDTO cabecera )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.ContratosDTO obtenerContratoNuevo(  )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.ContratosDTO getTipoContrato( com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.ContratosDTO entrada )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.SolicitudAutorizacionDescuentoDTO solicitarAprobaciones( com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.RegCargosDTO regCargosDTO )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.SolicitudAutorizacionDescuentoDTO consultaEstadoSolicitud( com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.SolicitudAutorizacionDescuentoDTO solicitudAutorizacionDescuentoDTO )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonbusinessentities.dto.ws.ListadoSSOutDTO[] getListadoSS( com.tmmas.cl.scl.commonbusinessentities.dto.ws.ListadoSSInDTO entrada )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.productdomain.businessobject.dto.ArticuloOutDTO[] getListadoArticulos( com.tmmas.cl.scl.commonbusinessentities.dto.ws.ArticuloInDTO articulo )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonbusinessentities.dto.ws.DatCteClienteOutDTO[] getDatosCliente( com.tmmas.cl.scl.commonbusinessentities.dto.ws.DatCteClienteInDTO entrada )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonbusinessentities.dto.ws.LstVtaRegistroResultadoDTO getListVentas( com.tmmas.cl.scl.commonbusinessentities.dto.ws.LstVtaRegistroVentaInDTO entrada )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonbusinessentities.dto.ws.LstPTaPlanTarifarioListOutDTO lstPlanTarif( com.tmmas.cl.scl.commonbusinessentities.dto.ws.LstPTaPlanTarifarioInDTO entrada )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonbusinessentities.dto.ws.LstPTaPlanTarifarioListOutDTO lstPlanTarifPosventa( com.tmmas.cl.scl.commonbusinessentities.dto.ws.LstPTaPlanTarifarioInDTO entrada )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.altaclientecommon.commonapp.dto.CuentaComDTO crearCliente( com.tmmas.cl.scl.altaclientecommon.commonapp.dto.CuentaComDTO cuentaComDTO )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonbusinessentities.dto.ws.ClienteOutDTO altaCliente( com.tmmas.cl.scl.commonbusinessentities.dto.ws.ClienteInDTO clienteIn )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.crmcommon.commonapp.dto.ConceptoVenta ValidarModalidadVenta( com.tmmas.cl.scl.crmcommon.commonapp.dto.DependenciasModalidadDTO entrada )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void liberarSeries( java.lang.String nroSimcard,java.lang.String nroTerminal,java.lang.String procEquipo,java.lang.String numVenta,java.lang.String codVendedor )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.crmcommon.commonapp.dto.TiposContratoListOutDTO ListaTipoContrato(  )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonbusinessentities.dto.ws.SimcardOutDTO validacionSimcard( com.tmmas.cl.scl.commonbusinessentities.dto.ws.SimcardInDTO entrada )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonbusinessentities.dto.ws.SalidaOutDTO bloqueaSolicitudEvRiesgo( com.tmmas.cl.scl.customerdomain.businessobject.dto.RegistroEvaluacionRiesgoDTO registroEvaluacionRiesgo )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.commonbusinessentities.dto.ws.SalidaOutDTO desBloqueaEstadoSolicitudEvRiesgo( com.tmmas.cl.scl.customerdomain.businessobject.dto.RegistroEvaluacionRiesgoDTO registroEvaluacionRiesgo )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.altaclientecommon.commonapp.dto.NumeroIdentificacionDTO validarIdentificador( com.tmmas.cl.scl.altaclientecommon.commonapp.dto.NumeroIdentificacionDTO entrada )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws GeneralException
    * @throws 
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.ActivacionLineaOutDTO altaLineaWeb( com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.AltaLineaWebDTO alta )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws GeneralException
    * @throws 
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.ActivacionLineaOutDTO altaVentaWeb( com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.AltaLineaWebDTO alta )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws GeneralException
    * @throws 
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.crmcommon.commonapp.dto.CargoSolicitudDTO[] getCargosVta( com.tmmas.cl.scl.crmcommon.commonapp.dto.CargoSolicitudDTO entrada )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws AltaClienteException
    * @throws VentasException
    * @throws RemoteException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.ResultadoAltaCarrierPasilloLDIDTO altaCarrierPasilloLDI( com.tmmas.cl.scl.activacionmasivacommon.commonapp.dto.AltaCarrierPasilloLDIDTO dto )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.VentasException, com.tmmas.cl.scl.altaclientecommon.commonapp.exception.AltaClienteException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws GeneralException
    * @throws 
    * @generated //TODO: Must provide implementation for bean method stub    */
   public long getSecuencia( java.lang.String nombreSecuencia )
      throws com.tmmas.cl.framework.exception.GeneralException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws GeneralException
    * @throws 
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String descripcionArticulo( java.lang.String codArticulo )
      throws com.tmmas.cl.scl.crmcommon.commonapp.exception.CustomerDomainException, java.rmi.RemoteException;

}
