/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.scl.operations.crm.fab.cim.mancon.bean.ejb.session;

/**
 * Session layer for ManConFacade.
 * @generated 
 * @wtp generated
 */
public class ManConFacadeSession
   extends com.tmmas.scl.operations.crm.fab.cim.mancon.bean.ejb.session.ManConFacadeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {

      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbRemove();
   }

}
