/*
 * Generated by XDoclet - Do not edit!
 */
package com.tmmas.cl.scl.spnscljms.negocio.ejb.session;

/**
 * Remote interface for SpnSclJMS.
 * @generated 
 * @wtp generated
 */
public interface SpnSclJMS
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws FrameworkException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void pruebaJMS( java.lang.String cierreVenta )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws FrameworkException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void AltaDeLineaJMS( com.tmmas.cl.scl.commonapp.dto.WsCunetaAltaDeLineaDTO CunetaAltaDeLinea,int rollback )
      throws java.rmi.RemoteException;

}
